pr for ticket 25933
sagemath/sage pull request #35009
Opened 2023-02-07 17:49 UTC by Bruno-TT

still trying to work out this new github workflow, hopefully this is alright

2023-02-07 20:21 UTC, dimpase requested changes

2023-02-07 20:21 UTC, dimpase commented on src/sage/graphs/generators/basic.py
> +    return Graph(adjacency_matrix, format="adjacency_matrix", name="Correlation Graph")
check the linter error (trailing space) in this line

2023-02-07 20:23 UTC, dimpase commented on src/sage/graphs/generators/basic.py
> +    return Graph(adjacency_matrix, format="adjacency_matrix", name="Correlation Graph")
https://github.com/sagemath/sage/actions/runs/4117765743/jobs/7109476469

2023-02-08 05:18 UTC, yyyyx4 commented
You can use one of [a few select keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link a pull request to an issue. For example, editing the description to include "fixes #25933" will instruct GitHub to automatically close #25933 when this pull request gets merged.

2023-02-08 10:25 UTC, dimpase commented
fixes #25933

2023-05-02 08:11 UTC, dimpase commented
that's why tests fail:
```
sage -t --random-seed=258796353776112123915659578485470282204 sage/graphs/generators/basic.py
**********************************************************************
File "sage/graphs/generators/basic.py", line 408, in sage.graphs.generators.basic.CorrelationGraph
Failed example:
    from sage.graphs.correlation_graph import CorrelationGraph
Exception raised:
    Traceback (most recent call last):
      File "/__w/sage/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/__w/sage/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.generators.basic.CorrelationGraph[0]>", line 1, in <module>
        from sage.graphs.correlation_graph import CorrelationGraph
    ModuleNotFoundError: No module named 'sage.graphs.correlation_graph'
```

2023-05-02 08:12 UTC, dimpase commented
and linting fails due to
```
pycodestyle-minimal: commands[0] /home/runner/work/sage/sage/src> pycodestyle --select E111,E211,E271,E306,E401,E502,E701,E702,E703,W291,W391,W605,E711,E712,E713,E721,E722
./sage/graphs/generators/basic.py:427:88: W291 trailing whitespace
1       W291 trailing whitespace
```

2023-05-04 09:59 UTC, dimpase approved these changes

2023-05-22 22:42 UTC, merged