a bijectionist's toolkit
sagemath/sage pull request #35060
Opened 2023-02-10 12:40 UTC by mantepse

We provide a toolkit for the combinatorialist to help find functions ("statistics") s: A -> Z and bijections A -> B given sequences of finite sets A and B that satisfy various constraints.

Closes #33238

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2023-02-10 21:35 UTC, mkoeppe approved these changes
As I said in https://github.com/sagemath/sage/issues/33238#issuecomment-1418161757, this is OK from my side, but I've really only looked at the code from the viewpoint of managing the MIPs and getting solutions out of them. So it would be good if other reviewers could take a look on the combinatorial statistics side of things.

2023-02-11 12:13 UTC, tscrim requested changes
I still haven't made it through everything, and mostly just looked at some of the doc. Most of my comments apply similarly to other parts of the doc. I will try to go through the rest of it later. (The only way I know how to push changes would be to make a completely separate PR, which just makes things way more complicated.)

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +
This whole block is over-indented.

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        sage: alpha1 = lambda p: len(p.weak_excedences())
```suggestion
        sage: def alpha1(p): return len(p.weak_excedences())
```
and similar here to be more pythonic.

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        sage: for solution in sorted(list(bij.solutions_iterator()), key=lambda d: tuple(sorted(d.items()))):
```suggestion
        sage: for solution in sorted(bij.solutions_iterator(), key=lambda d: sorted(d.items())):
```
The result of `sorted` is a list and compares the same as a tuple.

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          in `Z`
```suggestion
    - ``pi_rho`` (optional) -- a list of triples ``(k, pi, rho)``,
      where

      * ``pi`` -- a ``k``-ary operation composing objects in ``A``
        and
      * ``rho`` -- a ``k``-ary function composing statistic values
        in ``Z``
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    - ``tau`` (optional, default: ``None``) -- a function from ``B``
```suggestion
    - ``tau`` -- (optional) a function from ``B``
```
and similar changes below.

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        Calling ``set_statistics`` without arguments should restore the previous state.::
```suggestion
        Calling ``set_statistics`` without arguments should restore the previous state::
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        - ``header`` (optional, default: ``True``) -- whether to
```suggestion
        - ``header`` -- (default: ``True``) whether to
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +            sage: for sol in sorted(list(bij.solutions_iterator()), key=lambda d: tuple(sorted(d.items()))):
```suggestion
            sage: for sol in sorted(bij.solutions_iterator(), key=lambda d: sorted(d.items())):
```
and similar below.

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        any unique solutions.::
```suggestion
        any unique solutions::
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +            sage: concat = lambda p1, p2: Permutation(p1 + [i + len(p1) for i in p2])
```suggestion
            sage: def concat(p1, p2): return Permutation(p1 + [i + len(p1) for i in p2])
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        - ``Q``, a set partition of ``A``.
```suggestion
        - ``Q`` -- a set partition of ``A``
```

2023-02-11 12:13 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    def _find_counter_example(self, P, s0, d, on_blocks):
```suggestion
    def _find_counterexample(self, P, s0, d, on_blocks):
```
Typically counterexample is written as one word in English (at least as far as I have seen and recall).

2023-02-11 12:31 UTC, mantepse commented
@tscrim, many, many thanks for looking at this!  Please let me know when it is best for you that I incorporate your suggestions, so that I do not step on your toes!

2023-02-11 12:44 UTC, tscrim commented
I am not making any changes. (I am not going to make a separate PR at this point to not further fragment the discussion.)

2023-02-11 13:01 UTC, mantepse commented
> I am not making any changes. (I am not going to make a separate PR at this point to not further fragment the discussion.)

Yes, put if I push the changes you suggested, and you accidentally pull, the line numbers will be confusing.  I thought it would be nicer for you if am making changes locally, and will then push once.

2023-02-11 13:02 UTC, mantepse commented on src/sage/combinat/bijectionist.py
> +        sage: alpha1 = lambda p: len(p.weak_excedences())
I admit I dislike this one, it is longer and harder to read for me.  Are you sure?

2023-02-11 13:24 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        sage: alpha1 = lambda p: len(p.weak_excedences())
Yes, although the "proper" way would be
```
sage: def alpha1(p):
....:     return len(p.weak_excedences())
```

2023-02-11 13:26 UTC, tscrim commented
> 

I

> > I am not making any changes. (I am not going to make a separate PR at this point to not further fragment the discussion.)
> 
> Yes, put if I push the changes you suggested, and you accidentally pull, the line numbers will be confusing. I thought it would be nicer for you if am making changes locally, and will then push once.

No, it will be fine. (I don't really pay attention to line numbers too much; ctrl-f is generally how I find stuff.)

2023-02-13 08:54 UTC, mantepse commented
I'd be extremely grateful if this would make it into the upcoming release!

2023-02-13 12:16 UTC, tscrim requested changes
I have also now made it through all the code. Once all of these suggestions are incorporated, then it is a positive review by me.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +# -*- coding: utf-8 -*-
This is not needed anymore since switching to Python3 and dropping Python2 support.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +EXAMPLES:
The `EXAMPLES:` can be deleted. The guided tour indicator is sufficient I think.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +We find a statistic `s` such that `(s, wex, fix) \sim (llis, des, adj)`::
Reading this, I am not sure what all of these statistics are or on what set you are acting until I read the code. Since you are making this a guided tour, it would be good to explain at least a little bit more. Although it doesn't need too much more.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    sage: N = 8;
```suggestion
    sage: N = 8
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +
```suggestion
    - ``pi_rho`` -- (optional) a list of triples ``(k, pi, rho)``, where

      * ``pi`` -- a ``k``-ary operation composing objects in ``A`` and
      * ``rho`` -- a ``k``-ary function composing statistic values in ``Z``
```
The biggest thing is the indentation on the sublist.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        - ``p`` -- (optional, default: ``None``) -- a block of `P`, or
```suggestion
        - ``p`` -- (optional) a block of `P`, or
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          not to compute the minimal possible set of statistic values.
```suggestion
        - ``optimal`` -- (default: ``False``) whether or
          not to compute the minimal possible set of statistic values
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +            computing the minimal possible set of statistic values
```suggestion
            Computing the minimal possible set of statistic values
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        - ``Q`` -- a set partition of ``A``.
```suggestion
        - ``Q`` -- a set partition of ``A``
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          header with the standard greek letters.
```suggestion
        - ``header`` -- (default: ``True``) whether to include a
          header with the standard Greek letters
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    def __init__(self, A, B, tau=None, alpha_beta=tuple(), P=[],
Having `P=[]` as a mutable list is dangerous as a default argument as modifying `P` then changes the default. It is safer to have `P=None` and then set `P = []` within the function.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +                raise ValueError(f"Statistics alpha and beta do not have the same image, {v} is not a value of alpha, but of beta!")
I think we should follow Python conventions with the error messages and start with a lower case and not end with punctuation. (Sage generally follows this.)

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          blocks or on elements.
```suggestion
        - ``P` --, the representatives of the blocks, or `A` if
          ``on_blocks`` is ``False``

        - ``s0`` -- a solution

        - ``d`` -- a subset of `A`, in the form of a dict from `A` to `\{0, 1\}`

        - ``on_blocks`` -- whether to return the counterexample on
          blocks or on elements
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    """
```suggestion
    Wrapper class for the MixedIntegerLinearProgram (MILP).

    This class is used to manage the MILP, add constraints, solve
    the problem and check for uniqueness of solution values.
    """
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          appears as `a`.
```suggestion
        - ``bijectionist`` -- an instance of :class:`Bijectionist`

        - ``solutions`` -- (optional) a list of solutions of the problem, 
          each provided as a dictionary mapping `(a, z)` to a boolean,
          such that at least one element from each block of `P`
          appears as `a`
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        - ``on_blocks``, whether to return the solution on blocks or
```suggestion
        - ``on_blocks`` -- whether to return the solution on blocks or
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          on all elements.
```suggestion
        - ``additional_constraints`` -- a list of constraints for the
          underlying MILP

        - ``on_blocks``, whether to return the solution on blocks or
          on all elements
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          Boolean.
```suggestion
        - ``solution`` -- a dictionary from the indices of the MILP to
          a boolean
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +          specifying whether `a` is mapped to `z`.
```suggestion
        - ``constraint`` -- a
          :class:`sage.numerical.linear_functions.LinearConstraint`

        - ``values`` -- a candidate for a solution of the MILP as a
          dictionary from pairs `(a, z)\in A\times Z` to `0` or `1`,
          specifying whether `a` is mapped to `z`
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +            variable_index = next(iter(v.dict().keys()))
```suggestion
            variable_index = next(iter(v.dict()))
```
I think calling `keys()` here is unnecessary, but not 100% sure.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +        B_matrix = [[zero]*len(W) for _ in range(len(Z))]
```suggestion
        AZ_matrix = [[zero] * len(W) for _ in range(len(Z))]
        B_matrix = [[zero] * len(W) for _ in range(len(Z))]
```
A PEP8 thing.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +            for a_tuple in itertools.product(*([A]*pi_rho.numargs)):
```suggestion
            for a_tuple in itertools.product(A, repeat=pi_rho.numargs):
```
I think the `repeat` argument is what you are after here.

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    - ``d``, a ``dict``.
```suggestion
    - ``d`` -- a ``dict``
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +    - ``d``, a ``sage.sets.disjoint_set.DisjointSet_of_hashables``
```suggestion
    - ``d`` -- a :class:`sage.sets.disjoint_set.DisjointSet_of_hashables`
```

2023-02-13 12:16 UTC, tscrim commented on src/sage/combinat/bijectionist.py
> +it take (seemingly) forever.::
```suggestion
it take (seemingly) forever::
```

2023-02-14 08:03 UTC, tscrim approved these changes
Thanks. LGTM.

2023-02-14 08:04 UTC, tscrim commented
Sorry, accidentally hit the wrong button.

2023-02-14 08:05 UTC, tscrim approved these changes

2023-02-14 08:34 UTC, mantepse commented
Thank you so much!  This ticket means a lot to me!

2023-03-11 11:20 UTC, vbraun commented
On 32-bit:
```
**********************************************************************
File "src/sage/combinat/bijectionist.py", line 1578, in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
Failed example:
    for p in bij.constant_blocks(): print(list(p))
Expected:
    [[2, 1, 3, 4], [1, 2, 4, 3], [1, 3, 2, 4], [4, 2, 3, 1]]
    [[3, 2, 1], [1, 3, 2], [2, 1, 3]]
    [[2, 4, 3, 1], [3, 2, 4, 1], [2, 3, 1, 4], [1, 3, 4, 2]]
    [[1, 4, 2, 3], [3, 1, 2, 4], [4, 2, 1, 3], [4, 1, 3, 2]]
    [[1, 4, 3, 2], [3, 2, 1, 4]]
    [[2, 1, 4, 3], [4, 3, 2, 1]]
    [[2, 4, 1, 3], [3, 4, 2, 1], [4, 3, 1, 2], [3, 1, 4, 2]]
Got:
    [[1, 2, 4, 3], [4, 2, 3, 1], [1, 3, 2, 4], [2, 1, 3, 4]]
    [[2, 1, 3], [3, 2, 1], [1, 3, 2]]
    [[1, 3, 4, 2], [2, 3, 1, 4], [3, 2, 4, 1], [2, 4, 3, 1]]
    [[3, 1, 2, 4], [4, 2, 1, 3], [4, 1, 3, 2], [1, 4, 2, 3]]
    [[3, 2, 1, 4], [1, 4, 3, 2]]
    [[2, 1, 4, 3], [4, 3, 2, 1]]
    [[3, 4, 2, 1], [2, 4, 1, 3], [4, 3, 1, 2], [3, 1, 4, 2]]
**********************************************************************
File "src/sage/combinat/bijectionist.py", line 1587, in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
Failed example:
    for p in bij.constant_blocks(optimal=True): sorted(p, key=len)
Expected:
    [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]
    [[1, 3, 2],
     [2, 1, 3],
     [3, 2, 1],
     [2, 3, 4, 1],
     [1, 3, 4, 2],
     [2, 1, 3, 4],
     [1, 3, 2, 4],
     [2, 3, 1, 4],
     [1, 2, 4, 3],
     [3, 2, 4, 1],
     [2, 1, 4, 3],
     [2, 4, 3, 1],
     [4, 2, 3, 1],
     [4, 3, 2, 1],
     [1, 4, 3, 2],
     [3, 2, 1, 4]]
    [[1, 4, 2, 3],
     [4, 2, 1, 3],
     [2, 4, 1, 3],
     [4, 3, 1, 2],
     [4, 1, 3, 2],
     [3, 4, 2, 1],
     [3, 1, 2, 4],
     [3, 1, 4, 2]]
Got:
    [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]
    [[3, 2, 1],
     [1, 3, 2],
     [2, 1, 3],
     [2, 1, 4, 3],
     [1, 3, 2, 4],
     [2, 4, 3, 1],
     [1, 3, 4, 2],
     [2, 3, 1, 4],
     [3, 2, 1, 4],
     [4, 2, 3, 1],
     [1, 4, 3, 2],
     [2, 1, 3, 4],
     [1, 2, 4, 3],
     [3, 2, 4, 1],
     [4, 3, 2, 1],
     [2, 3, 4, 1]]
    [[3, 1, 2, 4],
     [4, 1, 3, 2],
     [4, 3, 1, 2],
     [1, 4, 2, 3],
     [3, 4, 2, 1],
     [4, 2, 1, 3],
     [2, 4, 1, 3],
     [3, 1, 4, 2]]
**********************************************************************
1 item had failures:
   2 of  65 in sage.combinat.bijectionist.Bijectionist._forced_constant_blocks
    [579 tests, 2 failures, 69.84 s]
----------------------------------------------------------------------
sage -t --long --random-seed=0 src/sage/combinat/bijectionist.py  # 2 doctests failed
----------------------------------------------------------------------
```

2023-03-11 15:19 UTC, mantepse commented
@vbraun, I hope this solved the issue, but I have no way to test on 32 bit, I am sorry about that.

2023-03-11 22:33 UTC, tscrim approved these changes
I also think this sorting should solve the issue.

2023-03-13 00:17 UTC, merged