sage.{finance,interacts,libs,numerical,stats,tests}: Replace imports from sage.*.all for namespace packages
sagemath/sage pull request #35107
Opened 2023-02-13 02:10 UTC by mkoeppe

### 📚 Description
Fixes #34957

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### ⌛ Dependencies

2023-02-13 18:15 UTC, mkoeppe commented
Yes, that's an unrelated concurrency bug in ECL.

2023-02-14 02:53 UTC, tobiasdiez requested changes, later dismissed

2023-02-14 02:53 UTC, tobiasdiez commented on src/sage/stats/distributions/discrete_gaussian_polynomial.py
> +from sage.rings.integer_ring import Z as ZZ
```suggestion
from sage.rings.integer_ring import ZZ
```
?

2023-02-14 03:00 UTC, tobiasdiez commented
There are a few more:
```
from sage.rings.integer_ring import Z as ZZ
from sage.rings.rational_field import Q as QQ
```

2023-02-14 03:06 UTC, mkoeppe commented
Thanks, I'll fix them with a script

2023-03-13 20:38 UTC, dimpase approved these changes
lgtm

2023-03-13 20:40 UTC, mkoeppe commented
Thanks, Dima!

2023-03-19 15:51 UTC, merged