`sage.{geometry,rings}`: More `# optional` tags in doctests
sagemath/sage pull request #35136
Opened 2023-02-15 02:30 UTC by mkoeppe

### 📚 Description

Adding more `# optional` tags in doctests so that doctests can be run with modularized distributions.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [ ] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### ⌛ Dependencies

2023-02-15 19:47 UTC, kliem approved these changes

2023-02-15 20:00 UTC, kliem requested changes
There are some failing tests, which makes me wonder whether `# optional - sage.libs.pari` is working at all.

2023-02-15 20:00 UTC, kliem commented on src/sage/geometry/polyhedron/base2.py
> +            sage: [Partitions(k, length=5).cardinality() for k in range(5,20)] == \             # optional - sage.combinat
The `# optional` needs to be in the second line here.

2023-02-15 20:00 UTC, kliem commented on src/sage/rings/integer.pyx
>              sage: ZZ( (k(0),k(1)), 2)
missing optional

2023-02-15 20:00 UTC, kliem commented on src/sage/rings/integer.pyx
>              sage: n.trial_division(bound=10^4)
Missing optional

2023-02-15 20:00 UTC, kliem commented on src/sage/rings/integer.pyx
>              sage: (-n).trial_division(bound=10^4)
Missing optional

2023-02-15 20:00 UTC, kliem commented on src/sage/rings/integer.pyx
>              sage: (-n).trial_division()
Missing optional

2023-02-15 21:24 UTC, mkoeppe commented
Indeed the optional tag was not working, fixed now.

2023-02-18 10:52 UTC, kliem approved these changes

2023-02-18 17:42 UTC, mkoeppe commented
Thank you!

2023-02-20 05:26 UTC, kliem approved these changes

2023-03-26 12:00 UTC, merged