symbolics: add derivative operator
sagemath/sage pull request #35193
Opened 2023-02-24 17:32 UTC by spaghettisalat

This allows for also using the syntax which sagemath already uses in the output of symbolic derivatives of functions like `D[0,1](f)(x+y,x-y)` in user input.

See #32554

2023-02-24 22:03 UTC, mkoeppe reviewed
This is a good idea.

I've made some small edits.

I think it would be good to add an example to the class doctest, so that it will be shown if the user types `D?`

2023-02-25 13:39 UTC, spaghettisalat commented
I've improved the documentation a bit as requested (and also added a `__repr__` method so that the new operator prints nicely).

2023-03-01 17:19 UTC, egourgoulhon commented
Thanks for implementing this!

2023-03-01 17:23 UTC, egourgoulhon requested changes

2023-03-01 17:23 UTC, egourgoulhon commented on src/sage/symbolic/operators.py
> +        The order in which the indices are given should not matter
```suggestion
        TESTS:

        The order in which the indices are given should not matter::
```
This should fix the [Validate docstring markup as RST](https://github.com/sagemath/sage/actions/runs/4270261047/jobs/7433946437#logs) issue.

2023-03-04 08:25 UTC, roed314 commented
I'm fine with this, but am leaving the positive review for others who work with symbolics more than I do.

2023-03-04 09:21 UTC, mkoeppe approved these changes

2023-03-04 09:47 UTC, egourgoulhon approved these changes
Fine for me too! 
Thanks.

2023-03-26 12:00 UTC, merged