`sage.graphs`: Add `# optional` doctest tags for modularization
sagemath/sage pull request #35266
Opened 2023-03-11 19:57 UTC by mkoeppe

### 📚 Description

These tags make it possible/meaningful to doctest `sage.graphs` even when some "standard" packages are not installed. 

- Part of #29705 
- Split out from #34998

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### ⌛ Dependencies

This is just one commit on top of:
- #35237

2023-03-14 09:46 UTC, dimpase commented on src/sage/graphs/generators/families.py
> +        sage: import networkx                                                   # optional - sage.groups
did you mean ` - networkx` here?

2023-03-14 09:48 UTC, dimpase requested changes
please check that `sage.groups`  tags are not placed by mistake, instead of  `networkx`

2023-03-14 18:26 UTC, mkoeppe commented
I've rebased on top of the dependency https://github.com/sagemath/sage/pull/35237

2023-03-14 18:51 UTC, dimpase approved these changes
lgtm

2023-03-14 19:24 UTC, dcoudert approved these changes
LGTM.

2023-03-14 19:24 UTC, dcoudert commented on src/sage/graphs/generators/families.py
> +        sage: import networkx                                                   # optional - sage.groups
Should be networkx and not sage.groups

2023-03-14 19:44 UTC, mkoeppe commented on src/sage/graphs/generators/families.py
> +        sage: import networkx                                                   # optional - sage.groups
Fixed already, thanks!

2023-03-14 19:44 UTC, mkoeppe commented
Thanks!

2023-03-29 22:32 UTC, vbraun commented
```
sage -t --long --warn-long 73.8 --random-seed=123 src/sage/interfaces/r.py  # 3 doctests failed
```

2023-04-01 16:34 UTC, merged