add .conductor() and .order_of_conductor() methods for orders in quadratic fields
sagemath/sage pull request #35271
Opened 2023-03-13 07:24 UTC by yyyyx4

This patch adds two tiny convenience methods:
* `.conductor()` for orders in quadratic fields, returning the unique positive integer $f$ such that the discriminant equals $f^2\cdot D$ with $D$ a fundamental discriminant.
* `.order_of_conductor()` for quadratic fields, returning the unique order with the given conductor.

2023-03-13 09:37 UTC, tscrim requested changes
LGTM modulo the two fairly trivial things.

2023-03-13 09:37 UTC, tscrim commented on src/sage/rings/number_field/order.py
> +        return ZZ(D / D0).sqrt()
```suggestion
        return ZZ(D // D0).sqrt()
```
Perhaps even the `ZZ` call here becomes unnecessary?

2023-03-13 09:37 UTC, tscrim commented on src/sage/rings/number_field/number_field.py
> +        return self.order([f*g for g in self.maximal_order().gens()])
```suggestion
        return self.order([f * g for g in self.maximal_order().gens()])
```
A PEP8 thing...

2023-03-14 04:06 UTC, yyyyx4 commented
Thank you, done.

2023-03-14 05:44 UTC, tscrim approved these changes
Thank you.

2023-03-14 08:18 UTC, yyyyx4 commented
It seems I forgot to actually run the test prior to pushing, but the good news is that it already revealed another bug!

2023-03-14 09:14 UTC, tscrim approved these changes
Good catch.

2023-04-03 12:39 UTC, tscrim approved these changes
LGTM. If desired, you can do two trivial things:

1. Pass an iterator to `order()` in `order_of_conductor()`.
2. Add a space `\neq2` -> `\neq 2` as I find it easier to read.

You can ignore these if you want and set the status badge to positive review.

2023-04-05 02:28 UTC, yyyyx4 commented
> 1. Pass an iterator to `order()` in `order_of_conductor()`.

This doesn't work without additional code changes: The `.order()` methods explicitly checks for `list`s and `tuple`s.

2023-04-05 02:29 UTC, tscrim commented
I see; I didn't notice that. Thanks for checking.

2023-04-13 22:55 UTC, merged