Use PARI implementation of Frobenius morphism
sagemath/sage pull request #35316
Opened 2023-03-20 11:07 UTC by remyoudompheng

### 📚 Description

This pull request uses PARI `fffrobenius` and `ffmap` to implement the p-th power map for Finite fields using the PARI implementation (issue #4625).

It does not seem necessary to implement a similar thing for the Givaro implementation (where exponentiation is very fast) or the NTL implementation (only for characteristic 2).

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2023-03-20 11:11 UTC, remyoudompheng commented
As opposed to suggestions in the linked issue, it does not use a matrix method, although this could be implemented concisely using this snippet:
```
# Cache these elements
ap = (K.gen().frobenius()).powers(degree)
# Compute
def frobenius(x): sum(z * a for z, a in zip(x.list(), ap))
```

The linear method needs to cache O(d) field elements, whereas PARI field morphism are defined by the image of the single generator, using less memory. For practical field sizes, the difference remains small and both methods are vastly more efficient than exponentiation, except for extremely small characteristics or very large extension degrees.

Performance numbers are as follows: for a 16-bit prime, the simple exponentiation is faster than PARI field morphisms only for degrees > 128.

```
p size = 128 bits, degree=2
old 625 loops, best of 3: 205 μs per loop
new 625 loops, best of 3: 3.69 μs per loop

p size = 128 bits, degree=64
old 25 loops, best of 3: 21.1 ms per loop
new 125 loops, best of 3: 2.44 ms per loop

p size = 1024 bits, degree=2
old  125 loops, best of 3: 4.07 ms per loop
new 625 loops, best of 3: 5.06 μs per loop

p size = 1024 bits, degree=128
old 5 loops, best of 3: 3.23 s per loop
new 5 loops, best of 3: 65.5 ms per loop
```

2023-03-23 14:51 UTC, tscrim requested changes

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/element_pari_ffelt.pyx
> +        - ``k`` -- integer (default: 1, must fit in C int type)
```suggestion
        r"""
        Return the `(p^k)^{th}` power of ``self``, where `p` is the
        characteristic of the field.

        INPUT:

        - ``k`` -- integer (default: 1); must fit in a C ``int``
```

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/element_pari_ffelt.pyx
> +    def pth_power(FiniteFieldElement_pari_ffelt self, int k = 1):
```suggestion
    def pth_power(FiniteFieldElement_pari_ffelt self, int k=1):
```

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/element_pari_ffelt.pyx
> +            return self**p
```suggestion
        """
        cdef int n = int(self._parent.degree())
        if k % n == 0:
            return self
        cdef Integer p = self._parent.characteristic()
        if k == 1 and (p < 100 or p.bit_length()**2 < n):
            # For extremely small primes or very large extension degrees,
            # exponentiation is faster.
            return self ** p
```

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/finite_field_pari_ffelt.py
> +            self.__pari_frobenius_powers.append(g.__pari__().fffrobenius(i+1))
```suggestion
        g = self.gen()
        i = len(self.__pari_frobenius_powers)
        while i < k:
            i += 1
            self.__pari_frobenius_powers.append(g.__pari__().fffrobenius(i))
```

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/finite_field_pari_ffelt.py
> +        self.__pari_frobenius_powers = None
```suggestion
        self.__pari_frobenius_powers = []
```

2023-03-23 14:51 UTC, tscrim commented on src/sage/rings/finite_rings/finite_field_pari_ffelt.py
> +            self.__pari_frobenius_powers = []
```suggestion
```
Better to just initialize this outright.

2023-03-23 18:06 UTC, remyoudompheng commented
Updated with review comments and updated commit message (Brent-Kung complexity is sqrt(degree))

2023-03-24 01:03 UTC, tscrim approved these changes
Thank you. LGTM.

2023-04-06 23:07 UTC, merged