Many more namespace packages
sagemath/sage pull request #35322
Opened 2023-03-21 03:27 UTC by mkoeppe

### 📚 Description
As discussed in https://github.com/sagemath/sage/pull/35100#issuecomment-1477174851, we remove many of the empty `__init__.py` files, turning these packages into PEP-420 implicit namespace packages.

### 📝 Checklist

- [x] I have made sure that the title is self-explanatory and the description concisely explains the PR.
- [x] I have linked an issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### ⌛ Dependencies

2023-03-21 17:26 UTC, mkoeppe commented
@tornaria There is only one doctest failure, for `sage.misc.dev_tools.load_submodules`, which is due to the long-standing issue https://github.com/python/cpython/issues/73444

I don't know if we care much about this function, but we can repair it using our function `sage.misc.package_dir.is_package_or_sage_namespace_package_dir`.

2023-03-22 02:32 UTC, tornaria commented
1. issue with sage.symbolic.integration
```
sage: import sage.symbolic.integration.integral
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import sage.symbolic.integration.integral

ModuleNotFoundError: No module named 'sage.symbolic.integration'
```

I think you need to `touch src/sage/symbolic/integration/all.py`

2. doctest failure in `src/sage/misc/package_dir.py`
```
sage -t --long --random-seed=247137144307186708220921933273202299041 src/sage/misc/package_dir.py
**********************************************************************
File "src/sage/misc/package_dir.py", line 180, in sage.misc.package_dir.is_package_or_sage_namespace_package_dir
Failed example:
    directory = os.path.join(os.path.dirname(sage.symbolic.__file__), 'ginac'); directory
Exception raised:
    Traceback (most recent call last):
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.package_dir.is_package_or_sage_namespace_package_dir[7]>", line 1, in <module>
        directory = os.path.join(os.path.dirname(sage.symbolic.__file__), 'ginac'); directory
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 152, in dirname
    TypeError: expected str, bytes or os.PathLike object, not NoneType
**********************************************************************
File "src/sage/misc/package_dir.py", line 182, in sage.misc.package_dir.is_package_or_sage_namespace_package_dir
Failed example:
    is_package_or_sage_namespace_package_dir(directory)
Expected:
    False
Got:
    True
**********************************************************************
1 item had failures:
   2 of  10 in sage.misc.package_dir.is_package_or_sage_namespace_package_dir
    [29 tests, 2 failures, 0.02 s]
----------------------------------------------------------------------
```
The following fixes it for me:
```diff
diff --git a/src/sage/misc/package_dir.py b/src/sage/misc/package_dir.py
index bb4e34d5c26..d4e5cb3bc7a 100644
--- a/src/sage/misc/package_dir.py
+++ b/src/sage/misc/package_dir.py
@@ -155,7 +155,7 @@ def is_package_or_sage_namespace_package_dir(path, *, distribution_filter=None):
     :mod:`sage.cpython` is an ordinary package::
 
         sage: from sage.misc.package_dir import is_package_or_sage_namespace_package_dir
-        sage: directory = os.path.dirname(sage.cpython.__file__); directory
+        sage: directory = sage.cpython.__path__[0]; directory
         '.../sage/cpython'
         sage: is_package_or_sage_namespace_package_dir(directory)
         True
@@ -163,21 +163,21 @@ def is_package_or_sage_namespace_package_dir(path, *, distribution_filter=None):
     :mod:`sage.libs.mpfr` only has an ``__init__.pxd`` file, but we consider
     it a package directory for consistency with Cython::
 
-        sage: directory = os.path.join(os.path.dirname(sage.libs.all.__file__), 'mpfr'); directory
+        sage: directory = os.path.join(sage.libs.__path__[0], 'mpfr'); directory
         '.../sage/libs/mpfr'
         sage: is_package_or_sage_namespace_package_dir(directory)
         True
 
     :mod:`sage` is designated to become an implicit namespace package::
 
-        sage: directory = os.path.dirname(sage.env.__file__); directory
+        sage: directory = sage.__path__[0]; directory
         '.../sage'
         sage: is_package_or_sage_namespace_package_dir(directory)
         True
 
     Not a package::
 
-        sage: directory = os.path.join(os.path.dirname(sage.symbolic.__file__), 'ginac'); directory
+        sage: directory = os.path.join(sage.symbolic.__path__[0], 'ginac'); directory
         '.../sage/symbolic/ginac'
         sage: is_package_or_sage_namespace_package_dir(directory)
         False
```

3. doctest failure in `src/sage/symbolic/pynac.pxi`:
```
sage -t --long --random-seed=167829029651056083008002563228240301164 src/sage/symbolic/pynac.pxi
**********************************************************************
File "src/sage/symbolic/pynac.pxi", line 6, in sage.symbolic.pynac
Failed example:
    cython(  # long time; random compiler warnings  # optional - sage.misc.cython
    '''
    from sage.symbolic cimport expression
    ''')
Exception raised:
    Traceback (most recent call last):
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/misc/cython.py", line 358, in cython
        ext, = cythonize([ext],
               ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1112, in cythonize
        cythonize_one(*args)
      File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1235, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: /tmp/tmpefpazx19/spyx/_tmp_tmp9_e5gg0j_tmp_hmvet0wv_pyx/_tmp_tmp9_e5gg0j_tmp_hmvet0wv_pyx_0.pyx

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.symbolic.pynac[0]>", line 1, in <module>
        cython(  # long time; random compiler warnings  # optional - sage.misc.cython
      File "sage/misc/lazy_import.pyx", line 404, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:4483)
        return self.get_object()(*args, **kwds)
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/misc/cython.py", line 673, in cython_compile
        return cython_import_all(tmpfile, get_globals(), **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/misc/cython.py", line 563, in cython_import_all
        m = cython_import(filename, **kwds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/misc/cython.py", line 534, in cython_import
        name, build_dir = cython(filename, **kwds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/tornaria/src/sage/sage-git/pkgs/sagemath-standard/build/lib.linux-x86_64-cpython-311/sage/misc/cython.py", line 374, in cython
        raise RuntimeError(cython_messages.strip())
    RuntimeError: Error compiling Cython file:
    ------------------------------------------------------------
    ...

    from sage.symbolic cimport expression
    ^
    ------------------------------------------------------------

    _tmp_tmp9_e5gg0j_tmp_hmvet0wv_pyx_0.pyx:2:0: 'sage/symbolic.pxd' not found
**********************************************************************
1 item had failures:
   1 of   2 in sage.symbolic.pynac
    [1 test, 1 failure, 0.01 s]
```

2023-03-22 02:49 UTC, tornaria commented
BTW, I noticed that the function `is_package_or_sage_namespace_package_dir` has an optional argument (`distribution_filter`) that is neither tested nor used anywhere that I could find...

2023-03-22 03:11 UTC, mkoeppe commented
> from sage.symbolic cimport expression
>     ^
>     ------------------------------------------------------------
> 
>     _tmp_tmp9_e5gg0j_tmp_hmvet0wv_pyx_0.pyx:2:0: 'sage/symbolic.pxd' not found

OK, this is from an unpatched Cython without namespace package support.
I guess I'll wrap a `with cython_namespace_package_support()` around it.

2023-03-22 03:20 UTC, mkoeppe commented
> I guess I'll wrap a `with cython_namespace_package_support()` around it.

Hm, no, that is already used in `sage.misc.cython`.

2023-03-22 03:23 UTC, mkoeppe commented
I can't reproduce this failure here, also not with stock Cython 0.29.33 installed via pip

2023-03-22 03:30 UTC, mkoeppe commented
> I noticed that the function `is_package_or_sage_namespace_package_dir` has an optional argument (`distribution_filter`) that is neither tested nor used anywhere that I could find...

I think the first use of that is on one of the pending tickets from #29705. I'll check later

2023-03-22 11:19 UTC, tornaria commented
> > ```diff
> >     Not a package::
> >  
> > -        sage: directory = os.path.join(os.path.dirname(sage.symbolic.__file__), 'ginac'); directory
> > +        sage: directory = os.path.join(sage.symbolic.__path__[0], 'ginac'); directory
> >          '.../sage/symbolic/ginac'
> >          sage: is_package_or_sage_namespace_package_dir(directory)
> >          False
> > ```
> 
> I think only this last example needs to be adjusted; the preceding examples are modules or ordinary packages.

Yes, but using `__path__[0]` seems more robust as it will work for either ordinary or namespace packages. It's shorter, and it's really what you mean, i.e. path to module `mpfr` inside package `sage.libs`.

2023-03-22 11:19 UTC, tornaria commented
> > from sage.symbolic cimport expression
> > ^
> > ------------------------------------------------------------
> > ```
> > _tmp_tmp9_e5gg0j_tmp_hmvet0wv_pyx_0.pyx:2:0: 'sage/symbolic.pxd' not found
> > ```
> 
> OK, this is from an unpatched Cython without namespace package support. I guess I'll wrap a `with cython_namespace_package_support()` around it.

I'll have a look and patch our Cython if it's necessary.

2023-03-22 12:37 UTC, tornaria commented
> I can't reproduce this failure here, also not with stock Cython 0.29.33 installed via pip

Did you test with `--long` ? Our cython is stock 0.29.33, unpatched, compiled from pypi source using setuptools, nothing strange AFAICT. I will add the namespaces patch and I guess everything will work for us, although I guess it'd be nice to support an unpatched cython (?).

Maybe `with cython_namespace_package_support()` does not work as expected? It's not tested, and maybe nothing really `cimport`ed from a namespace package before this PR.

2023-03-23 20:29 UTC, mkoeppe commented
> > I can't reproduce this failure here, also not with stock Cython 0.29.33 installed via pip
> 
> Did you test with `--long` ?

Oh... now I can reproduce it, thanks...

2023-03-23 20:54 UTC, tornaria commented
Also, note that
```
cython("cimport sage.symbolic.expression")
```
works, but
```
cython("cimport sage.symbolic")
```
doesn't (same failure as `from sage.symbolic cimport expression`).

Is the second one supposed to work? Both that one and the original failure work ok when `.../sage/symbolic/__init__.py` is present, so I'm guessing the answer is yes.

In the same style, should `cimport sage` work?

2023-03-23 21:13 UTC, tornaria commented
Also, note that
```
cython("cimport sage.symbolic.expression")
```
works, but
```
cython("cimport sage.symbolic")
```
doesn't (same failure as `from sage.symbolic cimport expression`).

Is the second one supposed to work? Both that one and the original failure work ok when `.../sage/symbolic/__init__.py` is present, so I'm guessing the answer is yes.

In the same style, should `cimport sage` work?

Nothing here changes with patched vs. unpatched cython.

2023-03-23 21:14 UTC, mkoeppe commented
> Is the second one supposed to work?

It would be worth checking what Cython 3 thinks about this.

2023-03-24 02:46 UTC, tornaria commented
Summary:
 - `cimport sage.symbolic.expression` needs either the patch (4918.patch) or the `cython_namespace_package_support()` hack.
 - `from sage.symbolic.expression cimport is_Expression` works fine, no need for patch or hack.
 - `from sage.symbolic import expression` this is broken and it's not fixed neither with the patch nor with the hack.

Here is a short term workaround:
```diff
--- a/src/sage/symbolic/pynac.pxi
+++ b/src/sage/symbolic/pynac.pxi
@@ -3,9 +3,9 @@ Declarations for pynac, a Python frontend for ginac
 
 Check that we can externally cimport this (:trac:`18825`)::
 
-    sage: cython(  # long time; random compiler warnings  # optional - sage.misc.cython
+    sage: cython(  # optional - sage.misc.cython
     ....: '''
-    ....: from sage.symbolic cimport expression
+    ....: cimport sage.symbolic.expression
     ....: ''')
 """
 
```
I removed the # long time and random since I don't think it's necessary, you may know better...

The long term solution is for cython to fix its pep 420 support.

Meanwhile, it would be nice to add the following tests:
```diff
---- a/src/sage/misc/cython.py
+++ b/src/sage/misc/cython.py
@@ -211,6 +211,28 @@ def cython(filename, verbose=0, compile_message=False,
         sage: cython('''
         ....: cdef size_t foo = 3/2
         ....: ''')
+
+    Check that Cython supports PEP 420 packages::
+
+        sage: cython('''
+        ....: cimport sage.misc.cachefunc
+        ....: ''')
+
+        sage: cython('''
+        ....: from sage.misc.cachefunc cimport cache_key
+        ....: ''')
+
+    In Cython 0.29.33 using `from PACKAGE cimport MODULE` is broken
+    when `PACKAGE` is a namespace package, see :trac:`35322`::
+
+        sage: cython('''
+        ....: from sage.misc cimport cachefunc
+        ....: ''')
+        Traceback (most recent call last):
+        ...
+        RuntimeError: Error compiling Cython file:
+        ...
+        ...: 'sage/misc.pxd' not found
     """
     if not filename.endswith('pyx'):
         print("Warning: file (={}) should have extension .pyx".format(filename), file=sys.stderr)
```
The last one is the broken one, this will warn us when it gets fixed...

2023-03-24 02:50 UTC, tornaria commented
Also, just `cimport sage.misc` is broken atm, and it should also work (the point is that namespace packages should be functionally identically to standard packages, so anything that works when an empty `__init__.py` file is there, should also work without it). Maybe we should also add a test for that situation and corresponding explanation (i.e. `cimport PACKAGE` is broken when `PACKAGE` is a namespace package, just like `from PACKAGE cimport MODULE`).

2023-03-25 00:35 UTC, mkoeppe commented
Excellent, thanks very much. Yes, I agree with your fixes; I'll put them on the branch.

2023-03-25 01:03 UTC, tornaria commented
> > > ```diff
> > >     Not a package::
> > >  
> > > -        sage: directory = os.path.join(os.path.dirname(sage.symbolic.__file__), 'ginac'); directory
> > > +        sage: directory = os.path.join(sage.symbolic.__path__[0], 'ginac'); directory
> > >          '.../sage/symbolic/ginac'
> > >          sage: is_package_or_sage_namespace_package_dir(directory)
> > >          False
> > > ```
> > 
> > 
> > I think only this last example needs to be adjusted; the preceding examples are modules or ordinary packages.
> 
> Yes, but using `__path__[0]` seems more robust as it will work for either ordinary or namespace packages. It's shorter, and it's really what you mean, i.e. path to module `mpfr` inside package `sage.libs`.

You didn't respond to this. I still think using `__path__[0]` is way better than using either `__file__` or `.all.__file__` because (a) which one you use depends on whether the package is one way or another; (b) you need to assume much more about the layout of the package; and (c) you need to use `os.path.dirname()` making the whole thing longer and less readable.

Do you see any drawback to changing all the tests as I suggested?

2023-03-25 01:05 UTC, mkoeppe commented
OK, I will push these changes too

2023-03-25 01:11 UTC, tornaria commented
> OK, I will push these changes too

Thanks, I'll clean up my worktree and test the PR as it is now, just to double check everything is ok, then approve since everything looks good now.

2023-03-25 02:16 UTC, tornaria commented
For the record, list of empty `__init__`  files after this PR:
```
$ find src/sage -size 0 | grep __init__ | sort
src/sage/docs/__init__.py
src/sage/groups/perm_gps/partn_ref/__init__.py
src/sage/groups/perm_gps/partn_ref2/__init__.py
src/sage/libs/arb/__init__.py
src/sage/libs/coxeter3/__init__.py
src/sage/libs/cremona/__init__.py
src/sage/libs/eclib/__init__.py
src/sage/libs/flint/__init__.py
src/sage/libs/glpk/__init__.py
src/sage/libs/gmp/__init__.py
src/sage/libs/gsl/__init__.py
src/sage/libs/lcalc/__init__.py
src/sage/libs/linbox/__init__.py
src/sage/libs/linkages/__init__.py
src/sage/libs/linkages/padics/__init__.py
src/sage/libs/linkages/padics/relaxed/__init__.py
src/sage/libs/lrcalc/__init__.py
src/sage/libs/mpmath/__init__.py
src/sage/libs/mwrank/__init__.py
src/sage/libs/pynac/__init__.py
src/sage/libs/singular/__init__.py
src/sage/libs/symmetrica/__init__.py
src/sage/repl/display/__init__.py
src/sage/repl/ipython_kernel/__init__.py
src/sage/structure/proof/__init__.py
src/sage/tests/__init__.py
src/sage/tests/books/computational-mathematics-with-sagemath/__init__.py
src/sage/tests/books/computational-mathematics-with-sagemath/sol/__init__.py
src/sage/tests/books/judson-abstract-algebra/__init__.py
```

What is the criteria to keep these?

2023-03-25 18:31 UTC, tornaria commented
Everything works ok for me on https://github.com/sagemath/sage/pull/35322/commits/dc8b3c50d849746ec69e11b45ebc33ceb9e3d0e4.

I'm approving, although I'm still wondering about the 29 empty `__init__.py` files I listed above.

In addition, among the 25 nonempty `__init__.*` there are 5 that seem equivalent to empty:
 - `src/sage/combinat/words/__init__.py` -- just a docstring
 - `src/sage/ext/interpreters/__init__.py` -- autogenerated, just a comment
 - `src/sage/libs/polybori/__init__.pxd` -- just a comment  ("to prevent repo corruption" ?)
 - `src/sage/modules/with_basis/__init__.py` -- just a docstring
 - `src/sage/structure/__init__.py`-- resolve a cyclic import (?)

2023-03-25 18:31 UTC, tornaria approved these changes

2023-03-25 18:44 UTC, tornaria commented
About my original concern of package conflicts between system installed sagemath vs. user installed one, I propose the following approach:
 - For system installed sagemath, we ask distro maintainers to remove every empty `__init__.py` file, so they will never show up in the system `site-packages`, i.e. they are namespace packages in the system tree.
 - From now on when some package in sagemath needs to be switched from "standard" to "namespace" proceed as follows:
   - if the package is standard because of an empty `__init__.*` file, just remove the file
   - if the package is standard because of a non-empty `__init__.*` file, require two releases of sagemath: in the first release, everything in the `__init__.*` file is rearranged as necessary, but *an empty `__init__.py` file is kept*; in the second release, the empty `__init__.py` file can be removed.

This ensures that we avoid conflicts with system packages. Anything having an empty  `__init__.py` file is a standard package in a user installation, but a namespace package in system installation, so it can be safely switched to fully namespace package. Anything having a non-trivial `__init__.*` file is a standard package in system installation so *it can't be switched to namespace package in development versions right away* (has to wait for a new release so distros have time to adjust)

2023-03-25 18:44 UTC, mkoeppe commented
Thanks! Sorry for the slowness in responding to your comments.

> For the record, list of empty `__init__` files after this PR:
> 
> ```
> $ find src/sage -size 0 | grep __init__ | sort
> src/sage/docs/__init__.py

`sage.docs` only has deprecated stuff in it and will disappear soon.

> src/sage/groups/perm_gps/partn_ref/__init__.py
> src/sage/groups/perm_gps/partn_ref2/__init__.py

I kept these because they looked "self-contained" to me, but it's fine with me to remove them.

> src/sage/libs/arb/__init__.py
> src/sage/libs/coxeter3/__init__.py
> [...]
> src/sage/libs/singular/__init__.py
> src/sage/libs/symmetrica/__init__.py

Quite likely, each of these can remain an ordinary package; we can look into this in more detail in a follow up.

> src/sage/repl/display/__init__.py
> src/sage/repl/ipython_kernel/__init__.py
> src/sage/structure/proof/__init__.py

All of `sage.repl` and all of `sage.structure` is intended to remain monolithic (see PR description above); and namespace packages within ordinary packages make no sense

> src/sage/tests/__init__.py
> src/sage/tests/books/computational-mathematics-with-sagemath/__init__.py
> src/sage/tests/books/computational-mathematics-with-sagemath/sol/__init__.py
> src/sage/tests/books/judson-abstract-algebra/__init__.py
> ```

Kept these because I don't have a plan for what to do with sage.tests yet. Likely to remain monolithic.

> In addition, among the 25 nonempty `__init__.*` there are 5 that seem equivalent to empty:
> 
> * `src/sage/combinat/words/__init__.py` -- just a docstring

OK, we can take care of the docstring using `sage.misc.namespace_package.install_doc`

> * `src/sage/ext/interpreters/__init__.py` -- autogenerated, just a comment

Follow-up PR

> * `src/sage/libs/polybori/__init__.pxd` -- just a comment  ("to prevent repo corruption" ?)

Monolithic 

> * `src/sage/modules/with_basis/__init__.py` -- just a docstring
> * `src/sage/structure/__init__.py`-- resolve a cyclic import (?)

Monolithic by design

2023-03-25 18:47 UTC, mkoeppe commented
> About my original concern of package conflicts between system installed sagemath vs. user installed one, I propose the following approach: [...]

Sounds good to me. PR to add this to `src/doc/en/developer/packaging_sage_library.rst`?

2023-03-31 22:42 UTC, tornaria requested changes
I'm removing my approval for this until all the troublesome interaction between system sagemath and development sagemath is sorted out.

2023-04-01 00:39 UTC, mkoeppe commented
@tornaria, the idea of such a configuration -- old incompatible Sage installed in system package, and hoping that the development Sage shadows it properly -- is just fundamentally flawed and cannot be supported. It's not just namespace packages vs old ordinary packages. Also when a Python module in the new version replaces a Cython module of the same name (as happened recently with `sage.geometry.lattice_points`, the old Cython module would continue to win.

2023-04-01 00:42 UTC, mkoeppe commented
As I wrote to your privately, if you need this for some reason (likely because your platform or workflow is not compatible with / aware of venvs), just putting an empty file `src/sage/__init__.py` will make `sage` an ordinary package, which will shadow everything that comes after it in the search path.

2023-04-01 01:01 UTC, tornaria commented
> As I wrote to your privately, if you need this for some reason (likely because your platform or workflow is not compatible with / aware of venvs), just putting an empty file `src/sage/__init__.py` will make `sage` an ordinary package, which will shadow everything that comes after it in the search path.

I will test this and report back.

The statement that there is no way to support a (quite up to date) system package of sagemath simultaneously with a development version of sagemath where I don't have to build infinite stuff other than the sagelib itself, it's very discouraging.

I'm willing to change my workflow, as long as it doesn't mean using a local "venv" in which I have to replicate all python packages that I already have installed in my system. It seems your idea will solve that.

Seriously, my workflow is very, very, lean, and it's a world of difference compared to anything else I knew before, that I'd rather stop using sage than go back to `./configure ; make`  (not to mention the download size). I think it takes less time to build sagelib (from a clean git checkout) than the time it takes just to run `./configure`.

2023-04-01 01:12 UTC, mkoeppe commented
On Fri, Mar 31, 2023 at 6:01 PM Gonzalo Tornaría ***@***.***>
wrote:

> I'm willing to change my workflow, as long as it doesn't mean using a
> local "venv" in which I have to replicate all python packages that I
> already have installed in my system. It seems your idea will solve that.
>
> I think distro package maintainers of Python packages should look into
providing PEP-660 "editable wheels" that correspond to packages installed
in system site-packages. (They wouldn't be really editable because it would
point to a root-owned location.) It's basically a mechanism to install a
symlink farm using Python packaging infrastructure.

This would allow users to provision venvs that contain selected
distribution-provided Python packages (instead of installing them from pip).

Matthias
-- 
Dr. Matthias Koeppe . . . . . . . . http://www.math.ucdavis.edu/~mkoeppe
Professor of Mathematics

2023-04-04 19:16 UTC, tornaria approved these changes

2023-04-04 19:32 UTC, tornaria commented
The solution of creating an empty `sage/__init__.py` file in the sagelib I'm testing works perfectly to isolate it from an "old" sage installed in the system site-packages.

I've tested both this PR and #35366 in this way, with sagemath 9.8 installed from system, without having to adjust anything in the system package.

Thus, I'm giving back my positive review / approval for this PR, which I had already looked at. Thanks for your patience.

2023-04-04 19:33 UTC, mkoeppe commented
Glad that this is working for you! Thanks for the review.

2023-04-06 23:07 UTC, merged