allow non-minimal equation for padic heights
sagemath/sage pull request #35614
Opened 2023-05-05 14:27 UTC by chriswuthrich

### :books: Description

Fixes #34790

The `p`-adic height calculations on an elliptic curve assumed that the equation was minimal.
This is fixed as well as some docstring formatting.

### :memo: Checklist

- `[x ]` The title is concise, informative, and self-explanatory.
- `[x ]` The description explains in detail what this PR is about.
- `[x ]` I have linked a relevant issue or discussion.
- `[x ]` I have created tests covering the changes.
- `[x ]` I have updated the documentation accordingly.

(My first pull request, tell me if I am doing something wrong or where I need to read up on how we do things now.)

2023-05-05 17:51 UTC, chriswuthrich commented
I don't understand the error in pycodestyle. Line 332 in constructor.py is ```When constructing a curve over `\QQ` from a Cremona or LMFDB``` and that has no "\Q" but a "\QQ" as it should.

2023-05-06 09:24 UTC, fchapoton commented
> I don't understand the error in pycodestyle. Line 332 in constructor.py is `` When constructing a curve over `\QQ` from a Cremona or LMFDB `` and that has no "\Q" but a "\QQ" as it should.

You just need to start any doctest containing latex macros with `r"""` instead of `"""`.

2023-05-06 12:04 UTC, chriswuthrich commented
> You just need to start any doctest containing latex macros with `r"""` instead of `"""`.

Oh, of course, thanks a lot for the help, Frédéric. I am a bit rusty.

2023-05-06 13:41 UTC, chriswuthrich commented
This is ready for review in component "elliptic curves". (Can I add labels myself?)
Maybe @JohnCremona knows who could be ready to look at the changes.

2023-05-07 11:08 UTC, JohnCremona commented
I will review this

2023-05-09 10:00 UTC, JohnCremona requested changes
Looks very good.  Th ecomments are all trivial, partly to keep codecov happy

2023-05-09 10:00 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +            if Emin.discriminant() %p != 0:
You could omit the !=0

2023-05-09 10:00 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +        otherbad = [p for p in otherbad if u%p != 0 ]
You could omit the !=0

2023-05-09 10:00 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +        st = ("This only implemented for integral models. "
add a doctest for this error

2023-05-09 10:00 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +                li.append(E.tamagawa_number(p) * (p-1) * p**(np-1))
perhaps add a doctest for this (split multiplicative) branch

2023-05-09 10:00 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +                li.append(E.tamagawa_number(p) * (p+1) * p**(np-1))
again, perhaps add a doctest for this

2023-05-09 16:46 UTC, chriswuthrich commented on src/sage/schemes/elliptic_curves/padics.py
> +            if Emin.discriminant() %p != 0:
I prefer keeping it. Old habit to think like a mathematician: I think they increase the readability of the code, but don't slow it down significantly. But you insist, I am ok taking it off.

2023-05-09 19:01 UTC, chriswuthrich commented on src/sage/schemes/elliptic_curves/padics.py
> +        st = ("This only implemented for integral models. "
imho: raise ValueError for arguments of the wrong type should not have a test. The worst that could happen is that we get the wrong kind of error.
But I will add one.

2023-05-09 20:58 UTC, chriswuthrich commented
The added commits contain the requested doctests in padics.py. And it corrects my earlier changes of "√élu". It now  reads "square-root Vélu" instead. A discussion on this issue took place in the pull request #35626 . I am open for a larger discussion of this question and change it back to  "√élu".

2023-05-09 21:00 UTC, chriswuthrich commented
I have clicked on "resolved" on the three reviewer's comments above that I think I have resolved. I don't know if that is my job or the reviewers' job.

2023-05-10 07:20 UTC, JohnCremona commented
Probably my job to mark them as resolved, I will look again soon

2023-05-10 07:35 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +            if Emin.discriminant() %p != 0:
I don't insist (I do the same) but some python purists might

2023-05-10 07:35 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/padics.py
> +        otherbad = [p for p in otherbad if u%p != 0 ]
as above

2023-05-10 07:37 UTC, JohnCremona approved these changes

2023-05-22 23:03 UTC, vbraun commented
Merge conflict

2023-06-01 11:08 UTC, JohnCremona commented
I'll switch this back to +ve review when tests pass

2023-06-03 23:32 UTC, vbraun commented
Merge conflict

2023-06-11 10:37 UTC, merged