Russian tableau and minor bug fixes
sagemath/sage pull request #35645
Opened 2023-05-16 08:37 UTC by thecaligarmo

### :books: Description

Tableaux have three different representations: English, French and Russian. Two of these representations are the most common and have been already integrated into sage (English and French notation). This will add the Russian notation/representation into sage for use by people who will need it.

Additionally, there was a bug in `plot` when descents were set to `True`. This has been corrected as well.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

There are no dependencies.

2023-05-16 11:02 UTC, thecaligarmo commented
Ok, I've updated the files to work properly with the lint/style checker. It looks like it's working now.

2023-05-19 08:11 UTC, tscrim commented
A few quick comments:

- It looks strange to have the boxes cut off in the ascii art. It also doesn't match the empty tableau behavior (which looks like a single box, and I would suggest changing).
- Use `"""` instead of `'''`.
- You're not responsible for any linter/style checkers on lines you don't write. While good to have it done, it can create unnecessary (merge) conflicts.
- ...and since you changed the line, could you also remove the unnecessary parentheses `while (l[i] == 0):` (and similar).

2023-05-25 15:20 UTC, thecaligarmo commented
> A few quick comments:
> 
>     * It looks strange to have the boxes cut off in the ascii art. It also doesn't match the empty tableau behavior (which looks like a single box, and I would suggest changing).
> 
>     * Use `"""` instead of `'''`.
> 
>     * You're not responsible for any linter/style checkers on lines you don't write. While good to have it done, it can create unnecessary (merge) conflicts.
> 
>     * ...and since you changed the line, could you also remove the unnecessary parentheses `while (l[i] == 0):` (and similar).

Sounds good. I've implemented all the fixes you wanted. 

The behaviour of the "single box" matches the single box behaviour for the normal tableau (it still looks like a single box). An alternative is to maybe just have it return a "." or an "X"?

Some things that this doesn't implement: "weird" tableaux. So for example if the data is something like:
```[[None, None, 1], [2, 2], [3,4,5], [None, None, 10], [], [6]]``` then it wouldn't show up properly. This use case seems minimal currently, but should be something for a later update.

2023-05-26 02:03 UTC, tscrim commented
That is an interesting corner case:
```
sage: Tableaux.options.ascii_art = "table"
sage: ascii_art(Tableau([]))
++
++
sage: ascii_art(Tableau([[None]]))
     
     
     
sage: unicode_art(Tableau([]))
┌┐
└┘
sage: unicode_art(Tableau([[None]]))
     
     
     
```
which is very strange IMO. There appears to be a deliberate choice for this made long ago. However, I think in keep with "equivalent" skew tableau representations, it should just return blank in all cases.

2023-05-26 08:41 UTC, thecaligarmo commented
Agreed. I'll make that change and push it next week. Was all the other things looking ok? And is it ok that I'm not implementing *all* tableaux for the Russian notation?

2023-05-26 08:56 UTC, tscrim commented
Yes, I believe everything else is okay.

2023-05-26 14:26 UTC, thecaligarmo commented
Sounds good. Looking at the code, I'm thinking this change might be a little more complicated than we'd imagine. Basically what's happening is that they count a ```None``` as a box that doesn't exist; not as a box with no value (which is what I had assumed it to be). So I'll need to update the "Russian" version this accordingly.
For now, if the data being put into a tableau is just empty (is ```None``` or is ```''``` then I'm going to have it return ```''```)

2023-05-27 07:18 UTC, tscrim commented
If I'm understanding what you're saying correctly, it's fine to only consider the actually empty (skew) tableau data of `[]` and have it return `''``. I wouldn't worry too much about if there was a difference in output with `[[None]]` in the Russian notation output. (There can be good reasons to not actually equate the two.)

2023-06-03 13:09 UTC, thecaligarmo commented
Ok, so I redid it so that it handles all types of Tableaux. This is because the way I was handling `None` and the way the other ascii art was handling `None` was different. So they should be in sync now. This should be good to go unless there are other things to check (or if you want anything altered)

2023-06-04 03:02 UTC, tscrim requested changes
Thank you. It looks good. Just a few other little things, but that's it.

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/tableau.py
> +        If Russian notation is set, we tilt the French by 45 degrees:
```suggestion
        If Russian notation is set, we tilt the French notation by 45 degrees:
```
At least, I don't think you want to make every French person live at a 45 degree angle. `:P`

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/tableau.py
> +            max_height = max([a + len(str_tab[a]) for a in range(len(str_tab))])
```suggestion
            max_height = max(a + len(val) for a, val in enumerate(str_tab))
```

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/tableau.py
> +            mm = min([len(re.search('^ +', sline)[0]) for sline in str_list]) - 1
```suggestion
            mm = min(len(re.search('^ +', sline)[0]) for sline in str_list) - 1
```

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/output.py
> +    return (len(tab[i:]) > 0 and len(tab[i][j:]) > 0 and tab[i][j] is not None)
This function needs a doctest. I think it can also be made a bit faster by
```suggestion
def box_exists(tab, i, j):
    """
    For Russian tableaux, it checks if a certain box exists or not.
    """
    if j < 0 or i < 0:
        return False
    return len(tab) >= i and len(tab[i]) >=j and tab[i][j] is not None
```
or possibly
```
return bool(tab[i:]) and bool(tab[i][j:]) and tab[i][j] is not None
```

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/output.py
> +    mm = min([len(re.search('^ +', l)[0]) for l in str_list]) - 1
```suggestion
    mm = min(len(re.search('^ +', l)[0]) for l in str_list) - 1
```

2023-06-04 03:02 UTC, tscrim commented on src/sage/combinat/output.py
> +    max_height = max([a + len(str_tab[a]) for a in range(len(str_tab))])
```suggestion
    row_height = int((diag_length + 1) // 2)
    max_height = max(a + len(val) for a, val in enumerate(str_tab))
```

2023-06-04 07:44 UTC, thecaligarmo commented on src/sage/combinat/tableau.py
> +        If Russian notation is set, we tilt the French by 45 degrees:
All the French!

2023-06-04 08:02 UTC, thecaligarmo commented
Is this kind of what you had  in mind for doc tests? Like just more info?

I'm wondering if for `box_exists`, since it's only used for Russian notation, I'm wondering if it makes more sense to just define it within the function `ascii_art_table_russian` itself? Kind of like how we do it for `get_len`?

2023-06-04 08:08 UTC, thecaligarmo commented
Side note: Looks like `pycodestyle` is failing at:
```
./sage/algebras/commutative_dga.py:3891:1: W293 blank line contains whitespace
3       E303 too many blank lines (2)
1       W293 blank line contains whitespace
```
Which is not a file that was altered by us.  I tried updating the branch, but it didn't fix it.

2023-06-05 01:04 UTC, tscrim commented on src/sage/combinat/output.py
> +        - ``j`` -- Second coordinate
```suggestion
   r """
    Return ``True`` if ``tab[i][j]`` exists and is not ``None``; in particular this
    allows for `tab[i][j]` to be ``''`` or ``0``.

    INPUT:

    - ``tab`` -- a list of lists
    - ``i`` -- first coordinate
    - ``j`` -- second coordinate
```

2023-06-05 01:05 UTC, tscrim commented
> Is this kind of what you had in mind for doc tests? Like just more info?
> 
> I'm wondering if for `box_exists`, since it's only used for Russian notation, I'm wondering if it makes more sense to just define it within the function `ascii_art_table_russian` itself? Kind of like how we do it for `get_len`?

It just needed at least one doctest (Sage policy that all functions have at least one doctest). I wouldn't be opposed to putting it inline, but you've already done the work and there is no problem having it as a standalone like this.

2023-06-05 01:07 UTC, tscrim commented
> Side note: Looks like `pycodestyle` is failing at:
> 
> ```
> ./sage/algebras/commutative_dga.py:3891:1: W293 blank line contains whitespace
> 3       E303 too many blank lines (2)
> 1       W293 blank line contains whitespace
> ```
> 
> Which is not a file that was altered by us. I tried updating the branch, but it didn't fix it.

Anything not in a file you modify (more specifically, in code you change), you can ignore. These issues are already known and are being fixed separately.

2023-06-05 23:46 UTC, tscrim commented on src/sage/combinat/output.py
> +   r """
```suggestion
    r"""
```

2023-06-12 01:24 UTC, tscrim approved these changes
Thank you!

2023-06-17 17:11 UTC, vbraun commented
pdf docs don't build
```
[sagemath_doc_pdf-none] [92] [1620] [384]
[sagemath_doc_pdf-none] ! Missing $ inserted.
[sagemath_doc_pdf-none] <inserted text> 
[sagemath_doc_pdf-none]                 $
[sagemath_doc_pdf-none] l.163614 \PYG{g+go}{   ╱ ╲         ╱ ╲}
[sagemath_doc_pdf-none]                                                
[sagemath_doc_pdf-none] ? 
```

2023-06-18 10:31 UTC, tscrim commented
@thecaligarmo This is annoying little thing as we don't have an automatic unicode -> pdf converter. There is a file that has all of the unicode to latex conversions (I forget offhand where it is) that is manually updated for the pdf doc to build. These extra symbols need to be added (but don't worry at all about having the output look good).

2023-06-19 22:54 UTC, thecaligarmo commented
Finally found the problem. Looks like there were 3 different problems in the file ` src/sage_docbuild/conf.py`. First was that two different unicode chars had the same value, the second was that one of them was missing `\ensuremath` so that it can work properly and the third was that I needed to add one for the only new unicode character I added. So this ticket now also fixes a bug in unicode handling since the creation of this file.

2023-06-20 05:04 UTC, tscrim approved these changes
Great, thank you for finding and fixing that. LGTM.

2023-07-01 21:11 UTC, merged