little refreshment of code in Weyl groups
sagemath/sage pull request #35730
Opened 2023-06-05 12:47 UTC by fchapoton

### :books: Description

Some minor code details in the file `weyl_groups.py`

also fixing #35508

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-06-05 14:49 UTC, mkoeppe commented on src/sage/combinat/root_system/weyl_group.py
> +                                                                                                         self._domain._name_string(capitalize=False,
perhaps assign to a variable first?

2023-06-05 19:30 UTC, fingolfin commented on src/sage/combinat/root_system/weyl_group.py
> +            libgap_group = libgap.Group([], 1)
Uff, that this works is a bug in GAP (I'll log it immediately): groups of cyclotomics (and that includes integers) are forbidden, because they make syntax like `x^y` ambiguous.

I recommend you avoid it here, as it will eventually run into other bugs (and it will directly raise an error once we fix this in GAP)

2023-06-05 20:25 UTC, fchapoton commented on src/sage/combinat/root_system/weyl_group.py
> +            libgap_group = libgap.Group([], 1)
so I should rather use an empty matrix or what ?

2023-06-05 20:42 UTC, fingolfin commented on src/sage/combinat/root_system/weyl_group.py
> +            libgap_group = libgap.Group([], 1)
No, that won't work. Either use a 1x1 matrix, or if your code does not care about what exact kind of underlying group you have, you could also just invoke `TrivialGroup()` (which by default creates a pc group)

2023-06-07 05:41 UTC, fchapoton commented on src/sage/combinat/root_system/weyl_group.py
> +            libgap_group = libgap.Group([], 1)
Thanks. I have used a 1x1 matrix.

2023-06-10 05:53 UTC, tscrim requested changes
Just a few little things. Once changed and if no objections from @fingolfin, then we can set this to a positive review I think.

2023-06-10 05:53 UTC, tscrim commented on src/sage/groups/group.pyx
>          from sage.misc.misc_c import prod
This import is no longer needed.

2023-06-10 05:53 UTC, tscrim commented on src/sage/combinat/root_system/weyl_group.py
> +            m = diagonal_matrix([-1 for _ in range(self.n)])
```suggestion
            m = diagonal_matrix([-1]*self.n)
```
since we aren't mutating anything.

2023-06-13 23:49 UTC, tscrim approved these changes
Thank you. LGTM.

If @fingolfin has any objections, we can revert the positive review.

2023-06-14 05:50 UTC, fchapoton commented
Arigato, Travis

2023-06-21 21:21 UTC, merged