fix most E301 warnings
sagemath/sage pull request #35768
Opened 2023-06-14 11:57 UTC by fchapoton

### :books: Description

This fixes most E301 warnings, except 2 problematic ones relating to strange new syntax for code typing

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-06-14 16:49 UTC, dcoudert requested changes
only a few minor remarks.

2023-06-14 16:49 UTC, dcoudert commented on src/sage/quadratic_forms/quadratic_form.py
> -# =========================================================================================================================
I don't understand this change in view of the bloc of commented code.

2023-06-14 16:49 UTC, dcoudert commented on src/sage/quadratic_forms/quadratic_form.py
> +        If a vector
You could align this bloc in 80 columns mode

2023-06-14 16:49 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/ell_rational_field.py
>      #<-------------------------------------------------------------------------
Isn't it a problem to let this line without space after `#` ?

2023-06-14 16:49 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/ell_rational_field.py
>      #<-------------------------------------------------------------------------
same question here

2023-06-15 15:40 UTC, dcoudert approved these changes
LGTM.

2023-06-15 16:16 UTC, fchapoton commented
Merci beaucoup, David.

2023-06-21 21:21 UTC, merged