Implementing Golod complexes
sagemath/sage pull request #35802
Opened 2023-06-21 09:27 UTC by OP5642

### Implementing Golod (simplicial) complexes 

This is a part of #35640 (GSoC 20223), relies on #35430 (bigraded Betti numbers).

Added two methods: `is_golod()` and `is_minimally_non_golod()`, defined for simplicial complexes. These are significant invariants used in toric topology.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2023-06-21 09:29 UTC, OP5642 commented
@tscrim

2023-06-27 00:38 UTC, tscrim requested changes
Here's some changes that I think will make the code faster.

2023-06-27 00:38 UTC, tscrim commented on src/sage/topology/simplicial_complex.py
> +        return True
```suggestion
        H = set(a+b for (a, b) in self.bigraded_betti_numbers())
        if 0 in H:
            H.remove(0)

        return all(i + j in H for i in H for j in H)
```

2023-06-27 00:38 UTC, tscrim commented on src/sage/topology/simplicial_complex.py
> +        return True
```suggestion
        def test(v):
            X = copy(self)
            X.delete_vertex(v)
            return X.is_golod()

        return (not self.is_golod()) and all(test(v) for v in self.vertices())
```

2023-06-28 01:03 UTC, tscrim requested changes

2023-06-28 01:03 UTC, tscrim commented on src/sage/topology/simplicial_complex.py
> +        return not any(i + j in H for i in H for j in H)
I think I changed the logic slightly for `is_golod`. Before, it was possible that `i + j == 0`, which would have returned `False`. However, the current code doesn't catch this. Also, with the commutativity, we can simplify it.
```suggestion
        H = set(a+b for (a, b) in self.bigraded_betti_numbers())
        if 0 in H:
            HL = list(H.difference([0]))
        else:
            HL = list(H)

        return not any(i + j in H for ii, i in enumerate(HL) for j in HL[ii:])
```

2023-07-03 02:23 UTC, tscrim approved these changes
LGTM.

2023-07-09 00:25 UTC, merged