Is fully commutative for Coxeter group elements
sagemath/sage pull request #35915
Opened 2023-07-07 19:06 UTC by fchapoton

### :books: Description

This is adding a method "is_fully_commutative" to all Coxeter group elements.

On the way, introduce iterators over the sets of reduced words of a given element.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-07-07 19:22 UTC, fchapoton commented
Maybe one could try instead to add a method "`is_fully_commutative`" to the `BraidOrbit` classes

2023-07-11 01:29 UTC, tscrim requested changes
Can we add a test showing things works for a Coxeter group with a "be_careful" indexing set?

Also, personally, I think we should expunge the `# optional` markers until they are actually used (in particular, can be reasonably tested against).

2023-07-11 01:29 UTC, tscrim commented on src/sage/categories/coxeter_groups.py
> +              ``self.index_set()``
```suggestion
            - ``word`` -- a list (or iterable) of indices in
              ``self.index_set()``
```

2023-07-11 05:33 UTC, fchapoton commented
> Can we add a test showing things works for a Coxeter group with a "be_careful" indexing set?

Hello Travis, thanks for the idea. Would you please suggest a simple way to create such a group ?

(I prefer not to mess with these damn markers)

2023-07-11 05:53 UTC, tscrim commented
There seems to be a bit of bug in the `CoxeterMatrixGroup` input ignoring the index set when passed something that can be interpreted as a Coxeter type.

Well, we can at least work around that by working with a Coxeter group for a very generic matrix:
```python
sage: W = CoxeterGroup(CM, index_set=('a', Permutation([2,1]), -2), implementation="reflection")
sage: W.index_set()
('a', [2, 1], -2)
```

2023-07-11 05:59 UTC, fchapoton commented
Thanks. Is my new doctest enough ?

2023-07-11 06:04 UTC, fchapoton commented
should be better now

2023-07-11 06:07 UTC, tscrim approved these changes
Thank you. This is good.

2023-07-20 22:59 UTC, merged