first sketch for callable factorisations
sagemath/sage pull request #35928
Opened 2023-07-10 12:23 UTC by fchapoton

Implement a simple substitution mechanism for "Factorization" instances, used when factorising polynomials for example.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-07-12 18:00 UTC, dcoudert requested changes

2023-07-12 18:00 UTC, dcoudert commented on src/sage/structure/factorization.py
> +        Return ``True`` if my factors commute.
In many places, we have instead: `Check whether the factors commute.`

2023-07-12 18:00 UTC, dcoudert commented on src/sage/structure/factorization.py
> +        - ``unit`` -- (default: 1) the unit part of the factorization.
missing `;` after parenthesis (many places).
```diff
- ``unit`` -- (default: 1) the unit part of the factorization.
+ ``unit`` -- (default: 1); the unit part of the factorization.
```

2023-07-12 18:00 UTC, dcoudert commented on src/sage/structure/factorization.py
> +        Return whether all exponents of this Factorization are non-negative.
Could be
```diff
- Return whether all exponents of this Factorization are non-negative.
+ Check whether all exponents of this Factorization are non-negative.
```

2023-07-13 06:15 UTC, dcoudert approved these changes
LGTM.

2023-07-20 22:59 UTC, merged

2023-09-06 14:53 UTC, fchapoton commented
Hmm, an interesting new bug has followed:
```
sage: g=(q-1)**-1
sage: factor(g)
(q - 1)^-1
sage: _(q=1)
0
```