`sage.categories`: Update `# needs`
sagemath/sage pull request #35945
Opened 2023-07-12 20:45 UTC by mkoeppe

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-08-14 10:13 UTC, dcoudert requested changes
I did my best but may have missed some details in this giant PR...

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/algebras.py
remove empty line and use block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/category_types.py
> +            sage: Sym = SymmetricFunctions(QQ)                                          # needs sage.combinat sage.modules
block scope ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/category_types.py
> +            sage: C = Cs(SymmetricGroup(3))                                             # needs sage.groups
block scope ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/coxeter_groups.py
> +                sage: len(W.standard_coxeter_elements())                                # needs sage.graphs
`W` is created using `sage.combinat`, so this line should also depend on it to avoid warning.

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/coxeter_groups.py
> +                sage: KL_cells = W.kazhdan_lusztig_cells()                              # needs sage.combinat sage.groups
also needs `sage.modules` ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/coxeter_groups.py
>                  sage: def P4toW(w): return W.from_reduced_word(w.reduced_word())
should also depend on `sage.combinat sage.groups`. So block scope is better here

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/coxeter_groups.py
> +                sage: def P4toW(w): return W.from_reduced_word(w.reduced_word())
also depends on `sage.combinat sage.groups` for `W`

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/examples/filtered_algebras_with_basis.py
> +            sage: x*y*x                                                                 # needs sage.symbolic
Why is it the only test needing `sage.symbolic` ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/fields.py
> +            sage: K(PolynomialRing(GF(3), 'x')) # indirect doctest
2 spaces before `#`

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/filtered_algebras_with_basis.py
> +                sage: f(x)                                                              # needs sage.all
block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/filtered_algebras_with_basis.py
> +                sage: grf(h.one())                                                      # needs sage.all
block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/filtered_algebras_with_basis.py
> +                sage: grf(h.one())                                                      # needs sage.all
block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
>                  ....:     return -L.basis().keys().index(x)
should also need on `sage.groups sage.modules`. So block scope ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/finite_lattice_posets.py
> +                sage: def f(b): return D(5*prod(b))
should also need `sage.combinat sage.graphs sage.modules`, so block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/finite_monoids.py
remove empty line to use block scope ?

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/homset.py
> +        sage: S in C
`sage.graphs` was needed to create `S`,  so this test should also need it

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/lie_conformal_algebras.py
> +                sage: V._test_jacobi()          # long time (6 seconds)                 # needs sage.combinat sage.modules
unify alignment

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/manifolds.py
> +                sage: Manifolds(RR).AlmostComplex().super_categories() # indirect doctest           # needs sage.rings.real_mpfr
2 spaces before `# indirect`

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/modules_with_basis.py
> +                sage: f = lambda part: 2 * s(part.conjugate())
`s` needs `sage.combinat sage.modules`

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/morphism.pyx
remove empty line and use block scope

2023-08-14 10:13 UTC, dcoudert commented on src/sage/categories/pushout.py
> +        sage: F(QQ)                                                                     # needs sage.rings.number_field
could also be in the block scope

2023-08-16 22:15 UTC, mkoeppe commented on src/sage/categories/modules_with_basis.py
> +                sage: f = lambda part: 2 * s(part.conjugate())
This is just a definition of a lambda function, it does not need the binding of s

2023-08-16 23:21 UTC, mkoeppe commented on src/sage/categories/examples/filtered_algebras_with_basis.py
> +            sage: x*y*x                                                                 # needs sage.symbolic
A mistake, fixed in 74cb689c0fa

2023-08-16 23:26 UTC, mkoeppe commented on src/sage/categories/coxeter_groups.py
> +                sage: def P4toW(w): return W.from_reduced_word(w.reduced_word())
Function definitions don't need bindings of globals

2023-08-16 23:30 UTC, mkoeppe commented on src/sage/categories/finite_lattice_posets.py
> +                sage: def f(b): return D(5*prod(b))
Function definitions don't need bindings of globals

2023-08-16 23:32 UTC, mkoeppe commented on src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
>                  ....:     return -L.basis().keys().index(x)
Function definitions don't need bindings of globals

2023-08-17 06:17 UTC, mkoeppe commented on src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
>                  ....:     return -L.basis().keys().index(x)
But I've switched other examples in this file to use block scope in cb7db9bccca

2023-08-17 06:21 UTC, mkoeppe commented on src/sage/categories/modules_with_basis.py
> +                sage: f = lambda part: 2 * s(part.conjugate())
But I have made some improvements to the file in 8b8164d09c5

2023-08-17 06:22 UTC, mkoeppe commented on src/sage/categories/coxeter_groups.py
>                  sage: def P4toW(w): return W.from_reduced_word(w.reduced_word())
The `def` does not needs a tag to work

2023-08-17 06:36 UTC, mkoeppe commented on src/sage/categories/category_types.py
> +            sage: Sym = SymmetricFunctions(QQ)                                          # needs sage.combinat sage.modules
done in d6981e4d24d

2023-08-17 10:05 UTC, dcoudert approved these changes
I propose to accept this PR. It improves many parts of the code. Further cosmetic improvements can be done in future PRs. This one is already big enough.

LGTM.

2023-08-17 16:32 UTC, mkoeppe commented
Thank you very much!

2023-08-27 20:08 UTC, merged