refresh descent_two_isogeny.pyx
sagemath/sage pull request #35979
Opened 2023-07-22 08:00 UTC by fchapoton

mostly pep8 formatting for the code

also removing 3 unused variables found by cython-lint

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-07-23 08:22 UTC, dcoudert requested changes
few remarks.

2023-07-23 08:22 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
> +            result = +1  # soluble
Simply `result = 1`

2023-07-23 08:22 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
> +            result = +1  # soluble
same here and other places

2023-07-23 08:22 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/descent_two_isogeny.pyx
> +    cdef Integer A,B,C,D,E
`cdef Integer A, B, C, D, E` ?

2023-07-30 13:19 UTC, fchapoton commented
ok, c'est fait. merci

2023-07-30 17:37 UTC, dcoudert approved these changes
LGTM.

2023-08-05 23:28 UTC, merged