Implement Goss polynomials of Drinfeld modules
sagemath/sage pull request #35991
Opened 2023-07-26 14:30 UTC by DavidAyotte

This PR implements Goss polynomials of Drinfeld modules. The interested PR reviewer should read section 3 of [this paper](https://link.springer.com/article/10.1007/BF01410204). In particular, the recurrence relation (ii) of Proposition 3.4 of op. cit. is used in order to compute the $n$-th Goss polynomial of a Drinfeld module.

CC: @xcaruso @ymusleh @kryzar 

### :memo: Checklist

- [X] The title is concise, informative, and self-explanatory.
- [X] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [X] I have created tests covering the changes.
- [X] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-07-26 16:35 UTC, xcaruso requested changes

2023-07-26 16:35 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
> +    def goss_polynomial(self, n, name='X'):
There are many recursive calls so I think that it worths adding the decorator `@cached_method` for efficiency.

Moreover, many checkings and several computations (e.g. `self.exponential()`) are done at each recursive call. It would be nice if you can find a way to avoid them. One options for this could be to separate your function into two parts.

2023-07-26 16:35 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
> +    def goss_polynomial(self, n, name='X'):
Usually we use `var` instead of `name` here.

2023-07-26 16:35 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
> +        exp = self.exponential()
Probably, for performances, it is much better to use the method `_compute_coefficient_exp` instead of `exponential` here.

2023-07-27 09:01 UTC, DavidAyotte commented
Thanks for the comments, I think I have addressed all of them.

2023-07-27 09:10 UTC, xcaruso reviewed
Just a small suggestion. Otherwise, LGTM.

2023-07-27 09:10 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
> +            return self.goss_polynomial(ZZ(n/q))**q
```suggestion
        if n % q == 0:
            return self.goss_polynomial(n // q)**q
```

2023-07-27 10:07 UTC, kryzar approved these changes
Thanks for this contribution @DavidAyotte. I approve the changes.

2023-07-29 09:31 UTC, xcaruso commented
It seems that they are currently problems with automatic checkings.

2023-08-01 07:38 UTC, xcaruso commented
Cc @vbraun 
I'd like to give a positive review to this ticket but the build test fails for some reason that I did not understand and which is most likely unrelated to this ticket. What should I do?

2023-08-21 12:08 UTC, fchapoton commented
I have re-launched the checks on top of 10.1. The branch has been re-based.

2023-08-21 14:53 UTC, DavidAyotte commented
> I have re-launched the checks on top of 10.1. The branch has been re-based.

Thanks Frédéric! The failing doctest does not seem to be related to this branch.

2023-08-21 15:03 UTC, fchapoton commented
Indeed, it is unrelated. Feel free to set to positive if you think this is ready.

2023-08-21 15:04 UTC, fchapoton commented
but note that the added raise is not correctly doctested

2023-08-21 19:16 UTC, xcaruso commented
Good point, Frédéric.
Maybe you could fix this by adding a doctest, David.

2023-08-22 19:04 UTC, DavidAyotte commented
Thanks for pointing this out. I added the desired doctest.

2023-08-23 08:57 UTC, kryzar approved these changes

2023-08-27 20:08 UTC, merged