Working MCDS implementation using MTZ constraints
sagemath/sage pull request #35990
Opened 2023-07-26 12:06 UTC by MrBanananator

Extended `dominating_sets` to be able to generate Minimum Connected Dominating Sets using Miller-Tucker-Zemlin connectivity constraints. This functionality can be toggled on by setting the `connected` parameter flag to true.

Fixes #35989.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2023-07-26 17:21 UTC, dcoudert commented
Can you comment the modifications of the graph and the constraints you add. I don't have access to the pdf of the paper you use and it seems much more complicated than what it should.

2023-07-27 02:33 UTC, MrBanananator commented
I've attached a screenshot of the MTZ constraints formulation from the paper here: https://github.com/sagemath/sage/assets/61144856/303989f4-94a2-4b94-84c5-bbc44d00c387

You can also access my breakdown/translation of the constraints here: https://docs.google.com/document/d/1zlPE6KKcjKqocCsAf-CXsYjtys6V7l5Li5sXqnOhMN8/edit?usp=sharing

2023-07-27 20:56 UTC, dcoudert commented
Your current proposals has several issues. The main one is that it assumes that the vertices of the graph are labeled `0,1,2,...,n-1`, which is not always the case. Furthermore, it is unclear if it can be used in combination with other parameters from the method. 

I have an alternative proposal (much simpler). It suffices to add the following in `dominating_sets`, just after the case `if independent`. There is no need for a specific method to add the constraints.
```py
    if connected:
        # edges used in the spanning tree
        edge = p.new_variable(binary=True)
        # relaxed edges to test for acyclicity
        r_edge = p.new_variable(nonnegative=True)

        # 1. We want a tree
        p.add_constraint(p.sum(edge[frozenset(e)] for e in g.edge_iterator(labels=False))
                         == p.sum(b[u] for u in g) - 1)

        # 2. An edge can be in the tree if its end vertices are selected
        for u, v in g.edge_iterator(labels=False):
            p.add_constraint(edge[frozenset((u, v))] <= b[u])
            p.add_constraint(edge[frozenset((u, v))] <= b[v])

        # 3. Subtour elimination constraints from the maximum average degree
        for u, v in g.edge_iterator(labels=False):
            p.add_constraint(edge[frozenset((u, v))] <= r_edge[u, v] + r_edge[v, u])
        eps = 1 / (5 * Integer(g.order()))
        for v in g:
            p.add_constraint(p.sum(r_edge[u, v] for u in g.neighbor_iterator(v)), max=1 - eps)
```

I did some tests and its faster than with the method you propose. Try it.

2023-07-29 10:51 UTC, dcoudert commented
To work properly with digraphs, we need the following to avoid counting twice some edge variables. Here, connectivity in digraphs is not strong connectivity. We only ensure that the underlying undirected graph is connected.
```py
    if connected:
        E = set(frozenset(e) for e in g.edge_iterator(labels=False))
        # edges used in the spanning tree
        edge = p.new_variable(binary=True, name='e')
        # relaxed edges to test for acyclicity
        r_edge = p.new_variable(nonnegative=True, name='re')

        # 1. We want a tree
        p.add_constraint(p.sum(edge[fe] for fe in E)
                         == p.sum(b[u] for u in g) - 1)

        # 2. An edge can be in the tree if its end vertices are selected
        for fe in E:
            u, v = fe
            p.add_constraint(edge[fe] <= b[u])
            p.add_constraint(edge[fe] <= b[v])

        # 3. Subtour elimination constraints
        for fe in E:
            u, v = fe
            p.add_constraint(edge[fe] <= r_edge[u, v] + r_edge[v, u])

        eps = 1 / (5 * Integer(g.order()))
        for v in g:
            p.add_constraint(p.sum(r_edge[u, v] for u in g.neighbor_iterator(v)), max=1 - eps)
```

2023-08-12 15:43 UTC, dcoudert commented
Do you plan to implement the proposed solution ? Otherwise, I can do a PR with this solution.

2023-08-12 17:04 UTC, MrBanananator commented
Yes, of course. I will submit it for review today. 

Interestingly, while doing some manual testing I noticed that the MTZ formulation (while outperformed on almost every other graph type) was actually more efficient than the other method for the HalfCube graph specifically. Any ideas why that may be?

2023-08-13 11:16 UTC, dcoudert commented
> Interestingly, while doing some manual testing I noticed that the MTZ formulation (while outperformed on almost every other graph type) was actually more efficient than the other method for the HalfCube graph specifically. Any ideas why that may be?

I don't know how to explain that. It's not surprising to find an instance for which one formulation is better than another one. I already observed that for problems like the Steiner tree.

2023-08-13 13:02 UTC, dcoudert requested changes

2023-08-13 13:02 UTC, dcoudert commented on src/sage/graphs/domination.py
> +    - ``connected`` -- boolean (default: ``False``); when ``True``, computes connected
make sure to respect 80 columns mode for documentation

2023-08-13 13:02 UTC, dcoudert commented on src/sage/graphs/domination.py
> +
Add a doctest showing that the subgraph induced by a dominating set is connected. For instance:

```
sage: all(G.subgraph(vertices=dom).is_connected() for dom in G.dominating_set(k=1, connected=True))
True
```

2023-08-13 13:02 UTC, dcoudert commented on src/sage/graphs/domination.py
>      Return a minimum distance-`k` dominating set of the graph.
add description of input parameter `connected`

2023-08-13 14:11 UTC, dcoudert commented
Can you update the name of this pull request to reflect what it does. It no longer uses MTZ.

2023-08-14 10:34 UTC, dcoudert approved these changes
LGTM. Thanks.

2023-08-20 22:30 UTC, vbraun commented
Docs don't build
```
[sagemath_doc_html-none] [graphs   ] The inventory files are in ../../local/share/doc/sage/inventory/en/reference/graphs.
[sagemath_doc_html-none] Error building the documentation.
[sagemath_doc_html-none] Traceback (most recent call last):
[sagemath_doc_html-none]   File "<frozen runpy>", line 198, in _run_module_as_main
[sagemath_doc_html-none]   File "<frozen runpy>", line 88, in _run_code
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/__main__.py", line 502, in <module>
[sagemath_doc_html-none]     sys.exit(main())
[sagemath_doc_html-none]              ^^^^^^
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/__main__.py", line 499, in main
[sagemath_doc_html-none]     builder()
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 818, in _wrapper
[sagemath_doc_html-none]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 162, in f
[sagemath_doc_html-none]     runsphinx()
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 327, in runsphinx
[sagemath_doc_html-none]     sys.stderr.raise_errors()
[sagemath_doc_html-none]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 263, in raise_errors
[sagemath_doc_html-none]     raise OSError(self._error)
[sagemath_doc_html-none] OSError: /home/release/Sage/src/sage/graphs/domination.py:docstring of sage.graphs.domination.dominating_set:36: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

2023-08-21 07:34 UTC, dcoudert requested changes

2023-08-21 07:34 UTC, dcoudert commented on src/sage/graphs/domination.py
> +      connected dominating set (see :wikipedia:`Connected_dominating_set`)
1 space is missing here
```diff
-      connected dominating set (see :wikipedia:`Connected_dominating_set`)
+       connected dominating set (see :wikipedia:`Connected_dominating_set`)
```

2023-08-22 17:52 UTC, dcoudert approved these changes
LGTM.

2023-08-27 20:08 UTC, merged