k-regular sequences: boundedness
sagemath/sage pull request #36029
Opened 2023-08-03 15:09 UTC by dkrenn

Implements an algorithm to check for boundedness of k-regular sequences. See issue #22964.

(Coding and reviewing already happend on trac (see #22964) and the branch was ready but never merged due to a trivial issue. Now the current develop (10.1.beta8) has been merged in to avoid conflicts the upcoming #36011 (where a renaming took place; set as depedency now).

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

- #36011: Experimental warning removed in class used in this PR and class was renamed.

2023-08-03 15:11 UTC, dkrenn commented
CC @cheuberg

2023-08-23 15:56 UTC, cheuberg requested changes
So this has originally been written by @galipnik and reviewed by @dkrenn. I reviewed the changes since the last conversation between the two on [#22964](https://github.com/sagemath/sage/issues/22964#issuecomment-1417902944) (mostly merges and minor adjustments of doctests).

However, due to one broken link, I could not have a look at the documentation of the new module; so @dkrenn could you perhaps fix that broken link first and then I'll have a look at the documentation of the new module? Thank you.

2023-08-23 15:56 UTC, cheuberg commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
Broken link: 

![grafik](https://github.com/sagemath/sage/assets/9355569/79598ef6-9581-4830-8f0b-2ebe3d0a5183)

2023-08-24 09:57 UTC, dkrenn commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
Fixed (and 10.1 merged in as well).

2023-08-24 11:20 UTC, dkrenn commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
...but appearently link is not linked :| ...not sure why

2023-08-24 11:38 UTC, cheuberg commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
Do we need to list the file in `src/doc/en/reference/combinat/module_list.rst` ?

2023-08-24 11:42 UTC, dkrenn commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
Maybe thats it; let's give it a try and see

2023-08-24 13:20 UTC, dkrenn commented on src/sage/combinat/regular_sequence.py
> +            :mod:`boundedness of `k`-regular sequences <sage.combinat.regular_sequence_bounded>`
Indeed, now the link works. Thank you.

2023-08-24 13:50 UTC, cheuberg requested changes
I scrolled through the documentation and made a few remarks.

2023-08-24 13:50 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +   North-Holland Publishing Company
I think  that the reference should go to the master reference list.

2023-08-24 13:50 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +    Tests::
```suggestion
    TESTS::
```

2023-08-24 13:50 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +    :func:`<sage.combinat.regular_sequence_bounded.mandel_simon_algorithm>`.
This link seems to be broken.

2023-09-10 18:57 UTC, galipnik commented on src/sage/combinat/regular_sequence_bounded.py
> +        return is_bounded_via_mandel_simon_algorithm(make_positive(matricesProd))
```suggestion
        if not is_bounded_via_mandel_simon_algorithm(make_positive(matricesProd)):
            return False
```

2025-02-25 15:21 UTC, dkrenn commented on src/sage/combinat/regular_sequence_bounded.py
> +   North-Holland Publishing Company
[d3af721](https://github.com/sagemath/sage/pull/36029/commits/d3af721115bfe427ddc9182a48863e1cedd51920)

2025-02-25 15:21 UTC, dkrenn commented on src/sage/combinat/regular_sequence_bounded.py
> +    :func:`<sage.combinat.regular_sequence_bounded.mandel_simon_algorithm>`.
[d3af721](https://github.com/sagemath/sage/pull/36029/commits/d3af721115bfe427ddc9182a48863e1cedd51920)

2025-02-25 15:22 UTC, dkrenn commented on src/sage/combinat/regular_sequence_bounded.py
> +    :func:`<sage.combinat.regular_sequence_bounded.mandel_simon_algorithm>`.
[e346176](https://github.com/sagemath/sage/pull/36029/commits/e346176026a624326d5f790116babed3af382763)

2025-02-25 15:22 UTC, dkrenn commented on src/sage/combinat/regular_sequence_bounded.py
> +   North-Holland Publishing Company
[c1bff79](https://github.com/sagemath/sage/pull/36029/commits/c1bff7934902b4e21d69f78ede55959ce8480b63)

2025-02-25 17:30 UTC, dkrenn commented
test-long failed unrelatedly to the changes of this PR and should somehow (don't know how) be restarted.

2025-03-27 17:18 UTC, cheuberg requested changes

2025-03-27 17:18 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +- by the criterion presented in [MS1977a].
```suggestion
- by the criterion presented in [MS1977a]_.
```

2025-03-27 17:18 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +    Return the set `\phi(S)` as defined in [MS1977a].
```suggestion
    Return the set `\phi(S)` as defined in [MS1977a]_.
```

2025-03-27 17:18 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +    A criterion based on [MS1977a] is used here.
```suggestion
    A criterion based on [MS1977a]_ is used here.
```

2025-03-27 17:18 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +   North-Holland Publishing Company
I think that `[MS1977a]` has to be replaced by `[MS1977a]_`, see https://doc.sagemath.org/html/en/developer/coding_basics.html#sage-s-master-bibliography-file , in order to have links in the html documentation. I added some suggestions.

2025-03-27 17:18 UTC, cheuberg commented on src/sage/combinat/regular_sequence_bounded.py
> +    :func:`<sage.combinat.regular_sequence_bounded.mandel_simon_algorithm>`.
ok.

2025-03-27 17:42 UTC, dkrenn commented on src/sage/combinat/regular_sequence_bounded.py
> +   North-Holland Publishing Company
Thank you. Suggestions applied.

2025-03-28 07:00 UTC, cheuberg approved these changes
Positive Review.

2025-04-02 21:21 UTC, merged