`sage.rings.polynomial`: Modularization fixes, `# needs`
sagemath/sage pull request #36045
Opened 2023-08-07 22:40 UTC by mkoeppe

- Part of: #29705 
- Cherry-picked from: #35095 

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-08-08 09:30 UTC, dcoudert requested changes
This is a giant ticket. Can't it be split per sub directories ?

There are several files in which you used `# optional` and not `# needs`. Also, block scope could be employed in many places. I noted only a few of these places (too many).

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/lazy_series.py
> +            sage: s = SymmetricFunctions(P).s()                                         # optional - sage.modules
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/lazy_series.py
> +            sage: s = SymmetricFunctions(QQ).s()                                        # optional - sage.modules
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/abc.pyx
> +        sage: isinstance(RR, sage.rings.abc.RealField)                                  # optional - sage.rings.real_mpfr
`# needs` ?

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/laurent_polynomial_ring.py
> +            sage: L.<a, b, c, d> = LaurentPolynomialRing(QQ)                            # needs sage.modules
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_element.py
> +            sage: K.<k> = NumberField(x^2 + 1)                                          # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_element.py
> +            sage: K.<k> = NumberField(x^2 - 5)                                          # needs sage.rings.number_field
block scope except for last line needing `sage.symbolic` ?

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_element.py
> +            sage: K.<k> = NumberField(x^2 - 5)                                          # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_ideal.py
> +            except (TypeError, NameError, ImportError): # conversion to Singular not supported
2 spaces before `#`

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_ideal.py
> +                except (TypeError, NameError, NotImplementedError, ImportError): # conversion to Singular not supported
2 spaces before `#`

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
> +            sage: R1 = MPolynomialRing_libsingular(GF(5), 2, ('x', 'y'),                # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
> +            sage: Q = copy(R)   # indirect doctest                                      # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
> +            sage: K = GF(4,'a')                                                         # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
>              y^6*a^4 - 4*y^5*a^4*b - 4*y^5*a^3*u + y^5*a^2 - y^5 + 6*y^4*a^4*b^2 + 12*y^4*a^3*b*u - 4*y^4*a^2*b + 6*y^4*a^2*u^2 - 2*y^4*a*u + 4*y^4*b - 4*y^3*a^4*b^3 - 12*y^3*a^3*b^2*u + 6*y^3*a^2*b^2
may be too much for this ticket, but the alignement could be changed

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_libsingular.pyx
> +            sage: K.<k> = NumberField(x^2 - 5)                                          # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_ring_base.pyx
> +            sage: K.<i> = NumberField(t^2 + 1)                                          # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial_sequence.py
> +            sage: I = sage.rings.ideal.Cyclic(R, 4)                                     # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/ore_polynomial_element.pyx
> +            sage: Frob = k.frobenius_endomorphism()                                     # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/ore_polynomial_element.pyx
> +            sage: k.<t> = GF(5^3)                                                       # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element.pyx
> +            sage: f = inverse_mod(x^2 + 1, x^5 + x + 1); f  # abs tol 1e-14             # needs sage.modules
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element.pyx
> +            sage: pol = (-1/7*a^5 - 1/7*a^4 - 1/7*a^3 - 1/7*a^2 - 2/7*a - 1/7)*t^10 + (4/7*a^5 - 2/7*a^4 - 2/7*a^3 - 2/7*a^2 - 2/7*a - 6/7)*t^9 + (90/49*a^5 + 152/49*a^4 + 18/49*a^3 + 24/49*a^2 + 30/
may be too much for this ticket, but the alignment could be improved

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element.pyx
> +            sage: f.is_primitive(15)                                                    # needs sage.rings.finite_rings
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element_generic.py
> +            sage: e = RDF(e)                                                            # needs sage.symbolic
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +            sage: S.<alpha> = R.quotient(x^3 - 3*x + 1)                                 # needs sage.libs.pari
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +            sage: Q1 = P.quo([(x^2+1)^2*(x^2-3)])                                       # needs sage.libs.pari
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring_element.py
> +            sage: K.<i> = NumberField(x^2 + 1)                                          # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring_element.py
> +            sage: S.<X> = K['X']                                                        # needs sage.rings.number_field
block scope

2023-08-08 09:30 UTC, dcoudert commented on src/sage/rings/rational_field.py
> +            sage: QQ.places()                                                           # optional - sage.rings.real_mpfr
`# needs`

2023-08-09 00:24 UTC, mkoeppe commented
> This is a giant ticket. Can't it be split per sub directories ?

There were a few commits with incidental changes in other directories. I have trimmed them away now.

> There are several files in which you used `# optional` and not `# needs`. Also, block scope could be employed in many places. I noted only a few of these places (too many).

Thanks for your patient review of this megaticket. I've made the indicated changes and many more.

2023-08-09 09:29 UTC, dcoudert requested changes
This is much better, but I noted a few more issues.

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/ore_polynomial_element.pyx
> +            sage: # needs sage.rings.finite_rings
This is redundant with line 1399

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/ore_polynomial_element.pyx
> +            sage: D = S.random_element(degree=2)                                        # needs sage.misc.cython
the `# needs` is redundant with line 1399

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element.pyx
> +            saeg: # needs sage.libs.pari
`saeg` -> `sage` ;)

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_element.pyx
> +            sage: f = x^16 + x^14 - x^10 + x^8 - x^6 + x^2 + 1                          # needs sage.libs.pari
`# needs` redundant with above line

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +    sage:
to remove

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +        sage:
to be removed

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +        sage:
again

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +            sage:
again

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +        sage:
another

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/polynomial_quotient_ring.py
> +            sage:
a few other places in this file. Result of a script/command.

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/term_order.py
> +            sage: P = PolynomialRing(GF(127), 8, names='x',
single line ?

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/laurent_polynomial_ring_base.py
> +            sage: L._is_valid_homomorphism_(Q5, (Q5(1/2), Q5(3/2))) # no coercion                   # needs sage.rings.number_field sage.rings.padics
2 spaces before `#`

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial.pyx
>              sage: ZZ(RR['x,y'](0)) # indirect doctest
2 spaces before `#`

2023-08-09 09:29 UTC, dcoudert commented on src/sage/rings/polynomial/multi_polynomial.pyx
> +            sage: F.reduced_form(smallest_coeffs=False) # tol 1e-8                      # needs sage.modules sage.rings.complex_interval_field
2 spaces before `# tol` ?

2023-08-10 08:07 UTC, dcoudert approved these changes
LGTM.

2023-08-13 11:57 UTC, merged