`sage.{topology,homology}`: Update # needs, modularization fixes
sagemath/sage pull request #36051
Opened 2023-08-09 05:20 UTC by mkoeppe

- Part of: #29705 
- Cherry-picked from: #35095 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-08-10 08:30 UTC, dcoudert requested changes
Only a few comments.

2023-08-10 08:30 UTC, dcoudert commented on src/sage/homology/chain_complex_morphism.py
> +    sage: S = simplicial_complexes.Sphere(1); S                                         # needs sage.graphs
block scope ?

2023-08-10 08:30 UTC, dcoudert commented on src/sage/homology/chain_complex_morphism.py
> +            sage: S = simplicial_complexes.Sphere(1); S                                 # needs sage.graphs
block scope or file level ? it seems needed every where

2023-08-10 08:30 UTC, dcoudert commented on src/sage/topology/simplicial_complex.py
> +# sage.doctest: needs sage.graphs
duplicated

2023-08-10 08:30 UTC, dcoudert commented on src/sage/topology/simplicial_set.py
> +    sage: G = groups.misc.MultiplicativeAbelian([3])                                    # needs sage.groups
`sage.groups` could be at block level here

2023-08-10 08:30 UTC, dcoudert commented on src/sage/topology/simplicial_set.py
> +            sage: T.homology() == SimplicialSet(T).homology()                           # needs sage.modules
block scope ?

2023-08-10 08:30 UTC, dcoudert commented on src/sage/topology/simplicial_set_constructions.py
> +            sage:
remove

2023-08-10 08:30 UTC, dcoudert commented on src/sage/topology/simplicial_set_constructions.py
> +            ....:
remove

2023-08-10 17:11 UTC, mkoeppe commented on src/sage/homology/chain_complex_morphism.py
> +            sage: S = simplicial_complexes.Sphere(1); S                                 # needs sage.graphs
Using block scope because there are quite a few doctests where the chain complex is constructed directly, not going through simplicial complexes

2023-08-11 08:44 UTC, dcoudert approved these changes
LGTM.

2023-08-11 15:36 UTC, mkoeppe commented
Thanks!

2023-08-13 11:57 UTC, merged