`sage.{cpython,data_structures,databases,ext,parallel,structure}`: Update `# needs`
sagemath/sage pull request #36067
Opened 2023-08-10 20:00 UTC by mkoeppe

- Part of: #29705 
- Cherry-picked from: #35095 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-08-12 12:31 UTC, dcoudert requested changes
a few remarks.

2023-08-12 12:31 UTC, dcoudert commented on src/sage/data_structures/stream.py
> +            sage: [f[i] for i in range(5)]                                              # needs sage.rings.finite_rings
block scope ?

2023-08-12 12:31 UTC, dcoudert commented on src/sage/ext/fast_callable.pyx
> +            sage: expr = (x+pi) * (x+1)                                                 # needs sage.symbolic
block scope

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/coerce.pyx
> +        sage: is_numpy_type(numpy.matrix)                                               # needs numpy
Could be block scope

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/coerce.pyx
> +            sage: parent(x) is parent(y)                                                # needs sage.modules
block scope

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/coerce.pyx
>              sage: gc.collect() #random
`#random` -> `# random`

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/coerce_actions.pyx
> +            sage: type(A)                                                               # needs sage.groups
could be merge with above block

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/coerce_actions.pyx
> +            sage: type(A)                                                               # needs sage.modular sage.modules
same here

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/element.pyx
> +        -  ``extend`` -- Whether to make a ring extension containing a square root if ``self`` is not a square (default: ``True``)
80 columns and starting with `boolean (default: ``True``);`

2023-08-12 12:31 UTC, dcoudert commented on src/sage/structure/element.pyx
> +        -  ``all`` -- Whether to return a list of all square roots or just a square root (default: False)
at least False -> ` ``False`` `

2023-08-12 16:15 UTC, mkoeppe commented
Thanks a lot, all fixed in 5212775b59

2023-08-12 16:43 UTC, dcoudert approved these changes
LGTM.

2023-08-12 16:56 UTC, mkoeppe commented
Thank you!

2023-08-13 17:50 UTC, mkoeppe commented
Rebased on 10.1.rc0

2023-08-27 20:08 UTC, merged