Added hash function to elements of the fundamental group of an extended affine Weyl group
sagemath/sage pull request #36122
Opened 2023-08-22 15:21 UTC by 65537

This change allows users to compute the python `hash` function for elements of the (Borovoi) fundamental group of an extended affine Weyl group, and subsequently for elements of the extended Weyl group itself if using the `FW` realization. This, in turn, allows to use these mathematical objects as keys in dictionaries.

Fixes #36121 . It adds a `__hash__` function to the class `FundamentalGroupElement` associated with `FundamentalGroupOfExtendedAffineWeylGroup`.

SAGE already associates to each element of the fundamental group an integer, accessible as its `value()` or `_value`.  This integer is unique among other elements of the same fundamental group and thus suitable as a hash for hashmap applications (e.g. Python dictionaries). We return the `hash` of that integer, which is the integer itself for current python implementations.

```
W = ExtendedAffineWeylGroup('A4')
fun = W.fundamental_group().an_element()
w = W.FW().an_element()

hash(fun), {w: 0}
```
yields the following result:
```
(4, {pi[4] * S0*S1*S2*S3*S4: 0})
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-09-07 06:28 UTC, tscrim requested changes
Thank you for noticing and fixing this.

For next time, please be sure to add a doctest showing the issue is fixed (also, all methods need to have at least one doctest).

2023-09-07 06:28 UTC, tscrim commented on src/sage/combinat/root_system/fundamental_group.py
> +        return hash(self.value())
```suggestion
        return wt.map_support(self.parent().action(self.value()))

    def __hash__(self):
        r"""
        Return the hash of ``self``.
        
        TESTS:
        
        Check that :issue:`36121` is fixed::
        
            sage: W = ExtendedAffineWeylGroup('A4')
            sage: fun = W.fundamental_group().an_element()
            sage: w = W.FW().an_element()
            sage: hash(w) == hash(w.value())
            True
        """
        return hash(self.value())
```

2023-09-07 10:05 UTC, 65537 commented
Dear Travis,

thank you for reviewing and improving my pull request. I was following the (mathematically very similar) class WeylGroupElement whose hash function has neither a docstring nor a test, but I will make sure to always include them in future pull requests.

Best, Felix

2023-09-07 13:14 UTC, tscrim approved these changes
Indeed, that is generally a good idea. Unfortunately in this case that is some fairly old code that was included before we developed our modern practices. Thank you for adding it. LGTM.

2023-09-10 09:59 UTC, vbraun commented
```
sage -t --long --warn-long 39.2 --random-seed=123 src/sage/combinat/root_system/fundamental_group.py
**********************************************************************
File "src/sage/combinat/root_system/fundamental_group.py", line 339, in sage.combinat.root_system.fundamental_group.FundamentalGroupElement.__hash__
Failed example:
    hash(w) == hash(w.value())
Exception raised:
    Traceback (most recent call last):
      File "/home/release/Sage/src/sage/doctest/forker.py", line 709, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/release/Sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.combinat.root_system.fundamental_group.FundamentalGroupElement.__hash__[3]>", line 1, in <module>
        hash(w) == hash(w.value())
                        ^^^^^^^^^
    TypeError: 'tuple' object is not callable
**********************************************************************
```

2023-09-10 10:24 UTC, tscrim commented
@65537 Sorry, I didn’t check the doctest carefully. Please change `value()` to `value`.

2023-09-10 11:14 UTC, 65537 reviewed
Testing for `value()` is correct, as long as you are testing on `FundamentalGroupElement`s, which was the main culprit here

2023-09-10 11:19 UTC, tscrim commented
Ah, indeed.

2023-09-13 05:56 UTC, tscrim commented
@vbraun Has this been merged? If so, should we close this?

2023-09-16 14:35 UTC, merged