`sage.groups`: Modularization fixes, `# needs`, doctest cosmetics
sagemath/sage pull request #36168
Opened 2023-09-01 04:54 UTC by mkoeppe

- Part of: #29705 
- Cherry-picked from: #35095 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-09-02 14:07 UTC, dcoudert requested changes
As a side effect of these changes, we have a failing doctest
```

sage -t --long --random-seed=286735480429121101562228604801325644303 sage/sets/set_from_iterator.py
**********************************************************************
File "sage/sets/set_from_iterator.py", line 511, in sage.sets.set_from_iterator.Decorator._sage_src_lines_
Failed example:
    S[0][25]
Expected:
    '            return Integer(1)\n'
Got:
    '        if not gens:\n'
**********************************************************************
1 item had failures:
   1 of   8 in sage.sets.set_from_iterator.Decorator._sage_src_lines_
    [216 tests, 1 failure, 4.56 s]
```

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/braid.py
> +            sage: b.jones_polynomial(skein_normalization=True)                          # needs sage.symbolic
block scope ?

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/galois_group.py
> +            sage: K.<a> = NumberField(x^5-2)                                            # needs sage.rings.number_field
block scope

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/misc_gps/imaginary_groups.py
> +            sage: J(3*I)                                                                # needs sage.symbolic
block scope

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/perm_gps/partn_ref/automorphism_group_canonical_label.pyx
> +# sage.doctest: optional - sage.groups
optional or needs ?

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/perm_gps/permgroup_element.pyx
>          """
enable latex mode with `r"""`

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/perm_gps/permgroup_element.pyx
>          """
needs `r"""`

2023-09-02 14:07 UTC, dcoudert commented on src/sage/groups/perm_gps/permgroup_morphism.py
>          """
`r"""`

2023-09-02 18:11 UTC, mkoeppe commented
> we have a failing doctest
> 
> ```
> 
> sage -t --long --random-seed=286735480429121101562228604801325644303 sage/sets/set_from_iterator.py
> ```

Fixed in ed9fcb476c

2023-09-03 08:16 UTC, dcoudert reviewed
Can we avoid the following warnings ?
```
sage -t --long --warn-long 33.0 --random-seed=131083448595464797617815522915862346074 src/sage/groups/generic.py
**********************************************************************
File "src/sage/groups/generic.py", line 1233, in sage.groups.generic.?
Warning: Variable 'order_from_multiple' referenced here was set only in doctest marked '# needs sage.rings.finite_rings'
    order_from_multiple(w, 230, operation='*')
**********************************************************************
File "src/sage/groups/generic.py", line 1376, in sage.groups.generic.?
Warning: Variable 'order_from_bounds' referenced here was set only in doctest marked '# needs sage.rings.finite_rings'
    order_from_bounds(w, (200, 250), operation='*')
    [257 tests, 1.87 s]
```

2023-09-04 04:41 UTC, dcoudert approved these changes
LGTM.

2023-09-04 07:02 UTC, mkoeppe commented
Thank you!

2023-09-10 08:28 UTC, vbraun commented
merge conflict

2023-09-13 12:38 UTC, dcoudert commented
I'm not sure how to review the addition of the last commits with the broken CI...

2023-09-13 20:45 UTC, mkoeppe commented
I've merged another PR, which should fix the CI

2023-09-15 08:40 UTC, dcoudert approved these changes
With the merged PR, everything seems fine.

2023-09-15 16:46 UTC, mkoeppe commented
Thanks!

2023-09-16 14:35 UTC, merged