full pep8 for modular/hecke
sagemath/sage pull request #36270
Opened 2023-09-15 19:20 UTC by fchapoton

small cleanup for `modular/hecke` folder

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

2023-09-16 09:20 UTC, dcoudert requested changes
otherwise LGTM

2023-09-16 09:20 UTC, dcoudert commented on src/sage/modular/hecke/element.py
> +        Return True if this element is Eisenstein.
`True` -> ` ``True`` `

Also in other places

2023-09-16 09:20 UTC, dcoudert commented on src/sage/modular/hecke/hecke_operator.py
>          """
Shouldn't it be `r"""` here ?

2023-09-16 11:05 UTC, dcoudert approved these changes
LGTM.

2023-09-22 21:11 UTC, vbraun commented
thats a no

2023-09-22 21:52 UTC, dcoudert commented on src/sage/modular/hecke/submodule.py
> +        :classl:`RuntimeError` exception.
hard to see, sorry.

2023-09-23 06:09 UTC, fchapoton commented
oups, sorry, fixed

2023-09-23 11:19 UTC, dcoudert approved these changes
Sorry I didn't see this error the first time.

LGTM.

2023-09-27 22:20 UTC, merged