`sage.sets`: Update `# needs`
sagemath/sage pull request #36272
Opened 2023-09-16 03:15 UTC by mkoeppe

- Part of: #29705 
- Cherry-picked from: #35095 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-09-30 10:04 UTC, dcoudert requested changes
a few possible improvements. otherwise LGTM.

2023-09-30 10:04 UTC, dcoudert commented on src/sage/sets/condition_set.py
> +            sage: BigSin = ConditionSet(RR, sin(x) > 0.9, vars=[x])                                 # needs sage.symbolic
block scope

2023-09-30 10:04 UTC, dcoudert commented on src/sage/sets/condition_set.py
> +            sage: TinyUniverse = ZZ^0                                                   # needs sage.modules
block scope ?

2023-09-30 10:04 UTC, dcoudert commented on src/sage/sets/image_set.py
> +            sage: H = Hom(M, R, category=Sets())                                                    # needs sage.modules
block scope

2023-09-30 10:04 UTC, dcoudert commented on src/sage/sets/image_set.py
> +            sage: H = Hom(M, R, category=Sets())                                        # needs sage.modules
block scope

2023-09-30 10:04 UTC, dcoudert commented on src/sage/sets/set.py
> +            sage: latex(X)                                                              # needs sage.modules
could remove empty line and use block scope

2023-10-01 04:47 UTC, mkoeppe commented
Thanks! All done in a330894

2023-10-01 12:19 UTC, dcoudert commented on src/sage/sets/condition_set.py
> +            sage: Interval = ConditionSet(RR, x >= -7, x <= 4, vars=[x]); Interval      # needs sage.symbolic
This raises a doctest warning
```
sage -t --long --warn-long 33.4 --random-seed=204097948585721018066760244858101334890 src/sage/sets/condition_set.py
**********************************************************************
File "src/sage/sets/condition_set.py", line 431, in sage.sets.condition_set.?._sympy_
Warning: Variable 'x' referenced here was set only in doctest marked '# needs sage.modules sage.symbolic'
    Interval = ConditionSet(RR, x >= -7, x <= 4, vars=[x]); Interval      # needs sage.symbolic
    [96 tests, 0.88 s]
```
My suggestion is to remove the empty line above.

2023-10-01 16:56 UTC, dcoudert approved these changes
no more warnings.

LGTM.

2023-10-01 17:44 UTC, mkoeppe commented
Thanks for the patient review!

2023-10-08 13:51 UTC, merged