`bootstrap-conda`: Refactor, generate versioned environment files
sagemath/sage pull request #36405
Opened 2023-10-05 01:08 UTC by mkoeppe

- Environment files are now versioned with the Python minor version, as proposed in (and cherry-picked from) #35986 by @tobiasdiez
- CI for conda now uses `--enable-system-site-packages` from #36141 by @orlitzky 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-10-05 01:28 UTC, mkoeppe commented
@tobiasdiez This is a cleaned up version of parts of #35593, which is independent from other changes that are still in the pipeline. This PR should be neutral on the CI workflows, i.e., neither fixing nor breaking something. Please take a look

2023-10-05 04:04 UTC, tobiasdiez commented
Thanks. But there is now a `pip` section, which makes the build fail. Can you please remove these additional packages again from the environment file?

2023-10-05 04:19 UTC, mkoeppe commented
Ah, I see. I'll back this change (creating the pip section not only for environment-optional and environment-dev, but also for environment) out from here until the package lists are fixed.

2023-10-05 06:29 UTC, tobiasdiez approved these changes
Thanks, looks good to me.

2023-10-05 15:38 UTC, mkoeppe commented
Thanks!

2023-10-08 20:01 UTC, vbraun commented
merge conflict

2023-10-09 04:21 UTC, tobiasdiez requested changes, later dismissed
Just noticed that the environment files contain also the declaration `- python` (coming from _prereq), which overwrites the other python version declaration.

2023-10-09 04:37 UTC, mkoeppe commented
Along similar lines, should we include the Python version in the default environment name written to the file?

2023-10-09 04:54 UTC, mkoeppe commented
> the environment files contain also the declaration `- python` (coming from _prereq), which overwrites the other python version declaration.

Care to elaborate why you think it would overwrite it? I don't think it does.

2023-10-09 05:14 UTC, tobiasdiez commented
> > the environment files contain also the declaration `- python` (coming from _prereq), which overwrites the other python version declaration.
> 
> Care to elaborate why you think it would overwrite it? I don't think it does.

I tried it out and it was not working (that's how I discovered it in the first place).

2023-10-09 05:18 UTC, mkoeppe commented
I also tried it out and it worked, so some details are needed.

2023-10-09 05:30 UTC, tobiasdiez commented
Might be a version mismatch, I don't know. Either way, I don't think its a good idea to have two python specifiers in the file.

2023-10-09 06:23 UTC, mkoeppe commented
Well ok, here you go.

2023-10-10 02:11 UTC, tobiasdiez commented
Thanks!

Are the `environment-dev` files working for you? I get errors related to sagenb, i.e. it only works without the pip dependencies.

2023-10-10 02:16 UTC, mkoeppe commented
I haven't tried. This PR, as requested, is focused narrowly on what is promised in its title. Other fixes are on other PRs.

2023-10-10 02:35 UTC, tobiasdiez commented
On `develop` the pip section is empty, with your changes here it is populated and breaks things.

2023-10-10 02:49 UTC, mkoeppe commented
OK, here's a temporary workaround.

2023-10-10 03:22 UTC, tobiasdiez approved these changes
Thanks

2023-10-14 23:29 UTC, merged