fix for E702 in pyx outside rings
sagemath/sage pull request #36420
Opened 2023-10-07 12:24 UTC by fchapoton

This fixes pycodestyle warning E702 in pyx files outside of rings

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

2023-10-07 21:14 UTC, dcoudert requested changes

2023-10-07 21:14 UTC, dcoudert commented on src/sage/groups/perm_gps/partn_ref/refinement_binary.pyx
> +        - partition -- an optional list of lists partition of the columns.
partition -> ` ``partition`` `

2023-10-07 21:14 UTC, dcoudert commented on src/sage/coding/binary_code.pyx
>                      if Theta.col_min_cell_rep[Theta.col_find(tvc)] == tvc:
`elif` ?

2023-10-08 08:52 UTC, kwankyu commented on src/sage/matrix/matrix2.pyx
>          if self.nrows() != self.ncols():
Spaces around.

2023-10-08 08:54 UTC, kwankyu commented
Otherwise lgtm.

2023-10-08 10:05 UTC, kwankyu approved these changes
Thanks.

2023-10-14 23:29 UTC, merged