some fixes for pycodestyle E221
sagemath/sage pull request #36556
Opened 2023-10-27 18:21 UTC by fchapoton

this is fixing some of the warnings

`E221 multiple spaces before operator`

mostly scripted with autopep8, plus a few manual cases

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.

2023-10-31 21:47 UTC, mkoeppe commented on src/sage/crypto/sboxes.py
>                   31, 25, 0, 23, 20, 22, 8, 27, 4, 3, 19, 5, 9, 10, 29, 15])
repair indentation please

2023-10-31 21:49 UTC, mkoeppe commented on src/sage/interfaces/tides.py
> -            string += 'log_t(itd, ' + el[1]  + ', link[{}], i);'.format(i)
switch to f-strings while at it?

2023-11-01 22:44 UTC, soehms requested changes
The following doctest failure seems to be related to your previous commit:

```
File "src/sage/interfaces/tides.py", line 695, in sage.interfaces.tides.?
Failed example:
    l[30]
Expected:
    '\t\tmpfrts_pow_t_c(itd, link[2], "-1.500000000000000000000000000000000000000000000000000", link[3], i);\n'
Got:
    '\t\tmpfrts_pow_t_c(itd, link[2], "-1.500000000000000000000000000000000000000000000000000", link[{i}], i);\n'
**********************************************************************
File "src/sage/interfaces/tides.py", line 736, in sage.interfaces.tides.?
Failed example:
    l[30]
Expected:
    '\t\tmpfrts_pow_t_c(itd, link[2], "-1.500000000000000000000000000000000000000000000000000", link[3], i);\n'
Got:
    '\t\tmpfrts_pow_t_c(itd, link[2], "-1.500000000000000000000000000000000000000000000000000", link[{i}], i);\n'
**********************************************************************
1 item had failures:
   2 of  95 in sage.interfaces.tides.?
    [120 tests, 2 failures, 0.28 s]
``

2023-11-02 18:06 UTC, soehms requested changes
Now there is this one:

```
File "src/sage/interfaces/tides.py", line 691, in sage.interfaces.tides.?
Failed example:
    l[15]
Expected:
    '\tstatic int PARAMETERS = 0;\n'
Got:
    '\tstatic int PARAMETERS = 4;\n'
**********************************************************************
1 item had failures:
   1 of  95 in sage.interfaces.tides.?
    [120 tests, 1 failure, 0.09 s]
```

Probably caused by this change (`PAR` -> `VAR`):

```
-    outfile.write("\tstatic int PARAMETERS = {};\n".format(PAR))
...
+        outfile.write(f"\tstatic int PARAMETERS = {VAR};\n")
```

@miguelmarco, ~can you check that the generated files are still good for the *TIDES* library?~ (not necessary any more). 

BTW: The workflows that run doctest of optional and experimental packages seem to be broken (at least the ones that run for the tag 10.2.beta9, example for [Ubuntu jammy maximal](https://github.com/sagemath/sage/actions/runs/6700323366/job/18294092977) is failing [here](https://github.com/sagemath/sage/actions/runs/6700323366/job/18294092977#step:10:37)).

Is this a known issue?

2023-11-03 07:17 UTC, soehms approved these changes
LGTM!

The generated files of the examples are not changed by the branch.

Anyway, the idea behind E221 is not clear to me. Looking through the changes my impression is that it makes code less readable.

2023-11-05 14:23 UTC, merged