`sage.manifolds`, `sage.tensor`: Update `# needs`
sagemath/sage pull request #36568
Opened 2023-10-29 02:38 UTC by mkoeppe

- Cherry picked from #35095 
- Part of #29705 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-10-31 18:28 UTC, dcoudert requested changes
otherwise LGTM.

2023-10-31 18:28 UTC, dcoudert commented on src/sage/manifolds/point.py
>              sage: F.display()
use block scope for `sage.plot`. I see the following warning:
```
sage -t --long --random-seed=255931835005052802712216202278992181532 src/sage/manifolds/point.py
**********************************************************************
File "src/sage/manifolds/point.py", line 909, in sage.manifolds.point.ManifoldPoint.?
Warning: Variable 'F' referenced here was set only in doctest marked '# needs sage.plot'
    F.display()
    [204 tests, 18.48 s]
```

2023-10-31 18:28 UTC, dcoudert commented on src/sage/manifolds/differentiable/tangent_vector.py
>              sage: graph_v + graph_S2  # long time
also needs sage.plot
```
sage -t --long --random-seed=255931835005052802712216202278992181532 src/sage/manifolds/differentiable/tangent_vector.py
**********************************************************************
File "src/sage/manifolds/differentiable/tangent_vector.py", line 436, in sage.manifolds.differentiable.tangent_vector.TangentVector.?
Warning: Variable 'graph_S2' referenced here was set only in doctest marked '# long time, needs sage.plot'
    graph_v + graph_S2  # long time
**********************************************************************
File "src/sage/manifolds/differentiable/tangent_vector.py", line 436, in sage.manifolds.differentiable.tangent_vector.TangentVector.?
Warning: Variable 'graph_v' referenced here was set only in doctest marked '# needs sage.plot'
    graph_v + graph_S2  # long time
    [94 tests, 11.01 s]
```

2023-10-31 18:28 UTC, dcoudert commented on src/sage/manifolds/subsets/pullback.py
> +            sage: McCube = ManifoldSubsetPullback(c_cart, Cube, name='McCube'); McCube  # needs sage.geometry.polyhedron
block scope

2023-10-31 18:52 UTC, mkoeppe commented on src/sage/manifolds/subsets/pullback.py
> +            sage: McCube = ManifoldSubsetPullback(c_cart, Cube, name='McCube'); McCube  # needs sage.geometry.polyhedron
Thanks! All fixed in f3f4416

2023-10-31 19:00 UTC, dcoudert approved these changes
LGTM.

2023-10-31 19:04 UTC, mkoeppe commented
Thank you!

2023-11-04 11:19 UTC, egourgoulhon commented on src/sage/manifolds/point.py
> +            sage: q.coord()                                                             # needs sage.plot
I don't understand why `q.coord()` needs sage.plot.

2023-11-05 14:23 UTC, merged