CI conda: Ignore baseline test failures
sagemath/sage pull request #36678
Opened 2023-11-08 21:50 UTC by mkoeppe

Less intrusive version of #36372.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-11-09 01:09 UTC, tobiasdiez requested changes, later dismissed
There are only a couple of test failures in these files. These ignore patterns are way to coarse.

(removing blocker label for that reason to not hide possible issues)

2023-11-09 01:42 UTC, tobiasdiez commented
So if another new test in the same file fails, the conda ci is red?

2023-11-09 02:17 UTC, mkoeppe commented
Perhaps you should clarify what you think the purpose of the ci-conda workflows is. 
To my understanding they are being run so that the major breakage that we have seen in the past (from unmonitored package upgrades in conda-forge) does not go unnoticed.
I don't think it's really the job of this workflow to duplicate the test coverage done by build.yml

Marking these files as baseline failures is done so that on unrelated workflows, the red checkmarks on the conda workflows do not annoy developers.

2023-11-09 02:20 UTC, mkoeppe commented
And obviously work is needed to actually diagnose, report, and fix these failures. The approach of #36372 ("skip_conda") hides these failures too well.

2023-11-09 20:32 UTC, tobiasdiez commented
> Perhaps you should clarify what you think the purpose of the ci-conda workflows is. To my understanding they are being run so that the major breakage that we have seen in the past (from unmonitored package upgrades in conda-forge) does not go unnoticed. I don't think it's really the job of this workflow to duplicate the test coverage done by build.yml

They have the same purpose as the Build & Test workflow for people using the conda environment. So yes, they should duplicate the test coverage.

(In the long term, once the conda runs are a bit more stable and there are no more conda-specific issues, we can remove the Build & Test workflow).

2023-11-10 00:47 UTC, kwankyu commented
> They have the same purpose as the Build & Test workflow for people using the conda environment. So yes, they should duplicate the test coverage.

B&T is mainly for checking sage library changes to help developers and reviewers. It is unlikely that some code change in the sage library works on a platform and fails on another. That is why B&T runs only on a specific decent platform and tests on all other platforms are done only for weekly release.

I do not use conda (linux neither). I regard conda as another platform. So it looks strange to me that currently 6 B&T workflows for conda platforms run for each PR. I think there is already too much duplication. 

Perhaps conda is special, and separate B&T for conda is necessary for PRs (perhaps upgrading packages). Then why not just two B&T for conda (one for ubuntu and one for mac) for PRs and more tests for weekly release?  

About #36372, I object to introducing conda-specific doctest tags into sage library. That is another cluttering of sage library, in addition to all doctest tags for modularization. We decided to live with modularization. But please never platform-specific doctest tags.

2023-11-10 18:10 UTC, mkoeppe commented
> it looks strange to me that currently 6 B&T workflows for conda platforms run for each PR. I think there is already too much duplication.

FWIW, I approved the change to run these jobs on all PRs in #36373. Tobias has already implemented a mitigation (see https://github.com/sagemath/sage/pull/36373#issuecomment-1742386153) there on my request by making it "fail-fast" and setting a max-parallel 2.

But I think at least the macOS jobs need reconsideration / additional adjustment. Given that we only have 5 macOS runners, launching 3 jobs for every PR is clearly too much. 

For example, at the time that 10.2.rc1 was released (over an 1 hour ago), at least 7 "ci-conda" workflows were already in the queue (https://github.com/sagemath/sage/actions/workflows/ci-conda.yml?query=is%3Aqueued), with at least 14 macOS jobs waiting for a runner. As a result, the CI-macos run of 10.2.rc1 (https://github.com/sagemath/sage/actions/runs/6827163283) has not been able to start yet.

2023-11-11 22:20 UTC, mkoeppe commented
> I think at least the macOS jobs need reconsideration / additional adjustment. Given that we only have 5 macOS runners, launching 3 jobs (each 1 hour) for every PR is clearly too much.

Implemented in  #36694

2023-11-14 18:22 UTC, mkoeppe commented
> Then why not just two B&T for conda (one for ubuntu and one for mac) for PRs and more tests for weekly release?

I agree and have updated #36694 to do this.

2023-11-23 10:39 UTC, kwankyu commented
Currently cond ci is the main reason breaking and delaying checks.

Let's get this in.

2023-11-23 15:33 UTC, tobiasdiez commented
https://github.com/sagemath/sage/pull/36678#pullrequestreview-1721526377 is still not addressed. If a single test in the "Build & Test" workflow would fail, you also wouldn't want to to exclude the whole file, would you?

2023-11-23 18:36 UTC, mkoeppe commented
> [#36678 (review)](https://github.com/sagemath/sage/pull/36678#pullrequestreview-1721526377) is still not addressed. If a single test in the "Build & Test" workflow would fail, you also wouldn't want to to exclude the whole file, would you?

We have addressed it in the discussion (@kwankyu in https://github.com/sagemath/sage/pull/36678#issuecomment-1804901930). The conda tests do *not* serve the same function as the Build & Test workflow:
- I understand that you hope to replace Build&Test by the conda workflow at some point, but no such decision has been taken; and I have seen no effort to make it ready for that.
- Amplifying the failure probability from random failures by running 7 workflows instead of 1 does not help with diagnosing or fixing them. (It also does not help that these random failures are scattered across these 7 workflows.)
- Currently, developers simply do not know what to do when the conda workflows fail. It has been a mixture of conda-specific failures and random errors.

2023-11-23 23:54 UTC, kwankyu commented
> [#36678 (review)](https://github.com/sagemath/sage/pull/36678#pullrequestreview-1721526377) is still not addressed. If a single test in the "Build & Test" workflow would fail, you also wouldn't want to to exclude the whole file, would you?

I would. We should. "B&T for conda" is specifically for conda. If there is a failure with it, I would exclude the file from  being tested for other PRs until the failure is fixed. Keeping it fail for other PRs betrays the purpose of checks. We expect all checks pass unless the PR itself has a problem.

If you want the file to be tested again for conda, you should spend time on fixing the failing test instead of worrying that other test might fail in the same file (which seems quite imaginary to me).

2023-11-24 12:59 UTC, tobiasdiez commented
> > [#36678 (review)](https://github.com/sagemath/sage/pull/36678#pullrequestreview-1721526377) is still not addressed. If a single test in the "Build & Test" workflow would fail, you also wouldn't want to to exclude the whole file, would you?
> 
> We have addressed it in the discussion (@kwankyu in [#36678 (comment)](https://github.com/sagemath/sage/pull/36678#issuecomment-1804901930)). The conda tests do _not_ serve the same function as the Build & Test workflow:
> 
>     * I understand that you hope to replace Build&Test by the conda workflow at some point, but no such decision has been taken; and I have seen no effort to make it ready for that.
> 
>     * Amplifying the failure probability from random failures by running 7 workflows instead of 1 does not help with diagnosing or fixing them. (It also does not help that these random failures are scattered across these 7 workflows.)
> 
>     * Currently, developers simply do not know what to do when the conda workflows fail. It has been a mixture of conda-specific failures and random errors.

I fail to see how any of that is relevant to the question whether to hide conda failures on the file or test level. As can be seen in https://github.com/sagemath/sage/pull/36372, the test failures happen once per file (with the exception of gap).
Concerning your first point: https://github.com/search?q=repo%3Asagemath%2Fsage+conda&type=pullrequests

> > [#36678 (review)](https://github.com/sagemath/sage/pull/36678#pullrequestreview-1721526377) is still not addressed. If a single test in the "Build & Test" workflow would fail, you also wouldn't want to to exclude the whole file, would you?
> 
> I would. We should. "B&T for conda" is specifically for conda. If there is a failure with it, I would exclude the file from being tested for other PRs until the failure is fixed. 

Really? You would exclude the whole file and not just mark the single failing test with "# random"?

2023-11-24 13:14 UTC, kwankyu commented
> > I would. We should. "B&T for conda" is specifically for conda. If there is a failure with it, I would exclude the file from being tested for other PRs until the failure is fixed.
> 
> Really? You would exclude the whole file and not just mark the single failing test with "# random"?

We are talking about some doctest failing only in conda ci, and there is no problem with the doctest on the rest of the platforms. Why tag it with `# random`?

2023-11-24 13:22 UTC, kwankyu commented
By the way, `# random` is used for inherently random outputs. It is not for random failures.

2023-11-25 03:52 UTC, tobiasdiez commented
> > > I would. We should. "B&T for conda" is specifically for conda. If there is a failure with it, I would exclude the file from being tested for other PRs until the failure is fixed.
> > 
> > 
> > Really? You would exclude the whole file and not just mark the single failing test with "# random"?
> 
> We are talking about some doctest failing only in conda ci, and there is no problem with the doctest on the rest of the platforms. Why tag it with `# random`?

It seems to be the established practice: https://github.com/sagemath/sage/pull/36647
But I agree with you that `random` is not a good solution for this, but since there are currently no means to tag a doctest "this breaks on system xyz, but not others" it's the next best thing. To have a more conceptual solution, I introduced the coda-specific exception.

Anyway, I'm okay with ignoring the failing tests using an external file. But this mechanism should only exclude the tests that are really failing to a) prevent that additional errors are introduced and b) to make it easier to work on these issues (it's essential to know which line actually breaks randomly in source file of +1000 lines).

2023-11-25 04:50 UTC, kwankyu commented
> > > > I would. We should. "B&T for conda" is specifically for conda. If there is a failure with it, I would exclude the file from being tested for other PRs until the failure is fixed.
> > > 
> > > 
> > > Really? You would exclude the whole file and not just mark the single failing test with "# random"?
> > 
> > 
> > We are talking about some doctest failing only in conda ci, and there is no problem with the doctest on the rest of the platforms. Why tag it with `# random`?
> 
> It seems to be the established practice: #36647 (among others) But I agree with you that `random` is not a good solution for this, but since there are currently no means to tag a doctest "this breaks on system xyz, but not others" it's the next best thing. To have a more conceptual solution, I introduced the coda-specific exception.
> 
> Anyway, I'm okay with ignoring the failing tests using an external file. But this mechanism should only exclude the tests that are really failing to a) prevent that additional errors are introduced and b) to make it easier to work on these issues (it's essential to know which line actually breaks randomly in source file of +1000 lines).

Just focus on the failing test that made the file excluded. We may add a comment telling the failing test (or tests) when we add the file to the list of the ignored files. It would make things complicated if we try to exclude only the failing tests. Why make things complicated just for rare cases (almost looking imaginary to me)?

2023-11-25 05:24 UTC, mkoeppe commented
> b) to make it easier to work on these issues (it's essential to know which line actually breaks randomly in source file of +1000 lines).

One sees this in the logs -- because with the approach here, the failures are not hidden but only marked as "[failed in baseline]".

2023-11-25 08:54 UTC, tobiasdiez commented
> > b) to make it easier to work on these issues (it's essential to know which line actually breaks randomly in source file of +1000 lines).
> 
> One sees this in the logs -- because with the approach here, the failures are not hidden but only marked as "[failed in baseline]".

That clearly only works for the issues that occur often/reproducible. I was talking about the random failures that happen once every 100 runs or so.

2023-11-25 10:31 UTC, kwankyu commented
The random failure you are talking about seems not related with PRs. Why do you want to observe it in PR checks? To investigate such a random failure, I would just devise massive repetitive test runs with just one version of sage. No?

2023-11-25 23:17 UTC, mkoeppe commented
I also don't understand the comment in https://github.com/sagemath/sage/pull/36678#issuecomment-1826258022

2023-11-26 15:17 UTC, tobiasdiez commented
> Why do you want to observe it in PR checks? 

I don't want to observe them at all. It just reality that these failing tests are occurring very rarely, which makes it hard to reproduce them locally. Heck, even now there are random test failures of the Build & Test workflow (e.g. https://github.com/sagemath/sage/actions/runs/6970122859/job/18967437726). Do you want to exclude the whole file from the tests because of this?

> To investigate such a random failure, I would just devise massive repetitive test runs with just one version of sage. No?

I actually did this. But that only revealed a couple of errors. But if you have computation time over that you don't need, I would appreciate it very much if you could run the conda tests in a loop and let me know about the failures.

> I also don't understand the comment in [#36678 (comment)](https://github.com/sagemath/sage/pull/36678#issuecomment-1826258022)

Take a failure that occurs once every 100 runs. If you only know that the failure happens in a given file, you need to run all doctests in that file for 100 times (I know, I know statistics...), which could easily take a few hours depending on the file, only to reproduce it locally. And that would imply that the error actually happens on the given system (some of the errors are occurring only on eg macos). If you know the exact test that fails, you copy that one to a test file, put a loop around it and have it reproduced in a couple of mins.

2023-11-26 17:56 UTC, mkoeppe commented
> even now there are random test failures of the Build & Test workflow [...]. Do you want to exclude the whole file from the tests because of this?

Asked and answered already.

2023-12-03 07:07 UTC, kwankyu commented
> 1. Test failure is noticed
> 2. You record it in a GitHub Issue. There you include the necessary information so that it does not take 2 hours to reconstruct it.
> 3. One adds stuff to the exclusion list to eliminate noise in the tests.

and items in the exclusion list are commented with the the GitHub Issue numbers...

2023-12-03 07:10 UTC, kwankyu approved these changes
LGTM.

2023-12-08 16:30 UTC, mkoeppe commented
> There are clear short comings with the approach of this PR as described above.

Nope, all have been refuted.

2023-12-19 00:07 UTC, merged