Choice of the name of primitive elements for subfields of QQbar
sagemath/sage pull request #36749
Opened 2023-11-22 12:01 UTC by enriqueartal

Added optional keywords `name` for the method `union` and the function `number_field_elements_from_algebraics` from `qqbar.py`. 

Without this option the name, the name is always `a` and it may conflict if  `a` is another object, see https://groups.google.com/g/sage-devel/c/mr9AzpUcbUM
### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2023-11-23 07:01 UTC, tscrim requested changes
Just some simple doc fixes. LGTM otherwise.

2023-11-23 07:01 UTC, tscrim commented on src/sage/rings/qqbar.py
> +
```suggestion
    - ``name`` -- string (default: ``'a'``); name of the primitive element
```
Let's not make things worse; instead, let's bring everything into the correct format.

2023-11-23 07:01 UTC, tscrim commented on src/sage/rings/qqbar.py
> +        - ``name`` - string (default: 'a'). A name for the primitive element.
```suggestion
        - ``other`` -- an algebraic number
        - ``name`` -- string (default: ``'a'``); a name for the primitive element
```

2023-11-24 12:37 UTC, fchapoton commented
Travis also suggested to remove the final dot in the description of parameters

2023-11-24 14:00 UTC, enriqueartal commented
> Travis also suggested to remove the final dot in the description of parameters

Sorry, I read it too quickly. Done.

2023-11-27 04:32 UTC, tscrim commented on src/sage/rings/qqbar.py
> +        - ``name`` - string (default: ``'a'``); a name for the primitive element
```suggestion
        - ``other`` -- an algebraic number
        - ``name`` -- string (default: ``'a'``); a name for the primitive element
```
there is also the second `-` needed to make the correct length hyphen.

2023-11-27 07:38 UTC, tscrim approved these changes
Thanks. LGTM.

 Whomever thought that a default commit message for some GH way of incorporating reviewer changes should actually work on a project of any meaningful size and then if they cannot see the clear gravity of their error should be immediately fired.

2023-12-14 00:16 UTC, merged