Remove sage.gaprc
sagemath/sage pull request #36755
Opened 2023-11-23 06:32 UTC by tobiasdiez

The ̀ sage.gaprc` allowed to customize the initialization of gap. But it's not used (at least in the sage distro) for a couple of years. So we remove the file, while leaving the mechanism in place (in case a certain distro needs it).

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-11-23 07:03 UTC, mkoeppe commented
What problem is solved by this?

2023-11-23 13:46 UTC, dimpase commented
in view of [GAP docs](https://docs.gap-system.org/doc/ref/chap3_mj.html#X87DF11C885E73583) on this, it appears to be a semi-obsolete feature; for compatibility these files, and these read by GAP, ought to be named appropriately and placed in GAP's standard dirs. Probably reading these things ought to be delegated to libgap, not 100% sure about it.

Note that `sage.gaprc` is also mentioned in `src/setup.cfg.m4`

2023-11-23 13:48 UTC, dimpase requested changes
src/setup.cfg.m4 mentions the file you're removing

Also, we need to rectify how to influence the initialisation of libgap by using such a file

2023-11-23 15:32 UTC, tobiasdiez commented
> What problem is solved by this?

Just a bit of cleanup/removal of semi-dead code.

> src/setup.cfg.m4 mentions the file you're removing

Thanks, I've removed it now.

> Also, we need to rectify how to influence the initialisation of libgap by using such a file

Not sure what you mean by "rectify". The process of adding a `sage.gaprc` file still works, in case it is needed at some point.

2023-11-23 16:02 UTC, dimpase commented
> > Also, we need to rectify how to influence the initialisation of libgap by using such a file
> 
> Not sure what you mean by "rectify". The process of adding a `sage.gaprc` file still works, in case it is needed at some point.

It's got to be documented, that's what I meant.

2023-11-24 10:06 UTC, tobiasdiez commented
Okay, I've now added a bit of documentation.

2023-11-24 10:06 UTC, dimpase commented
one has to figure out what GAP docs to cite, I suppose these for `gap.ini` - as it's ahead of any other initialisations

2023-11-24 10:31 UTC, tobiasdiez commented
Like this?

2023-11-24 11:33 UTC, dimpase commented
The GAP URL looks volatile. Also, please mention `gap.ini` explicitly

2023-11-25 03:30 UTC, tobiasdiez commented
> The GAP URL looks volatile. 

I agree, but it's the only deep link that's available (and it seem to be the same for at least the last year).

> Also, please mention `gap.ini` explicitly

Done.

2023-12-19 14:15 UTC, closed without merging