rename 'divided difference operator' to 'divided power operator'
sagemath/sage pull request #36796
Opened 2023-12-01 18:28 UTC by jacksonwalters

the action of e_i^{(p)} on Fock space corresponding to pair (i,p) is given by e_i^{(p)} := e_i^{p} / [p]_q

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-12-02 13:52 UTC, tscrim requested changes
The `f` operator should also have a similar change.

2023-12-02 13:52 UTC, tscrim commented on src/sage/algebras/quantum_groups/fock_space.py
> +                `e_i^{(p)}` = e_i^{p} / [p]_q on ``self``.
```suggestion
                `e_i^{(p)} = e_i^{p} / [p]_q` on ``self``.
```

2023-12-04 16:36 UTC, jacksonwalters reviewed
make analogous change for f

2023-12-05 00:17 UTC, tscrim requested changes
Thank you. This is good except for the change in `pkgs/sagemath-standard/setup.cfg`. Just revert that and it will be a positive review.

2023-12-05 23:17 UTC, tscrim approved these changes
@jacksonwalters Thank you.

@mkoeppe Matthias, something seems to be strange with this branch. Can you quickly fix the weirdness with the `setup.cfg`? I don't have super-push powers. This is a positive review otherwise.

2023-12-05 23:26 UTC, mkoeppe commented
I've squashed it away

2023-12-05 23:34 UTC, tscrim commented
@mkoeppe Thank you very much!

2023-12-08 19:21 UTC, jacksonwalters commented
sorry, is there anything I can do?

2023-12-28 04:05 UTC, tscrim commented
This should fix it. @jacksonwalters Please don't push to this branch (at least until this is merged). For future reference, it is good to have the branches have unique names; still somewhat short but related to the issue/PR in question.

2024-01-02 23:14 UTC, jacksonwalters commented
@tscrim Sounds good, thank you. I went ahead and deleted my local copy and re-cloned the repo. Git is no longer asking me to push changes. I will leave it alone.

2024-01-14 20:57 UTC, merged