Add is_(sparse_)paving() and automorphism_group()
sagemath/sage pull request #36962
Opened 2023-12-25 11:58 UTC by gmou3

Added three functions to the main matroid class.

These correspond to two connectivity check algorithms, `is_paving()` and `is_sparse_paving()`, and a miscellaneous function `automorphism_group()`. These are all standard and regularly used notions in matroid theory.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

2023-12-28 23:55 UTC, tscrim requested changes
Just a few small doc changes. Otherwise LGTM.

2023-12-28 23:55 UTC, tscrim commented on src/sage/matroids/matroid.pyx
> +        """
```suggestion
        OUTPUT:

        boolean

        EXAMPLES::

            sage: M = matroids.named_matroids.Vamos()
            sage: M.is_paving()
            True
        """
```
To match elsewhere.

2023-12-28 23:55 UTC, tscrim commented on src/sage/matroids/matroid.pyx
> +        a Boolean
Similarly here.

2023-12-28 23:55 UTC, tscrim commented on src/sage/matroids/matroid.pyx
> +        """
```suggestion
        [Oxl2011]_, p. 189.
        """
```
To match elsewhere.

2023-12-29 00:39 UTC, tscrim commented
Thanks. Can you squish those commits into one with at least slightly more useful message (e.g., "changes suggested by the reviewer")? Then this will be a positive review.

<rant> I *really* hate GH's way of incorporating reviewer changes. The commits are usually far too small, the message is completely generic without saying why these were being changed. I want to apply copious amounts of fire and holy water to it and then launch it into the sun. </rant>

2023-12-29 14:56 UTC, tscrim approved these changes
Thank you. LGTM.

2024-01-14 20:57 UTC, merged

2025-01-26 18:23 UTC, dimpase commented
@gmou3 - where do you get this definition of sparse paving? People [complain](https://groups.google.com/g/sage-support/c/XP351zBKTCM/m/JSSAgcpTDgAJ)  it's not correct, and I don't see any references to this added here.
Definitions found in https://doi.org/10.1016/j.ejc.2011.01.016
and https://www.sciencedirect.com/science/article/pii/S0196885812000802 look different.

2025-01-27 03:33 UTC, dimpase commented
There is also a missing reference to `paving` definition. One can refer to [Oxl2011], p.24.