Allow the use of PARI when appropriate for computing the Tate pairing
sagemath/sage pull request #36994
Opened 2024-01-02 16:46 UTC by GiacomoPope

To match `weil_pairing()` this pull request allows the use of PARI to compute the Tate pairing for elliptic curves over finite fields. 

This can be chosen explicitly via `algorithm="pari"`, as with the `weil_pairing()` call, or by default `algorithm=None` will use PARI when the base field of the elliptic curve is finite. 

This has been included for efficiency, with PARI offering a significant performance speed up:

```py
sage: GF(65537^2).inject_variables()
Defining z2
sage: E = EllipticCurve(GF(65537^2), [0,1])
sage: P = E(22, 28891)
sage: for _ in range(100):
....:     Q = E.random_point()
....:     e1 = P.tate_pairing(Q, 7282, 2, algorithm='sage')
....:     e2 = P.tate_pairing(Q, 7282, 2, algorithm='pari')
....:     assert e1 == e2
....:     
sage: %timeit P.tate_pairing(Q, 7282, 2, algorithm='sage')
1.33 ms ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
sage: %timeit P.tate_pairing(Q, 7282, 2, algorithm='pari')
52.3 µs ± 989 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2024-01-03 14:20 UTC, GiacomoPope commented
I'm now not actually convinced that the `tate_pairing()` is ever expected to be called over non-finite fields... I need to read more literature but if we only consider `E/K` with `characteristic(K) > 0`, then we can simply always use a pari call and simplify this function

2024-01-03 17:02 UTC, GiacomoPope commented
Rather than allow Pari to be used when the field is finite, we now assume that the field is finite for the reduced tate pairing, return a NotImplemented error when the field is not finite and always use Pari for the performance boost.

2024-01-04 13:47 UTC, GiacomoPope commented
I'm a bit confused about my doctests here... `codecov/patch` is highlighting that I didn't test for the check on line 1978, however this value error is precisely what I check in the `TESTs:` on lines 1931-1936, so I'm not sure what I'm doing wrong here.

2024-01-09 10:46 UTC, JohnCremona requested changes
It's a good idea to use pari where it has the functionality, as here (but was not the case back in 2011 I think).

I only made two suggestions, one a trivial one about wording and the other in response to the TODO.

2024-01-09 10:46 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/ell_point.py
> +            raise ValueError("The point P must be in the n-torsion")
Delete "in the" for better English

2024-01-09 10:46 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/ell_point.py
> +        exp = Integer((q**k - 1)/n)
I think it is a good idea to check that n divides q^k-1, for example by computing mod(q,n)^k, but only if q has been explicitly supplied and with a suitable error message if the condition fails.  So do this test in the code block which computes q perhaps.

2024-01-09 11:13 UTC, GiacomoPope commented
I have fixed the English in one of the ValueErrors and also added a new check that `n` divides `(q^k - 1)` which is only checked when `q` is not `None` (The case where a user supplies this information).

2024-01-09 12:05 UTC, JohnCremona approved these changes
Good, thanks!

2024-01-22 00:07 UTC, merged