Define behaviour of < and > for fractional ideals in a quaternion algebra
sagemath/sage pull request #37113
Opened 2024-01-19 15:56 UTC by syndrakon

Previously, comparison of quaternion algebra fractional ideals (in a quaternion algebra over QQ) was documented only for equality and did compare the matrices under HNF of bases of the ideals. This gave strange and undocumented behavior when comparing two ideals with inequalities.

This comparison is now replaced by the comparison of the fractional ideals as free modules. 

Now "smaller than" means "included in".

#sd123

2024-01-21 12:43 UTC, dcoudert requested changes
a few comments on the coding style.

2024-01-21 12:43 UTC, dcoudert commented on src/sage/modular/quatalg/brandt.py
> +                            #order by basis matrix (as ideals were previously ordered) for backward compatibility and deterministic order of the output
Comments need a space after `#` and are usually aligned in 80 columns mode
```diff
-                            #order by basis matrix (as ideals were previously ordered) for backward compatibility and deterministic order of the output
+                            # order by basis matrix (as ideals were previously
+	 		     # ordered) for backward compatibility and
+	 		     # deterministic order of the output
```

2024-01-21 12:43 UTC, dcoudert commented on src/sage/algebras/quatalg/quaternion_algebra.py
> +
You can remove this empty line.

2024-01-21 12:43 UTC, dcoudert commented on src/sage/algebras/quatalg/quaternion_algebra.py
> +        TESTS:
`TESTS:` -> `TESTS::`

and add en empty line after `TESTS::`

2024-02-02 14:03 UTC, yyyyx4 commented
Indeed, these look like flukes. (The `clean.py` failure is in almost every test log at the moment, and complaining about an untested empty line in a docstring is obviously nonsense...)

2024-02-02 14:04 UTC, yyyyx4 approved these changes
Looks good to me, thanks!

2024-02-13 23:40 UTC, merged