Fix a bug in reduction of element modulo ideal in exterior algebra
sagemath/sage pull request #37146
Opened 2024-01-23 06:38 UTC by trevorkarn

This adds a loop to continue doing reduction modulo a Grobner basis for an element modulo an ideal in the exterior algebra. This guarantees a unique representative for each element, and that representative will be $0$ if the element is in the ideal. This fixes #37108.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

None.

2024-01-23 08:40 UTC, tscrim requested changes
Thank you. Some minor things.

Does this also result in a reduced GB for the example you gave on #37108?

2024-01-23 08:40 UTC, tscrim commented on src/sage/algebras/exterior_algebra_groebner.pyx
> +        Check #37108 is fixed::
```suggestion
        Check :issue:`37108` is fixed::
```

2024-01-23 08:40 UTC, tscrim commented on src/sage/algebras/exterior_algebra_groebner.pyx
> +            ....:  e0*e1 - e0*e3 + e1*e3]
```suggestion
            sage: gens = [-e0*e1*e2 + e0*e1*e5 - e0*e2*e3 - e0*e3*e5 + e1*e2*e3 + e1*e3*e5,
            ....:         e1*e2 - e1*e5 + e2*e5, e0*e2 - e0*e4 + e2*e4,
            ....:         e3*e4 - e3*e5 + e4*e5, e0*e1 - e0*e3 + e1*e3]
```

2024-01-24 07:09 UTC, trevorkarn commented
> Thank you. Some minor things.

Fixed - thanks!

> Does this also result in a reduced GB for the example you gave on #37108?

No it does not.

```
sage: N = 4
sage: E = ExteriorAlgebra(QQ,binomial(N,2))
sage: e = E.gens()
sage: K = matroids.CompleteGraphic(N);
sage: C = K.circuits()
sage: ideal_gens = [sum([(-1)^j*E.prod(e[i] for i in list(c)[:j] + list(c)[j+1:]) for j in range(len(c))]) for c in C]
sage: OS = E.quo(ideal_gens)
sage: I = OS.defining_ideal()
sage: I.groebner_basis()
(e0*e1 - e0*e3 + e1*e3,
 e0*e2 - e0*e4 + e2*e4,
 e1*e2 - e1*e5 + e2*e5,
 -e0*e1*e2 + e0*e1*e5 - e0*e2*e3 - e0*e3*e5 + e1*e2*e3 + e1*e3*e5,
 e3*e4 - e3*e5 + e4*e5)
sage: GS = I._groebner_strategy
sage: GS.groebner_basis
(e0*e1 - e0*e3 + e1*e3,
 e0*e2 - e0*e4 + e2*e4,
 e1*e2 - e1*e5 + e2*e5,
 -e0*e1*e2 + e0*e1*e5 - e0*e2*e3 - e0*e3*e5 + e1*e2*e3 + e1*e3*e5,
 e3*e4 - e3*e5 + e4*e5)
sage: GS.reduce_computed_gb()
sage: GS.groebner_basis
(e0*e1 - e0*e3 + e1*e3,
 e0*e2 - e0*e4 + e2*e4,
 e1*e2 - e1*e5 + e2*e5,
 e3*e4 - e3*e5 + e4*e5)
```

2024-01-25 13:30 UTC, tscrim approved these changes
This is definitely the more important bug to fix, so let's get this in.

However, we should still fix that the GB is not reduced when it is claiming it is.

2024-01-25 13:51 UTC, trevorkarn commented
Sounds like a plan! Thanks!

2024-02-02 21:36 UTC, merged