throw ValueError instead of TypeError when logarithm doesn't exist in AdditiveAbelianGroupWrapper
sagemath/sage pull request #37142
Opened 2024-01-22 14:35 UTC by yyyyx4

Attempting to run the higher-level algorithms in the `additive_abelian_wrapper.py` file on a group with unhashable elements will also throw a `TypeError`, which leads to very strange behavior (rather than failing with a clear error message, as it should).

#sd123

2024-01-23 00:25 UTC, grhkm21 commented
LGTM

2024-01-24 17:38 UTC, roed314 commented
@grhkm21, I've invited you to the Sage organization (and the Triage team).  Once you accept, you can review PRs.

2024-01-25 21:39 UTC, grhkm21 commented
Doctests are failing

2024-01-25 21:45 UTC, grhkm21 requested changes
Doctests are failing. For example, line 110 (P1 in G) throws an error now even though it should return False.

Maybe [this line](https://github.com/yyyyx4/sage/blob/public/throw_ValueError_when_logarithm_does_not_exist/src/sage/modules/fg_pid/fgp_module.py#L705) should be modified to catch `ValueError` too?

2024-01-27 21:23 UTC, yyyyx4 commented
Thanks, and sorry, I ripped this out of a branch with a larger set of changes and apparently forgot to run the tests again prior to making the pull request...

2024-01-30 15:26 UTC, grhkm21 commented
LGTM :D

2024-02-02 21:36 UTC, merged