Fix a bug in `correlation_immunity` function
sagemath/sage pull request #37183
Opened 2024-01-28 19:57 UTC by RuchitJagodara

This patch fixes #36294. This PR fixes the issue of wrong answer given by 
correlation_immunity function. And I have also added some doctests in this.
﻿

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.

### :hourglass: Dependencies

2024-02-25 18:18 UTC, RuchitJagodara commented
@grhkm21, can you please review this PR ?

2024-02-25 18:59 UTC, grhkm21 commented on src/sage/crypto/boolean_function.pyx
>                      c = min(c, hamming_weight(i))
Add a `break` after

2024-02-26 13:52 UTC, RuchitJagodara commented on src/sage/crypto/boolean_function.pyx
>                      c = min(c, hamming_weight(i))
Done !

2024-02-26 14:44 UTC, RuchitJagodara commented
I have updated the code according to your suggestion.

2024-03-04 11:02 UTC, RuchitJagodara commented
@grhkm21, can you review this?

2026-02-25 17:23 UTC, jalich commented
@grhkm21  @vbraun  any chance this bugfix may be merged? I need this functionality and my current workaround is to compile sage myself with this patch merged.

2026-02-25 20:15 UTC, vbraun commented
> @grhkm21  @vbraun  any chance this bugfix may be merged? I need this functionality and my current workaround is to compile sage myself with this patch merged.

Can you review?

2026-02-26 11:03 UTC, jalich requested changes
The early abort is wrong and has to be reverted.

2026-02-26 11:03 UTC, jalich commented on src/sage/crypto/boolean_function.pyx
This change is wrong:

```
bf = BooleanFunction([True, False, True, False, False, False, False, False])
bf.walsh_hadamard_transform()
(4, 0, 0, -4, -4, 0, 0, -4)
```

since `W[0b100] != 0`, the correlation immunity is 0. However, since `0b011 < 0b100`, this change will report a correlation immunity of 1

2026-02-26 11:03 UTC, jalich commented on src/sage/crypto/boolean_function.pyx
```suggestion
                    c = min(c, hamming_weight(i))
```

2026-05-20 13:47 UTC, closed without merging