Add Pseudomorphism Implementation for Free Modules
sagemath/sage pull request #37214
Opened 2024-02-01 08:50 UTC by ymusleh

The goal of this PR is to add a basic implementation of pseudomorphisms of free modules.

Let $M$ be a free module over a ring $R$. Let $\theta: R \to R$ be a ring homomorphism and $\delta: R \to R$ a ring derivation.

A pseudomorphism $f: M \to M$ is an additive map *twisted* by $(\theta, \delta)$ such that

$f(\lambda x) = \theta(\lambda)f(x) + \delta(\lambda)x$

Currently this PR implements the following functionality:

- Constructors for pseudomorphisms and the space of pseudomorphisms with a fixed twist
- Call methods to apply pseudomorphisms to a fixed element of the module
- Call method for pseudohomspace to coerce matrix or module morphisms to a pseudomorphism

See the documentation for more details. 

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

None

2024-02-01 08:57 UTC, ymusleh commented on src/sage/modules/free_module_pseudomorphism.py
> +        TESTS::
Add tests.

2024-02-01 09:24 UTC, xcaruso requested changes

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module.py
> +    def PseudoHom(self, twist=None, codomain=None):
A doctest is needed.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module.py
> +        EXAMPLE::
```suggestion
        EXAMPLES::
```

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module.py
> +        sage:
Identation is needed

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +    def __init__(self, X, Y, twist=None):
Again, a doctest is needed.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +            Free module pseudomorphism defined by the                 matrix
Why all these spaces?

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +    def __call__(self, A, **kwds):
I think this code should go in the `__init__` function of the element.
And you need to use the `_element_constructor` stuff.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +    def _matrix_space(self):
Doctests are needed.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +        """
Examples in the doctest are needed.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudohomspace.py
> +        return self.base_homspace.identity()
Do you return a matrix or a pseudomorphism?

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudomorphism.py
> +            self.base_morphism = domain.hom(base_morphism, codomain)
Should be better to write `self._base_morphism`; the same for the other private parameters.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudomorphism.py
> +    def __call__(self, x):
I think you should rather implement `_call_` and let the `__call__` method of the parent class do the coercion stuff.

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudomorphism.py
> +            self.base_morphism = domain.hom(base_morphism, codomain)
Also why don't you work directly with the matrix (instead of building this linear morphism, which is not really relevant IMO).

2024-02-01 09:24 UTC, xcaruso commented on src/sage/modules/free_module_pseudomorphism.py
> +        """
Examples and needed.
The same for the few next methods.

2024-02-25 20:56 UTC, ymusleh commented
@xcaruso What is your opinion on continuing with this since I see you closed the Anderson motive PR, which was a major motivation for implementing pseudomorphisms. Should we still go ahead and get this merged?

2024-02-26 07:15 UTC, xcaruso commented
Yes.
I closed the PR on Anderson motive by mistake because I got a problem when trying to push. So I finally created a new branch on my github account: https://github.com/xcaruso/sage/tree/anderson-motives
I will re-create a PR (more probably, several PRs) when this will be ready.

2025-02-21 21:19 UTC, merged