make a category of Dedekind domains, remove code from ring.pyx
sagemath/sage pull request #37234
Opened 2024-02-03 17:51 UTC by fchapoton

This is creating a `DedekindDomains` category and moving the associated code from `ring.pyx` to the category.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2024-02-03 17:51 UTC, fchapoton commented
maybe one should make ZZ belong to this category ?

2024-02-05 06:52 UTC, tscrim requested changes
One tiny thing (it should be fixed more broadly though). However, I think it is a good thing to refine the category of `ZZ` and remove duplicate methods (these should never be a critical part of any algorithm IMO, so downgrading Cython -> Python shouldn't have any real effect...I hope).

2024-02-05 06:52 UTC, tscrim commented on src/sage/categories/dedekind_domains.py
> +            return 1
```suggestion
            return ZZ.one()
```
To avoid Python `int`s getting out.

2024-02-05 10:36 UTC, fchapoton commented
It seems that ZZ prefers to inherit `krull_dimension` from `rings/ring.pyx`. Same for `is_integrally_closed`. Not sure how to fix that.

2024-02-05 12:26 UTC, tscrim commented
Ah, right, categories have the lowest precedence. Yes, we can revert removing them. It was just trying to avoid some redundancies.

2024-02-06 05:30 UTC, tscrim requested changes
Thank you.

One last thing, but unfortunately it is somewhat annoying. We have an import of `DedekindDomain` in `rings/all.py`, which makes its way into the global namespace. So we need to properly formally deprecate the class. *sigh*

2024-02-06 13:13 UTC, tscrim approved these changes
Thank you. Once the bot shows tests pass, you can set a positive review.

2024-02-13 23:40 UTC, merged