use parent in quaternions
sagemath/sage pull request #37299
Opened 2024-02-11 16:24 UTC by fchapoton

replace the auld-style class by `Parent` and categories for quaternion algebras.

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

2024-02-12 12:45 UTC, tscrim requested changes
Just some little things. Otherwise LGTM.

2024-02-12 12:45 UTC, tscrim commented on src/sage/categories/algebras.py
> +                raise AttributeError("Basis is not yet implemented for this algebra.")
A while-we-are-at-it thing:
```suggestion
                raise AttributeError("basis is not yet implemented for this algebra")
```

2024-02-12 12:45 UTC, tscrim commented on src/sage/categories/algebras.py
> +        def has_standard_involution(self):
Should we move this method to `AlgebrasWithBasis` instead? Then we can assume it has a `basis()` method.

2024-02-12 19:36 UTC, fchapoton commented on src/sage/categories/algebras.py
> +        def has_standard_involution(self):
not here and now. This would require making quaternion algebras to be `WithBasis` (they are not) and this takes some work

2024-02-13 01:55 UTC, tscrim commented on src/sage/categories/algebras.py
> +        def has_standard_involution(self):
Understood, no problem.

2024-02-13 01:55 UTC, tscrim approved these changes

2024-02-13 01:56 UTC, tscrim commented
LGTM.

2024-02-25 11:16 UTC, merged