README.md: Move all mentions of release tarballs to the installation guide
sagemath/sage pull request #37309
Opened 2024-02-13 02:06 UTC by mkoeppe

As proposed in https://groups.google.com/g/sage-devel/c/5kmxaw105lg/m/liCPKG4bAQAJ

### :memo: Checklist

- [ ] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2024-02-20 21:16 UTC, jhpalmieri reviewed
Looks good to me, just a few minor comments. I'm happy to approve, although I'm not sure if this should be merged yet, since the "discussion" on sage-devel is ongoing.

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +#. If you need wish to prepare for having to build Sage in an environment
``
```suggestion
#. If you wish to prepare for having to build Sage in an environment
```

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +#. If you need wish to prepare for having to build Sage in an environment
(Or delete "wish" and keep "need")

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +     This creates the subdirectory `````sage-x.y```. Now change into it::
```suggestion
     This creates the subdirectory ``sage-x.y``. Now change into it::
```

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +     After downloading the source tarball ```sage-x.y.tar.gz``` into
```suggestion
     After downloading the source tarball ``sage-x.y.tar.gz`` into
```

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +     After downloading the source tarball ```sage-x.y.tar.gz``` into
I don't think we need visible backticks in the html documentation, which is what triple backticks produce.

2024-02-20 21:16 UTC, jhpalmieri commented on src/doc/en/installation/source.rst
> +     a directory ```~/sage/```::
```suggestion
     a directory ``~/sage/``::
```

2024-02-20 21:49 UTC, mkoeppe commented on src/doc/en/installation/source.rst
> +     After downloading the source tarball ```sage-x.y.tar.gz``` into
Thanks. I think I may need to clean my keyboard if these typos become more frequent

2024-02-20 21:52 UTC, mkoeppe commented
> I'm not sure if this should be merged yet, since the "discussion" on sage-devel is ongoing.

I'd say, let's just go ahead. Haven't seen any reaction in the thread (other than yours)

2024-02-21 11:06 UTC, saraedum commented
Cloning the repo uses 1GB of disk (without any upstream packages downloaded.) Using the tarball seems more economical to me in this case. Downloading a tarball of the GitHub repo (which is not advertised anywhere) is just 28MB for me.

Anyway, I don't really mind much either way. If you guys think this is a good idea, go ahead.

2024-02-21 11:58 UTC, dimpase commented
> Cloning the repo uses 1GB of disk (without any upstream packages downloaded.) 

no, it's "only" 615 Mb, and over 60% of it is `.git/`
```
$ git clone -c core.symlinks=true --origin upstream --branch develop --tags https://github.com/sagemath/sage.git
...
$ du -h sage/
...
615M	sage/
$ du -h sage/.git
388M	sage/.git/objects/pack
...
390M	sage/.git
```

Adding `--filter=blob:none`, as recommended in https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/ - results in only 141Mb in  `sage/.git`, and 366M for the whole `sage/`.

Perhaps this is, disk space and bandwidth-wise, a better advice than the one in the PR, to use the latter.


> Using the tarball seems more economical to me in this case. Downloading a tarball of the GitHub repo (which is not advertised anywhere) is just 28MB for me.
> 
> Anyway, I don't really mind much either way. If you guys think this is a good idea, go ahead.

2024-02-21 12:00 UTC, dimpase requested changes
consider adding `--filter=blob:none` to git clone options

2024-02-21 17:36 UTC, mkoeppe commented
Done in 04145de

2024-02-21 17:54 UTC, mkoeppe commented
Also need to link to git install instructions (similar to #30201)

2024-02-26 22:23 UTC, mkoeppe commented
Thanks for the review.

2024-03-25 23:47 UTC, merged