fix bad Frac(sparse polynomial ring over finite field)
sagemath/sage pull request #37377
Opened 2024-02-17 11:18 UTC by mezzarobba

The construction of the fraction field of a polynomial ring R over a
small finite fields tried ot use a class dedicated to the dense case
regardless whether R was dense or sparse, resulting in corrupted
elements represented as dense polynomials but with a parent set to a
sparse ring.

Fixes #37374

2024-02-20 03:29 UTC, tscrim requested changes
Just a few little details.

2024-02-20 03:29 UTC, tscrim commented on src/sage/rings/polynomial/polynomial_ring.py
> +        Issue :issue:`37374`:
```suggestion
        Fixed :issue:`37374`::
```

2024-02-20 03:29 UTC, tscrim commented on src/sage/rings/polynomial/polynomial_ring.py
> +        Returns the fraction field of self.
```suggestion
        """
        Return the fraction field of ``self``.
```

2024-02-20 03:29 UTC, tscrim commented on src/sage/rings/fraction_field_FpT.pyx
> +        - ``R`` -- A dense polynomial ring over a finite field of prime order `p` with `2 < p < 2^16`
```suggestion
        - ``R`` -- a dense polynomial ring over a finite field
          of prime order `p` with `2 < p < 2^16`
```
Two while-we-are-at-it changes.

2024-02-20 03:29 UTC, tscrim commented on src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
> +        Negative powers work (over prime fields) but use a generic
```suggestion
        Negative powers work (over prime fields) but use the generic
```

2024-02-20 11:25 UTC, mezzarobba commented
Thanks for your comments!

-- 
Marc

2024-02-20 12:35 UTC, tscrim approved these changes
Thanks. You can set a positive review after these are changed.

2024-02-20 12:35 UTC, tscrim commented on src/sage/rings/polynomial/polynomial_ring.py
> +        Issue :issue:`37374`::
```suggestion
        :issue:`37374`::
```
This is redundant, including in the compiled doc.

2024-02-20 12:35 UTC, tscrim commented on src/sage/rings/fraction_field_FpT.pyx
> +          `p` with `2 < p < 2^16`
```suggestion
          `p` with `2 < p < 2^{16}`
```
Sorry, one more little thing to display properly.

2024-02-20 15:07 UTC, tscrim commented
No problem. Thank you.

2024-02-21 22:30 UTC, vbraun commented
```
sage -t --warn-long 38.3 --random-seed=123 src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx
**********************************************************************
File "src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx", line 878, in sage.rings.polynomial.polynomial_modn_dense_ntl.Polynomial_dense_modn_ntl_zz.__pow__
Failed example:
    (x-1)^(-5)
Expected:
    Traceback (most recent call last):
    ...
    TypeError: self must be an integral domain.
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "sage/structure/category_object.pyx", line 855, in sage.structure.category_object.CategoryObject.getattr_from_category
        return self._cached_methods[name]
    KeyError: 'fraction_field'
    <BLANKLINE>
    During handling of the above exception, another exception occurred:
    <BLANKLINE>
    Traceback (most recent call last):
      File "sage/structure/element.pyx", line 2744, in sage.structure.element.RingElement._div_
        frac = self._parent.fraction_field()
      File "sage/structure/category_object.pyx", line 849, in sage.structure.category_object.CategoryObject.__getattr__
        return self.getattr_from_category(name)
      File "sage/structure/category_object.pyx", line 864, in sage.structure.category_object.CategoryObject.getattr_from_category
        attr = getattr_from_other_class(self, cls, name)
      File "sage/cpython/getattr.pyx", line 357, in sage.cpython.getattr.getattr_from_other_class
        raise AttributeError(dummy_error_message)
    AttributeError: 'PolynomialRing_dense_mod_n_with_category' object has no attribute '_SageObject__custom_name'
    <BLANKLINE>
    During handling of the above exception, another exception occurred:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/home/release/Sage/src/sage/doctest/forker.py", line 712, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/release/Sage/src/sage/doctest/forker.py", line 1147, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.rings.polynomial.polynomial_modn_dense_ntl.Polynomial_dense_modn_ntl_zz.__pow__[11]>", line 1, in <module>
        (x-Integer(1))**(-Integer(5))
        ~~~~~~~~~~~~~^^~~~~~~~~~~~~~~
      File "sage/rings/polynomial/polynomial_modn_dense_ntl.pyx", line 917, in sage.rings.polynomial.polynomial_modn_dense_ntl.Polynomial_dense_modn_ntl_zz.__pow__
        return ~r
      File "sage/rings/polynomial/polynomial_element.pyx", line 1522, in sage.rings.polynomial.polynomial_element.Polynomial.__invert__
        return self.parent().one() / self
      File "sage/rings/polynomial/polynomial_element.pyx", line 2701, in sage.rings.polynomial.polynomial_element.Polynomial.__truediv__
        return (<Element>left)._div_(right)
      File "sage/structure/element.pyx", line 2746, in sage.structure.element.RingElement._div_
        raise bin_op_exception('/', self, other)
    TypeError: unsupported operand parent(s) for /: 'Univariate Polynomial Ring in x over Ring of integers modulo 100 (using NTL)' and 'Univariate Polynomial Ring in x over Ring of integers modulo 100 (using NTL)'
**********************************************************************
1 item had failures:
   1 of  13 in sage.rings.polynomial.polynomial_modn_dense_ntl.Polynomial_dense_modn_ntl_zz.__pow__
    [335 tests, 1 failure, 0.31 s]
----------------------------------------------------------------------
sage -t --warn-long 38.3 --random-seed=123 src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx  # 1 doctest failed
----------------------------------------------------------------------
```

2024-02-23 10:22 UTC, mezzarobba commented
> File "src/sage/rings/polynomial/polynomial_modn_dense_ntl.pyx", line 878, in sage.rings.polynomial.polynomial_modn_dense_ntl.Polynomial_dense_modn_ntl_zz.__pow__
> Failed example:
>     (x-1)^(-5)

This is with some additional commits merged in, right? Because I can't reproduce it with my branch alone. Anyway, I changed the test to ignore the exception test.

2024-03-20 23:00 UTC, vbraun commented
Merge conflict

2024-03-31 23:16 UTC, merged