Refactor `bootstrap`, `bootstrap-conda`, `m4/sage_spkg_collect.m4` through `sage --package properties`
sagemath/sage pull request #37430
Opened 2024-02-22 17:31 UTC by mkoeppe

Using the command `sage --package properties` added in https://github.com/sagemath/sage/pull/37018, we eliminate some direct references to `build/pkgs/` from various scripts and reduce code duplication in reading SPKG metadata.

Review instructions:
- There is a change to the `bootstrap`-generated file `m4/sage_spkg_configures.m4`: The macro `SAGE_SPKG_COLLECT_INIT` is now called explicitly, with an argument (the full list of packages)

- Split out from #36740

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

2024-02-23 13:07 UTC, tobiasdiez requested changes

2024-02-23 13:07 UTC, tobiasdiez commented on bootstrap-conda
> +eval $(sage-package properties --format=shell :all:)
I don't think it's a good idea to tie bootstrap conda even closer to the sage-the-distribution scripts. Please revert the changes in the bootstrap-conda file.

2024-02-23 16:59 UTC, mkoeppe commented on bootstrap-conda
> +eval $(sage-package properties --format=shell :all:)
Nonsense

2024-03-21 21:02 UTC, saraedum commented on bootstrap-conda
> +eval $(sage-package properties --format=shell :all:)
@mkoeppe could you elaborate why this is "nonsense" from your point of view?

2024-03-21 21:24 UTC, mkoeppe commented on bootstrap-conda
> +eval $(sage-package properties --format=shell :all:)
This PR replaces direct access to the files in `build/pkgs` (an implementation detail of the sage-bootstrap package) by access through a script of the sage-bootstrap package. Such refactoring does not "tie bootstrap closer to sage-the-distribution scripts".

2024-05-14 05:52 UTC, mkoeppe commented
@orlitzky If you have a moment, could you take a look if my changes to `SAGE_PYTHON_PACKAGE_CHECK` look OK to you?

2024-05-14 17:13 UTC, orlitzky commented
Yeah LGTM

2024-05-17 04:40 UTC, mkoeppe commented
@orlitzky Can I interest you in reviewing the whole PR? 
It's the way to what you asked for in https://github.com/sagemath/sage/pull/37902#issuecomment-2084004407

2024-06-06 18:32 UTC, mkoeppe commented
@roed314 Would you perhaps be interested in reviewing this? See https://github.com/sagemath/sage/pull/37902#issuecomment-2116597286

2024-06-12 11:11 UTC, kwankyu commented
LGTM as far as I can understand. Most changes are simplifications using new `sage --package` command.

But with this PR, build fails for me:

[brial-1.2.8.log](https://github.com/user-attachments/files/15803681/brial-1.2.8.log)

2024-06-12 17:51 UTC, mkoeppe commented
Thanks for testing. Dependencies are broken; I've fixed this in one of the follow-up PRs already, I'll try to find it.

2024-06-13 03:34 UTC, kwankyu commented on m4/sage_python_package_check.m4
>  #
```
) are
```

2024-06-13 03:49 UTC, kwankyu approved these changes
Thanks. Working well.

2024-06-13 04:03 UTC, mkoeppe commented
Thank you!

2024-06-16 09:30 UTC, vbraun commented
Bootstrap download of the confball does not work (note the missing version):
```
$ ./bootstrap -u http://sagepad.org/spkg/upstream/configure
[...]
Error: downloading configure-.tar.gz from http://sagepad.org/spkg/upstream/configure failed
```

2024-06-16 11:43 UTC, mkoeppe commented
@vbraun Do you really use `bootstrap -u` or can we remove this option?

2024-06-16 11:47 UTC, mkoeppe commented
(setting `SAGE_SERVER=http://sagepad.org` should have the same effect)

2024-06-16 14:37 UTC, vbraun commented
The buildbot uses it to download the confball that is being tested

2024-06-16 17:00 UTC, mkoeppe commented
The existing code there doesn't even unpack the downloaded tarball

2024-06-16 17:17 UTC, mkoeppe commented
> The existing code there doesn't even unpack the downloaded tarball

Here's a repaired version, I've kept that as is

2024-06-22 19:42 UTC, merged