`SetPartition` return empty iterator instead of erroring out in degenerate cases
sagemath/sage pull request #37781
Opened 2024-04-10 09:10 UTC by Nolord

Replaced the error raised by `SetPartition` in a degenerate case (see below) by an empty iterator, to match the behaviour of similar functions such as `Partitions` and `OrderedSetPartitions`. Old behaviour:
```Python
sage: list( Partitions(3,length=4) )
[]
sage: list( OrderedSetPartitions(range(3),4) )
[]
sage: list( SetPartitions(range(3),4) )
...
ValueError: part must be <= len(set)
```
New behaviour
```Python
sage: list( SetPartitions(range(3),4) )
[]
```
This solves issue #37643.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation accordingly.

### :hourglass: Dependencies

2024-04-10 09:20 UTC, Nolord commented
Also, I'm not sure if a similar fix would be needed for the case when the second argument is a list. The element in the list should add up to the length of the set:
```Python
sage: SetPartitions(range(4), [2, 1, 1])
Set partitions of {0, 1, 2, 3} with sizes in [2, 1, 1]
sage: SetPartitions(range(4), [2, 1])
...
ValueError: part must be an integer partition of 4
```
We have the equivalence
```
sage: sorted(list(SetPartitions(range(4), 3))) == sorted(list(SetPartitions(range(4), [2, 1, 1])))
True
```
Maybe the error above should also be replaced by an empty iterator.

2024-04-10 11:01 UTC, grhkm21 commented
> Also, I'm not sure if a similar fix would be needed for the case when the second argument is a list.

yes

2024-04-15 04:40 UTC, tscrim requested changes
Let me also mention as a counterpoint, having the errors here are useful for catching logic bugs. So `OrderedSetPartitions` would error out for such clearly bad input.

Personally, I agree with your change here. However, it is something to consider.

Also, in case you haven't already, please check to make sure every place within Sage this is being called, the code isn't trying to catch the `ValueError` as program flow. (I don't think this is done anywhere, but we should check as it might not be covered by doctests.)

2024-04-15 04:40 UTC, tscrim commented on src/sage/combinat/set_partition_iterator.pyx
> +            yield from_word(<list> P, base)
```suggestion
    if n < k:
        return
    for P in _set_partition_block_gen(n, k, a):
        yield from_word(<list> P, base)
```
Basically bikeshedding, but I find this easier to understand (and easier to work with if we extend it).

2024-04-15 07:58 UTC, Nolord commented
> Let me also mention as a counterpoint, having the errors here are useful for catching logic bugs. So `OrderedSetPartitions` would error out for such clearly bad input.

I agree that getting an empty iterator in this case would most likely be unintended.

> Also, in case you haven't already, please check to make sure every place within Sage this is being called, the code isn't trying to catch the `ValueError` as program flow. (I don't think this is done anywhere, but we should check as it might not be covered by doctests.)

The only other file where the keyword `set_partition_iterator_blocks` is used is in `sage/src/sage/combinat/combinat_cython.pyx`. But it is only imported via `LazyImport`.

2024-04-19 07:41 UTC, tscrim approved these changes
That's not quite what I asked, but I checked and didn't see any cases of what I was looking for either. Anyways, this is good for me. Thank you.

2024-04-27 15:59 UTC, merged