`FreeModuleHomset`: Create subclass `FreeModuleEndset`, add methods for invariants `det`, `charpoly`, `fcp`, etc.
sagemath/sage pull request #37831
Opened 2024-04-19 05:02 UTC by mkoeppe

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-04-22 04:40 UTC, tscrim requested changes
The `__classcall_private__` needs a doctest. Otherwise LGTM.

2024-04-22 19:43 UTC, mkoeppe commented
> The `__classcall_private__` needs a doctest.

Thanks for catching this, done in abc65721ecb

2024-04-23 00:39 UTC, tscrim approved these changes
LGTM.

2024-04-23 00:46 UTC, mkoeppe commented
Thank you!

2024-04-24 11:17 UTC, egourgoulhon commented on src/sage/tensor/modules/free_module_homset.py
>          is some endomorphism set::
```suggestion
```

2024-04-24 11:18 UTC, egourgoulhon commented on src/sage/tensor/modules/free_module_homset.py
>  - Eric Gourgoulhon, Michal Bejger (2014-2015): initial version
```suggestion
- Eric Gourgoulhon, Michal Bejger (2014-2015): initial version
- Matthias Koeppe (2024): add :class:`FreeModuleEndset` 
```

2024-04-24 11:25 UTC, egourgoulhon commented on src/sage/tensor/modules/free_module_morphism.py
>  - Eric Gourgoulhon, Michal Bejger (2014-2015): initial version
```suggestion
- Eric Gourgoulhon, Michal Bejger (2014-2015): initial version
- Matthias Koeppe (2024): add subclass :class:`FiniteRankFreeModuleEndomorphism`
```

2024-04-24 11:31 UTC, egourgoulhon commented on src/sage/tensor/modules/free_module_morphism.py
> +        EXAMPLES:
```suggestion
        EXAMPLES::
```

2024-04-24 11:33 UTC, egourgoulhon requested changes
LGTM as well. I have only minor suggestions.

2024-04-25 01:14 UTC, mkoeppe commented
Thanks a lot for these edits!

2024-04-25 14:25 UTC, egourgoulhon approved these changes
Thanks for the changes!

2024-05-12 19:52 UTC, merged