Implement the ladder idempotents of the symmetric group algebra
sagemath/sage pull request #37859
Opened 2024-04-24 05:36 UTC by tscrim

We implement the so-called ladder idempotents of the symmetric group algebra $F[S_n]$, defined by Ryom-Hansen, which can be used to construct the projective covers of simple modules when the field $F$ has positive characteristic.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-04-24 05:37 UTC, tscrim commented
@AndrewMathas This is something I came across while trying to devise a method to construct the projective covers. Thought it might be worthwhile to add.

2024-05-01 05:52 UTC, tscrim commented
Thank you. That's a good point. I think I lost track of what $e$ meant when writing the function. I also made the other change you suggested and added your code.

In the trac workflow, you would be allowed to push commits. However, with GH this has become very inconvenient for reviewers (or general collaborative code writing) to do... (The "standard" ways would be to either do a PR to the branch on my fork (not the main repo here);  just do your own PR with the additional commit(s); or I pull commits from a specific branch of yours) Well, no matter what I am okay with you pushing changes in one form or another (we might even set up something so you can just generically push to my fork, but it might not be worth the trouble)

2024-05-01 05:58 UTC, AndrewMathas requested changes
Looks good but one more minor change that I should have picked up the first time.

2024-05-01 05:58 UTC, AndrewMathas commented on src/sage/combinat/partition.py
>          - ``e`` -- a positive integer
Sorry, should have caught this earlier too. You want `e` to be a non-negative integer, where `e=0` corresponds to (quantum) characteristic 0.

2024-05-01 05:58 UTC, AndrewMathas commented on src/sage/combinat/partition.py
> +        e -= 1
To cope with `e=0` this could be: `e = self.size() if e=0 else e-1`

2024-05-01 06:07 UTC, tscrim commented
What do you want `ladders()` to do when `e = 0`? Error out?

2024-05-01 06:45 UTC, tscrim commented
For the `ladder_tableau()` method, I agree that this is clear. However, the behavior of `ladders()` depends on the size.  While it isn't a major difference, it is not quite consistent as I add boxes to the bottom. Compare:
```
sage: Partition([3, 2]).ladders(0)
{0: [(0, 0)], 1: [(0, 1)], 2: [(0, 2)], 5: [(1, 0)], 6: [(1, 1)]}
sage: Partition([3, 2, 1]).ladders(0)
{0: [(0, 0)], 1: [(0, 1)], 2: [(0, 2)], 6: [(1, 0)], 7: [(1, 1)], 12: [(2, 0)]}
sage: Partition([3, 2, 1, 1]).ladders(0)
{0: [(0, 0)], 1: [(0, 1)], 2: [(0, 2)], 7: [(1, 0)], 8: [(1, 1)], 14: [(2, 0)], 21: [(3, 0)]}
```
In particular, see the ladder for the cell `(1, 0)` changing. It's just a matter of what the best behavior would be, but it is unlikely to be used in that setting I feel. So this might basically be bikeshedding...

2024-05-02 01:08 UTC, tscrim commented
Thank you. I added some more documentation and examples to illustrate these points about `e = 0`. If everything looks good to you, then please approve the PR and also set it to a positive review. (The former is more important as I cannot do that, but I can do the latter).

2024-05-02 08:45 UTC, tscrim commented
Thank you. Could you also please approve the PR by going to the "files changed" and do the "review changes" with selecting the "approve"?

2024-05-02 08:46 UTC, tscrim commented
(The last force push was just to remove some trailing whitespace I accidentally added.)

2024-05-02 11:21 UTC, AndrewMathas approved these changes
Everything looks good to me.

2024-05-02 13:43 UTC, tscrim commented
Thank you.

2024-05-04 09:09 UTC, vbraun commented
Docs don't build (see CI)

2024-05-07 03:10 UTC, tscrim commented
Sorry about that; fixed.

2024-05-12 19:52 UTC, merged