Fix order computation of linear groups
sagemath/sage pull request #37980
Opened 2024-05-10 21:36 UTC by S17A05

#36881 introduced some wrong results for orders of general linear groups since it did not check whether the base ring is a field. We add the necessary checks as well as formulas for some further cases, namely $\mathbb{Z}$ and $\mathbb{Z}/q\mathbb{Z}.$ Finally, we add a `NotImplementedError` for the cases that are not supported.

The formula for the general linear group over $\mathbb{Z}/q\mathbb{Z}$ is taken from https://math.stackexchange.com/a/2044571, and for the order of the special linear group we use the group isomorphism induced by the determinant.

Fixes #37934.

2024-05-14 01:06 UTC, tscrim requested changes
Mostly a bunch of little things. We do not want to return Python `int`s. We can take advantage of the closure in Python.  It would be good to add a test verifying the result:
```python
sage: G = GL(2, Integers(6))
sage: G.order() == len(list(G))
True
sage: G = SL(2, Integers(6))
sage: G.order() == len(list(G))
True
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
>              return 1
```suggestion
            return ZZ.one()
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +                return 1
```suggestion
                return ZZ.one()
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +            return 2
```suggestion
            return ZZ(2)
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +                ord = ord // (q-1)
```suggestion
            if self._special:
                return ord // (q-1)
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +        def order_over_finite_field(q, n, special):
```suggestion
        def order_over_finite_field(q, n):
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +                return order_over_finite_field(q, n, self._special)
```suggestion
                return order_over_finite_field(q, n)
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +                    ord_base = order_over_finite_field(p, n, self._special)
```suggestion
                    ord_base = order_over_finite_field(p, n)
```

2024-05-14 01:06 UTC, tscrim commented on src/sage/groups/matrix_gps/linear.py
> +                        ord *= p**((e-1)*(n**2 - 1)) * ord_base
```suggestion
                        ord *= p**((e-1)*(n**2-1)) * ord_base
```
Being consistent about the spacing.

2024-05-14 06:41 UTC, tscrim approved these changes
Thank you. LGTM.

2024-05-14 09:21 UTC, S17A05 commented
Not sure why the tests failed, but the error makes it seem like a CI issue.

2024-05-15 03:58 UTC, tscrim commented
Indeed, something seems borked with it.

2024-05-25 10:11 UTC, merged