lazy series/pushout experiment
sagemath/sage pull request #38108
Opened 2024-05-29 07:21 UTC by mantepse

- Initial implementation of integral() for lazy series; improvements to derivative.
- Adding functional equation and taylor series constructions.
- Adding more examples, fixing bugs, streamlining the implementation.
- Fixing more bugs, updating the inputs, other touchups.
- Improving the functional defintion; changing the method name/location; moving towards full coverage.
- Full doctest coverage for the PR.
- Adding Martin's patch and updating a few doctests reflecting the speed increase.
- Fixing some remaining details and polishing.
- provide method to access parent streams, trust that only last element of cache may contain variable, add failing test
- slightly improve substitution, test is failing elsewhere
- fix a typo and make the linter happy
- use a custom getitem method
- add optional argument input_streams to Stream_function
- WIP: merge Stream_functional_equation into Stream_uninitialized
- WIP: find all input streams at setup - bug because there are equal streams which are different
- walk through the closure in Stream_function to determine input streams, use 'is' for equality when finding input streams in Stream_uninitialized
- fix bad error message
- store the list of variables belonging to each implicitly defined stream separately
- solve systems of functional equations
- WIP: use no more new variables than necessary
- fix conversion issue
- better substitution, better error messages
- switch to ZZ.sum, add more failing doctests
- more failing doctests
- initial commit to solve also systems of functional equations
- work around bug in InfinitePolynomialRing, better error messages
- fix bad counting in _subs_in_caches
- fix to erroneous doctests - the bug was in the old version
- fix bookkeeping
- slightly simplify logic
- fix typo
- bypass buggy subs in InfinitePolynomialRing
- more work on the multivariate case
- replace InfinitePolynomialRing, make simple bivariate example work
- stay in the coefficient ring if possible in Stream_cauchy_invert and Stream_dirichlet_invert, add (currently failing) doctest for implicitly defined series involving composition
- provide functorial construction for coercion
- fix bug in composition, work around performance bug in subs
- make _terms_of_degree more correct for completions in higher arity
- provide a construction functor
- more constructions
- fix oversight in factorization of symmetric function: unit should be in the base ring
- skip construction for dual and orthotriang
- adapt to PolynomialSequence.coefficients_monomials
- add change_ring, add doctests demonstrating that coercions with different base rings work now
- add change_ring, add doctests demonstrating that coercions with different base rings work now
- make map_coefficients more general, in line with polynomials
- correct equality
- fix equality and subs in UndeterminedCoefficientsRingElement, fix construction of univariate LazyPowerSeriesRing
- beautify repr, add doctests, deprecate corresponding_basis_over
- provide _descriptor for llt
- construction for dual bases
- fix equality for llt
- correct ring for _terms_of_degrees in LazySymmetricFunctions
- fix doctests
- fix blank lines
- another test, fix type of constant in Stream_exact
- add output for a doctest
- move UndeterminedCoefficientsFunctor to stream.py, improve substitution and retraction of undetermined coefficients
- micro-optimization
- remove UndeterminedCoefficientsRing
- use bad workaround for InfinitePolynomialRing bug
- conversion is slower than direct computation
- fix doctests and error handling for undefined streams
- fix bad markup (:cls: should be :class:)
- remove workaround and fix InfinitePolynomialRing instead
- add documentation and tests, remove cached_method
- optimize and clarify substitution
- simplify VariablePool, add documentation and doctests
- improve documentation of doctests
- return numerator and denominator as elements of self, restrict element_constructor, fix coefficients
- add docstring to numerator, remove wrong denominator method (the inherited method is correct)
- remove workaround and fix InfinitePolynomialRing instead
- add documentation and tests, remove cached_method
- add doctest, fix linter
- add doctest for coercion issue
- Use proper reference role
- Remove wrong indentation
- Fix missing backticks
- Fix missing backticks
- remove misleading sentence and whitespace
- break expected output of doctest
- provide missing doctests
- add missing colon
- break expected output of doctest
- add missing # needs
- Remove wrong indentation
- break expected output of doctest
- Remove wrong indentation
- use proper sphinx roles
- remove whitespace
- Fix missing backticks
- Fix missing backticks
- remove misleading sentence and whitespace
- add missing colon
- use proper sphinx roles
- remove whitespace
- improve docstring formatting
- remove unnecessary parens
- improve docstring
- fix sphinx role
- dirty fix for composition, add doctests, one works only with rank of InfinitePolynomialFunctor lowered
- improve error messages
- fix filling of cache, improve documentation
- fix typo and implicit doctest -> indirect doctest
- fix doctest
- provide an option to look ahead in the equations, refactor
- free variables in VariablePool on destruction of a Stream_uninitialized
- remove duplicate example, cache _terms_of_degree
- replace list() with []
- improve doc formatting
- remove trailing blank lines in docstrings
- use list comprehension
- cosmetic fixes and replace else: if...: with elif:
- use PolynomialRing explicitly
- naive implementations of is_prime_field and fraction_field for symmetric functions
- add (currently failing) example
- work harder putting the coefficients into the correct parent
- introduce a functorial construction CoefficientRing

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-07-28 00:16 UTC, mantepse commented
There is a time-sink I don't completely understand:
```
sage: h = SymmetricFunctions(QQ).h()
sage: L.<t, u> = LazyPowerSeriesRing(h.fraction_field())
sage: D = L.undefined()
sage: s1 = L.sum(lambda n: h[n]*t^(n+1)*u^(n-1), 1)
sage: L.define_implicitly([D], [u*D - u - u*s1*D - t*(D - D(t, 0))])
sage: D[0]
h[]
sage: D[1]
0
sage: D[2]
h[1]*t^2
sage: %prun D[3]
         3357653 function calls (3326279 primitive calls) in 3.081 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
[...]
  777/111    0.038    0.000    2.599    0.023 {method 'gcd' of 'sage.rings.polynomial.multi_polynomial.MPolynomial' objects}
[...]
  793/110    0.012    0.000    2.226    0.020 unique_factorization_domains.py:134(_gcd_univariate_polynomial)
[...]
sage: D[3]
0
```

2024-07-30 10:30 UTC, mantepse commented
That time sink is also present with `L.<t, u> = LazyPowerSeriesRing(QQbar["x"].fraction_field())`, so I guess it cannot be easily fixed.

2024-11-02 21:00 UTC, mantepse commented
Notes to myself, concerning the time sink.  If I understand correctly, it is dominated by the code in `Stream_uninitialized.__getitem__` that creates the new undetermined element of the stream.

I tried a bit to optimize this in the special case where `isinstance(self._coefficient_ring, MPolynomialRing_polydict)`, mainly by bypassing `MPolynomialRing_polydict.__call__` and the like.  Curiously, it turned out that creating the string representation of the monomials takes a lot of time (it invokes multiplication and gcd!).  However, even with all these optimizations, the performance was still quite bad.  Essentially, we are using a lot of time in `gcd` computations, and it is not clear which of these can be avoided.
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
...
  1886         2       1883.0    941.5      0.0          for n0 in range(len(self._cache) + self._approximate_order, n+1):
  1887                                                       # WARNING: coercing the new variable to self._PF slows
  1888                                                       # down the multiplication enormously
  1889         1      12524.0  12524.0      0.0              if self._coefficient_ring == self._base_ring:
  1890                                                           x = (self._pool.new_variable(self._name + "[%s]" % n0)
  1891                                                                * self._terms_of_degree(n0, self._P)[0])
  1892                                                       else:
  1893         2   26085266.0    1e+07     11.6                  x = sum(self._pool.new_variable(self._name + "[%s]" % m) * m
  1894         1    4885896.0    5e+06      2.2                          for m in self._terms_of_degree(n0, self._P))
  1895         1  194465377.0    2e+08     86.2              x = self._U(x)
  1896         1       1333.0   1333.0      0.0              self._cache.append(x)
  1897                                           
  1898         1       2886.0   2886.0      0.0          return x
```

2024-11-02 21:31 UTC, mantepse commented
Hm, somebody is calling `Rings.ParentMethods.__getitem__` an awful lot.

2024-11-03 09:54 UTC, mantepse commented
Oh wow.  I extracted the bit.  Creating `FESDUMMY_13/h[]*t^4 + FESDUMMY_12/h[]*t^3*u + FESDUMMY_11/h[]*t^2*u^2 + FESDUMMY_10/h[]*t*u^3 + FESDUMMY_9/h[]*u^4` takes more than a second on my computer!
```
def testit(n0, _P, _U, _terms_of_degree):
    """
    sage: from sage.data_structures.stream import CoefficientRing, VariablePool
    sage: _base_ring = SymmetricFunctions(QQ).h().fraction_field()
    sage: _coefficient_ring = _base_ring["t", "u"]
    sage: _PF = CoefficientRing(_base_ring)
    sage: _U = _coefficient_ring.change_ring(_PF); _U
    sage: _P = _PF.base(); _P
    sage: _terms_of_degree = lambda n, R: [m.change_ring(R) for m in _coefficient_ring.monomials_of_degree(n)]
    sage: %time testit(4, _P, _U, _terms_of_degree)
    CPU times: user 1.3 s, sys: 4.02 ms, total: 1.3 s
    Wall time: 1.3 s
    FESDUMMY_13/h[]*t^4 + FESDUMMY_12/h[]*t^3*u + FESDUMMY_11/h[]*t^2*u^2 + FESDUMMY_10/h[]*t*u^3 + FESDUMMY_9/h[]*u^4
    """
    _pool = VariablePool(_P)
    x = sum(_pool.new_variable("[%s]" % m) * m for m in _terms_of_degree(n0, _P))
    return _U(x)
```

2024-11-03 11:29 UTC, mantepse commented
Apparently, there is a hidden cost in the dense implementation of the infinite polynomial ring, I'll ask a question on sage-devel.

2025-02-12 06:41 UTC, tscrim requested changes
Thank you. There just a few more details I have seen when giving this another look over.

I have one additional question. This gets rid of the old implicit definition, correct? I expect this to be slower than the "solver" we have before for `f = G(f)`. Thus, I am thinking we should keep that implementation for that special case. It's possible I missed something when looking at the code.

2025-02-12 06:41 UTC, tscrim commented on src/sage/combinat/sf/sfa.py
> +        return False
This needs a doctest.

2025-02-12 06:41 UTC, tscrim commented on src/sage/rings/polynomial/multi_polynomial_sequence.py
> +                                        InfinitePolynomialRing_sparse))
It would be good to add a doctest showing that it now works with infinite polynomial rings.

2025-02-12 06:41 UTC, tscrim commented on src/sage/rings/lazy_series_ring.py
> +        of basis elements of total degree ``n``.
This data/explanation is better with the concrete implementations as this could fall out of date as new implementations are added.

2025-02-12 06:41 UTC, tscrim commented on src/sage/rings/lazy_series_ring.py
> +        return l
```suggestion
        return [tensor(m) for c in IntegerVectors(n, self._arity)
                for m in cartesian_product_iterator([F.homogeneous_component_basis(p)
                                                     for F, p in zip(B.tensor_factors(), c)])]
```

2025-02-12 06:41 UTC, tscrim commented on src/sage/data_structures/stream.py
> +        EXAMPLES::
```suggestion
        """
        Initialize ``self``.

        EXAMPLES::
```

2025-02-12 06:41 UTC, tscrim commented on src/sage/data_structures/stream.py
> +        - ``val``, the value that should replace the variable
```suggestion
        - ``var`` -- a variable in ``self._P``
        - ``val`` -- the value that should replace the variable
```

2025-02-12 06:41 UTC, tscrim commented on src/sage/data_structures/stream.py
> +            sage: f = Stream_function(lambda n: QQ(n), True, 1)
Why is this necessary? This seems like a regression.

2025-02-12 08:23 UTC, mantepse commented
> Thank you. There just a few more details I have seen when giving this another look over.
> 
> I have one additional question. This gets rid of the old implicit definition, correct? I expect this to be slower than the "solver" we have before for `f = G(f)`. Thus, I am thinking we should keep that implementation for that special case. It's possible I missed something when looking at the code.

No, the special case is treated as before - although it is also handled by `Stream_uninitialized`.  The distinction is made by checking whether `self._target is None`, see `Stream_uninitialized.__getitem__`.

Yes, `f.define(G(f))` is *much* faster, whenever it works.

2025-02-12 08:25 UTC, tscrim commented
Ah, okay, thank you. Then once the other details are addressed, then this will be a positive review.

2025-02-12 08:26 UTC, mantepse commented
Cool, I'm on it.  Good evening? :-)

2025-02-12 09:40 UTC, mantepse commented
thank you, well, better indeed, but still somewhat so-so :-)

Currently running tests.  Short summary: `is_prime_field` is now indeed unnecessary, `QQ` in `Stream_function(lambda n: QQ(n), True, 1)` is necessary, because we expect elements of the stream to be in a correct parent, and `lambda n: n` in fact produces `int`.

2025-02-12 09:57 UTC, mantepse commented on src/sage/rings/lazy_series_ring.py
> +        of basis elements of total degree ``n``.
The specifications are also in the concrete implementations.  I slightly reworded to make it clear that this is intended as an explanation of the purpose of the (abstract) method.

2025-02-12 17:29 UTC, mantepse commented
I cannot reproduce the failure in `symmetric_ideal.py`.

2025-02-12 17:59 UTC, mantepse commented
I marked the one doctest failure on macos as random.  Apparently, the order of the variables is different on macos than on linux.  However, it is more valuable to have the full output of the doctest, and, since it is an error message, I do not want to try to make the error message less random, which would involve some work and introduce more brittleness.

2025-02-13 01:08 UTC, tscrim approved these changes
Thank you for the changes. This now LGTM. Thank you for all of your hard work in getting this implemented. This is a major new feature.

One last thing before a positive review.

2025-02-13 01:08 UTC, tscrim commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
```suggestion
        The following test results in a failure, but at different points
        on different machines::

            mac: coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0
            linux: ...
        
        Due to this, we only test that the base output::

            sage: F  # random
            <repr(...) failed: ValueError: could not determine any coefficients:
                coefficient ... == 0>
```
I don't think it is good to mark this as `# random` since that then only checks that an (uncaught) error is not raised. Instead, I think we should be more specific, both in the test and in the explanation.

2025-02-13 03:16 UTC, mantepse commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
I don't mind, but did you intend to remove#random in 812?

2025-02-13 03:21 UTC, tscrim commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
Ah, yes, I meant to remove that.

2025-02-13 03:22 UTC, mantepse commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
Oh, and it is only on some MacOS versions

2025-02-13 03:58 UTC, mantepse commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
Oh, and it is only on some MacOS versions

2025-02-13 08:40 UTC, mantepse commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
Actually, I think that "but at different points on different machines::" might be misunderstood.  The only thing that may differ is the order in which the monomials in the polynomial "6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1)" appear.  So here is another suggestion:

```suggestion
        We have thus specified that the degree 1 component equals `f1`.  This is still
        not enough to remove the ambiguity, so an error is raised.  However, we can
        see that the dependence on `series[1]` disappeared.  The equation which has
        no unique solution is now
        `6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0`::

            sage: F  # random
            <repr(...) failed: ValueError: could not determine any coefficients:
                coefficient [3]: ... == 0>
```

2025-02-13 17:53 UTC, tscrim commented on src/sage/rings/lazy_series_ring.py
> +                coefficient [3]: 6*series[3] + (-2*x - 2*y)*series[2] + (x*y*f1) == 0>
If you're removing the `# random`, then okay. Although it would be good to explain a bit why the `...` is in the doctest here. Can you give the two different outputs, at least here on this PR for the record?

Also, it would be {{{``}}} on both sides for code formatting.

2025-02-15 07:32 UTC, mantepse commented
After  #39523, the doctests after `The Frobenius character of labelled Dyck words`, lines 895-905, will not be slow anymore.

2025-02-17 01:19 UTC, tscrim approved these changes
Thank you. Let's get this in. Any additional improvements or fixes can be done on later on followup PRs.

2025-02-21 21:19 UTC, merged