Fix hashing for Weyl algebra elements
sagemath/sage pull request #38119
Opened 2024-05-31 04:28 UTC by darijgr

Weyl algebras elements cannot be hashed or compared, since the element class is too barren.
This patch lets the element class inherit from IndexedFreeModuleElement, which fixes this problem automatically.

2024-05-31 06:41 UTC, tscrim requested changes
The `_richcmp_` and `__init__` are no longer needed as it will be inherited from `IndexedFreeModuleElement`. Please keep the doctests somewhere though.

These methods are also unnecessary but can simply be removed: `_add_`, `__neg__`, `monomial_coefficients`, `support`, 

Please add a test showing the left and right multiplication of the Weyl algebra by the corresponding polynomial ring generates the correct results. I am slightly worried about the `_acted_upon_` versus `_lmul_` and `_rmul_` not being compatible...

2024-06-01 00:47 UTC, darijgr commented
Good points. All done -- except for the doctests, which already exist.

2024-06-01 06:35 UTC, tscrim approved these changes
Okay, thanks. Then let's get this in.

2024-06-01 12:11 UTC, darijgr commented
Thank you, Travis!

2024-06-09 10:25 UTC, merged