Deprecate `is_Integer` etc.
sagemath/sage pull request #38128
Opened 2024-06-01 06:35 UTC by mkoeppe

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-06-04 07:09 UTC, mkoeppe commented
The test failure in conda (src/sage/libs/singular/function.pyx) is unrelated, I think

2024-06-06 12:35 UTC, gmou3 requested changes

2024-06-06 12:35 UTC, gmou3 commented on src/sage/rings/polynomial/polynomial_element.pyx
>  from sage.rings.fraction_field import FractionField, is_FractionField
```suggestion
from sage.rings.fraction_field import FractionField
```
And also remove L58.

2024-06-06 18:16 UTC, gmou3 approved these changes

2024-06-22 19:42 UTC, merged