docstrings: large scale formatting
sagemath/sage pull request #38155
Opened 2024-06-05 11:10 UTC by gmou3

The commits will be kept in manageable sizes (~100 changed files).

### Changes:
- `True`, `False`, `None` to ` ``True`` `, ` ``False`` `, ` ``None`` `
- `- arg (type, default: *) -- description` to `- ``arg`` -- type (default: *); description`
- Remove end dots in input argument descriptions
- One-line OUTPUTs for short output descriptions
- More math (addition of `` `*` `` or change of ` ``*`` `  to `` `*` `` )

### :hourglass: Dependencies

- Depends on #38145.

2024-06-05 11:43 UTC, gmou3 commented
@kwankyu you may like to keep an eye and make suggestions dynamically.

2024-06-06 18:51 UTC, gmou3 commented
I wrote '*' in `` `*` `` to denote some string within backticks (math), not the actual character.

If however you are not referring to my previous post and you're instead referring to the contents of some docstring, please let me know. ('*' is indeed used in math already; not inserted by me.)

2024-06-06 20:45 UTC, mantepse commented
> I wrote '*' in `` `*` `` to denote some string within backticks (math), not the actual character. (Updated for more clarity.)
Oh, excellent, sorry for my confusion!

2024-06-10 05:46 UTC, kwankyu commented
I left some comments to https://github.com/sagemath/sage/commit/5219d62d74d92677076bef1b2928655fd3840ab5. I am not sure if you are notified.

2024-06-10 09:49 UTC, gmou3 commented
Yes, I was notified. Thank you!

2024-06-11 00:55 UTC, kwankyu commented on src/sage/algebras/steenrod/steenrod_algebra_misc.py
```
``None``
```

2024-06-11 00:55 UTC, kwankyu commented on src/sage/algebras/steenrod/steenrod_algebra_misc.py
> +    - ``p`` -- prime (default: 2)
```
``'auto'``
```
?

2024-06-11 02:09 UTC, kwankyu commented
I checked https://github.com/sagemath/sage/pull/38155/commits/75b48012a59db49cc75531f4735c45f8a2b41d8f. LGTM.

2024-06-11 02:12 UTC, kwankyu commented
Perhaps you have to update the review status of the commits to minimize confusion.

2024-06-11 11:33 UTC, gmou3 commented
Sure, you can also edit the post yourself if you like.

2024-06-11 17:49 UTC, davidlowryduda reviewed
These comments come from https://github.com/sagemath/sage/commit/1ed6ea59baf8d9687a7c3aaafd964d3049ebcca1. Other than these, https://github.com/sagemath/sage/commit/1ed6ea59baf8d9687a7c3aaafd964d3049ebcca1 looks good to me.

2024-06-11 17:49 UTC, davidlowryduda commented on src/sage/geometry/lattice_polytope.py
> +        OUTPUT: the output of nef.x as a string
```suggestion
        OUTPUT: the output of ``nef.x`` as a string
```

2024-06-11 17:49 UTC, davidlowryduda commented on src/sage/games/quantumino.py
> +        OUTPUT: iterator of QuantuminoState
```suggestion
        OUTPUT: iterator of :class:`QuantuminoState`
```

2024-06-11 17:49 UTC, davidlowryduda commented on src/sage/geometry/lattice_polytope.py
> +        OUTPUT: the output of poly.x as a string
```suggestion
        OUTPUT: the output of ``poly.x`` as a string
```

2024-06-11 21:13 UTC, gmou3 commented
Done. Thanks!

2024-06-11 21:17 UTC, davidlowryduda commented
Great! Now https://github.com/gmou3/sage/commit/1ed6ea59baf8d9687a7c3aaafd964d3049ebcca1 LGTM. I can't edit the initial comment tracking individual approvals, but please add me there.

2024-06-12 20:06 UTC, davidlowryduda reviewed
This is for commit https://github.com/sagemath/sage/commit/a6b03825c672cc01419a95c56d10ae6633f34506 . There are more suggestions than last time, but most are `maxima` -> `Maxima`

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/graphs/digraph.py
> +        OUTPUT: * When ``certificate=False``, returns a boolean value
This breaks a bulleted list.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/graphs/graph_decompositions/modular_decomposition.py
> +    OUTPUT: a node object with node_type set as NodeType.PRIME
```suggestion
    OUTPUT: a node object with ``node_type`` set as ``NodeType.PRIME``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/graphs/graph_decompositions/modular_decomposition.py
> +    OUTPUT: a node object with node_type set as NodeType.PARALLEL
```suggestion
    OUTPUT: a node object with ``node_type`` set as ``NodeType.PARALLEL``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/graphs/graph_decompositions/modular_decomposition.py
> +    OUTPUT: a node object with node_type set as NodeType.SERIES
```suggestion
    OUTPUT: a node object with ``node_type`` set as ``NodeType.SERIES``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/graphs/graph_decompositions/modular_decomposition.py
> +    OUTPUT: a node object representing the vertex with node_type set as NodeType.NORMAL
```suggestion
    OUTPUT: a node object representing the vertex with ``node_type`` set as ``NodeType.NORMAL``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/groups/perm_gps/permgroup_named.py
> +        OUTPUT: pGL(`n`, `q`)
We want either PGL(`n`, `q`) or `PGL(n, q)` I suppose.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/groups/perm_gps/permgroup_named.py
> +        OUTPUT: pSp(`n`, `q`)
Similarly, we want either PSp(`n`, `q`) or `PSp(n, q)`.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/groups/perm_gps/permgroup_named.py
> +        OUTPUT: pSU(n,q)
We want either PSU(`n`, `q`) or `PSU(n, q)`.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/groups/perm_gps/permgroup_named.py
> +        OUTPUT: pGU(`n`, `q`)
We want either PGU(`n`, `q`) or `PGU(n, q)`.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/magma.py
> +        OUTPUT: magmaFunction instance
```suggestion
        OUTPUT: :class:`MagmaFunction` instance
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/magma.py
> +        OUTPUT: magmaElement
```suggestion
        OUTPUT: :class:`MagmaElement`
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/magma.py
> +        OUTPUT: magmaElement or tuple of nvals MagmaElement's
```suggestion
        OUTPUT: instance of :class:`MagmaElement` or a tuple of ``nvals`` many :class:`MagmaElement` instances
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/magma.py
> +        OUTPUT: magmaElement
```suggestion
        OUTPUT: :class:`MagmaElement`
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/magma.py
> +        OUTPUT: magmaElement
```suggestion
        OUTPUT: :class:`MagmaElement`
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima's help for ``s``
I think this is a case where we should preserve capitalization. And I think calling the output a `Maxima function` is more helpful than trying to be more technically precise.

```suggestion
        OUTPUT: Maxima's help for ``s``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima's examples for ``s``
```suggestion
        OUTPUT: Maxima's examples for ``s``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima function
```suggestion
        OUTPUT: Maxima function
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima real
```suggestion
        OUTPUT: Maxima real
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima real
```suggestion
        OUTPUT: Maxima real
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima matrix
```suggestion
        OUTPUT: Maxima matrix
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +    OUTPUT: maxima function
```suggestion
    OUTPUT: Maxima function
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: maxima function
```suggestion
        OUTPUT: Maxima function
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_lib.py
> +    OUTPUT: maxima interface as a Library
```suggestion
    OUTPUT: Maxima interface as a Library
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_lib.py
> +        OUTPUT: maxima element equivalent to ``x``
```suggestion
        OUTPUT: Maxima element equivalent to ``x``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_lib.py
> +        OUTPUT: maxima object
```suggestion
        OUTPUT: Maxima object
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/matrix/matrix0.pyx
> +        OUTPUT: the polynomial f(self\*x).
I wonder what this notation is trying to say? Does this want to be

```
the polynomial ``f(self * x)``.
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/matrix/matrix0.pyx
> +        OUTPUT: the vector times matrix product v\*A
Similarly, I don't understand why this notation was used originally so I'm not sure what to recommend. But this doesn't seem right.

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/matrix/matrix_integer_dense.pyx
> +        OUTPUT: a, d such that ``A*self == d``
```suggestion
        OUTPUT: `A`, `d` such that ``A*self == d``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/matrix/matrix_integer_dense.pyx
> +        OUTPUT: a, d such that ``A*self == d``
```suggestion
        OUTPUT: `A`, `d` such that ``A*self == d``
```

2024-06-12 20:06 UTC, davidlowryduda commented on src/sage/interfaces/maxima_abstract.py
> +        OUTPUT: sage object
```suggestion
        OUTPUT: Sage object
```

2024-06-13 08:34 UTC, gmou3 commented
Thanks, you caught some good ones. Let me know if it looks fine now.

2024-06-13 20:01 UTC, davidlowryduda approved these changes
Now this and https://github.com/gmou3/sage/commit/a6b03825c672cc01419a95c56d10ae6633f34506 LGTM.

2024-06-13 20:44 UTC, davidlowryduda requested changes

2024-06-13 20:44 UTC, davidlowryduda commented on src/sage/rings/polynomial/polynomial_rational_flint.pyx
> +        OUTPUT: galois group
```suggestion
        OUTPUT: Galois group
```

2024-06-13 20:44 UTC, davidlowryduda commented on src/sage/rings/polynomial/polynomial_singular_interface.py
> +        OUTPUT: singular ring matching this ring
```suggestion
        OUTPUT: Singular ring matching this ring
```

(for the Singular CAS)

2024-06-13 20:44 UTC, davidlowryduda commented
I realized I was starting to want to fix more than just what this PR is after --- in particular I was initially recognizing that many `ClassName` instances should be ``:class:`ClassName` `` instances. I've stopped doing that.

With that, the remaining one-line OUTPUT commits

- https://github.com/sagemath/sage/commit/37fe9ec178e84fa65a455c6bfc6e8584222c31c8
- https://github.com/sagemath/sage/commit/c284b26f4ad05153247a1f197016534dd95fdc72
- https://github.com/sagemath/sage/commit/021184aad133dbd09563134a1e013a0bf0f5a59e
- https://github.com/sagemath/sage/commit/713e80d9fdb21c85ab7190a4f278b0659e056411
- https://github.com/sagemath/sage/commit/53ea68fdc1b40a942efdba13ea5bd70d775b90e5

all LGTM, except for the two suggestions I made just above.

2024-06-17 11:20 UTC, gmou3 commented
@kwankyu thanks for reviewing commits 9eab12f, 6c70e9e, c9f4492, 6922a4c, 0716b41!
If you wish, have a look at 16c9892 in case I've missed something.

2024-06-21 23:01 UTC, kwankyu commented
I don't know where the comment is; anyway I am okay with ``` :class:`Exception` ```, which is prevalent in docstrings.

2024-06-22 01:00 UTC, kwankyu commented
This PR sets high standards for sage docstrings. If you want this standards to persist, it is important that people become aware of them. So I recommend you 

- to post in sage-devel to invite people to come to review and /or learn
- to make another PR to reflect the new standards to the developer manual.

2024-06-22 07:28 UTC, gmou3 commented
Ok! I still have quite a few days of work here (changes are getting denser as I go).

Ideally we want more people to share the reviewing load, as it can be a time-consuming and mind-numbing job.

2024-07-08 05:01 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/numerical/backends/logging_backend.py
**********************************************************************
File "src/sage/numerical/backends/logging_backend.py", line 321, in sage.numerical.backends.logging_backend.?
Failed example:
    with open(fname) as f:
        for line in f.readlines(): _ = sys.stdout.write('|{}'.format(line))
Expected:
    |
    |    @classmethod
    |    def _test_something(cls, tester=None, **options):
    |        ...
    |        Run tests on ...
    |
    |        TESTS::
    |
    |            sage: from sage.numerical.backends.generic_backend import GenericBackend
    |            sage: p = GenericBackend()
    |            sage: p._test_something()
    |            Traceback (most recent call last):
    |            ...
    |            NotImplementedError
    |
    |        ...
    |        p = cls()                         # fresh instance of the backend
    |        if tester is None:
    |            tester = p._tester(**options)
    |        tester.assertEqual(p.add_variable(obj=42, name='Helloooooo'), 0)
    |        tester.assertEqual(p.add_variable(obj=1789), 1)
    |        with tester.assertRaises(MIPSolverException) as cm:
    |            p.solve()
Got:
    |
    |    @classmethod
    |    def _test_something(cls, tester=None, **options):
    |        """
    |        Run tests on ...
    |
    |        TESTS::
    |
    |            sage: from sage.numerical.backends.generic_backend import GenericBackend
    |            sage: p = GenericBackend()
    |            sage: p._test_something()
    |            Traceback (most recent call last):
    |            ...
    |            NotImplementedError
    |        """
    |        p = cls()                         # fresh instance of the backend
    |        if tester is None:
    |            tester = p._tester(**options)
    |        tester.assertEqual(p.add_variable(obj=42, name='Helloooooo'), 0)
    |        tester.assertEqual(p.add_variable(obj=1789), 1)
    |        with tester.assertRaises(MIPSolverException) as cm:
    |            p.solve()
**********************************************************************
1 item had failures:
   1 of  11 in sage.numerical.backends.logging_backend.?
    [45 tests, 1 failure, 0.05 s]
----------------------------------------------------------------------
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/numerical/backends/logging_backend.py  # 1 doctest failed
----------------------------------------------------------------------
```

2024-07-08 05:04 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/structure/global_options.py
**********************************************************************
File "src/sage/structure/global_options.py", line 1238, in sage.structure.global_options.GlobalOptions._instancedoc_
Failed example:
    print(Partitions.options.__doc__)                                     # needs sage.combinat
Expected:
    <BLANKLINE>
    Sets and displays the global options for elements of the partition,
    skew partition, and partition tuple classes.  If no parameters are
    set, then the function returns a copy of the options dictionary.
    <BLANKLINE>
    The ``options`` to partitions can be accessed as the method
    :obj:`Partitions.options` of :class:`Partitions` and
    related parent classes.
    <BLANKLINE>
    <BLANKLINE>
    OPTIONS:
    <BLANKLINE>
    - ``convention`` -- (default: ``English``)
      Sets the convention used for displaying tableaux and partitions
    <BLANKLINE>
      - ``English`` -- use the English convention
      - ``French``  -- use the French convention
    ...
Got:
    <BLANKLINE>
    Set and display the global options for elements of the partition,
    skew partition, and partition tuple classes.  If no parameters are
    set, then the function returns a copy of the options dictionary.
    <BLANKLINE>
    The ``options`` to partitions can be accessed as the method
    :obj:`Partitions.options` of :class:`Partitions` and
    related parent classes.
    <BLANKLINE>
    OPTIONS:
    <BLANKLINE>
    - ``convention`` -- (default: ``English``)
      Sets the convention used for displaying tableaux and partitions
    <BLANKLINE>
      - ``English`` -- use the English convention
      - ``French``  -- use the French convention
      - ``Russian`` -- use the Russian convention
    <BLANKLINE>
    - ``diagram_str`` -- (default: ``*``)
      The character used for the cells when printing Ferrers diagrams
    <BLANKLINE>
    - ``display`` -- (default: ``list``)
      Specifies how partitions should be printed
    <BLANKLINE>
      - ``array``           -- alias for ``diagram``
      - ``compact``         -- alias for ``compact_low``
      - ``compact_high``    -- compact form of ``exp_high``
      - ``compact_low``     -- compact form of ``exp_low``
      - ``diagram``         -- as a Ferrers diagram
      - ``exp``             -- alias for ``exp_low``
      - ``exp_high``        -- in exponential form (highest first)
      - ``exp_low``         -- in exponential form (lowest first)
      - ``ferrers_diagram`` -- alias for ``diagram``
      - ``list``            -- displayed as a list
      - ``young_diagram``   -- alias for ``diagram``
    <BLANKLINE>
    - ``latex`` -- (default: ``young_diagram``)
      Specifies how partitions should be latexed
    <BLANKLINE>
      - ``array``           -- alias for ``diagram``
      - ``diagram``         -- latex as a Ferrers diagram
      - ``exp``             -- alias for ``exp_low``
      - ``exp_high``        -- latex as a list in exponential notation (highest first)
      - ``exp_low``         -- as a list latex in exponential notation (lowest first)
      - ``ferrers_diagram`` -- alias for ``diagram``
      - ``list``            -- latex as a list
      - ``young_diagram``   -- latex as a Young diagram
    <BLANKLINE>
    - ``latex_diagram_str`` -- (default: ``\ast``)
      The character used for the cells when latexing Ferrers diagrams
    <BLANKLINE>
    - ``notation`` -- alternative name for ``convention``
    <BLANKLINE>
    <BLANKLINE>
    <BLANKLINE>
    EXAMPLES::
    <BLANKLINE>
        sage: P = Partition([4,2,2,1])
        sage: P
        [4, 2, 2, 1]
        sage: Partitions.options.display="exp"
        sage: P
        1, 2^2, 4
        sage: Partitions.options.display="exp_high"
        sage: P
        4, 2^2, 1
    <BLANKLINE>
    It is also possible to use user defined functions for the ``display`` and
    ``latex`` options::
    <BLANKLINE>
        sage: Partitions.options(display=lambda mu: '<%s>' % ','.join('%s'%m for m in mu._list)); P
        <4,2,2,1>
        sage: Partitions.options(latex=lambda mu: '\\Diagram{%s}' % ','.join('%s'%m for m in mu._list)); latex(P)
        \Diagram{4,2,2,1}
        sage: Partitions.options(display='diagram', diagram_str='#')
        sage: P
        ####
        ##
        ##
        #
        sage: Partitions.options(diagram_str='*', convention='french')
        sage: print(P.ferrers_diagram())
        *
        **
        **
        ****
    <BLANKLINE>
    Changing the ``convention`` for partitions also changes the ``convention``
    option for tableaux and vice versa::
    <BLANKLINE>
        sage: T = Tableau([[1,2,3],[4,5]])
        sage: T.pp()
          4  5
          1  2  3
        sage: Tableaux.options.convention="english"
        sage: print(P.ferrers_diagram())
        ****
        **
        **
        *
        sage: T.pp()
          1  2  3
          4  5
        sage: Partitions.options._reset()
    <BLANKLINE>
    See :class:`~sage.structure.global_options.GlobalOptions` for more features of these options.
**********************************************************************
1 item had failures:
   1 of   4 in sage.structure.global_options.GlobalOptions._instancedoc_
    [164 tests, 1 failure, 0.10 s]
----------------------------------------------------------------------
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/structure/global_options.py  # 1 doctest failed
----------------------------------------------------------------------
```

2024-07-08 05:08 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/doctest/parsing.py
**********************************************************************
File "src/sage/doctest/parsing.py", line 1036, in sage.doctest.parsing.SageDocTestParser.parse
Failed example:
    example3 = 'sage: Zp(5,4,print_mode='digits')(5)\n...00010'
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1143, in compile_and_execute
        compiled = compiler(example)
                   ^^^^^^^^^^^^^^^^^
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 682, in compiler
        code = compile(example.source, filename, "single",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest sage.doctest.parsing.SageDocTestParser.parse[26]>", line 1
        example3 = 'sage: Zp(5,4,print_mode='digits')(5)\n...00010'
                                             ^^^^^^
    SyntaxError: invalid syntax
```

2024-07-08 05:09 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/libs/lcalc/lcalc_Lfunction.pyx
**********************************************************************
File "src/sage/libs/lcalc/lcalc_Lfunction.pyx", line 121, in sage.libs.lcalc.lcalc_Lfunction.Lfunction.__repr__
Failed example:
    Lfunction_from_character(DirichletGroup(5)[1])
Expected:
    `L`-function with complex Dirichlet coefficients
Got:
    L-function with complex Dirichlet coefficients
```

2024-07-08 05:10 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/combinat/sloane_functions.py
**********************************************************************
File "src/sage/combinat/sloane_functions.py", line 1870, in sage.combinat.sloane_functions.A000012._repr_
Failed example:
    sloane.A000012._repr_()
Expected:
    "The all 1s sequence."
Got:
    'The all 1s sequence.'
**********************************************************************
File "src/sage/combinat/sloane_functions.py", line 1919, in sage.combinat.sloane_functions.A000120._repr_
Failed example:
    sloane.A000120._repr_()
Expected:
    "1s-counting sequence: number of 1s in binary expansion of n."
Got:
    '1s-counting sequence: number of 1s in binary expansion of n.'
**********************************************************************
File "src/sage/combinat/sloane_functions.py", line 2033, in sage.combinat.sloane_functions.A000069._repr_
Failed example:
    sloane.A000069._repr_()
Expected:
    "Odious numbers: odd number of 1s in binary expansion."
Got:
    'Odious numbers: odd number of 1s in binary expansion.'
**********************************************************************
File "src/sage/combinat/sloane_functions.py", line 2084, in sage.combinat.sloane_functions.A001969._repr_
Failed example:
    sloane.A001969._repr_()
Expected:
    "Evil numbers: even number of 1s in binary expansion."
Got:
    'Evil numbers: even number of 1s in binary expansion.'
**********************************************************************
4 items had failures:
   1 of   2 in sage.combinat.sloane_functions.A000012._repr_
   1 of   2 in sage.combinat.sloane_functions.A000069._repr_
   1 of   2 in sage.combinat.sloane_functions.A000120._repr_
   1 of   2 in sage.combinat.sloane_functions.A001969._repr_
    [1249 tests, 4 failures, 1.48 s]
----------------------------------------------------------------------
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/combinat/sloane_functions.py  # 4 doctests failed
----------------------------------------------------------------------
```

2024-07-08 05:10 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/misc/lazy_attribute.pyx
**********************************************************************
File "src/sage/misc/lazy_attribute.pyx", line 69, in sage.misc.lazy_attribute._lazy_attribute.__init__
Failed example:
    Parent.element_class.__doc__[91:147]
Expected:
    'The (default) class for the elements of this parent\n\n   '
Got:
    'The (default) class for the elements of this parent.\n\n  '
**********************************************************************
File "src/sage/misc/lazy_attribute.pyx", line 89, in sage.misc.lazy_attribute._lazy_attribute._sage_src_lines_
Failed example:
    lines
Expected:
    89
Got:
    85
**********************************************************************
2 items had failures:
   1 of  10 in sage.misc.lazy_attribute._lazy_attribute.__init__
   1 of   6 in sage.misc.lazy_attribute._lazy_attribute._sage_src_lines_
    [100 tests, 2 failures, 2.25 s]
----------------------------------------------------------------------
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/misc/lazy_attribute.pyx  # 2 doctests failed
----------------------------------------------------------------------
```

2024-07-08 05:17 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/repl/ipython_tests.py
**********************************************************************
File "src/sage/repl/ipython_tests.py", line 11, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo dummy')
Expected:
    Signature:      dummy(argument, optional=None)
    Docstring:
       Dummy Docstring Title
    <BLANKLINE>
       Dummy docstring explanation.
    <BLANKLINE>
       INPUT:
    <BLANKLINE>
       ... "argument" -- anything. Dummy argument.
    <BLANKLINE>
       ... "optional" -- anything (optional). Dummy optional.
    <BLANKLINE>
       EXAMPLES...
    <BLANKLINE>
    ...
    Init docstring: ...ee help(type(...)) for...signature...
    File:           .../sage/repl/ipython_tests.py
    Type:           function
Got:
    Signature:      dummy(argument, optional=None)
    Docstring:     
       Dummy Docstring Title.
    <BLANKLINE>
       Dummy docstring explanation.
    <BLANKLINE>
       INPUT:
    <BLANKLINE>
       * "argument" -- anything; dummy argument
    <BLANKLINE>
       * "optional" -- anything (optional); dummy optional
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: from sage.repl.ipython_tests import dummy
          sage: dummy(1)
          'Source code would be here'
    Init docstring: Initialize self.  See help(type(self)) for accurate signature.
    File:           ~/GitHub/sage-dev/src/sage/repl/ipython_tests.py
    Type:           function
**********************************************************************
File "src/sage/repl/ipython_tests.py", line 36, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo stl_int_vector')
Expected:
    ...
       Example class wrapping an STL vector
    <BLANKLINE>
       EXAMPLES...
    <BLANKLINE>
    ...
    Init docstring: ...ee help(type(...)) for...signature...
    File:           .../sage/tests/stl_vector.pyx
    Type:           type
    ...
Got:
    Init signature: stl_int_vector(self, /, *args, **kwargs)
    Docstring:     
       Example class wrapping an STL vector.
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: from sage.tests.stl_vector import stl_int_vector
          sage: v = stl_int_vector()
    Init docstring: Initialize self.  See help(type(self)) for accurate signature.
    File:           ~/GitHub/sage-dev/src/sage/tests/stl_vector.pyx
    Type:           type
    Subclasses:     
**********************************************************************
File "src/sage/repl/ipython_tests.py", line 52, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo r.lm')                     # optional - rpy2
Expected:
    Signature:       r.lm(...*args, **kwds)
    ...
    String form:     lm
    File:            .../sage/interfaces/r.py
    Docstring:...
    title
    *****
    <BLANKLINE>
    Fitting Linear Models
    ...
Got:
    Signature:      r.lm(*args, **kwds)
    Type:           RFunction
    String form:    lm
    File:           ~/GitHub/sage-dev/src/sage/interfaces/r.py
    Docstring:     
    WARNING: the enclosing module is marked 'needs rpy2',
    so doctests may not pass.
    <BLANKLINE>
       A Function in the R interface.
    <BLANKLINE>
       INPUT:
    <BLANKLINE>
       * "parent" -- the R interface
    <BLANKLINE>
       * "name" -- the name of the function for Python
    <BLANKLINE>
       * "r_name" -- the name of the function in R itself (which can have
         dots in it)
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: length = r.length
          sage: type(length)
          <class 'sage.interfaces.r.RFunction'>
          sage: loads(dumps(length))
          length
    Init docstring:
    WARNING: the enclosing module is marked 'needs rpy2',
    so doctests may not pass.
    <BLANKLINE>
       A Function in the R interface.
    <BLANKLINE>
       INPUT:
    <BLANKLINE>
       * "parent" -- the R interface
    <BLANKLINE>
       * "name" -- the name of the function for Python
    <BLANKLINE>
       * "r_name" -- the name of the function in R itself (which can have
         dots in it)
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: length = r.length
          sage: type(length)
          <class 'sage.interfaces.r.RFunction'>
          sage: loads(dumps(length))
          length
    Call docstring:
    WARNING: the enclosing module is marked 'needs rpy2',
    so doctests may not pass.
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: length = r.length
          sage: length([1,2,3])
          [1] 3
**********************************************************************
File "src/sage/repl/ipython_tests.py", line 70, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo2 dummy')
Expected:
    Signature: dummy(argument, optional=None)
    ...
    Source:
    def dummy(argument, optional=None):
        """
        Dummy Docstring Title
    <BLANKLINE>
        Dummy docstring explanation.
    <BLANKLINE>
        INPUT:
    <BLANKLINE>
        - ``argument`` -- anything. Dummy argument.
    <BLANKLINE>
        - ``optional`` -- anything (optional). Dummy optional.
    <BLANKLINE>
        EXAMPLES::
    <BLANKLINE>
        ...
        """
        return 'Source code would be here'
    File:      .../sage/repl/ipython_tests.py
    Type:      function
Got:
    Signature: dummy(argument, optional=None)
    Docstring:
       Dummy Docstring Title.
    <BLANKLINE>
       Dummy docstring explanation.
    <BLANKLINE>
       INPUT:
    <BLANKLINE>
       * "argument" -- anything; dummy argument
    <BLANKLINE>
       * "optional" -- anything (optional); dummy optional
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: from sage.repl.ipython_tests import dummy
          sage: dummy(1)
          'Source code would be here'
    Source:   
    def dummy(argument, optional=None):
        """
        Dummy Docstring Title.
    <BLANKLINE>
        Dummy docstring explanation.
    <BLANKLINE>
        INPUT:
    <BLANKLINE>
        - ``argument`` -- anything; dummy argument
    <BLANKLINE>
        - ``optional`` -- anything (optional); dummy optional
    <BLANKLINE>
        EXAMPLES::
    <BLANKLINE>
            sage: from sage.repl.ipython_tests import dummy
            sage: dummy(1)
            'Source code would be here'
        """
        return 'Source code would be here'
    File:      ~/GitHub/sage-dev/src/sage/repl/ipython_tests.py
    Type:      function
**********************************************************************
File "src/sage/repl/ipython_tests.py", line 99, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo2 stl_int_vector')
Expected:
    ...
    cdef class stl_int_vector(SageObject):
        """
        Example class wrapping an STL vector
    <BLANKLINE>
        EXAMPLES::
    <BLANKLINE>
    ...
        """
    <BLANKLINE>
        cdef vector[int] *data
        cdef string *name
    <BLANKLINE>
        def __cinit__(self):
            """
            The Cython constructor.
    <BLANKLINE>
            EXAMPLES::
    <BLANKLINE>
    ...
    File:   .../sage/tests/stl_vector.pyx
    Type:   type
    ...
Got:
    Init signature: stl_int_vector(self, /, *args, **kwargs)
    Docstring:     
       Example class wrapping an STL vector.
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: from sage.tests.stl_vector import stl_int_vector
          sage: v = stl_int_vector()
    Source:        
    cdef class stl_int_vector(SageObject):
        """
        Example class wrapping an STL vector.
    <BLANKLINE>
        EXAMPLES::
    <BLANKLINE>
            sage: from sage.tests.stl_vector import stl_int_vector
            sage: v = stl_int_vector()
        """
    <BLANKLINE>
        cdef vector[int] *data
        cdef string *name
    <BLANKLINE>
        def __cinit__(self):
            """
            The Cython constructor.
    <BLANKLINE>
            EXAMPLES::
  [...]

2024-07-08 05:24 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/sandpiles/sandpile.py
**********************************************************************
File "src/sage/sandpiles/sandpile.py", line 2797, in sage.sandpiles.sandpile.SandpileConfig.help
Failed example:
    SandpileConfig.help()
Expected:
    Shortcuts for SandpileConfig operations:
    ~c    -- stabilize
    c & d -- add and stabilize
    c * c -- add and find equivalent recurrent
    c^k   -- add k times and find equivalent recurrent
             (taking inverse if k is negative)
    <BLANKLINE>
    For detailed help with any method FOO listed below,
    enter "SandpileConfig.FOO?" or enter "c.FOO?" for any SandpileConfig c.
    <BLANKLINE>
    add_random             -- Add one grain of sand to a random vertex.
    burst_size             -- The burst size of the configuration with respect to the given vertex.
    deg                    -- The degree of the configuration.
    dualize                -- The difference with the maximal stable configuration.
    equivalent_recurrent   -- The recurrent configuration equivalent to the given configuration.
    equivalent_superstable -- The equivalent superstable configuration.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileConfig methods.
    is_recurrent           -- Is the configuration recurrent?
    is_stable              -- Is the configuration stable?
    is_superstable         -- Is the configuration superstable?
    is_symmetric           -- Is the configuration symmetric?
    order                  -- The order of the equivalent recurrent element.
    sandpile               -- The configuration's underlying sandpile.
    show                   -- Show the configuration.
    stabilize              -- The stabilized configuration.
    support                -- The vertices containing sand.
    unstable               -- The unstable vertices.
    values                 -- The values of the configuration as a list.
Got:
    Shortcuts for SandpileConfig operations:
    ~c    -- stabilize
    c & d -- add and stabilize
    c * c -- add and find equivalent recurrent
    c^k   -- add k times and find equivalent recurrent
             (taking inverse if k is negative)
    <BLANKLINE>
    For detailed help with any method FOO listed below,
    enter "SandpileConfig.FOO?" or enter "c.FOO?" for any SandpileConfig c.
    <BLANKLINE>
    add_random             -- Add one grain of sand to a random vertex.
    burst_size             -- The burst size of the configuration with respect to the given vertex.
    deg                    -- The degree of the configuration.
    dualize                -- The difference with the maximal stable configuration.
    equivalent_recurrent   -- The recurrent configuration equivalent to the given configuration.
    equivalent_superstable -- The equivalent superstable configuration.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileConfig methods.
    is_recurrent           -- Return whether the configuration is recurrent.
    is_stable              -- Return whether this configuration is stable.
    is_superstable         -- Return whether the configuration is superstable.
    is_symmetric           -- Is the configuration symmetric?
    order                  -- The order of the equivalent recurrent element.
    sandpile               -- The configuration's underlying sandpile.
    show                   -- Show the configuration.
    stabilize              -- The stabilized configuration.
    support                -- The vertices containing sand.
    unstable               -- The unstable vertices.
    values                 -- The values of the configuration as a list.

**********************************************************************
File "src/sage/sandpiles/sandpile.py", line 4045, in sage.sandpiles.sandpile.SandpileDivisor.help
Failed example:
    SandpileDivisor.help()
Expected:
    For detailed help with any method FOO listed below,
    enter "SandpileDivisor.FOO?" or enter "D.FOO?" for any SandpileDivisor D.
    <BLANKLINE>
    Dcomplex               -- The support-complex.
    add_random             -- Add one grain of sand to a random vertex.
    betti                  -- The Betti numbers for the support-complex.
    deg                    -- The degree of the divisor.
    dualize                -- The difference with the maximal stable divisor.
    effective_div          -- All linearly equivalent effective divisors.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileDivisor methods.
    is_alive               -- Is the divisor stabilizable?
    is_linearly_equivalent -- Is the given divisor linearly equivalent?
    is_q_reduced           -- Is the divisor q-reduced?
    is_symmetric           -- Is the divisor symmetric?
    is_weierstrass_pt      -- Is the given vertex a Weierstrass point?
    polytope               -- The polytope determining the complete linear system.
    polytope_integer_pts   -- The integer points inside divisor's polytope.
    q_reduced              -- The linearly equivalent q-reduced divisor.
    rank                   -- The rank of the divisor.
    sandpile               -- The divisor's underlying sandpile.
    show                   -- Show the divisor.
    simulate_threshold     -- The first unstabilizable divisor in the closed Markov chain.
    stabilize              -- The stabilization of the divisor.
    support                -- List of vertices at which the divisor is nonzero.
    unstable               -- The unstable vertices.
    values                 -- The values of the divisor as a list.
    weierstrass_div        -- The Weierstrass divisor.
    weierstrass_gap_seq    -- The Weierstrass gap sequence at the given vertex.
    weierstrass_pts        -- The Weierstrass points (vertices).
    weierstrass_rank_seq   -- The Weierstrass rank sequence at the given vertex.
Got:
    For detailed help with any method FOO listed below,
    enter "SandpileDivisor.FOO?" or enter "D.FOO?" for any SandpileDivisor D.
    <BLANKLINE>
    Dcomplex               -- The support-complex.
    add_random             -- Add one grain of sand to a random vertex.
    betti                  -- The Betti numbers for the support-complex.
    deg                    -- The degree of the divisor.
    dualize                -- The difference with the maximal stable divisor.
    effective_div          -- All linearly equivalent effective divisors.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileDivisor methods.
    is_alive               -- Is the divisor stabilizable?
    is_linearly_equivalent -- Is the given divisor linearly equivalent?
    is_q_reduced           -- Is the divisor q-reduced?
    is_symmetric           -- Is the divisor symmetric?
    is_weierstrass_pt      -- Return whether the given vertex is a Weierstrass point.
    polytope               -- The polytope determining the complete linear system.
    polytope_integer_pts   -- The integer points inside divisor's polytope.
    q_reduced              -- The linearly equivalent q-reduced divisor.
    rank                   -- The rank of the divisor.
    sandpile               -- The divisor's underlying sandpile.
    show                   -- Show the divisor.
    simulate_threshold     -- The first unstabilizable divisor in the closed Markov chain.
    stabili [...]

2024-07-08 05:26 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/doctest/forker.py
**********************************************************************
File "src/sage/doctest/forker.py", line 2562, in sage.doctest.forker.DocTestTask.?
Failed example:
    ntests, runner = DTT(options=DD)
Expected nothing
Got:
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1036, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        example3 = 'sage: Zp(5,4,print_mode='digits')(5)\n...00010'
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1143, in compile_and_execute
            compiled = compiler(example)
                       ^^^^^^^^^^^^^^^^^
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 682, in compiler
            code = compile(example.source, filename, "single",
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[26]>", line 1
            example3 = 'sage: Zp(5,4,print_mode='digits')(5)\n...00010'
                                                 ^^^^^^
        SyntaxError: invalid syntax
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1037, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        parsed3 = DTP.parse(example3)
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[27]>", line 1, in <module>
            parsed3 = DTP.parse(example3)
                                ^^^^^^^^
        NameError: name 'example3' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1038, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        dte = parsed3[1]
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[28]>", line 1, in <module>
            dte = parsed3[Integer(1)]
                  ^^^^^^^
        NameError: name 'parsed3' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1039, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        dte.sage_source
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[29]>", line 1, in <module>
            dte.sage_source
            ^^^
        NameError: name 'dte' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1041, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        dte.want
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[30]>", line 1, in <module>
            dte.want
            ^^^
        NameError: name 'dte' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1120, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        example4 = '::\n\n        sage: C.minimum_distance(algorithm='guava')  # optional - guava\n        ...\n        24\n\n'
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1143, in compile_and_execute
            compiled = compiler(example)
                       ^^^^^^^^^^^^^^^^^
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 682, in compiler
            code = compile(example.source, filename, "single",
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[36]>", line 1
            example4 = '::\n\n        sage: C.minimum_distance(algorithm='guava')  # optional - guava\n        ...\n        24\n\n'
                                                                          ^^^^^
        SyntaxError: invalid syntax
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1121, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        parsed4 = DTP.parse(example4)
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[37]>", line 1, in <module>
            parsed4 = DTP.parse(example4)
                                ^^^^^^^^
        NameError: name 'example4' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1122, in sage.doctest.parsing.SageDocTestParser.parse
    Failed example:
        dte = parsed4[1]
    Exception raised:
        Traceback (most recent call last):
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
            self.compile_and_execute(example, compiler, test.globs)
          File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
            exec(compiled, globs)
          File "<doctest sage.doctest.parsing.SageDocTestParser.parse[38]>", line 1, in <module>
            dte = parsed4[Integer(1)]
                  ^^^^^^^
        NameError: name 'parsed4' is not defined
    **********************************************************************
    File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/parsing.py", line 1123, in s [...]

2024-07-08 05:28 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/misc/cachefunc.pyx
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 72, in sage.misc.cachefunc
Failed example:
    cython_code = ['cpdef test_meth(self,x):',
    '    "some doc for a wrapped cython method"',
    '    return -x',
    'from sage.misc.cachefunc import cached_method',
    'from sage.structure.parent cimport Parent',
    'cdef class MyClass(Parent):',
    '    @cached_method',
    '    def direct_method(self, x):',
    '        "Some doc for direct method"',
    '        return 2*x',
    '    wrapped_method = cached_method(test_meth,name='wrapped_method')']
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1143, in compile_and_execute
        compiled = compiler(example)
                   ^^^^^^^^^^^^^^^^^
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 682, in compiler
        code = compile(example.source, filename, "single",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest sage.misc.cachefunc[8]>", line 11
        '    wrapped_method = cached_method(test_meth,name='wrapped_method')']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: invalid syntax. Perhaps you forgot a comma?
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 83, in sage.misc.cachefunc
Failed example:
    cython(os.linesep.join(cython_code))
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[9]>", line 1, in <module>
        cython(os.linesep.join(cython_code))
                               ^^^^^^^^^^^
    NameError: name 'cython_code' is not defined
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 84, in sage.misc.cachefunc
Failed example:
    O = MyClass()
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[10]>", line 1, in <module>
        O = MyClass()
            ^^^^^^^
    NameError: name 'MyClass' is not defined
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 85, in sage.misc.cachefunc
Failed example:
    O.direct_method
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[11]>", line 1, in <module>
        O.direct_method
    AttributeError: 'function' object has no attribute 'direct_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 87, in sage.misc.cachefunc
Failed example:
    O.wrapped_method
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[12]>", line 1, in <module>
        O.wrapped_method
    AttributeError: 'function' object has no attribute 'wrapped_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 89, in sage.misc.cachefunc
Failed example:
    O.wrapped_method.__name__
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[13]>", line 1, in <module>
        O.wrapped_method.__name__
        ^^^^^^^^^^^^^^^^
    AttributeError: 'function' object has no attribute 'wrapped_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 91, in sage.misc.cachefunc
Failed example:
    O.wrapped_method(5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[14]>", line 1, in <module>
        O.wrapped_method(Integer(5))
        ^^^^^^^^^^^^^^^^
    AttributeError: 'function' object has no attribute 'wrapped_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 93, in sage.misc.cachefunc
Failed example:
    O.wrapped_method(5) is O.wrapped_method(5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[15]>", line 1, in <module>
        O.wrapped_method(Integer(5)) is O.wrapped_method(Integer(5))
        ^^^^^^^^^^^^^^^^
    AttributeError: 'function' object has no attribute 'wrapped_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 95, in sage.misc.cachefunc
Failed example:
    O.direct_method(5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[16]>", line 1, in <module>
        O.direct_method(Integer(5))
        ^^^^^^^^^^^^^^^
    AttributeError: 'function' object has no attribute 'direct_method'
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 97, in sage.misc.cachefunc
Failed example:
    O.direct_method(5) is O.direct_method(5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 715, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.cachefunc[17]>", line 1, in <module>
        O.direct_met [...]

2024-07-08 05:29 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/misc/sageinspect.py
**********************************************************************
File "src/sage/misc/sageinspect.py", line 2239, in sage.misc.sageinspect.sage_getsourcelines
Failed example:
    sage_getsourcelines(cachedfib)[0][0]
Expected:
    'def fibonacci(n, algorithm='pari') -> Integer:\n'
Got:
    "def fibonacci(n, algorithm='pari') -> Integer:\n"
**********************************************************************
```

2024-07-08 05:31 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/graphs/generic_graph.py
**********************************************************************
File "src/sage/graphs/generic_graph.py", line 20376, in sage.graphs.generic_graph.GenericGraph.layout
Failed example:
    for key, value in sorted(layout_options.items()):
        print("option {} : {}".format(key, value))
Expected:
    option by_component : Whether to do the spring layout by connected component -- boolean.
    option dim : The dimension of the layout -- `2` or `3`.
    option forest_roots : An iterable specifying which vertices to use as roots for the ``layout='forest'`` option. If no root is specified for a tree, then one is chosen close to the center of the tree. Ignored unless ``layout='forest'``.
    option heights : A dictionary mapping heights to the list of vertices at this height.
    option iterations : The number of times to execute the spring layout algorithm.
    option layout : A layout algorithm -- one of : "acyclic", "circular" (plots the graph with vertices evenly distributed on a circle), "ranked", "graphviz", "planar", "spring" (traditional spring layout, using the graph's current positions as initial positions), or "tree" (the tree will be plotted in levels, depending on minimum distance for the root).
    option prog : Which graphviz layout program to use -- one of "circo", "dot", "fdp", "neato", or "twopi".
    option save_pos : Whether or not to save the computed position for the graph.
    option spring : Use spring layout to finalize the current layout.
    option tree_orientation : The direction of tree branches -- 'up', 'down', 'left' or 'right'.
    option tree_root : A vertex designation for drawing trees. A vertex of the tree to be used as the root for the ``layout='tree'`` option. If no root is specified, then one is chosen close to the center of the tree. Ignored unless ``layout='tree'``.
Got:
    option by_component : Whether to do the spring layout by connected component -- boolean.
    option dim : The dimension of the layout -- 2 or 3.
    option forest_roots : An iterable specifying which vertices to use as roots for the ``layout='forest'`` option. If no root is specified for a tree, then one is chosen close to the center of the tree. Ignored unless ``layout='forest'``.
    option heights : A dictionary mapping heights to the list of vertices at this height.
    option iterations : The number of times to execute the spring layout algorithm.
    option layout : A layout algorithm -- one of : "acyclic", "circular" (plots the graph with vertices evenly distributed on a circle), "ranked", "graphviz", "planar", "spring" (traditional spring layout, using the graph's current positions as initial positions), or "tree" (the tree will be plotted in levels, depending on minimum distance for the root).
    option prog : Which graphviz layout program to use -- one of "circo", "dot", "fdp", "neato", or "twopi".
    option save_pos : Whether or not to save the computed position for the graph.
    option spring : Use spring layout to finalize the current layout.
    option tree_orientation : The direction of tree branches -- 'up', 'down', 'left' or 'right'.
    option tree_root : A vertex designation for drawing trees. A vertex of the tree to be used as the root for the ``layout='tree'`` option. If no root is specified, then one is chosen close to the center of the tree. Ignored unless ``layout='tree'``.
**********************************************************************
1 item had failures:
   1 of  13 in sage.graphs.generic_graph.GenericGraph.layout
    [3915 tests, 1 failure, 21.22 s]
----------------------------------------------------------------------
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/graphs/generic_graph.py  # 1 doctest failed
----------------------------------------------------------------------
```

2024-07-08 05:33 UTC, kwankyu commented
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/doc/en/thematic_tutorials/sandpile.rst
**********************************************************************
File "src/doc/en/thematic_tutorials/sandpile.rst", line 3154, in doc.en.thematic_tutorials.sandpile
Failed example:
    SandpileConfig.help()
Expected:
    Shortcuts for SandpileConfig operations:
    ~c    -- stabilize
    c & d -- add and stabilize
    c * c -- add and find equivalent recurrent
    c^k   -- add k times and find equivalent recurrent
             (taking inverse if k is negative)
    <BLANKLINE>
    For detailed help with any method FOO listed below,
    enter "SandpileConfig.FOO?" or enter "c.FOO?" for any SandpileConfig c.
    <BLANKLINE>
    add_random             -- Add one grain of sand to a random vertex.
    burst_size             -- The burst size of the configuration with respect to the given vertex.
    deg                    -- The degree of the configuration.
    dualize                -- The difference with the maximal stable configuration.
    equivalent_recurrent   -- The recurrent configuration equivalent to the given configuration.
    equivalent_superstable -- The equivalent superstable configuration.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileConfig methods.
    is_recurrent           -- Is the configuration recurrent?
    is_stable              -- Is the configuration stable?
    is_superstable         -- Is the configuration superstable?
    is_symmetric           -- Is the configuration symmetric?
    order                  -- The order of the equivalent recurrent element.
    sandpile               -- The configuration's underlying sandpile.
    show                   -- Show the configuration.
    stabilize              -- The stabilized configuration.
    support                -- The vertices containing sand.
    unstable               -- The unstable vertices.
    values                 -- The values of the configuration as a list.
Got:
    Shortcuts for SandpileConfig operations:
    ~c    -- stabilize
    c & d -- add and stabilize
    c * c -- add and find equivalent recurrent
    c^k   -- add k times and find equivalent recurrent
             (taking inverse if k is negative)
    <BLANKLINE>
    For detailed help with any method FOO listed below,
    enter "SandpileConfig.FOO?" or enter "c.FOO?" for any SandpileConfig c.
    <BLANKLINE>
    add_random             -- Add one grain of sand to a random vertex.
    burst_size             -- The burst size of the configuration with respect to the given vertex.
    deg                    -- The degree of the configuration.
    dualize                -- The difference with the maximal stable configuration.
    equivalent_recurrent   -- The recurrent configuration equivalent to the given configuration.
    equivalent_superstable -- The equivalent superstable configuration.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileConfig methods.
    is_recurrent           -- Return whether the configuration is recurrent.
    is_stable              -- Return whether this configuration is stable.
    is_superstable         -- Return whether the configuration is superstable.
    is_symmetric           -- Is the configuration symmetric?
    order                  -- The order of the equivalent recurrent element.
    sandpile               -- The configuration's underlying sandpile.
    show                   -- Show the configuration.
    stabilize              -- The stabilized configuration.
    support                -- The vertices containing sand.
    unstable               -- The unstable vertices.
    values                 -- The values of the configuration as a list.
**********************************************************************
File "src/doc/en/thematic_tutorials/sandpile.rst", line 3952, in doc.en.thematic_tutorials.sandpile
Failed example:
    SandpileDivisor.help()
Expected:
    For detailed help with any method FOO listed below,
    enter "SandpileDivisor.FOO?" or enter "D.FOO?" for any SandpileDivisor D.
    <BLANKLINE>
    Dcomplex               -- The support-complex.
    add_random             -- Add one grain of sand to a random vertex.
    betti                  -- The Betti numbers for the support-complex.
    deg                    -- The degree of the divisor.
    dualize                -- The difference with the maximal stable divisor.
    effective_div          -- All linearly equivalent effective divisors.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileDivisor methods.
    is_alive               -- Is the divisor stabilizable?
    is_linearly_equivalent -- Is the given divisor linearly equivalent?
    is_q_reduced           -- Is the divisor q-reduced?
    is_symmetric           -- Is the divisor symmetric?
    is_weierstrass_pt      -- Is the given vertex a Weierstrass point?
    polytope               -- The polytope determining the complete linear system.
    polytope_integer_pts   -- The integer points inside divisor's polytope.
    q_reduced              -- The linearly equivalent q-reduced divisor.
    rank                   -- The rank of the divisor.
    sandpile               -- The divisor's underlying sandpile.
    show                   -- Show the divisor.
    simulate_threshold     -- The first unstabilizable divisor in the closed Markov chain.
    stabilize              -- The stabilization of the divisor.
    support                -- List of vertices at which the divisor is nonzero.
    unstable               -- The unstable vertices.
    values                 -- The values of the divisor as a list.
    weierstrass_div        -- The Weierstrass divisor.
    weierstrass_gap_seq    -- The Weierstrass gap sequence at the given vertex.
    weierstrass_pts        -- The Weierstrass points (vertices).
    weierstrass_rank_seq   -- The Weierstrass rank sequence at the given vertex.
Got:
    For detailed help with any method FOO listed below,
    enter "SandpileDivisor.FOO?" or enter "D.FOO?" for any SandpileDivisor D.
    <BLANKLINE>
    Dcomplex               -- The support-complex.
    add_random             -- Add one grain of sand to a random vertex.
    betti                  -- The Betti numbers for the support-complex.
    deg                    -- The degree of the divisor.
    dualize                -- The difference with the maximal stable divisor.
    effective_div          -- All linearly equivalent effective divisors.
    fire_script            -- Fire the given script.
    fire_unstable          -- Fire all unstable vertices.
    fire_vertex            -- Fire the given vertex.
    help                   -- List of SandpileDivisor methods.
    is_alive               -- Is the divisor stabilizable?
    is_linearly_equivalent -- Is the given divisor linearly equivalent?
    is_q_reduced           -- Is the divisor q-reduced?
    is_symmetric           -- Is the divisor symmetric?
    is_weierstrass_pt      -- Return whether the given vertex is a Weierstrass point.
    polytope               -- The polytope determining the complete linear system.
    polytope_integer_pts   -- The integer points inside divisor's polytope.
    q_reduced              -- The linearly equivalent q-reduced divisor.
    rank                   -- The rank of the divisor.
    sandpile               -- The divisor's underlying sandpile.
    show                   -- Show the divisor.
    simulate_threshold     -- The first unstabilizable divisor in the closed Markov ch [...]

2024-07-08 09:14 UTC, gmou3 commented
I still haven't figured out how to fix this one:
```
sage -t --warn-long 67.3 --random-seed=258355055080068059741298640195743082121 src/sage/repl/ipython_tests.py
```
I'll return to it later.

2024-07-08 10:45 UTC, kwankyu commented
Ah, there was already one doctest failure with the file. See https://github.com/sagemath/sage/pull/38226#issuecomment-2212614731

2024-07-08 10:58 UTC, gmou3 commented
Build & Test succeeds!
Maybe building from scratch was needed.

2024-07-08 11:17 UTC, gmou3 commented
Thanks @kwankyu for the stupendous reviewing work!

No more pending changes from my side. Hopefully now we have a cleaner slate for even more future improvements.

2024-07-08 11:21 UTC, kwankyu commented
Yes. This is a great work. I hope that developers will maintain the high quality of docstrings.

2024-07-08 12:23 UTC, kwankyu approved these changes
Thanks for the hard work!

2024-07-15 01:26 UTC, tscrim commented
One point that I think should be noted is that there is **no** preference in Python or Sage for `'string'` versus `"string"`.

2024-07-15 01:53 UTC, kwankyu commented
Right. Especially in code. This is a fine point for which each developer has his/her own preference. I tend to use double quotes for plain sentences (like error messages) but prefer single quotes for other strings. 

On the other hand, in docstrings, this PR is clearly in preference of single quotes, for **uniformity** purpose. I think this is an improvement over status quo.

2024-07-15 02:08 UTC, tscrim commented
That's my point; we should not make or imply such a preference in favor of uniformity for something that, by its nature, is not meant to be uniform. Note I've not said to revert/block the change either. But then what if someone has a PR that has double quotes? Then if we are implying that we have imposed unformity (a consequence of how this is PR is phrased), then someone could give that as a reason to reject a PR (like we do for the linter). We just should note and/or tweak the PR statement that this is a desired thing here. In fact, it violates your rule that we should leave such not-explicitly documented choices to the author.

2024-07-15 04:14 UTC, kwankyu commented
> ... But then what if someone has a PR that has double quotes? Then if we are implying that we have imposed unformity (a consequence of how this is PR is phrased), then someone could give that as a reason to reject a PR (like we do for the linter). 

Do you mean that this statement

> Large scale formatting of the docstrings in accordance with the [Developer Guide](https://doc.sagemath.org/html/en/developer/coding_basics.html).

implies that each of the changes made in this PR is from a rule in the developer guide? 

That is of course not true. For example, (S) single quotes vs double quotes.

> We just should note and/or tweak the PR statement that this is a desired thing here.

Yes, if the statement could be misconstrued as above. 

> In fact, it violates your rule that we should leave such not-explicitly-documented choices to the author.

Rather the rule is to follow the author's preference on the style if there is a dispute about it, and the rule mentions some cases. (S) is not mentioned. By the way, the developer guide is a guide, not a rule book.

2024-07-15 04:49 UTC, tscrim commented
> > ... But then what if someone has a PR that has double quotes? Then if we are implying that we have imposed unformity (a consequence of how this is PR is phrased), then someone could give that as a reason to reject a PR (like we do for the linter).
> 
> Do you mean that this statement
> 
> > Large scale formatting of the docstrings in accordance with the [Developer Guide](https://doc.sagemath.org/html/en/developer/coding_basics.html).
> 
> implies that each of the changes made in this PR is from a rule in the developer guide?
> 
> That is of course not true. For example, (S) single quotes vs double quotes.
> 
> > We just should note and/or tweak the PR statement that this is a desired thing here.
> 
> Yes, if the statement could be misconstrued as above.

I agree that is not the intent, but we should be careful about potential interpretations to avoid misunderstandings. I also carried some impressions over from the sage-devel post that is not in the PR statement; my apologies for that. However, there is an implication here in the PR phrasing that the single versus double quotes is in the dev guide.

> > In fact, it violates your rule that we should leave such not-explicitly-documented choices to the author.
> 
> Rather the rule is to follow the author's preference on the style if there is a dispute about it, and the rule mentions some cases. (S) is not mentioned.

I agree, and the mass change here is breaking the (original) authors' preference. It might also create a very slight dissonance between the docstring (single quotes) and code (double quotes). Again, this is not at all strong argument nor a reason to revert those changes. It's just a clarification on the PR wording.

> By the way, the developer guide is a guide, not a rule book.

I think that is a distinction without a difference. We do take what is in the dev guide as rules (with taking into account exceptions). This is especially important for new developers who don't feel like they should break from the dev guide (on the other side, what else can we point to in order to say "you must do X" such as 100% doctest coverage?).

2024-07-15 05:15 UTC, kwankyu commented
> ... This is especially important for new developers who don't feel like they should break from the dev guide.

Yes, that is the main point of the developer guide. 

Experienced developers should not expect that the rules of the developer guide give definite answers for all real cases. As you observed, if the "author wins for not-documented" rule is applied without exceptions, this PR is not possible. 

> (on the other side, what else can we point to in order to say "you must do X" such as 100% doctest coverage?).

Nothing else than the developer guide :-) Again I don't think the developer guide covers all cases. No need to do so.

2024-07-15 06:08 UTC, tscrim commented
> > ... This is especially important for new developers who don't feel like they should break from the dev guide.
> 
> Yes, that is the main point of the developer guide.
> 
> Experienced developers should not expect that the rules of the developer guide give definite answers for all real cases. As you observed, if the "author wins for not-documented" rule is applied without exceptions, this PR is not possible.

That is a nice exception you've created to your rule. Mitch McConnell would approve (sorry, US politics reference).

Again, my point is not that we cannot do this PR, but we should make some effort to not suggest that we are starting to recommend single quotes (which your comment about an improvement regarding uniformity also implies).

> > (on the other side, what else can we point to in order to say "you must do X" such as 100% doctest coverage?).
> 
> Nothing else than the developer guide :-) Again I don't think the developer guide covers all cases. No need to do so.

Right, correct, and I agree with you. However, when using the dev guide as justification (which is our only source for what devs should do), it should actually be in the dev guide. This also includes the hyphen with `non-` (which probably should be added as a preference now since that makes grep/find much easier).

2024-07-15 06:47 UTC, kwankyu commented
> .. but we should make some effort to not suggest that we are starting to recommend single quotes (which your comment about an improvement regarding uniformity also implies).

If you mean to rephrase the PR statements, an explicit suggestion would help the author. 

> .. This also includes the hyphen with `non-` (which probably should be added as a preference now since that makes grep/find much easier).

Which "non-negative" or "nonnegative" do you think should be added as a preference to the developer guide?

In my view, after this PR, preferences made in this PR should be reflected in the developer guide. That would need a discussion on sage-devel. If somehow we could reach to a consensus for some of the items, then it would be easy to implement the agreed preferences thanks to this PR.

2024-07-15 07:26 UTC, tscrim commented
> > .. but we should make some effort to not suggest that we are starting to recommend single quotes (which your comment about an improvement regarding uniformity also implies).
> 
> If you mean to rephrase the PR statements, an explicit suggestion would help the author.

Explicitly dividing the bullet points into things from the dev guide and those that were done to be uniform based on the preferences of @gmou3 when doing the PR.

> > .. This also includes the hyphen with `non-` (which probably should be added as a preference now since that makes grep/find much easier).
> 
> Which "non-negative" or "nonnegative" do you think should be added as a preference to the developer guide?

Personally I like nonnegative, but there might be cases where having non-foo might be important for avoiding confusion.

> In my view, after this PR, preferences made in this PR should be reflected in the developer guide. That would need a discussion on sage-devel. If somehow we could reach to a consensus for some of the items, then it would be easy to implement the agreed preferences thanks to this PR.

Indeed, we need a sage-devel discussion for them. While I do not think we should make the single quote a standard, that doesn't apply to all of them. (Although we should be very careful to point out that the changes of this PR should not influence such recommendations based on the number of occurrences; this would heavily and unfairly bias the outcome.)

2024-07-22 02:27 UTC, kwankyu commented
You may set it back to "positive review" after trivial merge.

2024-07-24 22:36 UTC, vbraun commented
merge conflict

2024-07-29 22:39 UTC, vbraun commented
Documentation doesn't build
```
[sagemath_doc_html-none] [spkg-install] [finite_ri] docstring of sage.rings.finite_rings.integer_mod.IntegerMod_abstract.log:15: WARNING: Bullet list ends without a blank line; unexpected unindent.
[sagemath_doc_html-none] [spkg-install] [finite_ri] The inventory file is in ../../local/share/doc/sage/inventory/en/reference/finite_rings.
[sagemath_doc_html-none] [spkg-install] Error building the documentation.
[sagemath_doc_html-none] [spkg-install] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install]   File "<frozen runpy>", line 198, in _run_module_as_main
[sagemath_doc_html-none] [spkg-install]   File "<frozen runpy>", line 88, in _run_code
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/__main__.py", line 530, in <module>
[sagemath_doc_html-none] [spkg-install]     sys.exit(main())
[sagemath_doc_html-none] [spkg-install]              ^^^^^^
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/__main__.py", line 526, in main
[sagemath_doc_html-none] [spkg-install]     builder()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 827, in _wrapper
[sagemath_doc_html-none] [spkg-install]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 163, in f
[sagemath_doc_html-none] [spkg-install]     runsphinx()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
[sagemath_doc_html-none] [spkg-install]     sys.stderr.raise_errors()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
[sagemath_doc_html-none] [spkg-install]     raise OSError(self._error)
[sagemath_doc_html-none] [spkg-install] OSError: docstring of sage.rings.finite_rings.integer_mod.IntegerMod_abstract.log:15: WARNING: Bullet list ends without a blank line; unexpected unindent.
[sagemath_doc_html-none] [spkg-install] 
[sagemath_doc_html-none] [spkg-install]     Note: incremental documentation builds sometimes cause spurious
[sagemath_doc_html-none] [spkg-install]     error messages. To be certain that these are real errors, run
[sagemath_doc_html-none] [spkg-install]     "make doc-clean doc-uninstall" first and try again.
[sagemath_doc_html-none] [spkg-install] [hyperboli] updating environment: 0 added, 5 changed, 0 removed
```

2024-07-30 00:08 UTC, kwankyu commented
Fix
```diff
diff --git a/src/sage/rings/finite_rings/integer_mod.pyx b/src/sage/rings/finite_rings/integer_mod.pyx
index 50eef256b70..0b220e81a1e 100644
--- a/src/sage/rings/finite_rings/integer_mod.pyx
+++ b/src/sage/rings/finite_rings/integer_mod.pyx
@@ -652,14 +652,13 @@ cdef class IntegerMod_abstract(FiniteRingElement):
           ``R.multiplicative_generator()`` is used, where
           ``R`` is the parent of ``self``.
 
-        -  ``order`` -- integer (unused), the order of ``b``.
+        - ``order`` -- integer (unused), the order of ``b``.
           This argument is normally unused, only there for
           coherence of apis with finite field elements.
 
         - ``check`` -- boolean (default: ``False``); if set,
           test whether the given ``order`` is correct
 
-
         OUTPUT:
 
         Integer `x` such that `b^x = a`, if this exists; a :exc:`ValueError`
```

2024-07-30 09:36 UTC, gmou3 commented
Documentation builds now.

2024-08-03 11:38 UTC, merged

2024-12-15 18:05 UTC, user202729 commented
This pull request changes file permissions to executable for no apparent reason. Should we revert?

```
old mode 100644
new mode 100755
```

2024-12-15 19:09 UTC, gmou3 commented
That's weird. You can open a PR to give more details and revert the permissions if you like. Running `git ls-files -s | grep 100755 | wc -l` shows the existence of 294 executable files, 150 of whom are in `src/sage`. These 150 better have 100644?