Improve performance of computing columns of matrices over GF(2)
sagemath/sage pull request #38152
Opened 2024-06-04 16:44 UTC by GiacomoPope

In response to issue https://github.com/sagemath/sage/issues/38150 I have adjusted the request for columns over dense matrices over GF(2) by replacing the standard call to columns with a transpose followed by a request of rows.

This results in almost a 1000x speed up.

```py
sage: M2 = random_matrix(GF(2), 2000, 2000)
sage: %time _  = M2.columns()
CPU times: user 14.1 ms, sys: 2.15 ms, total: 16.3 ms
Wall time: 16.2 ms
```

Fixes https://github.com/sagemath/sage/issues/38150

2024-06-05 13:27 UTC, grhkm21 requested changes
Just small style changes, then it should be good. Thanks for the easy but much needed improvement!

2024-06-05 13:27 UTC, grhkm21 commented on src/sage/matrix/matrix_mod2_dense.pyx
> +
```suggestion
```

2024-06-05 13:27 UTC, grhkm21 commented on src/sage/matrix/matrix_mod2_dense.pyx
> +        - ``copy`` - (default: True) if True, return a copy so you can
```suggestion
        - ``copy`` -- (default: ``True``) if True, return a copy so you can
```

2024-06-05 13:27 UTC, grhkm21 commented on src/sage/matrix/matrix_mod2_dense.pyx
> +            return C
```suggestion
        return C
```

2024-06-05 13:59 UTC, GiacomoPope commented
Thanks for the tips -- I was lazy and copy pasted old columns code, so these changes could be applied elsewhere too but that's for another day!

2024-06-06 18:05 UTC, grhkm21 approved these changes
good enough. I think the entire file can be refactored later lol

2024-06-09 10:25 UTC, merged