Fixing issue 38012
sagemath/sage pull request #38151
Opened 2024-06-04 16:30 UTC by Nathabolin

Fixes issue 38012

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-06-04 16:47 UTC, bhutz requested changes
Add that this doctest is fixing issue 38012.

add white space around '+' in the example (line 8446)

2024-06-05 09:09 UTC, S17A05 commented on src/sage/dynamics/arithmetic_dynamics/projective_ds.py
> +        Fixes issue 38012 by not forcing univariate polynomial to be univariate::
```suggestion
        Fixes :issue:`38012` by not forcing univariate polynomial to be univariate::
```

2024-06-05 09:09 UTC, S17A05 commented on src/sage/dynamics/arithmetic_dynamics/projective_ds.py
> +              G = G.polynomial(G.variable(0))
```suggestion
            if is_MPolynomialRing(G.parent()):
                G = G.polynomial(G.variable(0))
```

2024-06-05 19:40 UTC, mkoeppe commented
Hints:
- Please change the title of the PR so we don't have to look up the Issue by number.
- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-06-06 12:02 UTC, S17A05 commented
What @mkoeppe was referring to with the second hint: You should write "Fixes #38012" (without the "issue") in the PR text body, so that the issue gets linked to this PR.

2024-06-17 15:36 UTC, bhutz approved these changes
This good to me and all tests are passing and the docs build.

2024-07-03 18:16 UTC, Nathabolin commented
What needs to be done for this to be accepted? or is it accepted?

2024-07-03 18:34 UTC, S17A05 commented
> What needs to be done for this to be accepted? or is it accepted?

This is accepted, it just needs some time to be merged since the release of Sage 10.4 is currently being prepared, and afaik only urgent stuff is getting merged right now. Also merging the new develop-branch into your PR resets the "positive review"-label, so you should avoid it unless there are merge conflicts that need to be resolved.

2024-07-03 21:14 UTC, Nathabolin commented
Good to know thank you so much

2024-07-04 03:31 UTC, kwankyu commented on src/sage/dynamics/arithmetic_dynamics/projective_ds.py
> +            sage: R.<z> = PolynomialRing(QQ)
The comment says an implementation detail that is not understandable by a user. The usual way to introduce a test (example) for a fix is
```
TEST:

Check that :issue:`38012` is fixed::

    sage: R.<z> = PolynomialRing(QQ)

```

2024-07-04 03:32 UTC, kwankyu commented
Please correct the PR title.

2024-07-24 21:17 UTC, merged