implement morphisms from free algebras
sagemath/sage pull request #38166
Opened 2024-06-07 13:00 UTC by fchapoton

trying to enhance the morphisms from free monoids and free algebras.

I have added a doctest for the new behaviour of substitution in free monoids, namely the monoid unit lands as the unit 1 in `NN`.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

2024-06-09 23:16 UTC, tscrim requested changes
Big +1 on adding this. I probably should have done this a long time ago...

For polynomial rings, my understanding is the general principle is that the output parent should only depend on the parents of the input, not on any specific values. So the test you added would be breaking this. This consistency is useful for code to not have special cases in downstream code.

2024-06-09 23:16 UTC, tscrim commented on src/sage/algebras/free_algebra_element.py
> +            return codomain.coerce(self)
I am not sure we should coerce `self` but the underlying coefficient (i.e., we coerce the base ring element)

2024-06-10 09:20 UTC, fchapoton commented
there is an existing doctest that make sure one can plug non-square matrices.. That's the reason for the behaviour of the new doctest

2024-06-11 01:07 UTC, tscrim commented
I don't think what it does is good behavior. It is far too sensitive to the elements being passed in. Plus, that code is mostly untouched from 2007 (I believe well before we realized this consistency is good). I think we should full disentangle this with providing an example to reproduce the previous behavior but enforce consistency with `__call__` and the like.

2024-06-15 06:28 UTC, fchapoton commented
Travis, do you have an opinion on the current state ? It manages to keep the old behaviour and be more consistent, I hope.
Should we somehow require that the values that we substitute belongs to a ring ?

2024-06-17 13:11 UTC, tscrim approved these changes
Eventually I think we should make it belong to a common parent that is a ring (or monoid in the free monoid case). However, this is an improvement, and we can revisit dropping the general input later. Let’s get this in for now.

2024-07-24 21:17 UTC, merged