Implemented an Explicit Dimension Formula for the Newspace with character
sagemath/sage pull request #38385
Opened 2024-07-17 20:40 UTC by eross156

This PR implements a [recently computed](https://arxiv.org/abs/2407.08881) explicit dimension formula for newspaces of modular forms with character.
This completes Issue #38384  
The tests verify this formula against the current dimension computation in Sage.

### :memo: Checklist

- [ x] The title is concise and informative.
- [ x] The description explains in detail what this PR is about.
- [ x] I have linked a relevant issue or discussion.
- [ x] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-07-18 01:35 UTC, tscrim requested changes
Thank you for your contribution. @JohnCremona, perhaps you might have some thoughts on this PR?

For me, I would prefer not to have all of those internal functions as they make the code harder to follow (i..e, take a more iterative style approach instead of functional) as most of those are called in exactly one place. You are also going to get a lot of Python `int`s being mixed in instead of Sage `Integer`s too.

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/congroup_gamma1.py
> +    """
```suggestion
    r"""
    Compute the dimension formula given in Theorem 1.4 of :arxiv:`2407.08881`.
    
    For more tests, see :meth:`sage.modular.arithgroup.tests.Test.test_dim_formula_Ross()`.
    """
```
However this function does need at least one doctest of its own.

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/congroup_gamma1.py
> +
```suggestion
        return self.dimension_cusp_forms(k, eps, algorithm) - 2*old


```
One too many blank lines.

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/tests.py
> +from sage.rings.integer_ring import ZZ
```suggestion
```
The `ZZ` import is not needed and we can make the other import local.

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/tests.py
> +        for N in range(3,N_ub+1):
```suggestion
        """
        from sage.modular.dirichlet import DirichletGroup
        for N in range(3,N_ub+1):
```

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/tests.py
> +        Gamma1._dimension_new_cusp_forms_Ross()
```suggestion
        Test the dimension formula given in Theorem 1.4
        of :arxiv:`2407.08881`
```

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/tests.py
> +
```suggestion

```

2024-07-18 01:35 UTC, tscrim commented on src/sage/modular/arithgroup/congroup_gamma1.py
> +
```suggestion
    return ZZ(ret)
```

2024-07-18 11:54 UTC, JohnCremona commented
I will take a look -- saw the preprint but have not yet read it as I'm at ANTS this week and then on holdiday for a few days.

2024-07-18 12:42 UTC, eross156 commented
Thank you for all your feedback and updates. Especially thank you for all the style updates to match this repo; I'm still trying to figure out all the code standards here. 
I'm happy to make all the update suggestions.
Is that something that I should do the "commit suggestions" thing in GitHub. Or do I need to allow a maintainer to make those changes?

2024-07-29 02:16 UTC, tscrim commented
Sorry for the delay in responding (traveling).

Yes, usually you use `ZZ(123)`, which can run into problems if you end up dividing two `int`s.

I don't think it is so bad to get rid of all internal functions, but I can see some benefits to keeping some of them. However, the more trivial ones would be better to absorb as inline: `psi_local`, `psi`, `beta_psi_f`, `beta_sigma_f`, `rho`, `beta_rho_f`, `rhopm`, `beta_rhopm_f`, `c3`, `c4`, `c0`, `omega`. Many of these can be written as a `prod` and you could avoid refactoring `chi.conductor()` in a few places. (Also, it is better to use `x -= y` instead of `x = -1 * y` as a micro-optimization.) You should also always return a Sage `Integer` (in particular, line 896 to `return ZZ.zero()`).

2024-08-02 22:40 UTC, eross156 commented
Ok, thanks for the feedback. I will plan to add in these changes on Monday or Tuesday (I'm currently travelling as well).

2026-03-17 11:59 UTC, closed without merging

2026-03-17 12:01 UTC, erick-ross commented
This PR is two years old, and now hopelessly behind sagemath. 
So I think it is better that I just start a new PR from scratch.