number_field_elements_from_algebraics: Fix CyclotomicField embedding when embedding=False
sagemath/sage pull request #38441
Opened 2024-07-28 00:18 UTC by user202729

Fixes #38440.

Uses `.coerce_embedding()` to determine the existence of the embedding and modify the field accordingly, instead of doing what the code does currently (assume the field is unembedded by default).

Note that there's a behavior change --- now when `embedding=False` it will return a `NumberField` instead of `CyclotomicField` (even though it is technically possible to create a `CyclotomicField(5, embedding=None)`). I don't think this matters.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

2024-11-07 17:15 UTC, tscrim requested changes
LGTM modulo some details.

cc-ing some people who might have thoughts about this PR: @tornaria, @saraedum @roed314 @pjbruin

2024-11-07 17:15 UTC, tscrim commented on src/sage/rings/qqbar.py
> +    else:
```suggestion
    if fld is not QQ:
        # ignore the embedded parameter for QQ
```

2024-11-07 17:15 UTC, tscrim commented on src/sage/rings/qqbar.py
> +      NumberField embedded. Note that this has no effect when the
```suggestion
      NumberField embedded; note that this has no effect when the
```

2024-11-08 01:33 UTC, roed314 commented
Something strange got merged into this PR: there are 3036 files changed with 80k+ lines of changes....

2024-11-08 02:05 UTC, roed314 commented on src/sage/rings/qqbar.py
> +        sage: _[0].coerce_embedding()
I'm surprised that the underscore would work here.  Even if it does, I think it's clearer to give the return value explicit names.

2024-11-08 02:18 UTC, roed314 commented
Looks good to me, other than the underscore comment.

2024-11-08 02:27 UTC, user202729 commented on src/sage/rings/qqbar.py
> +          Defn: zeta10 -> 0.809016994374948? + 0.587785252292473?*I
```suggestion
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(2/3))], embedded=False, minimal=True); v
        (Number Field in zeta6 with defining polynomial x^2 - x + 1,
         [zeta6 - 1],
         Ring morphism:
           From: Number Field in zeta6 with defining polynomial x^2 - x + 1
           To:   Algebraic Field
           Defn: zeta6 |--> 0.500000000000000? + 0.866025403784439?*I)
        sage: v[0].coerce_embedding()
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(2/3))], embedded=True, minimal=True); v
        (Cyclotomic Field of order 6 and degree 2,
         [zeta6 - 1],
         Ring morphism:
           From: Cyclotomic Field of order 6 and degree 2
           To:   Algebraic Field
           Defn: zeta6 |--> 0.500000000000000? + 0.866025403784439?*I)
        sage: v[0].coerce_embedding()
        Generic morphism:
          From: Cyclotomic Field of order 6 and degree 2
          To:   Complex Lazy Field
          Defn: zeta6 -> 0.500000000000000? + 0.866025403784439?*I
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(1/2))], embedded=False, minimal=True); v
        (Number Field in I with defining polynomial x^2 + 1,
         [I],
         Ring morphism:
           From: Number Field in I with defining polynomial x^2 + 1
           To:   Algebraic Field
           Defn: I |--> 1*I)
        sage: v[0].coerce_embedding()
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(1/2))], embedded=True, minimal=True); v
        (Number Field in I with defining polynomial x^2 + 1 with I = 1*I,
         [I],
         Ring morphism:
           From: Number Field in I with defining polynomial x^2 + 1 with I = 1*I
           To:   Algebraic Field
           Defn: I |--> 1*I)
        sage: v[0].coerce_embedding()
        Generic morphism:
          From: Number Field in I with defining polynomial x^2 + 1 with I = 1*I
          To:   Complex Lazy Field
          Defn: I -> 1*I
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(1/5))], embedded=False, minimal=True); v
        (Number Field in zeta10 with defining polynomial x^4 - x^3 + x^2 - x + 1,
         [zeta10],
         Ring morphism:
           From: Number Field in zeta10 with defining polynomial x^4 - x^3 + x^2 - x + 1
           To:   Algebraic Field
           Defn: zeta10 |--> 0.8090169943749474? + 0.5877852522924731?*I)
        sage: v[0].coerce_embedding()
        sage: v = number_field_elements_from_algebraics([QQbar((-1)^(1/5))], embedded=True, minimal=True); v
        (Cyclotomic Field of order 10 and degree 4,
         [zeta10],
         Ring morphism:
           From: Cyclotomic Field of order 10 and degree 4
           To:   Algebraic Field
           Defn: zeta10 |--> 0.8090169943749474? + 0.5877852522924731?*I)
        sage: v[0].coerce_embedding()
        Generic morphism:
          From: Cyclotomic Field of order 10 and degree 4
          To:   Complex Lazy Field
          Defn: zeta10 -> 0.809016994374948? + 0.587785252292473?*I
```

2024-11-08 04:16 UTC, roed314 commented
Looks good to me.

2024-11-08 04:18 UTC, roed314 approved these changes

2024-11-16 11:39 UTC, merged