compute endomorphism orders for elliptic curves over finite fields (rank-2 case)
sagemath/sage pull request #38493
Opened 2024-08-10 12:53 UTC by yyyyx4

For an elliptic curve $E$ over a finite field with an endomorphism algebra of rank two over $\mathbb Q$, the endomorphism ring is a superorder of the "Frobenius order" $\mathbb Z[\pi]$.

This patch adds a simple method to compute the exact imaginary-quadratic order which is isomorphic to the endomorphism ring of the curve, and generalizes the algorithm to supersingular elliptic curves with a (rational) endomorphism algebra of rank 2.

2024-08-11 12:02 UTC, JohnCremona commented
I'll look at this tomorrow. I did implement a special case of Sutherland 's algorithm already for our CM testing algorithm last year.

2024-08-11 17:06 UTC, yyyyx4 commented
Thank you! I think the implementation you wrote is the function I'm calling here. I just extended it to work for the supersingular case, too.

2024-12-17 17:52 UTC, JohnCremona commented
Apologies to @yyyyx4 for promising and then not delivering -- sheer forgetfulness on my part.  I cannot promise to be able to review this in the next several days.  Feel free to send me reminders.

2024-12-17 18:57 UTC, yyyyx4 commented
No worries, @JohnCremona! I do think it would be nice to get this into the next release, but it is by no means urgent.

2025-04-29 07:45 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/ell_finite_field.py
> +                assert (ell**(2*e)).divides(self.base_field().cardinality())
Perhaps better to test that the ell-valuation is at least 2*e rather than computing ell**(2*e)?

2025-04-29 07:48 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/ell_finite_field.py
> +            assert E1
I don't think that including assert statements is good practice for production code (though of course essential while testing).  Does the developers' guide say something about this?  But the alternative would be to test the condition anyway and raise an error if it fails, so perhaps it does not make much difference.  (Laos, I am sure thta my own code in Sage does include assert statements...)

2025-04-29 07:50 UTC, JohnCremona commented on src/sage/schemes/elliptic_curves/ell_finite_field.py
> +            raise NotImplementedError
A comment here would be helpful.

2025-04-29 07:52 UTC, JohnCremona requested changes
Looks good, I made a few rather trivial comments but basically approve.

2025-04-29 09:44 UTC, yyyyx4 commented on src/sage/schemes/elliptic_curves/ell_finite_field.py
> +            raise NotImplementedError
This is essentially unreachable code unless something goes *seriously* wrong (cosmic rays). I've turned it into an assertion with a comment for clarity.

2025-04-29 09:59 UTC, yyyyx4 commented on src/sage/schemes/elliptic_curves/ell_finite_field.py
> +            assert E1
I don't think there are any rules about it. I left these in since they are very quick sanity checks that might detect if something is really wrong with the algorithm. Exceptions are for a different purpose; they communicate errors that can occur as part of the *expected* functionality of the code (e.g., invalid inputs). In my opinion, there should be assertions all over the code base anyway, with the default in production environments being that they are turned off (`python -O` or `PYTHONOPTIMIZE=1`), but that's a different discussion...

2025-04-29 10:01 UTC, yyyyx4 commented
Thanks for the review, @JohnCremona! If you are happy with my latest changes, don't forget to approve the pull request (I think I can no longer set "positive review" myself, contrary to the old Trac days).

2025-04-29 10:51 UTC, JohnCremona approved these changes

2025-05-11 17:36 UTC, merged