Fixes in pyx files
sagemath/sage pull request #38542
Opened 2024-08-21 12:31 UTC by fchapoton

This is fixing a few issues about division in various cython files.

All the fixes were found using the command `cython -a -3 *.pyx`.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.

2024-08-21 14:58 UTC, fchapoton commented
@kedlaya : could you please have a look at the 2 failing doctests in hypergeometric motives ? I wonder if the old results were correct.

2024-08-21 17:47 UTC, roed314 commented
I just checked in Magma, which agrees with Sage's old results (note that there's a `t <-> 1/t` difference in convention, thus the `1/2`):
```
H := HypergeometricData([[3],[4]]);
EulerFactor(H,1/2,7);
7*$.1^2 - 3*$.1 + 1
```

Indeed, 21 is too big since it needs to be a weight 1 Weil polynomial.

2024-08-21 17:49 UTC, roed314 commented
I haven't looked at the code in detail, but I wonder why you even want to change the signature here.  It doesn't seem to relate to the C division convention.

2024-08-21 17:51 UTC, fchapoton commented
Thanks. So my changes are not good. I will have to investigate. Probably I will undo the changes here about hypergeometric motives.

2024-08-21 17:54 UTC, fchapoton commented
I wanted to fix the warning displayed by "cython -a -3 hypergeometric_misc.pyx".

2024-08-21 18:01 UTC, kedlaya commented
Off the top of my head I am guessing that changing `p` to `unsigned long long` is changing the behavior of `%` down the line. This is of course fixable, let me have a look.

2024-08-21 19:16 UTC, fchapoton commented
I have tried to make a smaller change in hgm,  and this seems to work. Not sure that it appeases "cython -a -3" buit this is maybe not important

2024-08-21 22:24 UTC, kedlaya commented
> I have tried to make a smaller change in hgm, and this seems to work. Not sure that it appeases "cython -a -3" buit this is maybe not important

On my end changing only `f` to be `unsigned int` seems to fix the warning without disturbing the doctest (which makes sense as the issue is with raising an integer to a possibly negative integer power).

2024-08-22 13:05 UTC, fchapoton commented
Thanks. So this is now ready for review.

2024-09-04 07:40 UTC, fchapoton commented
please review, if you have time

2024-09-04 08:20 UTC, dcoudert requested changes
otherwise LGTM.

2024-09-04 08:20 UTC, dcoudert commented on src/sage/combinat/designs/subhypergraph_search.pyx
> +    h.limbs      = (n+63)//64 # =ceil(n/64)
2 spaces before #

2024-09-04 08:20 UTC, dcoudert commented on src/sage/schemes/elliptic_curves/mod_sym_num.pyx
> +        Nnew = N // p // q
I know it's ok, but isn't it better for readability to write `(N // p) // q`?

2024-09-04 09:50 UTC, fchapoton commented
merci ! Voilà !

2024-09-04 10:48 UTC, dcoudert approved these changes
LGTM.

2024-09-15 19:30 UTC, merged