Dropping support for power with Finite Field Polynomial Element
sagemath/sage pull request #38754
Opened 2024-10-02 18:52 UTC by Shay2Shay

Fixes issue : #32287
`Reference : pow ( Int, Finite Field)`
It was noticed that raising power with ModN field numbers and Gravio/NTL was not consistent.

- Finite Field = ModN : Coerced the FF element to Integer then performed Powering
- Finite Field = Gravio/NTL: Coerced the output to Gravio/NTL rather than Integer because it could only interpret non prime order elements to be polynomials.

Change:
Removed support for Gravio/NTL/Pari_ffelt in powering scenario.

### :memo: Checklist

- [X] The title is concise and informative.
- [X] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [X] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-10-04 06:47 UTC, Shay2Shay commented
@tscrim please have a look.

2024-10-05 00:01 UTC, tscrim requested changes
I don't think this is the correct way to fix the issue. Adding very special cases in generic code for deciding coercion should not be done without a very good reason. Contrast your code with the generic base class `IntegerModRing`. Hence, my proposed change, get every other case that is not an `IntegerModRing` but a finite field.

2024-10-05 00:01 UTC, tscrim commented on src/sage/structure/parent.pyx
> +                if isinstance(S, (FiniteField_pari_ffelt, FiniteField_ntl_gf2e, FiniteField_givaro)):
```suggestion
                elif isinstance(S, FiniteField):
```
You will also need to add
```
from sage.rings.finite_rings.finite_field_base import FiniteField
```

2024-10-05 00:01 UTC, tscrim commented on src/sage/structure/parent.pyx
> +                    raise TypeError('Unable to raise power using finite field polynomial element')
```suggestion
                    _record_exception()
```
I think this is the correct thing to do.

2024-10-05 07:46 UTC, Shay2Shay commented
I understood the 1st part `elif isinstance(S, FiniteField)` and I made desired changes.

But I couldn't understand the second part `_record_exception()`. I originally intended the function call to throw error and halt. 
But removing `raise error` will not stop the program and at it will coerce the base of power to be finite field element - this is what I am thinking.

2024-10-06 04:03 UTC, tscrim commented
Sorry, I forgot what `_record_exception` does; yes, that is not the proper thing to do there. Errors definitely should *not* be raised in that code. In turn, this made me realize something: specific coercions between specific parents should not be (dis)allowed by the coercion code. Those specific parents should be the ones to handle them. So I do not think this is the correct fix. We probably need to dig deeper into what coercions are being called and figure out a better mechanism for disallowing it.

2024-10-06 06:59 UTC, Shay2Shay commented
Understood

I will close this and look for another approach.

2024-10-06 08:46 UTC, closed without merging

2024-10-07 10:19 UTC, Shay2Shay commented
@tscrim 
If I add [here] (https://github.com/Shay2Shay/sage/blob/b0f09d9d7827d657cacb12bd5f18933fa8ed8fb5/src/sage/rings/finite_rings/element_givaro.pyx#L1239C1-L1240C48)  (Same with other variants):
```
if isinstance(exp.parent(), FiniteField) and not isinstance(exp.parent(), ModNField):
    raise TypeError("Cannot raise power with polynomial")
```

How would that be?? (This works locally)