Corrects some inner products in root systems
sagemath/sage pull request #38750
Opened 2024-10-02 00:12 UTC by skipgaribaldi

Goal of this PR: 
   * Fix Exhibit A in #15325 
   * Exhibits B and C in the issue are ignored because they are not strictly speaking errors

Status quo:
   * Some inner products for elements of root spaces or ambient spaces give wrong answers or raise exceptions
   
Fix:
   * Adds a few lines of code to scalar product functions in ambient_space and root_space
   * TESTS were added to scalar product member functions to exhibit fixing this issue

Notes:
   * I am unable to verify that the documentation builds because I cannot build the documentation (build problems with this version of Sage)

A more thorough test of this functionality, which checks Exhibit A from the issue on more cases, is provided by the following code snippet:

```
for ct in [['G', 2], ['F', 4], ['E', 8], ['E', 7]] + [[x, 6] for x in ['A', 'B', 'C', 'D', 'E']]:     
    rt = RootSystem(ct)
    print(ct)
    lat = rt.root_lattice()
    spc = rt.ambient_space()
    ell = lat.rank()
    C = rt.cartan_matrix()
    for i in range(1,ell+1):
        assert lat.simple_root(i) == spc.simple_root(i)
        assert lat.simple_coroot(i) == spc.simple_coroot(i)
        for j in range(1,ell+1):
            aprod = C[j-1,i-1]
            assert lat.simple_root(i).scalar(lat.simple_coroot(j)) == aprod
            assert spc.simple_root(i).scalar(spc.simple_coroot(j)) == aprod
            assert spc.simple_root(i).scalar(lat.simple_coroot(j)) == aprod
            assert lat.simple_root(i).scalar(spc.simple_coroot(j)) == aprod

```

### :memo: Checklist

- [X] The title is concise and informative.
- [X] The description explains in detail what this PR is about.
- [X] I have linked a relevant issue or discussion.
- [X] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-10-02 01:46 UTC, tscrim requested changes
Thank you for the improvements here. It is good to not require the user to be so explicit. Here are some improvements based on your PR.

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/root_space.py
> +        if (lambdacheck in self.parent().root_system.ambient_space()):
```suggestion
        if lambdacheck in self.parent().root_system.ambient_space():
```
Not needed in Python.

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/root_space.py
> +        if (lambdacheck in self.parent().coroot_lattice() or lambdacheck in self.parent().coroot_space()):
```suggestion
        if lambdacheck in self.parent().coroot_lattice() or lambdacheck in self.parent().coroot_space():
```
Not needed in Python.

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/root_space.py
> +            sage: rt = RootSystem(['E',8])  # verify that error from issue gh-15325 Exhibit A is fixed
```suggestion
        TESTS:

       Verify that :issue:`15325` (A) is fixed::

            sage: rt = RootSystem(['E', 8])
```

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/ambient_space.py
> +        raise TypeError(f"Don't know how to coerce {lambdacheck} into root or coroot space of {self}")
```suggestion
```

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/ambient_space.py
> +            sage: rt = RootSystem(['E',8])  # verify that error from issue gh-15325 Exhibit A is fixed
```suggestion
        TESTS:

        Verify that :issue:`15325` (A) is fixed::

            sage: rt = RootSystem(['E', 8])
```

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/ambient_space.py
> +        The scalar product with elements of the ambient space
```suggestion
        The scalar product with elements of the ambient space.
```

2024-10-02 01:46 UTC, tscrim commented on src/sage/combinat/root_system/ambient_space.py
> +            return lambdacheck.to_ambient().scalar(self)
```suggestion
        if self.parent() is not lambdacheck.parent():
            try:
                # see if lambdacheck can be converted to the ambient space
                lambdacheck = self.parent()(lambacheck)
            except (TypeError, ValueError):
                raise TypeError(f"unable to coerce {lambdacheck} into {self.parent()}")

        # self and lambdacheck both belong to the same ambient space, so use the inner product there
        self_mc = self._monomial_coefficients
        lambdacheck_mc = lambdacheck._monomial_coefficients

        result = self.parent().base_ring().zero()
        for t,c in lambdacheck_mc.items():
            if t in self_mc:
                result += c*self_mc[t]
        return result
```

2024-10-02 01:47 UTC, tscrim commented on src/sage/combinat/root_system/root_space.py
> +            sage: lat = RootSystem(['B', 3]).root_lattice()  # verify that directionality is correct for roots of different lengths
```suggestion
            0

        Verify that directionality is correct for roots of different lengths::

            sage: lat = RootSystem(['B', 3]).root_lattice()
```
One more change.

2024-10-02 02:32 UTC, skipgaribaldi commented on src/sage/combinat/root_system/ambient_space.py
> +            return lambdacheck.to_ambient().scalar(self)
Adopted!

2024-10-04 00:44 UTC, tscrim approved these changes
Sorry, I missed one doc-formatting thing. Once fixed, this will be a positive review.

2024-10-04 00:44 UTC, tscrim commented on src/sage/combinat/root_system/root_space.py
> +        TESTS::
```suggestion
        TESTS:
```

2024-10-04 04:14 UTC, tscrim commented
Thank you.

2024-10-12 09:34 UTC, merged