libbraiding version bump
sagemath/sage pull request #38887
Opened 2024-10-29 18:50 UTC by miguelmarco

Fixes #38886 by updating libbraiding package and adding new methods to braids.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-10-30 01:38 UTC, tscrim requested changes
A few little details. Otherwise LGTM.

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +        Return an element of the braid's super summit set, an the conjugating
```suggestion
        Return an element of the braid's super summit set and the conjugating
```

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +        Return the the braid's cyclic slidings.
```suggestion
        Return the braid's cyclic slidings.
```

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +    def send_to_sss(self):
This method name is not very clear. How about `super_summit_set[_element]`?

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +    def send_to_uss(self):
Same comment about the name.

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +        Return an element of the braid's ultra summit set, an the conjugating
```suggestion
        Return an element of the braid's ultra summit set and the conjugating
```

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +        """
```suggestion
            (s0*s2*s0*s1*s2*s1*s0, s0^-1*s1^-1*s0^-1*s2^-1*s1^-1*s0^-1*s1*s0*s2*s1*s0)
        """
```
We generally do not have this blank line IIRC.

2024-10-30 01:38 UTC, tscrim commented on src/sage/libs/braiding.pyx
> +    - ``braid```-- a braid
```suggestion
    - ``braid``` -- a braid
```

2024-10-30 01:38 UTC, tscrim commented on src/sage/groups/braid.py
> +        return tuple(B._element_from_libbraiding(b) for b in to_uss)
```suggestion
        return tuple([B._element_from_libbraiding(b) for b in to_uss])
```
For whatever reason, this is marginally faster.

2024-10-30 08:59 UTC, miguelmarco commented
Thanks for the quick review!

There is still a problem with the install of the new version of libbraiding that I don't know how to solve: in the CI environments the new version is not installed, and then the tests fail.

I guess it has something to do with the `environment-3*.yaml` files, which are automatically generated by conda-lock.

Do you know what should be the right way to proceed?

2024-11-01 10:21 UTC, enriqueartal reviewed
I find it OK, and I agreed with @tscrim comments. I add a couple of comments about documentation. Basically it is fine for me.

2024-11-01 10:21 UTC, enriqueartal commented on src/sage/groups/braid.py
> +        Return the braid's trajectory.
I guess a little more explanation would help.

2024-11-01 10:21 UTC, enriqueartal commented on src/sage/groups/braid.py
> +        Return the braid's cyclic slidings.
Same thing

2024-11-01 10:23 UTC, enriqueartal commented
> Thanks for the quick review!
> 
> There is still a problem with the install of the new version of libbraiding that I don't know how to solve: in the CI environments the new version is not installed, and then the tests fail.
> 
> I guess it has something to do with the `environment-3*.yaml` files, which are automatically generated by conda-lock.
> 
> Do you know what should be the right way to proceed?

Is it a more general problem? I updated my system to Fedora 41, and `sirocco` did not work after a compilation because of python's version. And it could not be reinstalled because it was already there.

2024-11-18 10:31 UTC, miguelmarco commented
I think I managed to force the CI systems to install the right version. Tests should pass now.

2024-11-18 12:23 UTC, enriqueartal commented
Since the test pass, it seems OK to a positive review.

2024-11-18 12:24 UTC, enriqueartal approved these changes

2024-12-08 22:57 UTC, merged