Overwrote methods concerning loops for a matching covered graph
sagemath/sage pull request #38955
Opened 2024-11-10 13:07 UTC by janmenjayap

The objective of this issue is to overwrite the methods pertaining to loops for a matching covered graph. 

More specifically, this PR aims to implement/ update the following methods:
- [x] `allow_loops()`: Change whether loops are allowed in (matching covered) graphs.
- [x] `allows_loops()`: Return whether loops are permitted in (matching covered) graphs.
- [x] `has_loops()`: Check whether thare are loops in the (matching covered) graph.
- [x] `loop_edges()`: Return a list of all loops in the (matching covered) graph.
- [x] `loop_vertices()`: Return a list of vertices with loops.
- [x] `loops()`: Return a list of all loops in the (matching covered) graph.
- [x] `number_of_loops()`: Return the number of edges that are loops.
- [x] `remove_loops()`: Remove loops on vertices in ``vertices``.

This PR shall address the methods related to loops for matching covered graphs.

Fixes #38216. Note that this issue fixes a small part of the mentioned issue.
This PR depends on the PR #38742.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

Nothing as of now (up to my knowledge).

cc: @dcoudert.

2024-11-10 13:32 UTC, dcoudert requested changes
I think you added too many doctests. Do we really need to tests all the methods in the tests of all methods ?

2024-11-10 13:32 UTC, dcoudert commented on src/sage/graphs/matching_covered_graph.py
> +
remove empty line

2024-11-10 13:32 UTC, dcoudert commented on src/sage/graphs/matching_covered_graph.py
> +        """
use `r"""`

2024-11-10 13:38 UTC, janmenjayap commented
> I think you added too many doctests. Do we really need to tests all the methods in the tests of all methods ?

Oh.
I will rectify this.

2024-11-11 19:13 UTC, dcoudert approved these changes
LGTM.

2024-11-12 08:37 UTC, janmenjayap commented
Hi,
If I am not mistaken, shouldn't we wait till the PR #38742 is merged followed by resolving the conflicts in this PR after pulling the changes from develop branch?

2024-11-12 09:12 UTC, dcoudert commented
Yes, it would be much better. I'm setting back this PR to needs review then.

2024-11-19 11:13 UTC, dcoudert approved these changes
LGTM.

2024-12-08 22:57 UTC, merged