Meson: find more dependencies via pkg-config
sagemath/sage pull request #38993
Opened 2024-11-18 06:39 UTC by tobiasdiez

Use pkg-config to find more dependencies, and add version constraints (mostly) as specified in the `spkg-configure` scripts.

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-12-23 10:59 UTC, antonio-rojas requested changes

2024-12-23 10:59 UTC, antonio-rojas commented on src/meson.build
> +gap = dependency('gap', version: '>=4.13.0', required: false)
gap's pc file is called `libgap`, not `gap`

https://github.com/gap-system/gap/blob/master/libgap.pc.in

2024-12-23 11:29 UTC, antonio-rojas commented
LGTM otherwise

2024-12-23 15:55 UTC, dimpase approved these changes

2024-12-24 03:26 UTC, tobiasdiez commented
Thanks @antonio-rojas for the suggestion, and both of you for the review!

2025-01-04 18:03 UTC, merged