is_circumscribable: support other MIP solvers
sagemath/sage pull request #39026
Opened 2024-11-24 11:04 UTC by Ordoviz

The graph methods [`is_circumscribable`](https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph.html#sage.graphs.graph.Graph.is_circumscribable) and [`is_inscribable`](https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph.html#sage.graphs.graph.Graph.is_inscribable) currently only work when the optional argument `solver` is kept unchanged at `PPL`. For example,

```sage
Graph("JIQCC?ZJ`i?").is_inscribable(solver="GLPK")
````

fails with `UnboundLocalError: cannot access local variable 'solution' where it is not associated with a value` while it should evaluate to `False` (at least that's what you get with `solver="PPL"`).

I fixed this in a quick-and-dirty way. It is unfortunate that we need to do a string comparison on the MIPSolverException since the solver can also fail for reasons like "unknown error during call to GLPK" (although in [other places](https://github.com/sagemath/sage/blob/b9e396a7444167fb334b12a5b41db9af0cfa8ef0/src/sage/graphs/matching.py#L157) a MIPSolverException is assumed to mean "unsolvable").

2024-11-24 17:27 UTC, dcoudert requested changes
otherwise LGTM. It also fixes the issue with cplex.

2024-11-24 17:27 UTC, dcoudert commented on src/sage/graphs/graph.py
> +            else:
here the `else`  is not needed.

2024-11-25 09:00 UTC, user202729 commented
Sounds reasonable. Maybe add a test? (then you can run `sage -t [file]` to run the test locally because you don't have approval to run workflow yet)

2024-11-25 14:00 UTC, Ordoviz commented
I'm closing this because more work is needed to support solvers other than PPL (there's even a TODO in the docstring of `is_circumscribable` about this). For example, with `g=Graph("IF?G]YiX_")`, we have `g.is_circumscribable() == True` and `g.is_circumscribable(solver="GLPK") == False`.

2024-11-25 14:00 UTC, closed without merging