Distro-meson
sagemath/sage pull request #39030
Opened 2024-11-25 03:49 UTC by tobiasdiez

Replace the old setuptools-based build by the new meson-based one in sage-the-distro. Delete most of the old stuff that is no longer needed now.

### :memo: Checklist

- [ ] The title is concise and informative.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### :hourglass: Dependencies

2024-11-30 04:31 UTC, dimpase commented
Sure, I'm ready to help as much as I can. Could you share an outline of how this is meant to work? 

I imagine it is an adaptation  to the Sage's venv (which is a more or less standard venv, no?) of what one can get e.g. with a standard venv on Gentoo Linux, or another environment where all the dependencies are available. Would this approach also work for a Conda-based environment?

2024-11-30 07:07 UTC, tobiasdiez commented
As a first step, I would not change how sage-the-distro works. So leave all the dependency installation (python and non-python deps) untouched for now. (We can discuss later how to transfer the configure checks to meson, and perhaps even completely replace the install scripts by mesons wrap files)

So, basically the only required change would be `pip install ./src` to `pip install . `, i.e. instead of using the pyproject.toml in src, the meson-based one in the root should be used to install sagelib. I tried to that in build/pkgs/sagelib/spkg-install.in in this branch, but not sure if the changes are correct. Then see what errors popup and resolve those.

2024-12-01 04:37 UTC, dimpase commented
running `./bootstrap` gives
```
sed: can't read ../sagelib/package-version.txt: No such file or directory
```

2024-12-01 04:40 UTC, dimpase commented
that's cause
```
$ git grep "sagelib/package-version.txt"
pkgs/sagemath-bliss/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
pkgs/sagemath-coxeter3/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
pkgs/sagemath-mcqd/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
pkgs/sagemath-meataxe/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
pkgs/sagemath-sirocco/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
pkgs/sagemath-tdlib/requirements.txt.m4:sagemath-standard==esyscmd(`printf $(sed "s/[.]p.*//;" ../sagelib/package-version.txt)')
```

2024-12-01 04:44 UTC, tobiasdiez commented
I think these requirements files can be safely deleted. At least I'm not aware of any usage of them.

2024-12-01 06:16 UTC, dimpase commented
> I think these requirements files can be safely deleted. At least I'm not aware of any usage of them.

these are for building all these sagemath-* pseudo-packages.

By the way, can you resolve the git conflict?

2024-12-01 08:00 UTC, tobiasdiez commented
> > I think these requirements files can be safely deleted. At least I'm not aware of any usage of them.
> 
> these are for building all these sagemath-* pseudo-packages.

You are right, these are actually used.

Does https://github.com/sagemath/sage/pull/39030/commits/ae33069c1a3d2bdf91da24b595d90c8a442f8e6d works for you? (I cannot test it atm on linux)

2024-12-01 17:19 UTC, dimpase commented
something in your branch broke the build system, with recursive make running wild. Not much fun to debug.

2024-12-01 18:38 UTC, dimpase commented
by the way, can this be based on the grayskull branch - this would make working a bit faster, as `bootstrap-conda` takes a nontrivial amount of time to run.

2024-12-01 19:35 UTC, dimpase commented
the recursion (I ran `make -d` in broken and in the non-broken environments, to compare) starts at
```
  Considering target file 'build/pkgs/saclib/package-version.txt'.
   Looking for an implicit rule for 'build/pkgs/saclib/package-version.txt'.
    Trying pattern rule '%::' with stem 'package-version.txt'.
   Found implicit rule '%::' for 'build/pkgs/saclib/package-version.txt'.
  Finished prerequisites of target file 'build/pkgs/saclib/package-version.txt'.
  No need to remake target 'build/pkgs/saclib/package-version.txt'.
  Considering target file 'build/pkgs/sage_conf/package-version.txt'.
   File 'build/pkgs/sage_conf/package-version.txt' does not exist.
   Looking for an implicit rule for 'build/pkgs/sage_conf/package-version.txt'.
    Trying pattern rule '%::' with stem 'package-version.txt'.
   Found implicit rule '%::' for 'build/pkgs/sage_conf/package-version.txt'.
  Finished prerequisites of target file 'build/pkgs/sage_conf/package-version.txt'.
  Must remake target 'build/pkgs/sage_conf/package-version.txt'.
make[1]: Entering directory '/mnt/opt/Sage/sage-dev'
Makefile:38: update target 'build/pkgs/sage_conf/package-version.txt' due to: target does not exist
if [ -x relocate-once.py ]; then ./relocate-once.py; fi
```

So the problem is that `build/pkgs/sage_conf/package-version.txt` is no longer there. I'll now try with `./configure --disable-sage_conf` to see if it makes a difference.

2024-12-01 19:48 UTC, dimpase commented
`--disable-sage_conf` has no effect. Has it ever worked? I see 
```
configure: WARNING: unrecognized options: --disable-sage_conf
```
in the output of ./configure.

2024-12-01 20:52 UTC, dimpase commented
your fix for VERSION.txt didn't work:
```
$ ls -l build/pkgs/sage_conf/
total 16
-rw-r--r-- 1 dima dima 167 Jan 26  2024 dependencies
lrwxrwxrwx 1 dima dima  12 Dec  1 12:17 package-version.txt -> 'VERSION.txt'$'\n'
...
```

2024-12-01 21:08 UTC, dimpase commented
To unblock this, one needs to fix

`build/pkgs/sage_*/package-version.txt` and `build/pkgs/sagemath_*/package-version.txt` - they should be links to `VERSION.txt`.
A failed attempt was make in this branch. Instead why not just 
```
cd build/pkgs/sage_conf
ln -sf  ../../../VERSION.txt package-version.txt
... etc
```
?

After these changes, `make` starts to run OK.

2024-12-02 05:04 UTC, dimpase commented
with changes as above, `./configure && make` ends with 
```
make --no-print-directory sagelib-SAGE_VENV-no-deps
[sagelib-10.5.rc2] Setting up build directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/sagelib-10.5.rc2
[sagelib-10.5.rc2] Host system: Linux hilbert 6.0.8-gentoo-x86_64 #2 SMP PREEMPT_DYNAMIC Sun Dec 18 22:31:12 GMT 2022 x86_64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz GenuineIntel GNU/Linux
[sagelib-10.5.rc2] C compiler: gcc, Using built-in specs., COLLECT_GCC=gcc, COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/14/lto-wrapper, Target: x86_64-pc-linux-gnu, Configured with: /var/tmp/portage/sys-devel/gcc-14.2.1_p20240817/work/gcc-14-20240817/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/14 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/14/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/14 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/14/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/14/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14 --disable-silent-rules --disable-dependency-tracking --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/14/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --disable-libunwind-exceptions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 14.2.1_p20240817 p4' --with-gcc-major-version-only --enable-libstdcxx-time --enable-lto --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --enable-cet --disable-systemtap --disable-valgrind-annotations --disable-vtable-verify --disable-libvtv --with-zstd --without-isl --enable-default-pie --enable-host-pie --enable-host-bind-now --enable-default-ssp --disable-fixincludes --with-build-config='bootstrap-O3 bootstrap-cet', Thread model: posix, Supported LTO compression algorithms: zlib zstd, gcc version 14.2.1 20240817 (Gentoo 14.2.1_p20240817 p4)
[sagelib-10.5.rc2] No stamp file for package 'sagelib' in /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/lib/sage/installed
[sagelib-10.5.rc2] No spkg-legacy-uninstall script; nothing to do
[sagelib-10.5.rc2] [spkg-install] Installing sagelib-10.5.rc2 (editable mode)
[sagelib-10.5.rc2] [spkg-install] Using pip 24.2 from /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/pip (python 3.12)
[sagelib-10.5.rc2] [spkg-install] Obtaining file:///mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp
[sagelib-10.5.rc2] [spkg-install] ERROR: file:///mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
[sagelib-10.5.rc2] [spkg-install] ***************************************************************************************************************************************************************************************************
[sagelib-10.5.rc2] [spkg-install] Error installing sagelib-10.5.rc2
[sagelib-10.5.rc2] [spkg-install] ***************************************************************************************************************************************************************************************************
```

the ERROR comes from `load_pyproject_toml()` in `local/var/lib/sage/venv-python3.12/lib64/python3.12/site-packages/pip/_internal/pyproject.py`, i.e. from `pip`.

Indeed, there is no `pyproject.toml` in `local/var/lib/sage/venv-python3.12/var/tmp` (and, needless to say, no `setup.py`)
The latter directory is set up by `extract_the_package()` from `build/bin/sage-spkg`, with `$PKG_SRC_TYPE` being `script` (sic!), and `$PKG_SRC` being `sagelib-10.5.rc2`. 

One way or another, `spkg-install` is not invoked from `build/pkgs/sagelib`, but rather from `local/var/lib/sage/venv-python3.12/var/tmp [etc]`, so `cd ../../../` in there does not bring us to the correct place, which is `$SAGE_ROOT`.

With 
```diff
--- a/build/pkgs/sagelib/spkg-install.in
+++ b/build/pkgs/sagelib/spkg-install.in
@@ -1,7 +1,7 @@
 if [ "$SAGE_EDITABLE" = yes ]; then
-    cd ../../..
+    cd $SAGE_ROOT
 else
-    cd ../../..
+    cd $SAGE_ROOT
     # Issue #34181: Do not allow scripts with shebang lines from old
     # venvs leak into new venvs. (Changes only seem to be necessary
     # for non-editable builds.)
```
one gets to `meson` being invoked for building. However, it ends with 
```
[sagelib-10.5.rc2] [spkg-install]   The Meson build system
[sagelib-10.5.rc2] [spkg-install]   Version: 1.5.1
[sagelib-10.5.rc2] [spkg-install]   Source dir: /mnt/opt/Sage/sage-dev
[sagelib-10.5.rc2] [spkg-install]   Build dir: /mnt/opt/Sage/sage-dev/build/cp312
[sagelib-10.5.rc2] [spkg-install]   Build type: native build
[sagelib-10.5.rc2] [spkg-install]   Project name: SageMath
[sagelib-10.5.rc2] [spkg-install]   Project version: 10.5.rc2
[sagelib-10.5.rc2] [spkg-install]   C compiler for the host machine: gcc (gcc 14.2.1 "gcc (Gentoo 14.2.1_p20240817 p4) 14.2.1 20240817")
[sagelib-10.5.rc2] [spkg-install]   C linker for the host machine: gcc ld.bfd 2.43
[sagelib-10.5.rc2] [spkg-install]   C++ compiler for the host machine: g++ -std=gnu++11 (gcc 14.2.1 "g++ (Gentoo 14.2.1_p20240817 p4) 14.2.1 20240817")
[sagelib-10.5.rc2] [spkg-install]   C++ linker for the host machine: g++ -std=gnu++11 ld.bfd 2.43
[sagelib-10.5.rc2] [spkg-install]   Cython compiler for the host machine: cython (cython 3.0.11)
[sagelib-10.5.rc2] [spkg-install]   Host machine cpu family: x86_64
[sagelib-10.5.rc2] [spkg-install]   Host machine cpu: x86_64
[sagelib-10.5.rc2] [spkg-install]   Program python found: YES (/mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3)
[sagelib-10.5.rc2] [spkg-install]   Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
[sagelib-10.5.rc2] [spkg-install]   Run-time dependency python found: YES 3.12
[sagelib-10.5.rc2] [spkg-install]   Program python (pytest) found: NO
[sagelib-10.5.rc2] [spkg-install] 
[sagelib-10.5.rc2] [spkg-install]   ../../src/meson.build:18:8: ERROR: Tried to form an absolute path to a dir in the source tree.
[sagelib-10.5.rc2] [spkg-install]   You should not do that but use relative paths instead, for
[sagelib-10.5.rc2] [spkg-install]   directories that are part of your project.
[sagelib-10.5.rc2] [spkg-install] 
```
where the log says
```
--- stderr ---


Running command: /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/bin/python3 -c 'import numpy
print(numpy.get_include())'
--- stdout ---
/mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/numpy/core/include

--- stderr --- 
```
So `meson` isn't happy about the full path here. Not sure what an easy fix is.

2024-12-02 05:06 UTC, dimpase commented
`--disable-sage_conf` issue mentioned above  is fixed in #39067

2024-12-02 05:35 UTC, dimpase commented
OK, please look at this meson weirdness. I don't quite know what's wrong there

2024-12-02 07:20 UTC, tobiasdiez commented
This should fix the issue about absolute vs relative imports. I only tested it in a local venv, not yet with make. 
Also the symlinks pointed to an absolute path on your system. I tried to correct this, hopefully without destroying the actual symlink (I'm currently on Windows only).

2024-12-02 15:32 UTC, dimpase commented
again symlinks going bad:
```
$ ls -l build/pkgs/sage_docbuild/package-version.txt 
lrwxrwxrwx 1 dima dima 21 Dec  2 08:54 build/pkgs/sage_docbuild/package-version.txt -> '../../../VERSION.txt'$'\n'
```

2024-12-02 17:53 UTC, dimpase commented
a way to identify numpy install is used, which does not set `inc_numpy` as it should.
```
Determining dependency 'numpy' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_NAME]: sagelib-10.5.rc2
env[PKG_BASE]: sagelib
env[PKG_VER]: 10.5.rc2
env[PKG_CONFIG_PATH]: /mnt/opt/Sage/sage-dev/local/lib/pkgconfig
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --modversion numpy` -> 1
stderr:
Package numpy was not found in the pkg-config search path.
Perhaps you should add the directory containing `numpy.pc'
to the PKG_CONFIG_PATH environment variable
Package 'numpy' not found
-----------
numpy-config binary missing from cross or native file, or env var undefined.
Trying a default numpy-config fallback at numpy-config
numpy-config found: YES (/usr/bin/numpy-config) 2.1.1
-----------
Called: `/usr/bin/numpy-config --cflags` -> 0
stdout:
-I/usr/lib/python3.12/site-packages/numpy/_core/include
-----------
Run-time dependency numpy found: YES 2.1.1
```
as a result I get  an error
```
../../src/sage/algebras/fusion_rings/meson.build:25:48: ERROR: Unknown variable "inc_numpy".
```

2024-12-03 03:25 UTC, dimpase commented
I think that to get sagelib built by meson, we need to move the top-level meson configuration from SAGE_ROOT to `src/`. This we won't be endlessly struggling with the requirement to use relative paths for anything that's not in `src/`, namely, all  dependencies.

Some dependencies can be coming either from a global environment, or built from the descriptions in `build/pkgs/`.
E.g. in the current setting such a triviality as  the include path for `numpy` (`inc_numpy`) is a struggle to get right, as  `local/`, `pkg/`, and `venv/` are parts of the meson project describing `sagelib`.

2024-12-03 08:50 UTC, tobiasdiez commented
According to the CI, it's now building nicely (on most systems) but there are quite a few doctest errors. I don't really see a pattern in the failures, do you?

2024-12-03 15:07 UTC, dimpase commented
after merging the updates, running "make" still gives
```
[sagelib-10.5.rc2] [spkg-install]   ../../src/sage/algebras/fusion_rings/meson.build:26:43: ERROR: Unknown variable "numpy".
```

Does meson keep a state somewhere? (I don't want to clean everything, and `make sagelib-clean sagelib-uninstall` doesn't help)

2024-12-03 15:20 UTC, dimpase commented
> According to the CI, it's now building nicely (on most systems) but there are quite a few doctest errors. I don't really see a pattern in the failures, do you?

I'm not at all sure it's relevant - are these docker containers used in tests built using meson? As for me building breaks very early one, I doubt this is the case.

2024-12-04 07:55 UTC, tobiasdiez commented
> after merging the updates, running "make" still gives
> 
> ```
> [sagelib-10.5.rc2] [spkg-install]   ../../src/sage/algebras/fusion_rings/meson.build:26:43: ERROR: Unknown variable "numpy".
> ```
> 
> Does meson keep a state somewhere? (I don't want to clean everything, and `make sagelib-clean sagelib-uninstall` doesn't help)

Sorry, another stupid typo / oversight. Should be fixed now.

> > According to the CI, it's now building nicely (on most systems) but there are quite a few doctest errors. I don't really see a pattern in the failures, do you?
> 
> I'm not at all sure it's relevant - are these docker containers used in tests built using meson? As for me building breaks very early one, I doubt this is the case.

I was wondering about this as well, but some of the "incremental" builds failed with exceptions that point to the meson build. So I assume that also the tests are run against the new meson build. But the failures might indeed coming from the fact that an old non-meson sagelib was/is installed in these docker images.

2024-12-04 17:53 UTC, dimpase commented
OK, what I get now is that the build runs, creates a wheel for sagemath-10.5, and then errors out trying to install it.
See the log attached (maybe we need to move sagetex to meson or whatever, too). The 2nd run of make finishes without an error, but Sage won't start. (full log attached too)
```
...
[sagelib-10.5] [spkg-install]   Cleaning... 0 files.
[sagelib-10.5] [spkg-install]   + /usr/bin/ninja
[sagelib-10.5] [spkg-install]   ninja: no work to do.
[sagelib-10.5] [spkg-install]   Preparing editable metadata (pyproject.toml): finished with status 'done'
[sagelib-10.5] [spkg-install] Building wheels for collected packages: sagemath
[sagelib-10.5] [spkg-install]   Building editable for sagemath (pyproject.toml): started
[sagelib-10.5] [spkg-install]   Running command Building editable for sagemath (pyproject.toml)
[sagelib-10.5] [spkg-install]   Building editable for sagemath (pyproject.toml): finished with status 'done'
[sagelib-10.5] [spkg-install]   Created wheel for sagemath: filename=sagemath-10.5-cp312-cp312-linux_x86_64.whl size=16620 sha256=694af9305c9ff46cecb6b837562bb9b759efa8bfba96d80ab637c6fe1a435332
[sagelib-10.5] [spkg-install]   Stored in directory: /tmp/pip-ephem-wheel-cache-w3obalmi/wheels/ea/5f/42/d0c1d5b0ce3e5bc0130230e94f7836497cbcc4633934712608
[sagelib-10.5] [spkg-install] Successfully built sagemath
[sagelib-10.5] [spkg-install] Installing collected packages: sagemath
[sagelib-10.5] [spkg-install]   Attempting uninstall: sagemath
[sagelib-10.5] [spkg-install]     Found existing installation: sagemath 10.5
[sagelib-10.5] [spkg-install]     Uninstalling sagemath-10.5:
[sagelib-10.5] [spkg-install]       Removing file or directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/__pycache__/_sagemath_editable_loader.cpython-312.pyc
[sagelib-10.5] [spkg-install]       Removing file or directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/_sagemath_editable_loader.py
[sagelib-10.5] [spkg-install]       Removing file or directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/sagemath-10.5.dist-info/
[sagelib-10.5] [spkg-install]       Removing file or directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/sagemath-editable.pth
[sagelib-10.5] [spkg-install]       Successfully uninstalled sagemath-10.5
[sagelib-10.5] [spkg-install] Successfully installed sagemath-10.5
[sagelib-10.5] Moving package files from temporary location /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/sagelib-10.5/inst to /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12
[sagelib-10.5] Deleting build directory /mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/sagelib-10.5
[sagelib-10.5] Finished installing sagelib-10.5
[sagelib-10.5] real 0m9.964s user 0m8.074s sys 0m1.765s
make[2]: Leaving directory '/mnt/opt/Sage/sage-dev/build/make'
Sage build/upgrade complete!
real 0m10.899s user 0m8.889s sys 0m1.918s
make[1]: Leaving directory '/mnt/opt/Sage/sage-dev'
dima@hilbert /mnt/opt/Sage/sage-dev $ ./sage
************************************************************************
It seems that you are attempting to run Sage from an unpacked source
tarball, but you have not compiled it yet (or maybe the build has not
finished). You should run `make` in the SAGE_ROOT directory first.
If you did not intend to build Sage from source, you should download
a binary tarball instead. Read README.txt for more information.
************************************************************************
```
[install.0.log](https://github.com/user-attachments/files/18012277/install.0.log)

[install.log](https://github.com/user-attachments/files/18012274/install.log)

2024-12-05 02:25 UTC, tobiasdiez commented
The sagetex error seems to be unrelated:
```
[sagetex-3.6.1] [spkg-install] Installing sagetex-3.6.1
[sagetex-3.6.1] [spkg-install] * Creating isolated environment: venv+pip...
[sagetex-3.6.1] [spkg-install] < ModuleNotFoundError: No module named 'certifi'
[sagetex-3.6.1] [spkg-install] Retrying with "python3 -m build --wheel --outdir=dist --no-isolation --skip-dependency-check  .".
[sagetex-3.6.1] [spkg-install] * Building wheel...
[sagetex-3.6.1] [spkg-install] Successfully built sagetex-3.6.1-py3-none-any.whl
[sagetex-3.6.1] [spkg-pipinst] Successfully installed sagetex-3.6.1
```
Probably just needs `certifi` to be added in https://github.com/sagemath/sagetex/blob/f9f1ba62c9aa5b3a22f7ac2b5c583df749594cd3/setup.py#L16.

2024-12-05 02:29 UTC, tobiasdiez commented
For the startup error:
```
# Check that we're not in a source tarball which hasn't been built yet (#13561).
    if [ "$SAGE_SRC_ENV_CONFIG" = 1 ] && [ ! -z "$SAGE_VENV" ] && [ ! -x "$SAGE_VENV/bin/sage" ]; then
        echo >&2 '************************************************************************'
        echo >&2 'It seems that you are attempting to run Sage from an unpacked source'
        echo >&2 'tarball, but you have not compiled it yet (or maybe the build has not'
        echo >&2 'finished). You should run `make` in the SAGE_ROOT directory first.'
        echo >&2 'If you did not intend to build Sage from source, you should download'
        echo >&2 'a binary tarball instead. Read README.txt for more information.'
        echo >&2 '************************************************************************'
        exit 1
    fi
```

Maybe `SAGE_VENV` is not set properly when using meson? No idea...

2024-12-05 02:55 UTC, dimpase commented
Sage venv can only be characterised as a totally overdesigned steampunk. 
![IMG_20241114_222407.jpg](https://github.com/user-attachments/assets/e9c0e624-d3f4-4ac9-8855-0b156b4566c7)

2024-12-05 04:04 UTC, dimpase commented
I see, it's another bug in handling `--disable-sage_conf` option (I ran `./configure` with this option`). After something like
```diff
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -289,7 +289,7 @@ fi
 # Prepare for running Sage, either interactively or non-interactively.
 sage_setup() {
     # Check that we're not in a source tarball which hasn't been built yet (#13561).
-    if [ "$SAGE_SRC_ENV_CONFIG" = 1 ] && [ ! -z "$SAGE_VENV" ] && [ ! -x "$SAGE_VENV/bin/sage" ]; then
+    if [ "$SAGE_SRC_ENV_CONFIG" = 0 ] && [ ! -z "$SAGE_VENV" ] && [ ! -x "$SAGE_VENV/bin/sage" ]; then
         echo >&2 '************************************************************************'
         echo >&2 'It seems that you are attempting to run Sage from an unpacked source'
         echo >&2 'tarball, but you have not compiled it yet (or maybe the build has not'
 ```
`./sage` starts just fine.

2024-12-05 17:14 UTC, dimpase commented
let me upload the results of the tests run (and config.log) 
here - with the manual fix for non-starting Sage. Most of the errors seem to be cython not finding the headers.
config.log is a bit weird, there is a lot of copying stuff around there.

[test.log](https://github.com/user-attachments/files/18027119/test.log)
[config.log](https://github.com/user-attachments/files/18027132/config.log)

2024-12-06 08:55 UTC, tobiasdiez commented
The copying comes from the lines around [SAGE_PYTHON_DISTUTILS_C_CONFTEST](https://github.com/sagemath/sage/blob/8ee1c4a9cf683dbe7efe80828592959aaa1baa31/m4/sage_check_python_for_venv.m4#L87). For some reason the temporary conftest is a placed in a directory where `src` is present as well (probably via a symlink). As the standard directory for source files, `src` is then picked up and its content is copied over.
```
CC=gcc CXX=g++ -std=gnu++11 conftest_venv/bin/python3 conftest.py --verbose build --build-base=conftest.dir
No `packages` or `py_modules` configuration, performing automatic discovery.
`src-layout` detected -- analysing ./src
```
I tried to fix it (untested).

The cython error seems to come from a problem in
https://github.com/sagemath/sage/blob/56f95c9d568fc6fcfc95cb38ca50de21ce9166ab/src/sage/env.py#L324-L327

I would assume if you fix the failing test for this function, then the other cython tests should pass as well. I'm not totally sure but my guess would be adding the directory returned by `importlib.util.find_spec("sage")` to `dirs` there should work (and probably make the distinction between `use_sources=true/false` obsolete.

2024-12-08 05:04 UTC, dimpase commented
> ```diff
> SAGE_SRC_ENV_CONFIG
> ```

Actually, the problem is in `$SAGE_VENV/bin/sage` not existing after the meson build is done. So one way would be to
just `touch $SAGE_VENV/bin/sage` at the end of the build. Done in [48c8b4a](https://github.com/sagemath/sage/pull/39030/commits/48c8b4afae10b2b105e44b4e891b59dd588b4c05)

2024-12-08 05:15 UTC, dimpase commented
> Sage venv can only be characterised as a totally overdesigned steampunk.

that's from our basement here, in fact. The thing on the right leaked, and took 5 days and $12K to fix.

2024-12-08 05:26 UTC, dimpase commented
> The copying comes from the lines around [SAGE_PYTHON_DISTUTILS_C_CONFTEST](https://github.com/sagemath/sage/blob/8ee1c4a9cf683dbe7efe80828592959aaa1baa31/m4/sage_check_python_for_venv.m4#L87). For some reason the temporary conftest is a placed in a directory where `src` is present as well (probably via a symlink). As the standard directory for source files, `src` is then picked up and its content is copied over.
> 
> ```
> CC=gcc CXX=g++ -std=gnu++11 conftest_venv/bin/python3 conftest.py --verbose build --build-base=conftest.dir
> No `packages` or `py_modules` configuration, performing automatic discovery.
> `src-layout` detected -- analysing ./src
> ```
> 
> I tried to fix it (untested).
> 
> The cython error seems to come from a problem in
> 
> https://github.com/sagemath/sage/blob/56f95c9d568fc6fcfc95cb38ca50de21ce9166ab/src/sage/env.py#L324-L327
> 
> I would assume if you fix the failing test for this function, then the other cython tests should pass as well. I'm not totally sure but my guess would be adding the directory returned by `importlib.util.find_spec("sage")` to `dirs` there should work.

Doesn't seem to be any different from `sage.__path__`:
```
sage: importlib.util.find_spec("sage")
ModuleSpec(name='sage', loader=<_frozen_importlib_external.NamespaceLoader object at 0x7f5ddc461220>, submodule_search_locations=['/mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/_sagemath_editable_loader.py/sage'])
sage: 
sage: sage.__path__
['/mnt/opt/Sage/sage-dev/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/_sagemath_editable_loader.py/sage']
```

I'm attaching the new config.log, doesn't seem to make a difference.
[config.log](https://github.com/user-attachments/files/18050870/config.log)

2024-12-10 01:58 UTC, dimpase commented
looks like my rebase didn't fly. I'll do a merge and post update

2024-12-10 19:34 UTC, dimpase commented
This test fails - but actually I don't know its purpose:
```
File "src/sage/misc/cython.py", line 232, in sage.misc.cython.?
Failed example:
    cython('''
    from sage.misc cimport cachefunc
    ''')
Expected:
    Traceback (most recent call last):
    ...
    RuntimeError: Error compiling Cython file:
    ...
    ...: 'sage/misc.pxd' not found
Got:
    <BLANKLINE>
```
with the current fix - adding SAGE_SRC to the list of directories to search for Cython headers - it just works.

SAGE_SRC isn't quite right in some cases, e.g. for a setup where Sage is installed from a package manager.
Can @orlitzky @antonio-rojas @tornaria comment?

2024-12-10 20:54 UTC, dimpase commented
targets `sagelib-clean` and `fast-rebuild-clean` in the top-level `Makefile` refer to `build/pkgs/sagelib/src/` and should be fixed or removed.

2024-12-11 05:28 UTC, tobiasdiez commented
The difference comes from the fact that cython doesn't fully work with PEP 420 implicit namespace packages (essentially the test is recording this fact). However, when we use meson to build sagelib, then `__init__` files are created during build so that `sage.misc` is no longer an implicit namespace package. Hence the compilation in this example actually works.

Can we check in the test if `sage/misc/__init__.py` exists and then change the expected output according to it?

2024-12-11 13:26 UTC, tornaria commented
Some quick comments:
 - I think the test is reasonably explained there; since `sage.misc` is a PEP 420 "namespace package" (i.e. no `__init__.py`) using `from <PACKAGE> cimport <MODULE>` does not work (shortcoming of cython, it's not fixed in cython 3).
 - Please do not add random directories to search paths. Sometimes it might seem to fix something, but in the end it often ends up biting back and causing pain.
 - For similar reasons, I think `sage.misc` should either be a namespace package, or else be a regular namespace. Making different choices on different build systems seems a bad idea to me, since there are subtle differences in behavior (as we can see here).

2024-12-11 14:04 UTC, dimpase commented
meson is meant to become the only system to build sagelib, as far as I am concerned. Transition is not straightforward, though.

2024-12-11 14:07 UTC, dimpase commented
@tornaria - my question was: how do you set paths to sagelib Cython header files on Void, say. I imagine you keep a full source directory somewhere, but where? How can it be customised?

2024-12-11 21:49 UTC, dimpase commented
> Can we guard the test be the absence of `sage/misc/__init__.py`?

I don't think this is easily doable in our current doctest framework. Unless, perhaps, pytest gets used.

2024-12-13 02:42 UTC, orlitzky commented
Why keep this test at all?

```python
"""
    In Cython 0.29.33 using `from PACKAGE cimport MODULE` is broken            
    when `PACKAGE` is a namespace package, see :issue:`35322`::                
                                                                               
        sage: cython('''                                                       
        ....: from sage.misc cimport cachefunc                                 
        ....: ''')                                                             
        Traceback (most recent call last):                                     
        ...                                                                    
        RuntimeError: Error compiling Cython file:                             
        ...                                                                    
        ...: 'sage/misc.pxd' not found
"""
```

If the test fails, than it's no longer broken: great! Meson solved the problem.

2024-12-13 02:47 UTC, orlitzky commented
> with the current fix - adding SAGE_SRC to the list of directories to search for Cython headers (see the change in `src/sage/misc/cython.py`) - it just works.
> 
> SAGE_SRC isn't quite right in some cases, e.g. for a setup where Sage is installed from a package manager. Can @orlitzky @antonio-rojas @tornaria comment?

I'm far from an expert on this. For the pxd files, things usually just work if they're installed next to the pyx files? For the `*.h` files, the last time I needed to do this, I copied Tobias's solution of importing the corresponding module and using `__file__`.

2024-12-13 15:41 UTC, dimpase commented
> > with the current fix - adding SAGE_SRC to the list of directories to search for Cython headers (see the change in `src/sage/misc/cython.py`) - it just works.
> > SAGE_SRC isn't quite right in some cases, e.g. for a setup where Sage is installed from a package manager. Can @orlitzky @antonio-rojas @tornaria comment?
> 
> I'm far from an expert on this. For the pxd files, things usually just work if they're installed next to the pyx files? For the `*.h` files, the last time I needed to do this, I copied Tobias's solution of importing the corresponding module and using `__file__`.

Sage's `.pxd` files (aka Cython headers) are akin to the usual `.h` etc headers, in the situation where Sage is installed system-wide. If a user writes Cython code using Sage's system-wide headers, asking them to copy these over looks a bit unclean to me. So there ought to be a solution to this, and in such a case `SAGE_SRC` might not be appropriate to use.

2024-12-13 15:49 UTC, dimpase commented
> If the test fails, then it's no longer broken: great! Meson solved the problem.

OK, "plonk" it  goes then. [e1167ee](https://github.com/sagemath/sage/pull/39030/commits/e1167ee7eb79a959d003b54329b34571568ce586)

2024-12-13 20:59 UTC, orlitzky commented
> Sage's `.pxd` files (aka Cython headers) are akin to the usual `.h` etc headers, in the situation where Sage is installed system-wide. If a user writes Cython code using Sage's system-wide headers, asking them to copy these over looks a bit unclean to me. So there ought to be a solution to this, and in such a case `SAGE_SRC` might not be appropriate to use.

I think that there are two related problems here. The first is the pxd files, which are needed to `cimport` stuff from other cython programs, and the problem is that cython will look for the pxd file in the wrong place unless there is an `__init__.py`. For example,

```
sage: cython('''from sage.misc.cachefunc cimport cachefunc''')
...
_tmp_tmp7m7cufjo_tmp_cl1obc0v_pyx_0.pyx:1:0: 'sage/misc/cachefunc/cachefunc.pxd' not found
```

should be looking for `sage/misc/cachefunc.pxd` instead. If I touch `sage/misc/__init__.py`, this error goes away. So I think we are waiting for cython to fix this. In the meantime, should we install `__init__.py`? (Is anyone using the modularized distributions?)

The other issue is the `*.h` files. If you write an external cython module that builds against sage, you will find that the cythonized (i.e. C) code expects to find headers like  `sage/cpython/cython_metaclass.h`, which won't be installed in the C compiler's include path. I don't really know how this is supposed to work, but Tobias's solution seems good enough if your external module has a build system. I do not know if it is possible to trick e.g. `cythonize()` into needing these headers.

2024-12-13 21:27 UTC, dimpase commented
> Is anyone using the modularized distributions?

in my book they are basically abandonware.

2024-12-14 00:02 UTC, orlitzky commented
> > Is anyone using the modularized distributions?
> 
> in my book they are basically abandonware.

Well, meson generates the necessary `__init__.py` already. All we need to do is install them, probably by adding them to `py.install_sources(...)`.

2024-12-16 04:07 UTC, tobiasdiez commented
> > > Is anyone using the modularized distributions?
> > 
> > 
> > in my book they are basically abandonware.
> 
> Well, meson generates the necessary `__init__.py` already. All we need to do is install them, probably by adding them to `py.install_sources(...)`.

This is now https://github.com/sagemath/sage/pull/39139

2024-12-16 23:35 UTC, dimpase commented
This needs more work on macOS, where different C++ interfaces need different options, e.g. linbox needs `std=gnu++11`
(due to std::binary_function used) and similarly with giac (using pointer_to_binary_function, also removed in c++17)

2025-06-24 22:28 UTC, tobiasdiez commented
Tests are passing (the failing CI runs are due to unrelated issues), so this is now ready for review.

2025-06-27 01:58 UTC, dimpase commented
I have issues with a local build on macOS; they seem to come from the C++ compiler being configured differently (or lack of `-std=gnu++14` or something like this) 

* one needed change is #40133
* as well, m4rie needs to be C++17-compliant (it's currently not); I opened  https://github.com/malb/m4rie/pull/5 upstream

2025-06-27 02:07 UTC, dimpase commented
another, platform independent thing - one needs to correctly deal with `make sagelib-clean sagelib-uninstall` - these should do `meson setup --wipe...`, right?

2025-06-27 04:48 UTC, dimpase commented
another small issue is that `-j` parameter of `make -j 42 test` leaks into the `ninja` parameters, causing doctest errors like
```
File "src/sage/misc/sagedoc.py", line 32, in sage.misc.sagedoc
Failed example:
    os.system("sage -c \"if 'sphinx' in sys.modules: sys.exit(1)\"")
Expected:
    0
Got:
    ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=-p TEST_TARGET=ptest]
    0
```
as `ninja` doesn't support `-j`.

2025-06-27 17:37 UTC, dimpase commented
The m4rie C++ trouble could be of our own making - there is no apparent reason for m4ri and m4rie extensions to built with a C++ compiler.
Does meson get the extension language for a Cython extension from the `#distutils:` directives?

2025-06-27 22:04 UTC, tobiasdiez commented
> I have issues with a local build on macOS; they seem to come from the C++ compiler being configured differently (or lack of -std=gnu++14 or something like this) ..
> The m4rie C++ trouble could be of our own making - there is no apparent reason for m4ri and m4rie extensions to built with a C++ compiler. Does meson get the extension language for a Cython extension from the `#distutils:` directives?

Do you get these error really while building the brial/m4rie package, or while build sagelib? In the later case:
- We could try to compile the cython extensions with c instead of c++ (e.g. move `matrix_gf2e_dense` in `src/sage/matrix/meson.build` to `extension_data` from `extension_data_cpp`)
- Specify `cpp_args: '-std=c++11',` in the meson config for the relevant files (cf `src/sage/symbolic/meson.build`)

2025-06-27 22:06 UTC, tobiasdiez commented
> another, platform independent thing - one needs to correctly deal with `make sagelib-clean sagelib-uninstall` - these should do `meson setup --wipe...`, right?

What's the difference between clean and uninstall? Based on the naming, `--wipe` is indeed a good option for `clean` while uninstall should just call `pip uninstall`.

2025-06-27 22:08 UTC, tobiasdiez commented
> another small issue is that `-j` parameter of `make -j 42 test` leaks into the `ninja` parameters, causing doctest errors like
> I actually don't understand why tests are run with `ninja`, and not `make`.

What happens is probably: make calls `sage -t`, which calls meson-python/ninja to check if some cython files changed that need to be recompiled. Is there a way to have `make -j` pass the jobs only to `sage -t` without setting any env variables?

2025-06-28 02:47 UTC, dimpase commented
> > I have issues with a local build on macOS; they seem to come from the C++ compiler being configured differently (or lack of -std=gnu++14 or something like this) ..
> > The m4rie C++ trouble could be of our own making - there is no apparent reason for m4ri and m4rie extensions to built with a C++ compiler. Does meson get the extension language for a Cython extension from the `#distutils:` directives?
> 
> Do you get these error really while building the brial/m4rie package, or while build sagelib? In the later case:

when building sagelib.

> - We could try to compile the cython extensions with c instead of c++ (e.g. move `matrix_gf2e_dense` in `src/sage/matrix/meson.build` to `extension_data` from `extension_data_cpp`)

Oh, ok, so this explains why it's built with C++, thanks.
As far as I understand, there is no need to build this extension with C++.

2025-06-28 02:48 UTC, dimpase commented
> > another, platform independent thing - one needs to correctly deal with `make sagelib-clean sagelib-uninstall` - these should do `meson setup --wipe...`, right?
> 
> What's the difference between clean and uninstall? Based on the naming, `--wipe` is indeed a good option for `clean` while uninstall should just call `pip uninstall`.

yes, uninstall only makes sense for python spkgs.

2025-06-28 12:05 UTC, tobiasdiez commented
Thanks! These issues should be fixed now. But CI still fails with
```
2025-06-28T11:46:14.9728370Z   [sagelib-10.7.beta7]   [spkg-install]   FAILED: [code=1] src/sage/libs/eclib/mwrank.cpython-313-darwin.so
2025-06-28T11:46:14.9730650Z   [sagelib-10.7.beta7]   [spkg-install]   g++ -std=gnu++11 -std=gnu++11  -o src/sage/libs/eclib/mwrank.cpython-313-darwin.so src/sage/libs/eclib/mwrank.cpython-313-darwin.so.p/meson-generated_src_sage_libs_eclib_mwrank.pyx.cpp.o -L/Users/runner/work/sage/sage/.tox/local-homebrew-macos-opthomebrew-standard/local/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-ld_classic -g -O2 -Wl,-rpath,@loader_path/../../../../../../.tox/local-homebrew-macos-opthomebrew-standard/local/lib -Wl,-rpath,/opt/homebrew/Cellar/mpfr/4.2.2/lib -Wl,-rpath,/opt/homebrew/Cellar/gmp/6.3.0/lib -lec -lecl /Users/runner/work/sage/sage/.tox/local-homebrew-macos-opthomebrew-standard/local/lib/libflint.dylib /opt/homebrew/Cellar/mpfr/4.2.2/lib/libmpfr.dylib /opt/homebrew/Cellar/gmp/6.3.0/lib/libgmp.dylib
2025-06-28T11:46:14.9731130Z   [sagelib-10.7.beta7]   [spkg-install]   ld: illegal thread local variable reference to regular symbol __ZN3NTL2RR4precE for architecture arm64
2025-06-28T11:46:14.9731400Z   [sagelib-10.7.beta7]   [spkg-install]   clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
on macos. Is this a problem with the homebrew ntl?

2025-06-28 18:07 UTC, dimpase commented
> > another, platform independent thing - one needs to correctly deal with `make sagelib-clean sagelib-uninstall` - these should do `meson setup --wipe...`, right?
> 
> What's the difference between clean and uninstall? Based on the naming, `--wipe` is indeed a good option for `clean` while uninstall should just call `pip uninstall`.

I have a working meson build of sagelib, and if I try `--wipe`, I get the following error:
```
% meson setup --wipe build/cp313 
Could not find any valid candidate for native files: /Volumes/dima/sage/build/cp313/meson-python-native-file.ini

ERROR: Cannot find specified native file: /Volumes/dima/sage/build/cp313/meson-python-native-file.ini
```
and the file it claims it cannot find was there!

2025-06-28 21:20 UTC, tobiasdiez commented
Sorry, no idea about this problem and cannot really find it upstream https://github.com/search?q=%22Cannot+find+specified+native+file%22+org%3Amesonbuild+&type=issues Perhaps updating meson works?

2025-06-29 04:09 UTC, dimpase commented
> Sorry, no idea about this problem and cannot really find it upstream https://github.com/search?q=%22Cannot+find+specified+native+file%22+org%3Amesonbuild+&type=issues Perhaps updating meson works?

this is with meson 1.8.2 (Sage still distributes 1.7.0 - should it be bumped ?)

2025-06-29 04:21 UTC, dimpase commented
[1c119e8](https://github.com/sagemath/sage/pull/39030/commits/1c119e88d565dc2f1192744bc73ea6fde3485ea6) - there is no reason for this extension to be built as C++ one! 
The following works for me:
```
diff --git a/src/sage/libs/m4ri.pxd b/src/sage/libs/m4ri.pxd
index 1306b72a74c..01526183972 100644
--- a/src/sage/libs/m4ri.pxd
+++ b/src/sage/libs/m4ri.pxd
@@ -1,6 +1,3 @@
-# distutils: extra_compile_args = -std=c++11
-# distutils: language = c++
-
 cdef extern from "m4ri/m4ri.h":
     ctypedef int rci_t
     ctypedef int wi_t
diff --git a/src/sage/matrix/meson.build b/src/sage/matrix/meson.build
index ead32fdfae9..f2bce0588d3 100644
--- a/src/sage/matrix/meson.build
+++ b/src/sage/matrix/meson.build
@@ -78,6 +78,7 @@ extension_data = {
   'matrix_generic_dense' : files('matrix_generic_dense.pyx'),
   'matrix_generic_sparse' : files('matrix_generic_sparse.pyx'),
   'matrix_gfpn_dense' : files('matrix_gfpn_dense.pyx'),
+  'matrix_gf2e_dense': files('matrix_gf2e_dense.pyx'),
   'matrix_laurent_mpolynomial_dense' : files(
     'matrix_laurent_mpolynomial_dense.pyx',
   ),
@@ -129,7 +130,6 @@ endforeach
 
 extension_data_cpp = {
   'matrix_cyclo_dense': files('matrix_cyclo_dense.pyx'),
-  'matrix_gf2e_dense': files('matrix_gf2e_dense.pyx'),
   'matrix_integer_dense': files('matrix_integer_dense.pyx'),
   'matrix_integer_sparse': files('matrix_integer_sparse.pyx'),
   'matrix_mod2_dense': files('matrix_mod2_dense.pyx'),
```

I think these `#distutils` (and thus you copying these settings in meson) were added in 731ff530491a without any proper reason, just in haste to fix `extra_compile_args = -std=c99` (which was a C setting, using obsolete C standard for with old m4ri, I guess)

2025-06-29 12:34 UTC, tobiasdiez commented
Okay, I've applied this now and it indeed works. Thanks! Anything else that needs work?

2025-06-29 20:02 UTC, dimpase commented
> Okay, I've applied this now and it indeed works. Thanks! Anything else that needs work?

let me try a local build on Linux - I'm still worried that `meson setup --wipe` does not work properly.

2025-06-30 01:20 UTC, dimpase commented
I'm getting a problem building sagelib interface to cypari
```
[sagelib-10.7.beta7] [spkg-install]   [54/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_ZZ_pX.pyx
[sagelib-10.7.beta7] [spkg-install]   [55/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_GF2EX.pyx
[sagelib-10.7.beta7] [spkg-install]   [56/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pyx
[sagelib-10.7.beta7] [spkg-install]   FAILED: src/sage/libs/pari/convert_flint.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_flint.pyx.c
[sagelib-10.7.beta7] [spkg-install]   cython -M --fast-fail -3 -I /home/dima/software/sage-src/src -I /home/dima/software/sage-src/build/cp313/src '-X auto_pickle=False' '-X autotestdict=False' '-X binding=False' '-X c_api_binop_methods=True' '-X cdivision=True' '-X cpow=True' '-X embedsignature=True' --embed-positions '-X fast_getattr=True' '-X legacy_implicit_noexcept=True' '-X preliminary_late_includes_cy28=True' /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pyx -o src/sage/libs/pari/convert_flint.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_flint.pyx.c
[sagelib-10.7.beta7] [spkg-install] 
[sagelib-10.7.beta7] [spkg-install]   Error compiling Cython file:
[sagelib-10.7.beta7] [spkg-install]   ------------------------------------------------------------
[sagelib-10.7.beta7] [spkg-install]   ...
[sagelib-10.7.beta7] [spkg-install]   from cypari2.types cimport GEN
[sagelib-10.7.beta7] [spkg-install]   ^
[sagelib-10.7.beta7] [spkg-install]   ------------------------------------------------------------
[sagelib-10.7.beta7] [spkg-install] 
[sagelib-10.7.beta7] [spkg-install]   /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pxd:1:0: 'cypari2/types.pxd' not found
[sagelib-10.7.beta7] [spkg-install]   [57/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_lzz_pX.pyx
[sagelib-10.7.beta7] [spkg-install]   [58/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_mat_GF2E.pyx
[sagelib-10.7.beta7] [spkg-install]   [59/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/pari/convert_gmp.pyx
[sagelib-10.7.beta7] [spkg-install]   FAILED: src/sage/libs/pari/convert_gmp.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_gmp.pyx.c
```

somehow meson cannot find `./local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/cypari2/types.pxd`which is certainly there.

This with pari from the system, and cypari2 built by Sage.
cython came from the system. If I install cypari2 system-wide, then this problem goes away.

2025-07-01 02:40 UTC, dimpase commented
and another problem is with system-wide sphinx installation - perhaps sphinx 8.2.3 is too new?
```
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Extension error (sage_docbuild.conf)!
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Versions
[sagemath_doc_html-none] [spkg-install] [tensor_fr] ========
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Platform:         linux; (Linux-6.13.4-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_Ultra_7_165U-with-glibc2.41)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Python version:   3.13.3 (CPython)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Sphinx version:   8.2.3
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Docutils version: 0.21.2
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Jinja2 version:   3.1.6
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * Pygments version: 2.19.1
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Last Messages
[sagemath_doc_html-none] [spkg-install] [tensor_fr] =============
[sagemath_doc_html-none] [spkg-install] [tensor_fr]     index
[sagemath_doc_html-none] [spkg-install] [tensor_fr]     morphisms
[sagemath_doc_html-none] [spkg-install] [tensor_fr]     sage/tensor/modules/alternating_contr_tensor
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Loaded Extensions
[sagemath_doc_html-none] [spkg-install] [tensor_fr] =================
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.mathjax (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * alabaster (1.0.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.applehelp (2.0.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.devhelp (2.0.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.htmlhelp (2.1.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.serializinghtml (2.0.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.qthelp (2.0.0)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.inventory_builder (unknown version)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.multidocs (unknown version)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.preserve_defaults (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.type_comment (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.typehints (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.sage_autodoc (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.todo (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.extlinks (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.linkcode (8.2.3)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx_copybutton (0.5.2)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx_inline_tabs (2023.04.21)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * IPython.sphinxext.ipython_directive (unknown version)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] * matplotlib.sphinxext.plot_directive (3.10.1)
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Traceback
[sagemath_doc_html-none] [spkg-install] [tensor_fr] =========
[sagemath_doc_html-none] [spkg-install] [tensor_fr]       File "/usr/lib/python3.13/site-packages/sphinx/events.py", line 415, in emit
[sagemath_doc_html-none] [spkg-install] [tensor_fr]         raise ExtensionError(
[sagemath_doc_html-none] [spkg-install] [tensor_fr]         ...<4 lines>...
[sagemath_doc_html-none] [spkg-install] [tensor_fr]         ) from exc
[sagemath_doc_html-none] [spkg-install] [tensor_fr]     sphinx.errors.ExtensionError: Handler <function find_sage_dangling_links at 0x7fa6111dd120> for event 'missing-reference' threw an exception (exception: No such config value: 'intersphinx_resolve_self')
[sagemath_doc_html-none] [spkg-install] [tensor_fr] The full traceback has been saved in:
[sagemath_doc_html-none] [spkg-install] [tensor_fr] /tmp/sphinx-err-14qkvtd8.log
[sagemath_doc_html-none] [spkg-install] [tensor_fr] To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
[sagemath_doc_html-none] [spkg-install] [tensor_fr] Please also report this if it was a user error, so that a better error message can be provided next time.
```
(and lots more of these `No such config value: 'intersphinx_resolve_self'`)

2025-07-01 03:09 UTC, dimpase commented
Also on Linux I get this weirdness with `meson setup --wipe`
```
dima@tarski ~/software/sage-src $ ls -l build/cp313/
total 2944
-rw-r--r-- 1 dima dima 1602600 Jun 30 21:49 build.ninja
-rw-r--r-- 1 dima dima 1393485 Jun 30 21:49 compile_commands.json
drwxr-xr-x 2 dima dima    4096 Jun 30 21:49 meson-info
drwxr-xr-x 2 dima dima      27 Jun 29 18:16 meson-logs
drwxr-xr-x 5 dima dima    4096 Jun 30 21:49 meson-private
-rw-r--r-- 1 dima dima      99 Jun 30 21:49 meson-python-native-file.ini
drwxr-xr-x 3 dima dima      18 Jun 29 18:16 src
dima@tarski ~/software/sage-src $ meson setup --wipe build/cp313/
Could not find any valid candidate for native files: /home/dima/software/sage-src/build/cp313/meson-python-native-file.ini

ERROR: Cannot find specified native file: /home/dima/software/sage-src/build/cp313/meson-python-native-file.ini
dima@tarski ~/software/sage-src $ ls -l build/cp313/
total 0
drwxr-xr-x 2 dima dima  6 Jun 30 22:06 meson-info
drwxr-xr-x 2 dima dima  6 Jun 30 22:06 meson-logs
drwxr-xr-x 2 dima dima 26 Jun 30 22:06 meson-private
```

looks as if it first removes `meson-python-native-file.ini` and then complains it cannot find it.
This is meson 1.8.1

2025-07-01 11:39 UTC, tobiasdiez commented
> I'm getting a problem building sagelib interface to cypari
> 
> ```
> [sagelib-10.7.beta7] [spkg-install]   [54/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_ZZ_pX.pyx
> [sagelib-10.7.beta7] [spkg-install]   [55/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_GF2EX.pyx
> [sagelib-10.7.beta7] [spkg-install]   [56/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pyx
> [sagelib-10.7.beta7] [spkg-install]   FAILED: src/sage/libs/pari/convert_flint.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_flint.pyx.c
> [sagelib-10.7.beta7] [spkg-install]   cython -M --fast-fail -3 -I /home/dima/software/sage-src/src -I /home/dima/software/sage-src/build/cp313/src '-X auto_pickle=False' '-X autotestdict=False' '-X binding=False' '-X c_api_binop_methods=True' '-X cdivision=True' '-X cpow=True' '-X embedsignature=True' --embed-positions '-X fast_getattr=True' '-X legacy_implicit_noexcept=True' '-X preliminary_late_includes_cy28=True' /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pyx -o src/sage/libs/pari/convert_flint.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_flint.pyx.c
> [sagelib-10.7.beta7] [spkg-install] 
> [sagelib-10.7.beta7] [spkg-install]   Error compiling Cython file:
> [sagelib-10.7.beta7] [spkg-install]   ------------------------------------------------------------
> [sagelib-10.7.beta7] [spkg-install]   ...
> [sagelib-10.7.beta7] [spkg-install]   from cypari2.types cimport GEN
> [sagelib-10.7.beta7] [spkg-install]   ^
> [sagelib-10.7.beta7] [spkg-install]   ------------------------------------------------------------
> [sagelib-10.7.beta7] [spkg-install] 
> [sagelib-10.7.beta7] [spkg-install]   /home/dima/software/sage-src/src/sage/libs/pari/convert_flint.pxd:1:0: 'cypari2/types.pxd' not found
> [sagelib-10.7.beta7] [spkg-install]   [57/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_lzz_pX.pyx
> [sagelib-10.7.beta7] [spkg-install]   [58/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/ntl/ntl_mat_GF2E.pyx
> [sagelib-10.7.beta7] [spkg-install]   [59/1782] Compiling Cython source /home/dima/software/sage-src/src/sage/libs/pari/convert_gmp.pyx
> [sagelib-10.7.beta7] [spkg-install]   FAILED: src/sage/libs/pari/convert_gmp.cpython-313-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_gmp.pyx.c
> ```
> 
> somehow meson cannot find `./local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/cypari2/types.pxd`which is certainly there.
> 
> This with pari from the system, and cypari2 built by Sage. cython came from the system. If I install cypari2 system-wide, then this problem goes away.

Could you please attach `build\cp313\meson-info\intro-targets.json` and `build\cp313\meson-logs\meson-log.txt`, then I'll have a look. It appears to me that cypari2 is not properly found by https://github.com/sagemath/sage/blob/3b955fdb401228739dd52fcf6ccf172b9d4295b9/src/meson.build#L70-L87. Probably an issue with the venv.

2025-07-01 11:45 UTC, tobiasdiez commented
> Also on Linux I get this weirdness with `meson setup --wipe`
> 
> ```
> dima@tarski ~/software/sage-src $ ls -l build/cp313/
> total 2944
> -rw-r--r-- 1 dima dima 1602600 Jun 30 21:49 build.ninja
> -rw-r--r-- 1 dima dima 1393485 Jun 30 21:49 compile_commands.json
> drwxr-xr-x 2 dima dima    4096 Jun 30 21:49 meson-info
> drwxr-xr-x 2 dima dima      27 Jun 29 18:16 meson-logs
> drwxr-xr-x 5 dima dima    4096 Jun 30 21:49 meson-private
> -rw-r--r-- 1 dima dima      99 Jun 30 21:49 meson-python-native-file.ini
> drwxr-xr-x 3 dima dima      18 Jun 29 18:16 src
> dima@tarski ~/software/sage-src $ meson setup --wipe build/cp313/
> Could not find any valid candidate for native files: /home/dima/software/sage-src/build/cp313/meson-python-native-file.ini
> 
> ERROR: Cannot find specified native file: /home/dima/software/sage-src/build/cp313/meson-python-native-file.ini
> dima@tarski ~/software/sage-src $ ls -l build/cp313/
> total 0
> drwxr-xr-x 2 dima dima  6 Jun 30 22:06 meson-info
> drwxr-xr-x 2 dima dima  6 Jun 30 22:06 meson-logs
> drwxr-xr-x 2 dima dima 26 Jun 30 22:06 meson-private
> ```
> 
> looks as if it first removes `meson-python-native-file.ini` and then complains it cannot find it. This is meson 1.8.1

Strange. I've now replaced it by a simple `rm`.

2025-07-01 11:53 UTC, tobiasdiez commented
> and another problem is with system-wide sphinx installation - perhaps sphinx 8.2.3 is too new?
> 
> ```
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Extension error (sage_docbuild.conf)!
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Versions
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] ========
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Platform:         linux; (Linux-6.13.4-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_Ultra_7_165U-with-glibc2.41)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Python version:   3.13.3 (CPython)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Sphinx version:   8.2.3
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Docutils version: 0.21.2
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Jinja2 version:   3.1.6
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * Pygments version: 2.19.1
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Last Messages
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] =============
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]     index
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]     morphisms
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]     sage/tensor/modules/alternating_contr_tensor
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Loaded Extensions
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] =================
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.mathjax (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * alabaster (1.0.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.applehelp (2.0.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.devhelp (2.0.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.htmlhelp (2.1.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.serializinghtml (2.0.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinxcontrib.qthelp (2.0.0)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.inventory_builder (unknown version)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.multidocs (unknown version)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.preserve_defaults (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.type_comment (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.autodoc.typehints (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sage_docbuild.ext.sage_autodoc (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.todo (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.extlinks (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx.ext.linkcode (8.2.3)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx_copybutton (0.5.2)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * sphinx_inline_tabs (2023.04.21)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * IPython.sphinxext.ipython_directive (unknown version)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] * matplotlib.sphinxext.plot_directive (3.10.1)
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Traceback
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] =========
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]       File "/usr/lib/python3.13/site-packages/sphinx/events.py", line 415, in emit
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]         raise ExtensionError(
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]         ...<4 lines>...
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]         ) from exc
> [sagemath_doc_html-none] [spkg-install] [tensor_fr]     sphinx.errors.ExtensionError: Handler <function find_sage_dangling_links at 0x7fa6111dd120> for event 'missing-reference' threw an exception (exception: No such config value: 'intersphinx_resolve_self')
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] The full traceback has been saved in:
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] /tmp/sphinx-err-14qkvtd8.log
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
> [sagemath_doc_html-none] [spkg-install] [tensor_fr] Please also report this if it was a user error, so that a better error message can be provided next time.
> ```
> 
> (and lots more of these `No such config value: 'intersphinx_resolve_self'`)
> 
> With Sage's sphinx, I also get errors, which look different.

Yes, looks like a problem with new sphinx versions: https://github.com/gripped/archpkgbuilds/blob/accda28029af4760cabd43ad500bca50701ba6b7/extra/sagemath-doc/sphinx-8.2.patch#L20

2025-07-01 22:49 UTC, dimpase commented
> Yes, looks like a problem with new sphinx versions

yes, this patch fixes this issue for me, thanks.

2025-07-02 05:04 UTC, dimpase commented
I had been fixing my local toolchain : https://github.com/gentoo/gentoo/pull/42825 https://github.com/gentoo/gentoo/pull/42835 But finally everything runs, modulo sphinx 8.2.3 patch

Should we bump sphinx to 8.2.3 ?

2025-07-02 11:05 UTC, tobiasdiez commented
> I had been fixing my local toolchain : [gentoo/gentoo#42825](https://github.com/gentoo/gentoo/pull/42825) [gentoo/gentoo#42835](https://github.com/gentoo/gentoo/pull/42835) But finally everything runs, modulo sphinx 8.2.3 patch
> 
> Should we bump sphinx to 8.2.3 ?

Sure, but then best as a separate PR since this issue doesn't seem to be really related to the changes of this PR here.

2025-07-02 18:34 UTC, dimpase commented
> Could you please attach `build\cp313\meson-info\intro-targets.json` and `build\cp313\meson-logs\meson-log.txt`, then I'll have a look. It appears to me that cypari2 is not properly found by

these are from a working build, where cython is from the system.
[intro-targets.json.gz](https://github.com/user-attachments/files/21023615/intro-targets.json.gz)
[meson-log.txt.gz](https://github.com/user-attachments/files/21023618/meson-log.txt.gz)

2025-07-03 09:38 UTC, tobiasdiez commented
Happy to hear that the issue disappeared.

Is there anything else to do here, or is it good to go?

2025-07-03 13:18 UTC, dimpase commented
looking into the pdf docs build now, although it's probably not related

2025-07-03 14:13 UTC, dimpase commented
I am getting, locally, a jupyter kernel error while running `make doc-pdf` 
```
[spkg-install] [tutorial ] Traceback
[spkg-install] [tutorial ] =========
[spkg-install] [tutorial ]       File "/home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/jupyter_sphinx/utils.py", line 15, in blank_nb
[spkg-install] [tutorial ]         raise ExtensionError("Unable to find kernel", orig_exc=e)
[spkg-install] [tutorial ]     sphinx.errors.ExtensionError: Unable to find kernel (exception: No such kernel named sagemath)
```

2025-07-03 15:30 UTC, dimpase commented
the CI error looks different, but it's probably coming from the same source:
```
2025-07-02T21:58:43.0194880Z [sagemath_doc_pdf-none] [spkg-install] Running 'lualatex --file-line-error --interaction=batchmode  -recorder  "a_tour_of_sage.tex"'
2025-07-02T21:58:43.0194985Z [sagemath_doc_pdf-none] [spkg-install] ------------
2025-07-02T21:58:43.0195200Z [sagemath_doc_pdf-none] [spkg-install] This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian) 
2025-07-02T21:58:43.0195364Z [sagemath_doc_pdf-none] [spkg-install]  restricted system commands enabled.
2025-07-02T21:58:43.0195563Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: Getting log file 'a_tour_of_sage.log'
2025-07-02T21:58:43.0195741Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: Examining 'a_tour_of_sage.fls'
2025-07-02T21:58:43.0195907Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: Examining 'a_tour_of_sage.log'
2025-07-02T21:58:43.0196119Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: Index file 'a_tour_of_sage.idx' was written
2025-07-02T21:58:43.0196334Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: Log file says output to 'a_tour_of_sage.pdf'
2025-07-02T21:58:43.0196666Z [sagemath_doc_pdf-none] [spkg-install] Latexmk: All targets (a_tour_of_sage.pdf) are up-to-date
2025-07-02T21:58:43.0196756Z [sagemath_doc_pdf-none] [spkg-install] 
2025-07-02T21:58:43.0197048Z [sagemath_doc_pdf-none] [spkg-install] make[4]: Leaving directory '/sage/local/share/doc/sage/latex/en/a_tour_of_sage'
2025-07-02T21:58:43.0197395Z [sagemath_doc_pdf-none] [spkg-install] Build finished. The built documents can be found in /sage/local/share/doc/sage/pdf/en/a_tour_of_sage.
2025-07-02T21:58:43.0197907Z [sagemath_doc_pdf-none] [spkg-install] LATEXOPTS="--file-line-error --interaction=batchmode" sage --docbuild tutorial pdf --no-prune-empty-dirs
2025-07-02T21:58:43.0198092Z [sagemath_doc_pdf-none] [spkg-install] [tutorial ] building [latex]: all documents
2025-07-02T21:58:43.0198369Z [sagemath_doc_pdf-none] [spkg-install] [tutorial ] updating environment: [new config] 23 added, 0 changed, 0 removed
2025-07-02T21:58:43.0198729Z [sagemath_doc_pdf-none] [spkg-install] usage: sage [-h] [-v] [-q] [--simple-prompt] [-V] [-n [{jupyter,jupyterlab}]]
2025-07-02T21:58:43.0198871Z [sagemath_doc_pdf-none] [spkg-install]             [-c [COMMAND]]
2025-07-02T21:58:43.0198991Z [sagemath_doc_pdf-none] [spkg-install]             [file]
2025-07-02T21:58:43.0199272Z [sagemath_doc_pdf-none] [spkg-install] sage: error: unrecognized arguments: --python -m -f /tmp/tmpvde0yhwe.json
2025-07-02T21:58:43.0199421Z [sagemath_doc_pdf-none] [spkg-install] [tutorial ] Extension error:
2025-07-02T21:58:43.0199760Z [sagemath_doc_pdf-none] [spkg-install] [tutorial ] Notebook execution failed (exception: Kernel died before replying to kernel_info)
2025-07-02T21:58:43.0200021Z [sagemath_doc_pdf-none] [spkg-install] LaTeX files can be found in /sage/local/share/doc/sage/latex/en/tutorial.
2025-07-02T21:58:43.0200293Z [sagemath_doc_pdf-none] [spkg-install] make[4]: Entering directory '/sage/local/share/doc/sage/latex/en/tutorial'
2025-07-02T21:58:43.0200589Z [sagemath_doc_pdf-none] [spkg-install] make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
2025-07-02T21:58:43.0200796Z [sagemath_doc_pdf-none] [spkg-install] make[4]: *** No rule to make target 'all-pdf'.  Stop.
2025-07-02T21:58:43.0201059Z [sagemath_doc_pdf-none] [spkg-install] make[4]: Leaving directory '/sage/local/share/doc/sage/latex/en/tutorial'
2025-07-02T21:58:43.0201224Z [sagemath_doc_pdf-none] [spkg-install] Error building the documentation.
2025-07-02T21:58:43.0201383Z [sagemath_doc_pdf-none] [spkg-install] Traceback (most recent call last):
2025-07-02T21:58:43.0201606Z [sagemath_doc_pdf-none] [spkg-install]   File "<frozen runpy>", line 198, in _run_module_as_main
2025-07-02T21:58:43.0201789Z [sagemath_doc_pdf-none] [spkg-install]   File "<frozen runpy>", line 88, in _run_code
2025-07-02T21:58:43.0202031Z [sagemath_doc_pdf-none] [spkg-install]   File "/sage/src/sage_docbuild/__main__.py", line 532, in <module>
2025-07-02T21:58:43.0202168Z [sagemath_doc_pdf-none] [spkg-install]     sys.exit(main())
2025-07-02T21:58:43.0202289Z [sagemath_doc_pdf-none] [spkg-install]              ^^^^^^
2025-07-02T21:58:43.0202520Z [sagemath_doc_pdf-none] [spkg-install]   File "/sage/src/sage_docbuild/__main__.py", line 528, in main
2025-07-02T21:58:43.0202628Z [sagemath_doc_pdf-none] [spkg-install]     build()
2025-07-02T21:58:43.0202860Z [sagemath_doc_pdf-none] [spkg-install]   File "/sage/src/sage_docbuild/builders.py", line 298, in pdf
2025-07-02T21:58:43.0203082Z [sagemath_doc_pdf-none] [spkg-install]     raise RuntimeError(error_message % (command, tex_dir))
2025-07-02T21:58:43.0203403Z [sagemath_doc_pdf-none] [spkg-install] RuntimeError: failed to run $MAKE all-pdf in /sage/local/share/doc/sage/latex/en/tutorial
2025-07-02T21:58:43.0203487Z [sagemath_doc_pdf-none] [spkg-install] 
2025-07-02T21:58:43.0203736Z [sagemath_doc_pdf-none] [spkg-install]     Note: incremental documentation builds sometimes cause spurious
2025-07-02T21:58:43.0203972Z [sagemath_doc_pdf-none] [spkg-install]     error messages. To be certain that these are real errors, run
2025-07-02T21:58:43.0204187Z [sagemath_doc_pdf-none] [spkg-install]     "make doc-clean doc-uninstall" first and try again.
2025-07-02T21:58:43.0204665Z [sagemath_doc_pdf-none] [spkg-install] Exception ignored in atexit callback: <bound method run_sync.<locals>.wrapped of <nbclient.client.NotebookClient object at 0x7f9ca4e77ce0>>
2025-07-02T21:58:43.0204827Z [sagemath_doc_pdf-none] [spkg-install] Traceback (most recent call last):
2025-07-02T21:58:43.0205305Z [sagemath_doc_pdf-none] [spkg-install]   File "/sage/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
2025-07-02T21:58:43.0205618Z [sagemath_doc_pdf-none] [spkg-install]     return loop.run_until_complete(inner)
2025-07-02T21:58:43.0205775Z [sagemath_doc_pdf-none] [spkg-install]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-02T21:58:43.0206148Z [sagemath_doc_pdf-none] [spkg-install]   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2025-07-02T21:58:43.0206300Z [sagemath_doc_pdf-none] [spkg-install]     return future.result()
2025-07-02T21:58:43.0206561Z [sagemath_doc_pdf-none] [spkg-install]            ^^^^^^^^^^^^^^^
2025-07-02T21:58:43.0207046Z [sagemath_doc_pdf-none] [spkg-install]   File "/sage/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/nbclient/client.py", line 500, in _async_cleanup_kernel
2025-07-02T21:58:43.0207197Z [sagemath_doc_pdf-none] [spkg-install]     assert self.km is not None
2025-07-02T21:58:43.0207339Z [sagemath_doc_pdf-none] [spkg-install]            ^^^^^^^^^^^^^^^^^^^
2025-07-02T21:58:43.0207464Z [sagemath_doc_pdf-none] [spkg-install] AssertionError: 
2025-07-02T21:58:43.0207669Z [sagemath_doc_pdf-none] [spkg-install] make[3]: *** [Makefile:74: doc-pdf--tutorial] Error 1
2
```

2025-07-03 19:06 UTC, tobiasdiez commented
> I am getting, locally, a jupyter kernel error while running `make doc-pdf`
> 
> ```
> [spkg-install] [tutorial ] Traceback
> [spkg-install] [tutorial ] =========
> [spkg-install] [tutorial ]       File "/home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/jupyter_sphinx/utils.py", line 15, in blank_nb
> [spkg-install] [tutorial ]         raise ExtensionError("Unable to find kernel", orig_exc=e)
> [spkg-install] [tutorial ]     sphinx.errors.ExtensionError: Unable to find kernel (exception: No such kernel named sagemath)
> ```

Do you see where the kernel spec are installed to instead?
https://github.com/tobiasdiez/sage/blob/a1c4c81fc2578d173b2c89df33496a8a8490b60a/src/sage/meson.build#L154
should put them into the active python prefix.

Is doc-html working for you (it's strange that the ci for html is green but the pdf fails with this cryptic error). 

If we cannot solve this here, it might be easier to finish the meson doc building for pdfs and then reuse it instead.

2025-07-03 19:20 UTC, dimpase commented
I looked at the results of doc-html again, and they error out at the same place, only the job finishes "normally".
I'd consider the latter a bug (not sure if it's introduced here or was there before)

2025-07-03 19:35 UTC, dimpase commented
> Do you see where the kernel spec are installed to instead?
it's apparently
`./build/cp313/src/sage/kernel.json` - but the system-wide `jupyter` does not get informed about it, it seems. Indeed:
```
$ jupyter --path
config:
    /home/dima/.jupyter
    /home/dima/.local/etc/jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/dima/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/dima/.local/share/jupyter/runtime
```

2025-07-03 20:03 UTC, dimpase commented
by the way, it seems that #39643 tells us that the doc-pdf CI failure stems from `"sage.repl.ipython_kernel"` not being filled in (the error there has `-m` immediately followed by `-f`)

`["python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"]`

2025-07-03 20:11 UTC, dimpase commented
note that `logo-64x64.png` and `logo.png` don't get installed anywhere, their only occur once, in 
`src/sage/ext_data/notebook-ipython/`

so something is off with the jupyter kernel install - in several ways.

2025-07-04 05:45 UTC, dimpase commented
I think `install_dir:` is badly broken in `meson.build`. I tried
```diff
--- a/src/sage/meson.build
+++ b/src/sage/meson.build
@@ -152,14 +152,14 @@ subdir('sat')
 # meson-python maps 'datadir' currently the python prefix, see
 # https://github.com/mesonbuild/meson-python/issues/517
 kernel_dir = get_option('datadir') / 'share/jupyter/kernels/sagemath'
-install_data('ext_data/notebook-ipython/logo.svg', install_dir: kernel_dir)
+install_data('ext_data/notebook-ipython/logo.svg', install_dir: '/tmp/foobar') # kernel_dir)
 install_data('ext_data/notebook-ipython/logo-64x64.png', install_dir: kernel_dir)
 kernel_data = configuration_data()
 kernel_data.set('SAGE_VERSION', meson.project_version())
 configure_file(
   input: 'ext_data/notebook-ipython/kernel.json.in',
   output: 'kernel.json',
-  install_dir: kernel_dir,
+  install_dir: '/tmp/foobar', # kernel_dir,
   install: true,
   configuration: kernel_data,
 )
```

and no, `/tmp/foobar` remains uncreated, so neither `install_data` nor `configure_file` use `/tmp/foobar` in any way.

2025-07-04 15:57 UTC, dimpase commented
the latter was with meson 1.8.1, trying 1.8.2 now

This looks like a step in the right direction, I get 
```
[sagelib-10.7.beta7] [spkg-install]   meson-python: error: Could not map installation path to an equivalent wheel directory: '/tmp/foobar/kernel.json'
[sagelib-10.7.beta7] [spkg-install]   error: subprocess-exited-with-error
```
with the silly patch above

2025-07-04 19:59 UTC, dimpase commented
still no cigar, but in meson logs I see
```
Failed to guess install tag for /usr/local/share/share/jupyter/kernels/sagemath/kernel.json
Failed to guess install tag for /usr/local/share/share/jupyter/kernels/sagemath/logo.svg
Failed to guess install tag for /usr/local/share/share/jupyter/kernels/sagemath/logo-64x64.png
```

which seems to indicate that in `src/sage/meson.build` 
`kernel_dir = get_option('datadir')` the value of `kernel_dir` is `/usr/local/share`, which is the default value specified in meson docs for "Universal options", something that can be set at the command line (how?), or inside project () function (again, how?).

There is also a warning in the log:

```
Message: Warning: The specified datadir does not contain the necessary Cremona database. Either specify a different datadir or specify a correct the correct path via the environment variable SAGE_SHARE during runtime.
```
which might mean that the default value is rejected, and so nothing gets installed.

2025-07-04 20:33 UTC, dimpase commented
but I cannot for the life of me figure out how to modify that `datadir`. 
All I can say that I can pass the full path to `local/share` (where Cremona database is) to `meson setup --reconfigure` as `-Ddatadir=...`, e.g.
```
meson setup --reconfigure /home/dima/software/sage-src /home/dima/software/sage-src/build/cp313 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --default-library=static --native-file=/home/dima/software/sage-src/build/cp313/meson-python-native-file.ini -Ddatadir='/home/dima/software/sage-src/local/share'
```
and then I don't see the warning.

It's probably cursed in a special way, which make people use installation tools from meson-python, e.g. scipy does this: https://github.com/scipy/scipy/blob/fb5d436433b6ee9c24fc5a61eb2687d55c8ce7bb/scipy/linalg/meson.build#L290

2025-07-05 06:57 UTC, tobiasdiez commented
I think what's happening is that things in datadir are not 'installed' in editable mode - I'm also not sure if that's possible.

Not sure whats a proper fix. The easiest way would be to register the build dir with Jupiter. But sage - -docbuild poisens the data path env variables for Jupiter...

2025-07-05 20:15 UTC, dimpase commented
> I think what's happening is that things in datadir are not 'installed' in editable mode - I'm also not sure if that's possible.
> 
> Not sure whats a proper fix. The easiest way would be to register the build dir with Jupiter. But sage - -docbuild poisens the data path env variables for Jupiter...

note that `install_data` does not seem to be doing anything at all, it's only `configure_file`, and not to the correct location in the build dir, anyway.
What is the correct location?
In the classical build it's something like
`local/var/lib/sage/venv-python3.13/share/jupyter/kernels/python3/`, which says that `kernel.json` should be the datadir of the venv we're installing in, not some kind of global datadir like `/usr/local/share`.
In this sense, assuming that meson-python understands the venv we're building in, is the right tool to use for installing it (or we should change the location it goes to, and make it `local/share`.


But note that `cremona.db` is not in ``local/var/lib/sage/venv-python3.13/share`, it's in `local/share/cremona`,
and this might make meson complain that datadir is wrong all along.

2025-07-06 02:39 UTC, dimpase commented
I also don't understand how copying files alone is going to make sagemath jupyter kernel available. 

The docs say one should run `jupyter kernelspec install <kernel location>`. Maybe this is somehow sufficient to just copy files, but it's a hack.

2025-07-06 04:58 UTC, dimpase commented
> The easiest way would be to register the build dir with Jupiter. But sage - -docbuild poisens the data path env variables for Jupiter

running
```
$ jupyter kernelspec install --name=sagemath src/sage/ext_data/notebook-ipython/ --user
```
does create a kernel:
```
$ jupyter kernelspec list
Available kernels:
  sagemath            /home/dima/.local/share/jupyter/kernels/sagemath
  python3             /usr/share/jupyter/kernels/python3
```

but it does not get picked up by docbuild, so some poisoning is happening beyond env. var. However, doing
```
$ sudo jupyter kernelspec install --name=sagemath src/sage/ext_data/notebook-ipython/
```
does create a `sagemath` kernel in `/usr/share/jupyter/kernels/sagemath` docbuild picks up, and doc-html building works.

```
$ jupyter kernelspec list
Available kernels:
  python3             /usr/share/jupyter/kernels/python3
  sagemath            /usr/share/jupyter/kernels/sagemath
```

However, while building doc-pdf, I still see `sphinx.errors.ExtensionError: Unable to find kernel`.

The 1st thing would be to undo all that poisoning - where exactly is it?

2025-07-06 13:31 UTC, tobiasdiez commented
I don't have too much time right now, so just some quick notes:
- I tried to switch to the meson-based docbuild - let's see if it's work
- The poisoning of the jupyter env variables was done in https://github.com/sagemath/sage/issues/33650
- I've opened https://github.com/mesonbuild/meson-python/issues/774 to ask for how to solve the issue of installing these data files on the meson-side.

2025-07-06 20:12 UTC, dimpase commented
Now docbuild html fails with a new to me error (coming from ninja missing a target, or something?)
`ERROR: Unknown target name: "sage --notebook=export". [docutils]`
```
[spkg-install] [92/190] Generating src/doc/doc-html-other-en-prep with a custom command
[spkg-install] FAILED: src/doc/htmlen-prep 
[spkg-install] /home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/bin/python3 /home/dima/
software/sage-src/src/build-docs.py --no-pdf-links en/prep html -o src/doc --source /home/dima/softwar
e/sage-src/src/doc
[spkg-install] [prep     ] inventory <https://ipywidgets.readthedocs.io/en/stable/> contains multiple 
definitions for std:label:examples/Widget Layout.ipynb#display
[spkg-install] [prep     ] building [html]: targets for 17 source files that are out of date
[spkg-install] [prep     ] updating environment: [new config] 17 added, 0 changed, 0 removed
[spkg-install] [prep     ] /home/dima/software/sage-src/src/doc/en/prep/Logging-On.rst:54: ERROR: Unkn
own target name: "sage --notebook=export". [docutils]
[spkg-install] [prep     ] The HTML pages are in src/doc/html/en/prep.
[spkg-install] Error building the documentation.
[spkg-install] Traceback (most recent call last):
[spkg-install]   File "/home/dima/software/sage-src/src/build-docs.py", line 4, in <module>
[spkg-install]     main()
[spkg-install]     ~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/__main__.py", line 548, in main
[spkg-install]     build()
[spkg-install]     ~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 136, in f
[spkg-install]     runsphinx()
[spkg-install]     ~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 324, in ru
nsphinx
[spkg-install]     sys.stderr.raise_errors()
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 255, in ra
ise_errors
[spkg-install]     raise OSError(self._error)
[spkg-install] OSError: /home/dima/software/sage-src/src/doc/en/prep/Logging-On.rst:54: ERROR: Unknown target name: "sage --notebook=export". [docutils]
```

2025-07-06 21:50 UTC, tobiasdiez commented
After a bit of research, this error usually happens because rst thinks "sage --notebook=export" is a reference, but it can't find a matching target. But I have no idea where this is triggered from - the only occurrence of this string is in `sage-notebook` and not in `Logging-On`. No idea, sorry :(

2025-07-06 23:34 UTC, dimpase commented
@tobiasdiez - apparently it's just an invalid sphinx target. The following pseudo-fix makes docs build.

```diff
--- a/src/doc/en/prep/Logging-On.rst
+++ b/src/doc/en/prep/Logging-On.rst
@@ -54,7 +54,7 @@ the third option to "export" them will not make sense.
 The legacy SageNB has been retired in Sage 9.1.
 Please use the Jupyter notebook.
 Old SageNB worksheets can be converted to Jupyter notebooks
-using the `sage --notebook=export`_ command or to RST
+using the `sage --notebook=export <https://foo.bar>`_ command or to RST
 using the `sage-sws2rst <https://pypi.org/project/sage-sws2rst/>`_ package.

 Jupyter will bring you to a screen
```

2025-07-07 02:57 UTC, dimpase commented
`build/sage-distro` should be cleanable by `make ...`.

2025-07-07 04:02 UTC, dimpase commented
OK, looks better - html docs build, etc. Why do I see (on a system with Sage-installed jupyter)
```
-rw-r--r--  1 dima  wheel  173 Jul  6 20:47 ./build/sage-distro/src/sage/kernel.json
-rw-r--r--  1 dima  wheel  193 Jul  6 20:46 ./local/var/lib/sage/venv-python3.13/share/jupyter/kernels/python3/kernel.json
```

what has been done to make sure all these kernel.json get installed?

2025-07-07 05:04 UTC, dimpase commented
docs still build incorrectly due to kernel.json blues 
```
[spkg-install] [94/190] Generating src/doc/doc-html-other-zh-tutorial with a custom command
[spkg-install] [tutorial ] inventory <https://ipywidgets.readthedocs.io/en/stable/> contains multiple definitions for std:label:examples/Widget Layout.ipynb#display
[spkg-install] [tutorial ] building [html]: targets for 23 source files that are out of date
[spkg-install] [tutorial ] updating environment: [new config] 23 added, 0 changed, 0 removed
[spkg-install] [tutorial ] Extension error:
[spkg-install] [tutorial ] Unable to find kernel (exception: No such kernel named sagemath)
[spkg-install] Build finished. The built documents can be found in /Volumes/dima/sage/build/sage-distro/src/doc/html/zh/tutorial.
```

indeed:

```
(sage-buildsh) dima@studio:~/sage$ jupyter kernelspec list
Available kernels:
  python3    /Volumes/dima/sage/local/var/lib/sage/venv-python3.13/share/jupyter/kernels/python3
```

2025-07-07 09:25 UTC, tobiasdiez commented
Can you try this version pls? CI is still failing, but with a different error (it runs out of space).

2025-07-07 21:11 UTC, dimpase commented
OK, this works locally. (both html and pdf docs)

interactive jupyter does not, but it's for another PR

2025-07-07 22:16 UTC, dimpase commented
what remains is to fix cleaning targets in the top Makefile. I presume this 
```make
        @for d in "$(SAGE_ROOT)"/build/cp[0-9]*; do \
                if [ -d "$$d" ]; then \
                        rm -rf "$$d"; \
                fi; \
        done
```
is no longer needed and should be replaces by
```
        rm -rf "$(SAGE_ROOT)"/build/sage-distro
```

2025-07-08 08:52 UTC, tobiasdiez commented
Right, thanks!

2025-07-08 12:08 UTC, dimpase approved these changes

2025-07-08 12:56 UTC, tobiasdiez commented
Thanks a lot @dimpase for your help with this!

2025-07-20 19:21 UTC, vbraun commented
Docbuild is broken, most likely a race condition. If I run
```
make doc-clean && make -j10 doc-html
```
then it always errors out in random modules with e.g.
```
[sagemath_doc_html-none] [spkg-install] [spkg     ] The inventory file is in src/doc/inventory/en/reference/spkg.
[sagemath_doc_html-none] [spkg-install] Error building the documentation.
[sagemath_doc_html-none] [spkg-install] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/build-docs.py", line 4, in <module>
[sagemath_doc_html-none] [spkg-install]     main()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/__main__.py", line 548, in main
[sagemath_doc_html-none] [spkg-install]     build()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 645, in _wrapper
[sagemath_doc_html-none] [spkg-install]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/builders.py", line 136, in f
[sagemath_doc_html-none] [spkg-install]     runsphinx()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 324, in runsphinx
[sagemath_doc_html-none] [spkg-install]     sys.stderr.raise_errors()
[sagemath_doc_html-none] [spkg-install]   File "/home/release/Sage/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
[sagemath_doc_html-none] [spkg-install]     raise OSError(self._error)
[sagemath_doc_html-none] [spkg-install] OSError: /home/release/Sage/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features' [toc.not_readable]
```
If I re-run `make -j10 doc-html` often enough then eventually it passes.

2025-07-20 20:24 UTC, dimpase commented
I only tested this with sphinx 8.2.3, and I didn't see any problems like this.
It could be a bug in 8.1.3.
(Or I got lucky).

Let me double-check, and get the sphinx update ready.

2025-07-20 20:59 UTC, dimpase commented
@vbraun  - could you check if you still have it with #40457 ?
Anyhow, #40457 is ready for a review, too.

2025-07-20 21:30 UTC, tobiasdiez commented
@vbraun Do you build the "live docs" or just the normal ones? Does it occur only without parallelization (`-j1`)?

Could you please show also the error message of the corresponding doc module, i.e. `sage/features` in the above example.

2025-07-20 22:16 UTC, vbraun commented
I don't know anything about live docs, I'm running `make -j10 doc-html`

I'm assuming that it works without parallelization, but who has time for that.

2025-07-21 08:45 UTC, tobiasdiez commented
> I don't know anything about live docs, I'm running `make -j10 doc-html`

Live docs are activated by `SAGE_LIVE_DOC: yes`, and with this option activated I do get some kind of race errors in https://github.com/sagemath/sage/pull/40379

> I'm assuming that it works without parallelization, but who has time for that.

Sure not in production. It was only a suggestion to see where the problem comes from.

Similar to Dima, I cannot reproduce it on my system and it's also seems to succeed on CI (the failure comes from the fact that it runs out of space later). So without the concrete failure message, there is nothing I can do to fix it...

2025-07-22 06:58 UTC, ptrrsn commented
When testing this PR as recommended by @dimpase in https://github.com/sagemath/cypari2/pull/180, I got an error:
```
ImportError: /home/risan/sage/sage/build/sage-distro/src/sage/symbolic/expression.cpython-312-x86_64-linux-gnu.so: undefined symbol: fmpq_poly_set_fmpz
```
which I got around by adding FLINT dependency in symbolic. I am not sure if it is just because of my setup, but reporting it here just in case.

2025-07-22 16:12 UTC, dimpase requested changes
this doesn't work for me:
```
[spkg-install] Installing sagelib-10.7.beta8 (editable mode)
[spkg-install] Using pip 25.1.1 from /usr/lib/python3.13/site-packages/pip (python 3.13)
[spkg-install] Obtaining file:///home/dima/software/sage-src
[spkg-install]   Checking if build backend supports build_editable: started
[spkg-install]   Running command Checking if build backend supports build_editable
[spkg-install]   Checking if build backend supports build_editable: finished with status 'done'
[spkg-install]   Preparing editable metadata (pyproject.toml): started
[spkg-install]   Running command Preparing editable metadata (pyproject.toml)
[spkg-install]   + meson setup --reconfigure /home/dima/software/sage-src /home/dima/software/sage-src/build/sage-distro -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --default-library=static -DSAGE_LOCAL=/home/dima/software/sage-src/local --native-file=/home/dima/software/sage-src/build/sage-distro/meson-python-native-file.ini
[spkg-install] 
[spkg-install]   ERROR: Unknown options: ":SAGE_LOCAL" not found.
[spkg-install]   error: subprocess-exited-with-error
[spkg-install]   
[spkg-install]   × Preparing editable metadata (pyproject.toml) did not run successfully.
[spkg-install]   │ exit code: 1
[spkg-install]   ╰─> See above for output.
```

2025-07-24 18:31 UTC, tobiasdiez commented
@ptrrsn Thanks, I've included your fix - which is indeed needed.

@dimpase This needs now https://github.com/sagemath/sage/pull/40071 (which I will merge into this PR after the next release).

2025-08-03 13:12 UTC, tobiasdiez commented
Setting back to positive review since the issue with the docs should have been fixed by the sphinx update and the tests are green after the rebase (the red ones have known issues also before, not sure about why the build times out on some systems even before building sagelib...hopefully a temporary issue).

2025-08-14 00:03 UTC, vbraun commented
Seems to use wrong build flags on macos
```
[sagelib-10.7] [spkg-install]   FAILED: src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.o
[sagelib-10.7] [spkg-install]   g++ -std=gnu++11 -Isrc/sage/graphs/base/boost_graph.cpython-312-darwin.so.p -Isrc/sage/graphs/base -I../../src/sage/graphs/base -Isrc/sage/cpython -I../../src/sage/cpython -Isrc/sage/data_structures -I../../src/sage/data_structures -Isrc/sage/rings -I../../src/sage/rings -I../../local/var/lib/sage/venv-python3.12.5/lib/python3.12/site-packages/cysignals -I/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.12.5/include/python3.12 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c++17 -O3 -g -O2 -MD -MQ src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.o -MF src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.o.d -o src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.o -c src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/src/sage/graphs/base/boost_graph.pyx.cpp
[sagelib-10.7] [spkg-install]   In file included from src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/src/sage/graphs/base/boost_graph.pyx.cpp:1240:
[sagelib-10.7] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/boost/graph/adjacency_list.hpp:21:
[sagelib-10.7] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/boost/unordered_set.hpp:17:
[sagelib-10.7] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/boost/unordered/unordered_set.hpp:18:
[sagelib-10.7] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/boost/functional/hash.hpp:6:
[sagelib-10.7] [spkg-install]   /Users/buildbot-sage/worker/sage_git/build/local/include/boost/functional/hash/hash.hpp:74:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
[sagelib-10.7] [spkg-install]      74 |         struct hash_base : std::unary_function<T, std::size_t> {};
[sagelib-10.7] [spkg-install]         |                            ~~~~~^~~~~~~~~~~~~~
[sagelib-10.7] [spkg-install]         |                                 __unary_function
```

2025-08-14 01:10 UTC, dimpase commented
> Seems to use wrong build flags on macos

our boost is extremely old, not touched for 7 years.
Let's bump to 1.88.
(of course gnu++11 should go, too)

> 
> ```
> [sagelib-10.7] [spkg-install]   FAILED: src/sage/graphs/base/boost_graph.cpython-312-darwin.so.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.o
>

2025-08-14 01:37 UTC, dimpase commented
even better, let's just move boost to prereqs. It's available everywhere.

2025-08-14 06:54 UTC, tobiasdiez commented
Could you please see if https://github.com/sagemath/sage/pull/39030/commits/e0c9f9bcafe0708c31cc06784ee2de4ba83b4249 does the job for you? Thanks!

> g++ -std=gnu++11

This is used also for the compilation of other libraries in the buildbot (eg pari). So I suspect that it's set globally somewhere in the build bot config.

> even better, let's just move boost to prereqs. It's available everywhere.

fine with me. But then someone probably has to teach the buildbots to install prereq and bootstrap packages as well first. Currently, it misses them, eg:
> bootstrap: line 142: aclocal: command not found

2025-08-14 14:22 UTC, dimpase commented
can all the C++ libraries (including optional) be built with gnu++11?
E.g. symengine?

2025-08-15 12:02 UTC, tobiasdiez commented
No idea, but that's apparently the config in the buildbots... @vbraun can you share how/where the build bot env and the steps it runs. Thanks!

---


Setting this back to positive review so that the latest changes are tested on the build bot (github CI passes)

2025-08-15 20:45 UTC, vbraun commented
@tobiasdiez I've added you to https://github.com/sagemath/buildbot-sage

2025-08-16 15:41 UTC, vbraun commented
merge conflict, please fix

2025-08-16 16:51 UTC, dimpase commented
> @tobiasdiez I've added you to https://github.com/sagemath/buildbot-sage

why do we have a top secret buildbot-sage repo? I don't even see it. (despite being on @sagemath/core ) @roed314 @vbraun ?

2025-08-16 18:48 UTC, dimpase commented on pyproject.toml
> -  "pkg:generic/boost",
why is boost removed? Are we there yet qua removal of boost spkg? Without boost one cannot build some standard parts of sagelib, no?

2025-08-16 20:02 UTC, vbraun commented
The buildbot repo includes the worker secrets, not super secret but you could in principle use it to submit incorrect build reports.

2025-08-16 22:54 UTC, dimpase commented on pyproject.toml
> -  "pkg:generic/boost",
I took liberty to fix it

2025-08-17 14:05 UTC, tobiasdiez commented
@vbraun I've noticed that the build bot fails with a similar error also on another file (http://build.sagemath.org/?#/builders/32/builds/26/steps/10/logs/sagelib). This should be fixed in https://github.com/sagemath/sage/pull/39030/commits/46a3e7842bb23d268598f8e88c9e12471e5ed607.

2025-08-17 21:41 UTC, kiwifb commented
Apologies for interjecting in this thread. I have a working sage-on-gentoo ebuild that uses meson for some time now, but I have not figured out how you are supposed to build the doc in the meson model.
Currently I build the doc as a separate package once sage is installed, is it still a valid strategy in the meson setup?

2025-08-17 21:42 UTC, kiwifb commented
Apologies for the closing as well, my finger slipped _and_ I_was_shocked_to_have_that_power.

2025-08-17 22:07 UTC, vbraun commented
I'm getting a bunch of build failures on macos: http://build.sagemath.org/?#/builders/24/builds/1/steps/11/logs/stdio

2025-08-17 22:13 UTC, vbraun commented
![he-man-i-have-the-power](https://github.com/user-attachments/assets/81263a32-c047-4aed-bb0d-bc9987a165be)

2025-08-17 22:40 UTC, dimpase commented
do you really have to build gmp on the buildbot?

2025-08-18 01:20 UTC, tobiasdiez commented
> I'm getting a bunch of build failures on macos: http://build.sagemath.org/?#/builders/24/builds/1/steps/11/logs/stdio

I only see 
```
g++ -std=gnu++11 -Isrc/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p -Isrc/sage/rings/polynomial/pbori -I../../src/sage/rings/polynomial/pbori -Isrc/sage/cpython -I../../src/sage/cpython -Isrc/sage/ext -I../../src/sage/ext -Isrc/sage/rings -I../../src/sage/rings -Isrc -I../../src -I../../local/var/lib/sage/venv-python3.12.5/lib/python3.12/site-packages/cysignals -I/Users/buildbot-sage/worker/sage_git/build/local/var/lib/sage/venv-python3.12.5/include/python3.12 -I/Users/buildbot-sage/worker/sage_git/build/local/include/libpng16 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c++17 -O3 -g -O2 -MD -MQ src/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p/meson-generated_src_sage_rings_polynomial_pbori_pbori.pyx.cpp.o -MF src/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p/meson-generated_src_sage_rings_polynomial_pbori_pbori.pyx.cpp.o.d -o src/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p/meson-generated_src_sage_rings_polynomial_pbori_pbori.pyx.cpp.o -c src/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p/src/sage/rings/polynomial/pbori/pbori.pyx.cpp
[sagelib-10.8.beta0] [spkg-install]   In file included from src/sage/rings/polynomial/pbori/pbori.cpython-312-darwin.so.p/src/sage/rings/polynomial/pbori/pbori.pyx.cpp:1144:
[sagelib-10.8.beta0] [spkg-install]   In file included from ../../src/sage/libs/polybori/pb_wrap.h:1:
[sagelib-10.8.beta0] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/polybori/BoolePolynomial.h:36:
[sagelib-10.8.beta0] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/polybori/BooleSet.h:25:
[sagelib-10.8.beta0] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/polybori/diagram/CCuddDDFacade.h:50:
[sagelib-10.8.beta0] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/polybori/routines/pbori_routines_hash.h:19:
[sagelib-10.8.beta0] [spkg-install]   In file included from /Users/buildbot-sage/worker/sage_git/build/local/include/boost/functional/hash.hpp:6:
[sagelib-10.8.beta0] [spkg-install]   /Users/buildbot-sage/worker/sage_git/build/local/include/boost/functional/hash/hash.hpp:74:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
```

and that should be fixed in the latest commit https://github.com/sagemath/sage/pull/39030/commits/46a3e7842bb23d268598f8e88c9e12471e5ed607. Are there other errors?

2025-08-18 01:23 UTC, tobiasdiez commented
> Apologies for interjecting in this thread. I have a working sage-on-gentoo ebuild that uses meson for some time now, but I have not figured out how you are supposed to build the doc in the meson model. Currently I build the doc as a separate package once sage is installed, is it still a valid strategy in the meson setup?

You can run `meson compile -C <builddir> doc-html` to build the html docs (and the pdfs with doc-pdf, but that may require #40597). For this you need to have to specify the builddir that you also used for the sage compilation (and have sage installed).

2025-08-18 02:43 UTC, kiwifb commented
> > Apologies for interjecting in this thread. I have a working sage-on-gentoo ebuild that uses meson for some time now, but I have not figured out how you are supposed to build the doc in the meson model. Currently I build the doc as a separate package once sage is installed, is it still a valid strategy in the meson setup?
> 
> You can run `meson compile -C <builddir> doc-html` to build the html docs (and the pdfs with doc-pdf, but that may require #40597). For this you need to have to specify the builddir that you also used for the sage compilation (and have sage installed).

OK, from where do I run this command? And do you mean to say I need to have both sage installed and the tree I used to compile it? Will a clean source tree suffice?

2025-08-18 05:24 UTC, dimpase commented
This would work with meson-built Sage. On Gentoo with all the standard Sage packages (non-python and Python)  installed you can, on the Sage source tree, run `meson setup <builddir>` followed by `meson  compile -C  <builddir>` (as described in meson.rst`).

2025-08-18 11:49 UTC, cxzhong commented
```
[spkg-install] Installing numpy-2.2.4
[spkg-install] * Creating isolated environment: venv+pip...
[spkg-install] * Installing packages in isolated environment:
[spkg-install]   - Cython>=3.0.6
[spkg-install]   - meson-python>=0.15.0
[spkg-install] > /home/zhongcx/sage/local/var/lib/sage/venv-python3.13/bin/python3 -m pip
[spkg-install]   --python /tmp/build-env-i49a562k/bin/python install --use-pep517 --no-warn-
[spkg-install]   script-location --no-compile -r /tmp/build-reqs-hmt1n_99.txt
[spkg-install] < Looking in links: /home/zhongcx/sage/local/var/lib/sage/venv-
[spkg-install]   python3.13/var/lib/sage/wheels
[spkg-install] < Processing /home/zhongcx/sage/local/var/lib/sage/venv-
[spkg-install]   python3.13/var/lib/sage/wheels/meson_python-0.17.1-py3-none-any.whl (from -r
[spkg-install]   /tmp/build-reqs-hmt1n_99.txt (line 1))
[spkg-install] < Processing /home/zhongcx/sage/local/var/lib/sage/venv-
[spkg-install]   python3.13/var/lib/sage/wheels/cython-3.1.3-cp313-cp313-linux_x86_64.whl
[spkg-install]   (from -r /tmp/build-reqs-hmt1n_99.txt (line 2))
[spkg-install] < INFO: pip is looking at multiple versions of meson-python to determine which
[spkg-install]   version is compatible with other requirements. This could take a while.
[spkg-install] < ERROR: Could not find a version that satisfies the requirement meson>=1.2.3;
[spkg-install]   python_version >= "3.12" (from meson-python) (from versions: none)
[spkg-install] < ERROR: No matching distribution found for meson>=1.2.3; python_version >=
[spkg-install]   "3.12"
[spkg-install] 
[spkg-install] Traceback (most recent call last):
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/__main__.py", line 178, in _handle_build_error
[spkg-install]     yield
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/__main__.py", line 429, in main
[spkg-install]     built = build_call(
[spkg-install]         args.srcdir,
[spkg-install]     ...<5 lines>...
[spkg-install]         args.installer,
[spkg-install]     )
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/__main__.py", line 238, in build_package
[spkg-install]     out = _build(isolation, srcdir, outdir, distribution, config_settings, skip_dependency_check, installer)
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/__main__.py", line 170, in _build
[spkg-install]     return _build_in_isolated_env(srcdir, outdir, distribution, config_settings, installer)
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/__main__.py", line 135, in _build_in_isolated_env
[spkg-install]     env.install(builder.build_system_requires)
[spkg-install]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/env.py", line 136, in install
[spkg-install]     self._env_backend.install_requirements(requirements)
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/env.py", line 265, in install_requirements
[spkg-install]     run_subprocess(cmd)
[spkg-install]     ~~~~~~~~~~~~~~^^^^^
[spkg-install]   File "/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/lib/python3.13/site-packages/build/_ctx.py", line 71, in run_subprocess
[spkg-install]     subprocess.run(cmd, capture_output=True, check=True, env=env)
[spkg-install]     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[spkg-install]   File "/usr/lib/python3.13/subprocess.py", line 577, in run
[spkg-install]     raise CalledProcessError(retcode, process.args,
[spkg-install]                              output=stdout, stderr=stderr)
[spkg-install] subprocess.CalledProcessError: Command '['/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/bin/python3', '-m', 'pip', '--python', '/tmp/build-env-i49a562k/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-hmt1n_99.txt']' returned non-zero exit status 1.
[spkg-install] 
[spkg-install] ERROR Command '['/home/zhongcx/sage/local/var/lib/sage/venv-python3.13/bin/python3', '-m', 'pip', '--python', '/tmp/build-env-i49a562k/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-hmt1n_99.txt']' returned non-zero exit status 1.
[spkg-install] Warning: building with "python3 -m build --wheel --outdir=dist   ." failed.
[spkg-install] Retrying with "python3 -m build --wheel --outdir=dist --no-isolation --skip-dependency-check  .".
```
Finally, I have checked the install log: I found `numpy`, `cysignals` and `kiwisolver` appear the similar errors. Maybe there `pyproject.toml` does not support python3.13

2025-08-18 13:21 UTC, dimpase commented
after `meson compile` you probably need `meson install` before anything else can be done.

and if `meson compile` failed then it got to be fixed before `meson install`.

2025-08-18 13:31 UTC, tobiasdiez commented
@vbraun another fix for the issue (due to a random race condition) in http://build.sagemath.org/#/builders/24/builds/2.

2025-08-18 16:57 UTC, orlitzky commented
> and if `meson compile` failed then it got to be fixed before `meson install`.

FWIW I am using

```
    meson setup \
	 --python.install-env=prefix \
	 --prefix="${HOME}/.local" \
	 --wrap-mode=nofallback \
	 -Dauto_features=disabled
```

and usually append `-Dbuild-docs=false`. This eventually causes sagelib to be installed to the normal python user location, ` ~/.local/lib/python3.13/site-packages/sage`, where it can be used without further ado...

_Except_ that the `./sage` script clobbers `PYTHONUSERBASE` if it is unset. So I have my own script that does,

```
export PYTHONUSERBASE="${HOME}/.local"
export SAGE_SHARE="/usr/share/sage"  # sage-on-gentoo databases
exec "/path/to/sage/script" "${@}"
```

2025-08-21 12:41 UTC, vbraun commented
There is a merge conflict with the current merge tree for the record

2025-08-21 13:41 UTC, tobiasdiez commented
> There is a merge conflict with the current merge tree for the record

Thanks for letting me know. Should be resolved now by removing the merge conflict with https://github.com/sagemath/sage/pull/40166 (in fact the change in `pyproject.toml` is no longer correct).

Would be awesome if we could get this in as soon as possible. It's currently blocking a few other follow-up PRs and most likely fixes issues with the pdf doc build.

2025-08-22 17:53 UTC, dimpase commented
I am trying this branch, and still get errors in `make doc-html`, like
```
[spkg-install] [152/190] Generating src/doc/doc-html-reference-plotting with a custom command
[spkg-install] FAILED: [code=1] src/doc/htmlplotting 
[spkg-install] /home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/bin/python3 /home/dima/software/sage-src/src/build-docs.py --no-pdf-links reference/plotting html -o src/doc --source /home/dima/software/sage-src/src/doc
[spkg-install] [plotting ] inventory <https://ipywidgets.readthedocs.io/en/stable/> contains multiple definitions for std:label:examples/Widget Layout.ipynb#display
[spkg-install] [plotting ] no targets are out of date.
[spkg-install] [plotting ] WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
[spkg-install] [plotting ] Versions
[spkg-install] [plotting ] ========
[spkg-install] [plotting ] * Platform:         linux; (Linux-6.13.4-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_Ultra_7_165U-with-glibc2.41)
[spkg-install] [plotting ] * Python version:   3.13.5 (CPython)
[spkg-install] [plotting ] * Sphinx version:   8.2.3
[spkg-install] [plotting ] * Docutils version: 0.21.2
[spkg-install] [plotting ] * Jinja2 version:   3.1.6
[spkg-install] [plotting ] * Pygments version: 2.19.2
[spkg-install] [plotting ] Last Messages
[spkg-install] [plotting ] =============
[spkg-install] [plotting ]     genindex
[spkg-install] [plotting ]     py-modindex
[spkg-install] [plotting ]     search
[spkg-install] [plotting ]     failed
[spkg-install] [plotting ] Loaded Extensions
[spkg-install] [plotting ] =================
[spkg-install] [plotting ] * sphinx.ext.mathjax (8.2.3)
[spkg-install] [plotting ] * alabaster (1.0.0)
[spkg-install] [plotting ] * sphinxcontrib.applehelp (2.0.0)
[spkg-install] [plotting ] * sphinxcontrib.devhelp (2.0.0)
[spkg-install] [plotting ] * sphinxcontrib.htmlhelp (2.1.0)
[spkg-install] [plotting ] * sphinxcontrib.serializinghtml (2.0.0)
[spkg-install] [plotting ] * sphinxcontrib.qthelp (2.0.0)
[spkg-install] [plotting ] * sage_docbuild.ext.inventory_builder (unknown version)
[spkg-install] [plotting ] * sage_docbuild.ext.multidocs (unknown version)
[spkg-install] [plotting ] * sphinx.ext.autodoc.preserve_defaults (8.2.3)
[spkg-install] [plotting ] * sphinx.ext.autodoc.type_comment (8.2.3)
[spkg-install] [plotting ] * sphinx.ext.autodoc.typehints (8.2.3)
[spkg-install] [plotting ] * sage_docbuild.ext.sage_autodoc (8.2.3)
[spkg-install] [plotting ] * sphinx.ext.todo (8.2.3)
[spkg-install] [plotting ] * sphinx.ext.extlinks (8.2.3)
[spkg-install] [plotting ] * sphinx.ext.linkcode (8.2.3)
[spkg-install] [plotting ] * sphinx_copybutton (0.5.2)
[spkg-install] [plotting ] * sphinx_inline_tabs (2023.04.21)
[spkg-install] [plotting ] * IPython.sphinxext.ipython_directive (unknown version)
[spkg-install] [plotting ] * matplotlib.sphinxext.plot_directive (3.10.3)
[spkg-install] [plotting ] * jupyter_sphinx (0.5.3)
[spkg-install] [plotting ] * furo (2024.07.18)
[spkg-install] [plotting ] * sphinx_basic_ng (1.0.0.beta2)
[spkg-install] [plotting ] Traceback
[spkg-install] [plotting ] =========
[spkg-install] [plotting ]       File "/usr/lib/python3.13/site-packages/sphinx/search/__init__.py", line 434, in freeze
[spkg-install] [plotting ]         docnames, titles = zip(*sorted(self._titles.items()), strict=True)
[spkg-install] [plotting ]         ^^^^^^^^^^^^^^^^
[spkg-install] [plotting ]     ValueError: not enough values to unpack (expected 2, got 0)
[spkg-install] [plotting ] The full traceback has been saved in:
[spkg-install] [plotting ] /tmp/sphinx-err-_o5d04fw.log
[spkg-install] [plotting ] To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
[spkg-install] [plotting ] Please also report this if it was a user error, so that a better error message can be provided next time.
[spkg-install] Error building the documentation.
[spkg-install] Traceback (most recent call last):
[spkg-install]   File "/home/dima/software/sage-src/src/build-docs.py", line 11, in <module>
[spkg-install]     main()
[spkg-install]     ~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/__main__.py", line 548, in main
[spkg-install]     build()
[spkg-install]     ~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 645, in _wrapper
[spkg-install]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 136, in f
[spkg-install]     runsphinx()
[spkg-install]     ~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 324, in runsphinx
[spkg-install]     sys.stderr.raise_errors()
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
[spkg-install]     raise OSError(self._error)
[spkg-install] OSError: WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
```
is there a missing separator somewhere? `src/doc/htmlplotting` looks funny.
Only entries related to plotting are failing, which points at an incorrect interaction with jupyter-sphinx

2025-08-22 17:55 UTC, dimpase commented
otherwise it builds and tests mostly pass. doc-pdf is broken, too, in a way similar to already mentioned doc-html

2025-08-22 20:51 UTC, enriqueartal commented
Reverting https://github.com/sagemath/sage/commit/b81df17fc7e9f65ef46b82aabb0c17c37813d3ab as in https://github.com/sagemath/sage/pull/40586#issuecomment-3214560728 solves this problem and also the complete rebuild of sagelib.

2025-08-22 21:48 UTC, dimpase commented
in my doc-html build I see warnings (`Missing character: There is no ...`) about two characters: ⊙ and â

2025-08-22 21:48 UTC, dimpase commented
> Reverting [b81df17](https://github.com/sagemath/sage/commit/b81df17fc7e9f65ef46b82aabb0c17c37813d3ab) as in [#40586 (comment)](https://github.com/sagemath/sage/pull/40586#issuecomment-3214560728) solves this problem and also the complete rebuild of sagelib.

what problem does it solve?

2025-08-22 22:12 UTC, enriqueartal commented
Sorry, I am not sure but I got an error like this and later on, it blamed the absence of sagemath kernel


> I am trying this branch, and still get errors in `make doc-html`, like
> 
> ```
> [spkg-install] [152/190] Generating src/doc/doc-html-reference-plotting with a custom command
> [spkg-install] FAILED: [code=1] src/doc/htmlplotting 
> [spkg-install] /home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/bin/python3 /home/dima/software/sage-src/src/build-docs.py --no-pdf-links reference/plotting html -o src/doc --source /home/dima/software/sage-src/src/doc
> [spkg-install] [plotting ] inventory <https://ipywidgets.readthedocs.io/en/stable/> contains multiple definitions for std:label:examples/Widget Layout.ipynb#display
> [spkg-install] [plotting ] no targets are out of date.
> [spkg-install] [plotting ] WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
> [spkg-install] [plotting ] Versions
> [spkg-install] [plotting ] ========
> [spkg-install] [plotting ] * Platform:         linux; (Linux-6.13.4-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_Ultra_7_165U-with-glibc2.41)
> [spkg-install] [plotting ] * Python version:   3.13.5 (CPython)
> [spkg-install] [plotting ] * Sphinx version:   8.2.3
> [spkg-install] [plotting ] * Docutils version: 0.21.2
> [spkg-install] [plotting ] * Jinja2 version:   3.1.6
> [spkg-install] [plotting ] * Pygments version: 2.19.2
> [spkg-install] [plotting ] Last Messages
> [spkg-install] [plotting ] =============
> [spkg-install] [plotting ]     genindex
> [spkg-install] [plotting ]     py-modindex
> [spkg-install] [plotting ]     search
> [spkg-install] [plotting ]     failed
> [spkg-install] [plotting ] Loaded Extensions
> [spkg-install] [plotting ] =================
> [spkg-install] [plotting ] * sphinx.ext.mathjax (8.2.3)
> [spkg-install] [plotting ] * alabaster (1.0.0)
> [spkg-install] [plotting ] * sphinxcontrib.applehelp (2.0.0)
> [spkg-install] [plotting ] * sphinxcontrib.devhelp (2.0.0)
> [spkg-install] [plotting ] * sphinxcontrib.htmlhelp (2.1.0)
> [spkg-install] [plotting ] * sphinxcontrib.serializinghtml (2.0.0)
> [spkg-install] [plotting ] * sphinxcontrib.qthelp (2.0.0)
> [spkg-install] [plotting ] * sage_docbuild.ext.inventory_builder (unknown version)
> [spkg-install] [plotting ] * sage_docbuild.ext.multidocs (unknown version)
> [spkg-install] [plotting ] * sphinx.ext.autodoc.preserve_defaults (8.2.3)
> [spkg-install] [plotting ] * sphinx.ext.autodoc.type_comment (8.2.3)
> [spkg-install] [plotting ] * sphinx.ext.autodoc.typehints (8.2.3)
> [spkg-install] [plotting ] * sage_docbuild.ext.sage_autodoc (8.2.3)
> [spkg-install] [plotting ] * sphinx.ext.todo (8.2.3)
> [spkg-install] [plotting ] * sphinx.ext.extlinks (8.2.3)
> [spkg-install] [plotting ] * sphinx.ext.linkcode (8.2.3)
> [spkg-install] [plotting ] * sphinx_copybutton (0.5.2)
> [spkg-install] [plotting ] * sphinx_inline_tabs (2023.04.21)
> [spkg-install] [plotting ] * IPython.sphinxext.ipython_directive (unknown version)
> [spkg-install] [plotting ] * matplotlib.sphinxext.plot_directive (3.10.3)
> [spkg-install] [plotting ] * jupyter_sphinx (0.5.3)
> [spkg-install] [plotting ] * furo (2024.07.18)
> [spkg-install] [plotting ] * sphinx_basic_ng (1.0.0.beta2)
> [spkg-install] [plotting ] Traceback
> [spkg-install] [plotting ] =========
> [spkg-install] [plotting ]       File "/usr/lib/python3.13/site-packages/sphinx/search/__init__.py", line 434, in freeze
> [spkg-install] [plotting ]         docnames, titles = zip(*sorted(self._titles.items()), strict=True)
> [spkg-install] [plotting ]         ^^^^^^^^^^^^^^^^
> [spkg-install] [plotting ]     ValueError: not enough values to unpack (expected 2, got 0)
> [spkg-install] [plotting ] The full traceback has been saved in:
> [spkg-install] [plotting ] /tmp/sphinx-err-_o5d04fw.log
> [spkg-install] [plotting ] To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
> [spkg-install] [plotting ] Please also report this if it was a user error, so that a better error message can be provided next time.
> [spkg-install] Error building the documentation.
> [spkg-install] Traceback (most recent call last):
> [spkg-install]   File "/home/dima/software/sage-src/src/build-docs.py", line 11, in <module>
> [spkg-install]     main()
> [spkg-install]     ~~~~^^
> [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/__main__.py", line 548, in main
> [spkg-install]     build()
> [spkg-install]     ~~~~~^^
> [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 645, in _wrapper
> [spkg-install]     getattr(DocBuilder, build_type)(self, *args, **kwds)
> [spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
> [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 136, in f
> [spkg-install]     runsphinx()
> [spkg-install]     ~~~~~~~~~^^
> [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 324, in runsphinx
> [spkg-install]     sys.stderr.raise_errors()
> [spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~^^
> [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
> [spkg-install]     raise OSError(self._error)
> [spkg-install] OSError: WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
> ```
> 
> is there a missing separator somewhere? `src/doc/htmlplotting` looks funny. Only entries related to plotting are failing, which points at an incorrect interaction with jupyter-sphinx

2025-08-22 23:41 UTC, tobiasdiez commented
What is the full stack trace mentioned in the error message?

You might also try it with https://github.com/sagemath/sage/pull/40597 merged.

2025-08-23 00:19 UTC, dimpase commented
> What is the full stack trace mentioned in the error message?
> 
> You might also try it with #40597 merged.

if I don't use `--enable-system-site-packages` then `doc-html` passes for me. So this seems like the never ending shenanigans involving proper installation of sagemath jupyter kernel. Was it fixed in  #40597?

the trouble I see with `doc-pdf` might be due to misconfigured fonts/luatex on the machine I an trying, there "Missing characters" stuff.

2025-08-23 03:52 UTC, dimpase commented
I've fixed fonts for doc-pdf, but now am hitting a situation where some files don't build as `latexmk` runs too many times, as a cache of luatex keeps changing (which is not at all a suprise with running luatex in parallel, so it's pretty non-deterministic - @vbraun - does this match your observations on `doc-pdf` ?).

 I think it's https://tex.stackexchange.com/questions/347980/how-to-make-latexmk-ignore-certain-input-files-as-dependencies
and I am now trying a proposed there way to put certain magic into a `.latexmkrc` file. (I read that it's a recent, 2024, TeXLive "feature")

2025-08-23 17:54 UTC, dimpase commented
> Reverting [b81df17](https://github.com/sagemath/sage/commit/b81df17fc7e9f65ef46b82aabb0c17c37813d3ab) as in [#40586 (comment)](https://github.com/sagemath/sage/pull/40586#issuecomment-3214560728) solves this problem and also the complete rebuild of sagelib.

instead of reverting stuff, just apply #40633 - at least this works for me, I don't get any errors (the only trouble is doc-pdf, but it has nothing to do with any of this).

2025-08-23 18:30 UTC, dimpase commented
after `make doc-clean doc-uninstall` I am getting errors in `make doc-html`: `WARNING: toctree contains reference to nonexisting document 'sage/features'`:

```
[sagemath_doc_html-none] [spkg-install] [24/190] Generating src/doc/doc-inventory-reference-cryptography with a custom command
[sagemath_doc_html-none] [spkg-install] [cryptogra] updating environment: 0 added, 0 changed, 24 removed
[sagemath_doc_html-none] [spkg-install] [cryptogra] no targets are out of date.
[sagemath_doc_html-none] [spkg-install] [cryptogra] The inventory file is in src/doc/inventory/en/reference/cryptography.
[sagemath_doc_html-none] [spkg-install] [25/190] Generating src/doc/doc-inventory-reference-spkg with a custom command
[sagemath_doc_html-none] [spkg-install] FAILED: [code=1] src/doc/inventoryspkg 
[sagemath_doc_html-none] [spkg-install] /home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/bin/python3 /home/dima/software/sage-src/src/build-docs.py --no-pdf-links reference/spkg inventory -o src/doc --source /home/dima/software/sage-src/src/doc
[sagemath_doc_html-none] [spkg-install] [spkg     ] building [inventory]: targets for 440 source files that are out of date
[sagemath_doc_html-none] [spkg-install] [spkg     ] updating environment: 0 added, 441 changed, 31 removed
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/join_feature' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/all' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/sagemath' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/pkg_systems' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/bliss' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/csdp' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/databases' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/dvipng' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/ffmpeg' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/four_ti_2' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/gap' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/graph_generators' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/graphviz' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/imagemagick' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/interfaces' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/internet' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/kenzo' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/latex' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/latte' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/lrs' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/mcqd' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/meataxe' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/mip_backends' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/normaliz' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/pandoc' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/pdf2svg' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/polymake' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/rubiks' [toc.not_readable]
[sagemath_doc_html-none] [spkg-install] [spkg     ] /home/dima/software/sage-src/src/doc/en/reference/spkg/index.rst:28: WARNING: toctree contains reference to nonexisting document 'sage/features/tdlib' [toc.not_readab [...]

2025-08-23 19:10 UTC, dimpase commented
the doc-clean issue is "fixed" by `make sagelib-clean sagelib-uninstall`, so docs cleaning clearly needs work.

2025-08-23 19:37 UTC, dimpase commented
As `doc` is just a `subdir`, I'm not sure what's the proper mesonic way to clean it, if it exists at all.
Perhaps for this `doc` must be something more selfcontained? I don't know.

2025-08-23 21:51 UTC, dimpase commented
As `build/sage-distro/src/doc/` is the place where all the docs are build build, probably all what `make doc-clean` should do is `rm -rf build/sage-distro/src/doc/`.
`src/doc/Makefile` ought to be reviewed, and probably deleted, or severely pruned.

2025-08-23 22:29 UTC, dimpase commented
@tobiasdiez - modulo merging #40597 here, and modulo dealing with `doc-clean`, all good. Let's do the one final push here.

2025-08-23 23:59 UTC, dimpase commented
we'll also need to sort out `sage --docbuild` thing - I'd rather see it gone

2025-08-24 00:05 UTC, tobiasdiez commented
> As `build/sage-distro/src/doc/` is the place where all the docs are build build, probably all what `make doc-clean` should do is `rm -rf build/sage-distro/src/doc/`.

Okay done. This was indeed missing. Could you please give it a try?

> we'll also need to sort out `sage --docbuild` thing - I'd rather see it gone

It should be moved to `tools` like the other development-oriented stuff as well. But let's do it in a follow-up ;-)

2025-08-24 01:21 UTC, dimpase commented
no, running `make doc-clean` followed by `make doc-html` leads to `WARNING: undefined label:`

```
...
[sagemath_doc_html-none] [spkg-install] [thematic_] /home/dima/software/sage-src/src/doc/en/thematic_tutorials/tutorial-implementing-algebraic-structures.rst:221: WARNING: undefined label: 'sage.categories.primer' [ref.ref]
[sagemath_doc_html-none] [spkg-install] [thematic_] The HTML pages are in src/doc/html/en/thematic_tutorials.
[sagemath_doc_html-none] [spkg-install] Error building the documentation.
[sagemath_doc_html-none] [spkg-install] Traceback (most recent call last):
[sagemath_doc_html-none] [spkg-install]   File "/home/dima/software/sage-src/src/build-docs.py", line 11, in <module>
[sagemath_doc_html-none] [spkg-install]     main()
[sagemath_doc_html-none] [spkg-install]     ~~~~^^
[sagemath_doc_html-none] [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/__main__.py", line 548, in main
[sagemath_doc_html-none] [spkg-install]     build()
[sagemath_doc_html-none] [spkg-install]     ~~~~~^^
[sagemath_doc_html-none] [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 137, in f
[sagemath_doc_html-none] [spkg-install]     runsphinx()
[sagemath_doc_html-none] [spkg-install]     ~~~~~~~~~^^
[sagemath_doc_html-none] [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 324, in runsphinx
[sagemath_doc_html-none] [spkg-install]     sys.stderr.raise_errors()
[sagemath_doc_html-none] [spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~^^
[sagemath_doc_html-none] [spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
[sagemath_doc_html-none] [spkg-install]     raise OSError(self._error)
[sagemath_doc_html-none] [spkg-install] OSError: /home/dima/software/sage-src/src/doc/en/thematic_tutorials/coding_theory.rst:100: WARNING: undefined label: 'sage.coding.linear_code' [ref.ref]
```

I gather that not all artifacts related to the docbuild are localized in build/sage-distro/, which is kind of an unpleasant surprise.

2025-08-24 04:45 UTC, dimpase commented
how about 
```diff
diff --git a/Makefile b/Makefile
index 06a87e8f265..4fae3471a74 100644
--- a/Makefile
+++ b/Makefile
@@ -137,14 +137,7 @@ sage_setup-clean:
 build-clean: clean doc-clean sagelib-clean sage_docbuild-clean
 
 doc-clean:
-       if [ -f "$(SAGE_SRC)"/bin/sage-env-config ]; then \
-           . "$(SAGE_SRC)"/bin/sage-env-config; \
-           if [ -n "$$SAGE_LOCAL" ]; then \
-               rm -rf "$$SAGE_LOCAL/share/doc/sage/inventory"; \
-               rm -rf "$$SAGE_LOCAL/share/doc/sage/doctrees"; \
-           fi; \
-       fi; \
-       cd "$(SAGE_SRC)/doc" && $(MAKE) clean
+       (cd "$(SAGE_SRC)/doc" && $(MAKE) clean)
 
 # Deleting src/lib is to get rid of src/lib/pkgconfig
 # that was forgotten to clean in #29082.
diff --git a/src/doc/Makefile b/src/doc/Makefile
index 60166be4129..c371b3cd966 100644
--- a/src/doc/Makefile
+++ b/src/doc/Makefile
@@ -12,10 +12,6 @@
 all: doc-html
 
 clean:
-       rm -rf en/reference/*/sage
-       rm -rf en/reference/documentation/sage_docbuild
-       rm -rf en/reference/sage
-       rm -f common/*.pyc
        rm -rf "$(SAGE_ROOT)/build/sage-distro/src/doc"
 
 doc-html:
```

?
In the 1st chunk, we definitely don't want to invoke `sage-env-config`, which triggers events in sage-distro, like a rebuild of stuff...

less sure about the 2nd chunk - do we keep it to remove old artifacts from the "classic" docbuild?

2025-08-24 04:52 UTC, dimpase commented
Unfortunately, I'm now getting apparent race conditions, such as
```
[spkg-install] [100/190] Generating src/doc/doc-html-reference-manifolds with a custom command
[spkg-install] FAILED: [code=1] src/doc/htmlmanifolds 
[spkg-install] /home/dima/software/sage-src/local/var/lib/sage/venv-python3.13/bin/python3 /home/dima/software/sage-src/src/build-docs.py --no-pdf-links reference/manifolds html -o src/doc --source /home/dima/software/sage-src/src/doc
[spkg-install] [manifolds] inventory <https://ipywidgets.readthedocs.io/en/stable/> contains multiple definitions for std:label:examples/Widget Layout.ipynb#display
[spkg-install] [manifolds] updating environment: 0 added, 0 changed, 68 removed
[spkg-install] [manifolds] no targets are out of date.
[spkg-install] [manifolds] /home/dima/software/sage-src/src/doc/en/reference/manifolds/manifold.rst:4: WARNING: toctree contains reference to non-existing document 'sage/manifolds/manifold' [toc.not_readable]
[spkg-install] [manifolds] /home/dima/software/sage-src/src/doc/en/reference/manifolds/manifold.rst:4: WARNING: toctree contains reference to non-existing document 'sage/manifolds/subset' [toc.not_readable]
[spkg-install] [manifolds] /home/dima/software/sage-src/src/doc/en/reference/manifolds/manifold.rst:4: WARNING: toctree contains reference to non-existing document 'sage/manifolds/structure' [toc.not_readable]
...
[spkg-install] [manifolds] /home/dima/software/sage-src/src/doc/en/reference/manifolds/index.rst:13: WARNING: toctree contains reference to non-existing document 'sage/manifolds/catalog' [toc.not_readable]
[spkg-install] [manifolds] The HTML pages are in src/doc/html/en/reference/manifolds.
[spkg-install] Error building the documentation.
[spkg-install] Traceback (most recent call last):
[spkg-install]   File "/home/dima/software/sage-src/src/build-docs.py", line 11, in <module>
[spkg-install]     main()
[spkg-install]     ~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/__main__.py", line 548, in main
[spkg-install]     build()
[spkg-install]     ~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 670, in _wrapper
[spkg-install]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/builders.py", line 137, in f
[spkg-install]     runsphinx()
[spkg-install]     ~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 324, in runsphinx
[spkg-install]     sys.stderr.raise_errors()
[spkg-install]     ~~~~~~~~~~~~~~~~~~~~~~~^^
[spkg-install]   File "/home/dima/software/sage-src/src/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
[spkg-install]     raise OSError(self._error)
[spkg-install] OSError: /home/dima/software/sage-src/src/doc/en/reference/manifolds/manifold.rst:4: WARNING: toctree contains reference to non-existing document 'sage/manifolds/manifold' [toc.not_readable]
```

which I don't understand. Here is a complete log of this run.
[sagemath_doc_html-none.log](https://github.com/user-attachments/files/21955316/sagemath_doc_html-none.log)

The build is invoked by `make doc-html`, after `make doc-clean` (with the patch above applied)

Well, either a race condition, or some unlean meson cache, no idea.

2025-08-24 06:00 UTC, dimpase commented
most probably cleaning up by just removing a part of build tree is a no-no, as  various ninja and meson artifacts related to the removed part are left inconsistent, and there are there:

```
 $ ls -al build/sage-distro/
total 5176
drwxr-xr-x 6 dima dima     230 Aug 24 00:44 .
drwxr-xr-x 9 dima dima     177 Aug 24 00:03 ..
-rw-r--r-- 1 dima dima      94 Aug 24 00:03 .gitignore
-rw-r--r-- 1 dima dima     110 Aug 24 00:03 .hgignore
-rw-r--r-- 1 dima dima 1274412 Aug 24 00:21 .ninja_deps
-rw-r--r-- 1 dima dima  292273 Aug 24 00:46 .ninja_log
-rw-r--r-- 1 dima dima 2278208 Aug 24 00:03 build.ninja
-rw-r--r-- 1 dima dima 1422179 Aug 24 00:03 compile_commands.json
drwxr-xr-x 2 dima dima    4096 Aug 24 00:03 meson-info
drwxr-xr-x 2 dima dima      27 Aug 24 00:03 meson-logs
drwxr-xr-x 5 dima dima    4096 Aug 24 00:03 meson-private
-rw-r--r-- 1 dima dima      99 Aug 24 00:03 meson-python-native-file.ini
drwxr-xr-x 4 dima dima      29 Aug 24 00:03 src
```
this appears to be a question for Meson/ninja people - how to clean up a part of a build tree? Is it possible?

2025-08-24 08:54 UTC, tobiasdiez commented
Okay, then let's do it the correct way: don't auto-generate stuff in the source folder (but in the build dir), don't copy stuff from the build dir back in the source dir and other stuff like this. Then run the sphinx command against the build dir. 

This is now implemented in https://github.com/sagemath/sage/pull/39030/commits/63620bd4b5d4d1da2a7dec44c32e3ce211ffacc3. But since sphinx doesn't support multiple source directories, the existing files in `src/doc` have to be copied into the build dir. And since meson doesn't support a simple `copyfolder`, this means we have to add a hundred or so very simple meson.build files that copy the existing sources.

This works for me and CI seems to agree.

2025-08-24 08:56 UTC, tobiasdiez commented
> how about
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index 06a87e8f265..4fae3471a74 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -137,14 +137,7 @@ sage_setup-clean:
>  build-clean: clean doc-clean sagelib-clean sage_docbuild-clean
>  
>  doc-clean:
> -       if [ -f "$(SAGE_SRC)"/bin/sage-env-config ]; then \
> -           . "$(SAGE_SRC)"/bin/sage-env-config; \
> -           if [ -n "$$SAGE_LOCAL" ]; then \
> -               rm -rf "$$SAGE_LOCAL/share/doc/sage/inventory"; \
> -               rm -rf "$$SAGE_LOCAL/share/doc/sage/doctrees"; \
> -           fi; \
> -       fi; \
> -       cd "$(SAGE_SRC)/doc" && $(MAKE) clean
> +       (cd "$(SAGE_SRC)/doc" && $(MAKE) clean)
>  
>  # Deleting src/lib is to get rid of src/lib/pkgconfig
>  # that was forgotten to clean in #29082.
> diff --git a/src/doc/Makefile b/src/doc/Makefile
> index 60166be4129..c371b3cd966 100644
> --- a/src/doc/Makefile
> +++ b/src/doc/Makefile
> @@ -12,10 +12,6 @@
>  all: doc-html
>  
>  clean:
> -       rm -rf en/reference/*/sage
> -       rm -rf en/reference/documentation/sage_docbuild
> -       rm -rf en/reference/sage
> -       rm -f common/*.pyc
>         rm -rf "$(SAGE_ROOT)/build/sage-distro/src/doc"
>  
>  doc-html:
> ```
> 
> ? In the 1st chunk, we definitely don't want to invoke `sage-env-config`, which triggers events in sage-distro, like a rebuild of stuff...
> 
> less sure about the 2nd chunk - do we keep it to remove old artifacts from the "classic" docbuild?

This could be used now that everything is outside of the source folder. Not sure if you still want to remove old files that were previously generated in the source directory. (Similarly: we could remove now the gitignore entries for these auto-gen files)

2025-08-24 16:44 UTC, dimpase commented
> This is now implemented in [63620bd](https://github.com/sagemath/sage/commit/63620bd4b5d4d1da2a7dec44c32e3ce211ffacc3)

OK, this appears to work with `make doc`, no ugly errors. For some reason `make doc-pdf` triggers `doc-html` unconditionally, even if the latter was just successfully ran. (but this is minor, if you don't see immediately how to fix it, let's do it in a follow-up PR).

2025-08-24 17:08 UTC, enriqueartal commented
> > This is now implemented in [63620bd](https://github.com/sagemath/sage/commit/63620bd4b5d4d1da2a7dec44c32e3ce211ffacc3)
> 
> OK, this appears to work with `make doc`, no ugly errors. For some reason `make doc-pdf` triggers `doc-html` unconditionally, even if the latter was just successfully ran. (but this is minor, if you don't see immediately how to fix it, let's do it in a follow-up PR).

For me, `make doc-pdf` has always triggered `doc-html`

2025-08-24 17:22 UTC, tobiasdiez commented
The meson-based CI run of the pdf build doesn't trigger a html build. So it seems to be a problem with the makefiles. I suspect the doc build stuff in `build/make/Makefile.in` can now go (just call the correct target in the `doc/Makefile`).

2025-08-24 19:43 UTC, dimpase commented
should we fix it here?

Also, do you know if it's possible to trigger a rebuild of docs for a particular file or document? (just by running ninja with an appropriate target, maybe?)

2025-08-25 03:33 UTC, tobiasdiez commented
It's going to be a bigger project, since you probably also can remove the doc packages under `pkgs`, move the code from the `doc/Makefile` to the root etc. Let's to do this as a follow-up.

> Also, do you know if it's possible to trigger a rebuild of docs for a particular file or document? (just by running ninja with an appropriate target, maybe?)

I don't think there is such a functionality. What would work is a) implement a dep file mechanism so that meson/ninja can correctly track what files are the source of a given doc file or b) run sphinx in the correct subfolder of the builddir.

2025-08-25 03:58 UTC, dimpase commented
ok, fine. This one is good to go then.

2025-08-25 03:58 UTC, dimpase approved these changes

2025-08-25 08:00 UTC, fchapoton commented
I tried and failed to use that (without conda) on two machines. In particular, I met an issue with existing scripts `/usr/local/bin/gp` and `/usr/local/bin/gap`. Once both removed, the build fails on compiling maxima. This is on Ubuntu 24.04.3.
```
FAILED: subprojects/maxima-5.47.0/maxima-5.47.0.stamp
```

2025-08-25 08:14 UTC, tobiasdiez commented
@fchapoton Thanks for testing. Could you please give more details on what the error with gp and gap was? Could you also please attach the meson.log in `build/sage-distro`

2025-08-25 09:34 UTC, fchapoton commented
The `gp` and `gap` scripts in `/usr/local/bin` were similar to
```
maxima:exec sage --maxima "$@"
mwrank:exec sage --mwrank "$@"
```
and complained that sage do not exist. Probably put there by `install_scripts" long ago.

These are the commands that I am trying. I do no want to use conda. These commands are probably very wrong, but I have not found where to look for the correct ones.
```
chapoton@pc-chapoton:~$ python3 -m venv sage-meson
chapoton@pc-chapoton:~$ cd sage-meson/
chapoton@pc-chapoton:~/sage-meson$ ./bin/pip install --verbose --editable .
```

I have no `sage-distro` folder in the build folder

The build fails during 
`Running command Preparing editable metadata (pyproject.toml)`

2025-08-25 09:58 UTC, fchapoton commented
The current failure may be this one :
```
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:3538:61: error: unknown type name ‘pari_prime’; did you mean ‘pari_timer’?
   3538 | static CYTHON_INLINE PyObject* __Pyx_PyLong_From_pari_prime(pari_prime value);
        |                                                             ^~~~~~~~~~
        |                                                             pari_timer
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c: In function ‘__pyx_f_4sage_4libs_4pari_12convert_sage_pari_prime_range’:
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:9263:19: error: ‘pari_PRIMES’ undeclared (first use in this function)
   9263 |     __pyx_t_2 = ((pari_PRIMES[__pyx_v_i]) < __pyx_v_c_start);
        |                   ^~~~~~~~~~~
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:9263:19: note: each undeclared identifier is reported only once for each function it appears in
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:9303:19: warning: implicit declaration of function ‘__Pyx_PyLong_From_pari_prime’; did you mean ‘__Pyx_PyLong_From_int’? [-Wimplicit-function-declaration]
   9303 |       __pyx_t_1 = __Pyx_PyLong_From_pari_prime((pari_PRIMES[__pyx_v_i])); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 581, __pyx_L1_error)
        |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |                   __Pyx_PyLong_From_int
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c: At top level:
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:15479:61: error: unknown type name ‘pari_prime’; did you mean ‘pari_timer’?
  15479 | static CYTHON_INLINE PyObject* __Pyx_PyLong_From_pari_prime(pari_prime value) {
        |                                                             ^~~~~~~~~~
        |                                                             pari_timer
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:15481:24: error: expected end of line before ‘push’
  15481 | #pragma GCC diagnostic push
        |                        ^~~~
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:15482:24: error: expected end of line before ‘ignored’
  15482 | #pragma GCC diagnostic ignored "-Wconversion"
        |                        ^~~~~~~
  src/sage/libs/pari/convert_sage.cpython-312-x86_64-linux-gnu.so.p/src/sage/libs/pari/convert_sage.pyx.c:15486:24: error: expected end of line before ‘pop’
  15486 | #pragma GCC diagnostic pop
```

2025-08-25 12:43 UTC, dimpase commented
@fchapoton - this branch does replace the backend used to build sagelib with meson.

The usual `./bootstrap && ./configure && make`
should work, as if nothing happened

2025-08-25 13:01 UTC, fchapoton commented
ok, thank you Dima for the helpful clarification. Now running, it will take hours.

2025-08-25 15:07 UTC, fchapoton commented
now trying with bootstrap, configure and  `make build -j2`. The build fails in sagelib, with something like
```
[spkg-install]   [7/2145] Compiling C++ object src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_fast_parallel_fmats_methods.pyx.cpp.o
[spkg-install]   FAILED: src/sage/algebras/fusion_rings/fast_parallel_fmats_methods.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_fast_parallel_fmats_methods.pyx.cpp.o
```
and then
```
[spkg-install]   ninja: build stopped: subcommand failed.
[spkg-install]   error: subprocess-exited-with-error
[spkg-install]   
[spkg-install]   × Preparing editable metadata (pyproject.toml) did not run successfully.
[spkg-install]   │ exit code: 1
[spkg-install]   ╰─> See above for output.
[spkg-install]   
[spkg-install]   note: This error originates from a subprocess, and is likely not a problem with pip.
[spkg-install]   full command: /home/chapoton/sage-meson/local/var/lib/sage/venv-python3.12/bin/python3 /home/chapoton/sage-meson/local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpndcn4b6_
[spkg-install]   cwd: /home/chapoton/sage-meson
[spkg-install]   Preparing editable metadata (pyproject.toml): finished with status 'error'
[spkg-install] error: metadata-generation-failed
```

2025-08-25 15:23 UTC, dimpase commented
> The build fails in sagelib, with something like

what is the full C++ error you see? It's in logs/install.log
or in logs/pkgs/sagelib-10.8.beta0.log

(in case, also OS and the gcc version used, whether you set any custom CFLAGS etc...)

2025-08-25 15:33 UTC, fchapoton commented
I am on Ubuntu 24.04.3 using gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0

EDIT: no custom CFLAGS or other flags, I think

I am not able to locate the precise c++ error in this long logs, sorry. Here is an excerpt with "error" inside

```
[spkg-install]   src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp:6894:13: error: 'PyDataType_ELSIZE' was not declared in this scope; did you mean 'PyDataType_ISUNSIZED'?
[spkg-install]    6894 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
[spkg-install]         |             ^~~~~~~~~~~~~~~~~
[spkg-install]         |             PyDataType_ISUNSIZED
[spkg-install]   src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp: In function 'npy_intp __pyx_f_5numpy_5dtype_9alignment_alignment(PyArray_Descr*)':
[spkg-install]   src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp:6928:13: error: 'PyDataType_ALIGNMENT' was not declared in this scope; did you mean 'PyDataType_ISSIGNED'?
[spkg-install]    6928 |   __pyx_r = PyDataType_ALIGNMENT(__pyx_v_self);
[spkg-install]         |             ^~~~~~~~~~~~~~~~~~~~
[spkg-install]         |             PyDataType_ISSIGNED
[spkg-install]   src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp: In function 'PyObject* __pyx_f_5numpy_5dtype_6fields_fields(PyArray_Descr*)':
[spkg-install]   src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp:6966:15: error: 'PyDataType_FIELDS' was not declared in this scope; did you mean 'PyDataType_HASFIELDS'?
```

EDIT: Looks like numpy is involved in the problem

2025-08-25 15:43 UTC, dimpase commented
Could you attach your logs/pkgs/sagelib-10.8.beta0.log here?

2025-08-25 15:48 UTC, fchapoton commented
Voila :
[config.log](https://github.com/user-attachments/files/21972643/config.log)
[sagelib-10.8.beta0.log](https://github.com/user-attachments/files/21972650/sagelib-10.8.beta0.log)

2025-08-25 16:03 UTC, dimpase commented
Oops, the system-wide old numpy leaks into the build, as seen in the sagelib.*.log:

```
[spkg-install]   -> First build of interpreters
[spkg-install]   [4/2145] Compiling C++ object src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_shm_managers.pyx.cpp.o
[spkg-install]   FAILED: src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_shm_managers.pyx.cpp.o
[spkg-install]   g++ -std=gnu++11 -Isrc/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p -Isrc/sage/algebras/fusion_rings -I../../src/sage/algebras/fusion_rings -Isrc/sage/cpython -I../../src/sag
e/cpython -Isrc/sage/libs/ntl -I../../src/sage/libs/ntl -Isrc/sage/rings -I../../src/sage/rings -I../../local/var/lib/sage/venv-python3.12/lib/python3.12/site-packages/cysignals -I/usr/include/python3.12 -I/usr/include/x
86_64-linux-gnu/python3.12 -I/usr/lib/python3/dist-packages/numpy/core/include -I/home/chapoton/sage-meson/local/include/singular -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -D_FIL
E_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -g -O2 -fPIC -DSING_NDEBUG -DOM_NDEBUG -MD -MQ src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_ri
ngs_shm_managers.pyx.cpp.o -MF src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_shm_managers.pyx.cpp.o.d -o src/sage/algebras/fusion_rings/shm_m
anagers.cpython-312-x86_64-linux-gnu.so.p/meson-generated_src_sage_algebras_fusion_rings_shm_managers.pyx.cpp.o -c src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_ri
ngs/shm_managers.pyx.cpp
```

[spkg-install]   In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
[spkg-install]                    from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
[spkg-install]                    from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
[spkg-install]                    from src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp:1138:
[spkg-install]   /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[spkg-install]      17 | #warning "Using deprecated NumPy API, disable it with " \
[spkg-install]         |  ^~~~~~~
[spkg-install]   In file included from /home/chapoton/sage-meson/local/include/singular/kernel/mod2.h:13,
[spkg-install]                    from /home/chapoton/sage-meson/local/include/singular/Singular/libsingular.h:6,
[spkg-install]                    from src/sage/algebras/fusion_rings/shm_managers.cpython-312-x86_64-linux-gnu.so.p/src/sage/algebras/fusion_rings/shm_managers.pyx.cpp:1148:
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/polys/monomials/p_polys.h: In function 'void p_SetCompP(poly, int, ring)':
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/misc/auxiliary.h:101:21: warning: statement has no effect [-Wunused-value]
[spkg-install]     101 | #define TRUE        1
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/polys/monomials/p_polys.h:176:36: note: in expansion of macro 'TRUE'
[spkg-install]     176 | #define p_Test(p,r)               (TRUE)
[spkg-install]         |                                    ^~~~
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/polys/monomials/p_polys.h:260:5: note: in expansion of macro 'p_Test'
[spkg-install]     260 |     p_Test(p, r);
[spkg-install]         |     ^~~~~~
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/polys/monomials/p_polys.h: In function 'spolyrec* p_Copy(poly, ring)':
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/misc/auxiliary.h:101:21: warning: statement has no effect [-Wunused-value]
[spkg-install]     101 | #define TRUE        1
[spkg-install]   /home/chapoton/sage-meson/local/include/singular/polys/monomials/p_polys.h:176:36: note: in expansion of macro 'TRUE'
[spkg-install]     176 | #define p_Test(p,r)               (TRUE)
[spkg-install]         |                                    ^~~~

2025-08-25 16:14 UTC, dimpase commented
> Voila : [config.log](https://github.com/user-attachments/files/21972643/config.log) [sagelib-10.8.beta0.log](https://github.com/user-attachments/files/21972650/sagelib-10.8.beta0.log)

please try to pull the latest update here, and run `make` again. In your case there is an apparent mess-up involving an old system-wide numpy and the Sage's numpy.

2025-08-25 17:00 UTC, dimpase commented
I'm discussing the numpy issue here https://github.com/mesonbuild/meson-python/issues/791#issuecomment-3221023848 - it seems that meson devs think this should not have happened...

2025-08-25 17:32 UTC, vbraun commented
Documentation build fails with
```
[sagelib-10.8.beta0] [spkg-install]   ../../src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/meson.build:27:16: ERROR: File conf.py does 
not exist. 
````

2025-08-25 18:35 UTC, dimpase commented
> Documentation build fails with
> 
> ```
> [sagelib-10.8.beta0] [spkg-install]   ../../src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/meson.build:27:16: ERROR: File conf.py does 
> not exist. 
> ```

how do you invoke the docbuild?
`make doc-html` and `make doc-pdf` work for me, on Linux and macOS

2025-08-25 19:01 UTC, fchapoton commented
on another machine (ubuntu 24.04.3) compilation and `make doc-html` both work

2025-08-25 20:49 UTC, kiwifb commented
> > Documentation build fails with
> > ```
> > [sagelib-10.8.beta0] [spkg-install]   ../../src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/meson.build:27:16: ERROR: File conf.py does 
> > not exist. 
> > ```
> 
> how do you invoke the docbuild? `make doc-html` and `make doc-pdf` work for me, on Linux and macOS
> 
> @tobiasdiez - What I don't understand is why `meson.build` is invoked in $SAGE_SRC. Shouldn't a copy in `build/sage-distro/` be invoked instead?

Actually, I am at a similar point in sage-on-gentoo and contemplating my next move. So, how do I get there:
1) I build and install sagemath with meson. Done, dusted and source tree deleted.
2) now I cleanly checkout this branch.
3) meson setup build/sage-distro # so that I match what is in src/doc/Makefile. I notice that in a standard install, it only matches for an editable install. I presume it fails miserably in the other case.
4) cd src/doc && make doc-html
a stream of 191 instances of something like
```
Versions
========

* Platform:         linux; (Linux-6.12.41-gentoo-dist-x86_64-Intel-R-_Core-TM-_i7-9700_CPU_@_3.00GHz-with-glibc2.41)
* Python version:   3.13.5 (CPython)
* Sphinx version:   8.2.3
* Docutils version: 0.21.2
* Jinja2 version:   3.1.6
* Pygments version: 2.19.2

Last Messages
=============

None.

Loaded Extensions
=================

None.

Traceback
=========

    Traceback (most recent call last):
      File "/usr/lib/python3.13/site-packages/sphinx/cmd/build.py", line 414, in build_main
        app = Sphinx(
            srcdir=args.sourcedir,
        ...<14 lines>...
            exception_on_warning=args.exception_on_warning,
        )
      File "/usr/lib/python3.13/site-packages/sphinx/application.py", line 266, in __init__
        self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                      ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/sphinx/config.py", line 354, in read
        raise ConfigError(
            __("config directory doesn't contain a conf.py file (%s)") % confdir
        )
    sphinx.errors.ConfigError: config directory doesn't contain a conf.py file (/home/portage/sci-mathematics/sagemath-doc-9999/work/sagemath-doc-9999/build/sage-distro/src/doc/it/tutorial)
```
Do those files get copied over when you build the python package with meson? 
My logical next move is to build the doc, just after the regular meson build before system wide install. And amend that `src/doc/Makefile` because `build/sage-distro` will not be where Gentoo builds things.

2025-08-25 21:41 UTC, dimpase commented
@kiwifb  and @vbraun - please, this PR has nothing to do with the meson-based custom sagelib install. This PR is for
`./bootstrap && ./configure <...opts here..> && make doc-html`
And our CI.

It might have broken your custom stuff. We have not fully codified anything of this sort yet, so well, it might have broken it. Like Volker says it breaks something, probably a similar custom stuff (?),  in a repo I cannot even see! 

Let us get this in, and work out how the custom stuff has to be modified and codified.

2025-08-25 21:46 UTC, dimpase commented
@kiwifb - on Gentoo, `./bootstrap && ./configure --enable-system-site-packages && make` is a close, modulo few Python packages, (by the way, please merge #40568 (and review it again)) approximation of a pure meson build of sagelib.

2025-08-25 23:05 UTC, kiwifb commented on build/pkgs/sagelib/spkg-install.in
> +    sdh_pip_install --no-build-isolation . --config-settings=setup-args="-DSAGE_LOCAL=$SAGE_LOCAL"
So, a concrete comment @dimpase in the non-editable install you do not set the `build-dir`. So, I am expecting that if you try to build the documentation with `make doc-html` after a non editable install, it will fail because it specifically looks for `build/sage-distro` and I am fairly sure that will not be what pip uses by default.

2025-08-26 00:23 UTC, vbraun commented
I'm guessing this breaks incremental builds, ok but maybe make it more explicit then there will be fewer failure reports from people that test incremental builds

2025-08-26 00:57 UTC, dimpase commented
> I'm guessing this breaks incremental builds, ok but maybe make it more explicit then there will be fewer failure reports from people that test incremental builds

before trying this PR one most probably needs `make distclean`, as it's a big change.

Then it should be fine (perhaps more cleaning up of things triggering senseless recursive rebuilds might be needed)

2025-08-26 01:02 UTC, dimpase commented on build/pkgs/sagelib/spkg-install.in
> +    sdh_pip_install --no-build-isolation . --config-settings=setup-args="-DSAGE_LOCAL=$SAGE_LOCAL"
`SAGE_EDITABLE=no make  build` quickly errors out:

```
[sagelib-10.8.beta0] [spkg-install] Installing sagelib-10.8.beta0
[sagelib-10.8.beta0] [spkg-install] usage: python -m build [-h] [--version] [--verbose] [--sdist] [--wheel]
[sagelib-10.8.beta0] [spkg-install]                        [--outdir PATH] [--skip-dependency-check]
[sagelib-10.8.beta0] [spkg-install]                        [--no-isolation | --installer {pip,uv}]
[sagelib-10.8.beta0] [spkg-install]                        [--config-setting KEY[=VALUE]]
[sagelib-10.8.beta0] [spkg-install]                        [srcdir]
[sagelib-10.8.beta0] [spkg-install] python -m build: error: unrecognized arguments: --config-settings=setup-args=-DSAGE_LOCAL=/home/dima/software/sage-src/local
```
@tobiasdiez - what's the correct way to do this, or it's indeed broken?
It seems to have been broken before this PR, too, no?

2025-08-26 04:48 UTC, tobiasdiez commented
> Documentation build fails with
> 
> ```
> [sagelib-10.8.beta0] [spkg-install]   ../../src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/meson.build:27:16: ERROR: File conf.py does 
> not exist. 
> ```

@vbraun
That comes since your branch includes a commit that deletes it: https://github.com/vbraun/sage/commit/e01e900a6bd8d221ca490ec78f2463c683793310

Would it be possible to test this branch here on isolation on the build bots. Since it completely changes how sagelib is built, it's very likely that other PRs are indeed changing things in a way that needs slight modification afterwards.

2025-08-26 05:04 UTC, tobiasdiez commented on build/pkgs/sagelib/spkg-install.in
> +    sdh_pip_install --no-build-isolation . --config-settings=setup-args="-DSAGE_LOCAL=$SAGE_LOCAL"
Thanks a lot @kiwifb! I indeed missed to change the builddir for non-editable builds. Should be fixed now.

@dimpase just a typo due to different conventions of `build` and `pip install` (config-setting vs config-settings). What I don't understand is why the non-editable install needs to create wheels using `build`, instead of using `pip install` without `-e`. But that's for another day.

2025-08-26 08:50 UTC, fchapoton commented
I confirm that the build works with the current branch on the Ubuntu machine where it failed because of NumPy.

2025-08-26 12:39 UTC, tobiasdiez commented
> I confirm that the build works with the current branch on the Ubuntu machine where it failed because of NumPy.

Awesome, thanks for testing!

2025-08-27 03:30 UTC, tobiasdiez commented
> Documentation build fails with
> 
> ```
> [sagelib-10.8.beta0] [spkg-install]   ../../src/doc/en/thematic_tutorials/explicit_methods_in_number_theory/meson.build:27:16: ERROR: File conf.py does 
> not exist. 
> ```

Fixed that now by removing the conf.py files also here in this PR. Since the CI is passing, setting it back to positive review.

2025-08-27 16:24 UTC, vbraun commented
merge conflict

2025-08-28 07:07 UTC, tobiasdiez commented
> merge conflict

Resolved now. @vbraun

2025-09-07 10:12 UTC, merged

2025-09-27 22:07 UTC, antonio-rojas commented
This breaks the standalone build of the docs. Previously I was doing
```
  meson setup build sage
  meson compile -C build doc-html
```
and this no longer works, sphinx throws multiple errors such as
```
[tutorial ] Configuration error!
[tutorial ] Versions
[tutorial ] ========
[tutorial ] * Platform:         linux; (Linux-6.15.7-arch1-1-x86_64-with-glibc2.42)
[tutorial ] * Python version:   3.13.7 (CPython)
[tutorial ] * Sphinx version:   8.2.3
[tutorial ] * Docutils version: 0.21.2
[tutorial ] * Jinja2 version:   3.1.6
[tutorial ] * Pygments version: 2.19.2
[tutorial ] Last Messages
[tutorial ] =============
[tutorial ] None.
[tutorial ] Loaded Extensions
[tutorial ] =================
[tutorial ] None.
[tutorial ] Traceback
[tutorial ] =========
[tutorial ]       File "/usr/lib/python3.13/site-packages/sphinx/config.py", line 354, in read
[tutorial ]         raise ConfigError(
[tutorial ]             __("config directory doesn't contain a conf.py file (%s)") % confdir
[tutorial ]         )
[tutorial ]     sphinx.errors.ConfigError: config directory doesn't contain a conf.py file (/build/sagemath-doc-git/src/build/src/doc/ru/tutorial)
[tutorial ] The full traceback has been saved in:
[tutorial ] /tmp/sphinx-err-6fr5ejwk.log
[tutorial ] To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
[tutorial ] Please also report this if it was a user error, so that a better error message can be provided next time.
```
The `conf.py` files are in the source dirs, not the build dirs.

2025-09-28 02:21 UTC, tobiasdiez commented
The conf.py files should be copied upon build to the build dir via: https://github.com/sagemath/sage/blob/f4adc250dcc80e99aa25e7146b5eae3daaa41d88/src/doc/ru/tutorial/meson.build#L5

Is this not working for you?

(`build/sagemath-doc-git/src/build` that part looks a bit strange to me. is `/build/sagemath-doc-git/src` the root of the sage project in this case?)

2025-09-28 03:11 UTC, kiwifb commented
I must say that matches my experiences when I looked into it a few weeks ago when testing the ticket. I used to have a separate from scratch build of the documentation and doing the same thing that antonio-rojas mentions gave the same results. I may have commented upon it, that it was looking like, I was going to have to build the documentation straight after sage and before installing it (sage that is). I have not looked at it again since then.

2025-09-28 07:00 UTC, antonio-rojas commented
> The conf.py files should be copied upon build to the build dir via:
> 
> https://github.com/sagemath/sage/blob/f4adc250dcc80e99aa25e7146b5eae3daaa41d88/src/doc/ru/tutorial/meson.build#L5
> 
> Is this not working for you?

No. In the `build.ninja` file I see many `/foo/conf.py` targets that are supposed to do the copying, but they are not dependencies of the `doc-html` target, only of the `all` target.

> (`build/sagemath-doc-git/src/build` that part looks a bit strange to me. is `/build/sagemath-doc-git/src` the root of the sage project in this case?)

That's fine, it's the build path in the container where we build distro packages (I get the same issue building locally so it is irrelevant).

2025-09-28 08:28 UTC, antonio-rojas commented
Uncommenting the commented out line `#input: doc_src,` in https://github.com/sagemath/sage/blob/10.8.beta5/src/doc/meson.build#L82 fixes this.

However, this creates a humongous `build.ninja` file that grows quadratically in the number of doc files, since all doc sources are added as dependencies of every single file target, and the target build step takes longer than building the sage library itself.

2025-09-28 09:24 UTC, tobiasdiez commented
Okay, thanks. So it's indeed only a build-target-dependency issue. I don't have much time at the moment to look into this more, but perhaps https://github.com/sagemath/sage/pull/40904 fixes this.

Still find it curious that the doc build succeeds on CI with what looks like essentially the same commands as what you use...