a few details in master reference file
sagemath/sage pull request #39134
Opened 2024-12-15 19:50 UTC by fchapoton

in particular, using the arxiv role

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.

2024-12-15 21:24 UTC, dcoudert requested changes

2024-12-15 21:24 UTC, dcoudert commented on src/doc/en/reference/references/index.rst
> +              `arxiv:`cs/0609020`
should be `:arxiv:`

2024-12-15 21:24 UTC, dcoudert commented on src/doc/en/reference/references/index.rst
> +.. [CFZ2002] Chapoton, Fomin, Zelevinsky - *Polytopal realizations of
add first names ?

2024-12-16 17:00 UTC, dcoudert approved these changes
LGTM.

2024-12-16 17:03 UTC, fchapoton commented
merci David ! :christmas_tree:

2024-12-22 17:02 UTC, merged