Add hyperelliptic curves using the smooth model
sagemath/sage pull request #39161
Opened 2024-12-18 17:35 UTC by GiacomoPope

The current implementation of hyperelliptic curves in SageMath uses the projective plane model. Although this works nicely enough for imaginary curves with only one point at infinity, it is not descriptive enough for the real models.

This PR is a total rewrite of the hyperelliptic curve classes to instead use the smooth model for hyperelliptic curves which facilitates implementing arithmetic of Jacobians of hyperelliptic curves for (almost) all cases. In particular, now if one tries to perform arithmetic on Jac(C) one either gets the correct value or a well-handled error instead of just returning something which is wrong.

This PR looks WAY bigger than it is, as it duplicates ALL code from `hyperelliptic_curves` and then has modifications to allow this to work in the new curve model. I believe the best thing to do in the long run is to depreciate the old hyperelliptic curve impl and have this replace it, but this will take years(?) so I think we'll just have to have both side by side for a while.

This PR still needs a lot of work including:

- more tests
- better comments and docstrings
- potentially refactoring of which files belong where

but the code has sat at this stage for a long time without much more progress from the three of us, so I think the best thing to do is open up the PR and try and get some extra attention on getting this code ready to be included.

2024-12-19 06:55 UTC, user202729 commented
Not an expert here, but why exactly would it be backwards incompatible to just replace the old class with the new one entirely? (can't you find some reasonable bijective correspondence between old and new model?)

2024-12-19 10:50 UTC, GiacomoPope commented
there's some details about it here: https://groups.google.com/g/sage-devel/c/kIwcYIzm4is/m/b3eefNSzAQAJ

generally, my understanding is that if a user is running code with `hyperelliptic` right now and we dropped this in to replace it, there's a good chance their code would either not work, or work in an unexpected way and so we must do the proper depreciation.

In my mind that means

1. Add this code in without any warnings
2. Add a depreciation warning to `hyperelliptic` once this is feature full
3. Once the depreciation time is elapsed, make `hyperelliptic` the  `hyperelliptic_sm`. Also keep `hyperelliptic_sm` and add a new depreciation to `hyperelliptic_sm` warning to move to `hyperelliptic`
4. Delete `hyperelliptic_sm` and have only `hyperelliptic` which is this new code

2024-12-19 10:50 UTC, GiacomoPope commented
@grhkm21 looks like your most recent commits broke other doctests

2024-12-24 14:51 UTC, user202729 commented
Do you think it's worth making a global flag `hyperelliptic_curve.use_smooth_model(True/False)` (so e.g. it takes less time to deprecate things, for example if an user now want to use the smooth model they need to type `SmoothModel` everywhere, then after deprecation period they need to delete that everywhere)

Of course in that case whatever the global variable is, the user can always import explicitly from one of the two module to select which to use regardless.

Some cursory notes:

* in

	```diff
	+    The construction of hyperelliptic curves is supported over different fields. The correct class is chosen automatically::
	+        sage: F = FiniteField(13)
	+        sage: S.<x> = PolynomialRing(F)
	+        sage: HF = HyperellipticCurve(x^5 + x^4 + x^3 + x^2 + x + 1, x^3 + x); HF
	+        Hyperelliptic Curve over Finite Field of size 13 defined by y^2 + (x^3 + x)*y = x^5 + x^4 + x^3 + x^2 + x + 1
	+        sage: type(HF)
	+        <class 'sage.schemes.hyperelliptic_curves.constructor.HyperellipticCurve_g2_FiniteField_with_category'>
	```

	This still uses the old class? (a few more examples below)

* I don't think it's a good idea to copy the docstring between the module and the `def HyperellipticCurveSmoothModel`. Since the user is most likely to type `HyperellipticCurveSmoothModel?` in the sage command-line it seems best to put all these in the function docstring, then in the module docstring type ``See :func:`HyperellipticCurveSmoothModel` for more details.``

* in

	```diff
	+        # Ensure we are adding two divisors
	+        assert isinstance(other, type(self))
	```

	no harm, but redundant. The coercion model ensures `_add_` is only ever called on elements with same parent.

* in

	```diff
	+    def _richcmp_(self, other, op):
	+        """
	+        Test the weighted projective equality of two points.
	+        ...
	+        return richcmp(self._coords, other._coords, op)
	```

	this feels dangerous (no total ordering induced on points?) since there is `normalize_coordinates()` implemented I guess that can be used (is the performance hit worth it?)

* in

	```
	+    def __hash__(self):
	+        """
	+        Computes the hash value of this point.
	+
	+        OUTPUT: Integer.
	+
	+        EXAMPLES::
	+
	+            sage: P.<x,y> = ProjectiveSpace(QQ, 1)
	+            sage: hash(P([1/2, 1])) == hash(P.point([1, 2], False))
	+            True
	+        """
	+        P = copy(self)
	+        P.normalize_coordinates()
	+        return hash(tuple(P))
	+
	```

	There's something that feel morally wrong. Either `normalize_coordinates` is completely harmless and it's free to invoke it everywhere (including `_repr_`), then the copy is not necessary, or it dangerously mutates the object (in which case it seems better to make as many things immutable as possible). I prefer the former.

2024-12-24 22:47 UTC, GiacomoPope commented
A lot of these points are very good, thank you. I'll try and fix them all after the holidays!

2024-12-25 02:21 UTC, grhkm21 commented
@GiacomoPope can you mark this PR as draft?

2025-02-20 13:22 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +        element `D_1 = [P - Q] = [P + (-Q) - D_\infty]` on the Jacobian.
all the changes about removing `::` are bad and should be reverted

2025-02-20 13:42 UTC, sabrinakunzweiler commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +        element `D_1 = [P - Q] = [P + (-Q) - D_\infty]` on the Jacobian.
done

2025-02-20 17:32 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/jacobian_homset_split.py
> +        """
```suggestion
        r"""
```

2025-02-20 17:32 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/jacobian_homset_split.py
> +        """
This will fix the warning about `\i`

2025-02-20 18:16 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +
```suggestion

```

2025-02-20 18:17 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +
see the Lint warnings about spaces at the end of lines : they should be removed

2025-02-20 18:18 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +        Returns the Jacobian of the hyperelliptic curve.
```suggestion
        Return the Jacobian of the hyperelliptic curve.
```

2025-02-21 08:07 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +        Returns the Jacobian of the hyperelliptic curve.
The first line in the doc should use "imperative mode", like when giving an order.

2025-05-07 20:38 UTC, vincentmacri commented
> This PR looks WAY bigger than it is, as it duplicates ALL code from `hyperelliptic_curves` and then has modifications to allow this to work in the new curve model. I believe the best thing to do in the long run is to depreciate the old hyperelliptic curve impl and have this replace it, but this will take years(?) so I think we'll just have to have both side by side for a while.

Can the duplicated code be moved into a file of utility functions or something like that? Would it be possible to change the old implementation to act as a wrapper for your new one so we don't have two implementations of basically the same thing lying around until we deprecate the old interface?

> This code needs more work, and lots of time spent on the review
I think I have the expertise to review this as I'm currently writing my Master's thesis on a related topic. However as I'm currently writing said thesis I won't have the time to do a big review until the thesis is done (probably not until late August at the earliest). Happy to have higher-level (and less time-consuming discussions) in the meantime though.

2025-05-15 17:27 UTC, grhkm21 commented
Sorry for the late reply.

> > This PR looks WAY bigger than it is, as it duplicates ALL code from `hyperelliptic_curves` and then has modifications to allow this to work in the new curve model. I believe the best thing to do in the long run is to depreciate the old hyperelliptic curve impl and have this replace it, but this will take years(?) so I think we'll just have to have both side by side for a while.
> 
> Can the duplicated code be moved into a file of utility functions or something like that? Would it be possible to change the old implementation to act as a wrapper for your new one so we don't have two implementations of basically the same thing lying around until we deprecate the old interface?

I don't see how this can be done. As mentioned, our implementation is incompatible with the existing implementation. Indeed, the main reason why this PR exists at all is because the existing implementation is wrong in the even degree model case (e.g. #32024 as referenced in the PR description). We fixed this by using a completely separate representation of points (IIRC) which is why it's incompatible.

> > This code needs more work, and lots of time spent on the review
> 
> I think I have the expertise to review this as I'm currently writing my Master's thesis on a related topic. However as I'm currently writing said thesis I won't have the time to do a big review until the thesis is done (probably not until late August at the earliest). Happy to have higher-level (and less time-consuming discussions) in the meantime though.

That would be great. However, I still think it's unreasonable for one person to review 14k lines of code (`cloc` reports 4k). How should we handle this PR? I propose we can PR e.g. "file by file", or PR the class structure first and actual useful methods later.

2025-05-15 22:46 UTC, vincentmacri commented
> That would be great. However, I still think it's unreasonable for one person to review 14k lines of code (`cloc` reports 4k). How should we handle this PR? I propose we can PR e.g. "file by file", or PR the class structure first and actual useful methods later.

If there is any way to break this PR up that would be ideal. If you have any classes/files/modules that do something on their own (for example, construct a hyperelliptic curve without the ability to do Jacobian arithmetic on it) you could separate those out. If you can't split up the PR I think we could just review it slowly, reviewing a component at a time until it's all been looked at.

As for reviewing the class structure, we might want someone with a bit more experience with Sage's class structure to take a look. @kwankyu somewhat recently added general Jacobian arithmetic to Sage, so maybe he could provide some input? It might even be possible in terms of the class structure for your implementation to use the general Jacobian interface @kwankyu implemented.

Here's what I'd say for the class structure though. There are several algorithms for hyperelliptic Jacobian arithmetic. For instance, for the even degree case, the two main ones I'm familiar with (not counting the variants of these) are due to Paulus and Rück, and to Galbraith, Harrison, and Mireles. Addition can be done with Cantor's algorithm or NUCOMP. You don't need to implement all these algorithms and variants, that would make this big PR even bigger. But it would be good if the class structure is setup in a way that we (Sage developers) or even users can, by extending the appropriate classes, add implementations of hyperelliptic arithmetic that use different algorithms. We have something like this for general Jacobian arithmetic (https://doc.sagemath.org/html/en/reference/function_fields/sage/rings/function_field/jacobian_base.html) where we have the `hess`, `km_small`, `km_medium`, and `km_large` algorithms available.

Lastly, and this goes for all PRs, but especially one of this size: make sure you have doctests for everything, that all the doctests are passing, and that the linter is passing before asking for a code review.

2025-05-15 23:32 UTC, grhkm21 commented
FYI (again) #40070 is ready for review

2025-08-16 15:50 UTC, GiacomoPope commented
Is this all held up by 40070 atm?

2025-08-18 18:23 UTC, vincentmacri commented
> Is this all held up by 40070 atm?

If it depends on #40070 then yes. I commented there that I want the docbuild to be working before I try to review it further (if it works locally but CI is broken then fine, just let me know).

As for reviewing, I will have limited time to review this until early/mid September (when I defend my Master's thesis on curve arithmetic). I have the time for higher-level discussions before then, but I won't have the time to really look at the code and give a proper review until after I defend. I expect I'll have time for a detailed review after September 8th, maybe a few days earlier or later depending on how many revisions I'm asked to make. The first thing I'll ask when I review it is to make sure all the tests pass and that the documentation builds successfully, so if you can get that working by September 8th, it would help me a lot in reviewing this faster.

2025-08-18 18:35 UTC, vincentmacri commented
> > Can the duplicated code be moved into a file of utility functions or something like that? Would it be possible to change the old implementation to act as a wrapper for your new one so we don't have two implementations of basically the same thing lying around until we deprecate the old interface?
> 
> I don't see how this can be done. As mentioned, our implementation is incompatible with the existing implementation. Indeed, the main reason why this PR exists at all is because the existing implementation is wrong in the even degree model case (e.g. #32024 as referenced in the PR description). We fixed this by using a completely separate representation of points (IIRC) which is why it's incompatible.

If the existing implementation is mathematically wrong then I'm comfortable breaking existing code that uses it (because I would consider that code to be already broken), but we should double-check what our formal deprecation policy is for situations like this where we have a public API that is wrong for certain inputs in a way that cannot be fixed without an API change. For imaginary models (which are not broken in Sage), isn't what we do now just weighted projective space with the same weight on all three coordinates? That would seem to be a special case of the weighted projective models you're implementing.

In the meantime, you could add a [stopgap warning](https://doc.sagemath.org/html/en/reference/misc/sage/misc/stopgap.html) and [deprecation warning](https://doc.sagemath.org/html/en/reference/misc/sage/misc/superseded.html) for real models to speed up that deprecation.

2025-08-18 18:52 UTC, vincentmacri commented
> How should we handle this PR? I propose we can PR e.g. "file by file", or PR the class structure first and actual useful methods later.

I've thought more about this. I see that the PR has code for finite fields, the rational field, and p-adic fields. You could split it up to add one at a time. Unless there are technical reasons preventing this, my preference would be finite fields, then rational field, then p-adic fields just because that's the order of my familiarity with the subject so it will be easiest for me to review it in that order. I won't complain if you want to do the rational field before finite fields, but if you do p-adic fields first then I'll have to simultaneously read up on p-adic hyperelliptic arithmetic and get familiar with your code which will slow down how quickly I can review it.

2025-09-11 17:41 UTC, vincentmacri commented
I have time to start looking at this now.

I understand there is this PR and the related #40070. Are there any others? Where should I start? Which are ready for review?

2025-11-13 20:10 UTC, vincentmacri commented
@GiacomoPope Are there any PRs related to this work that are ready for review?

2025-11-13 20:31 UTC, GiacomoPope commented
As far as this code is considered I think the only PR above it is one by @grhkm21 but I've not checked how that's going. Sorry.

2025-11-17 17:24 UTC, vincentmacri commented
> As far as this code is considered I think the only PR above it is one by @grhkm21 but I've not checked how that's going. Sorry. 

Okay. @user202729 has revived that work in #41170 and I'm reviewing it. If you could merge the latest develop into this PR, and make sure the linter and tests are passing, then I can review this PR after #41170 is merged. You'll probably need to merge develop again once #41170 is merged since this PR depends on it.

2025-11-21 17:23 UTC, GiacomoPope commented
I see that progress has been made with the projective model, so I'm going to open this up for review -- there's probably a lot to adjust and there might be some necessary changes but I think it's best to work with this as some enormous PR rather than lots of small ones as the time I have to work on this is fleeting and as it's just a lot of new code it should hopefully only help research rather than break any existing code.

2025-11-21 17:51 UTC, vincentmacri commented
#41170 has been approved. Once #41170 is merged into develop, merge develop again into this PR. I'll ignore the code here for the time being about weighted projective curves/points since that's all in #41170.

To speed up the review, make sure you've done the following:

- Linter and (relevant) tests are passing
  - I'm not going to review a PR this big until the linter is passing and all relevant tests are passing. You can of course ping me if you want to discuss how to resolve some failure. Most linter failures can be fixed by `ruff`.
- Docstrings for all modules, classes, and methods
  - AUTHORS block for module docstrings
  - Link to relevant papers/textbooks for where algorithms come from (especially GHM balanced divisors)
- Copyright headers on all files
- Sufficient tests
  - You can test an objects `G` in Sage with `TestSuite(G).run()`. `TestSuite(G).run(verbose=True)` is useful for debugging. This will run a generic test suite for whatever type of object you've implemented, as long as you've inherited from the correct classes and have the correct categories. So if you've implemented an abelian group (like the Jacobian) it will run a full test suite that all abelian group axioms hold for a few elements. You need to implement `some_elements()` and (I think) `_an_element_()` to provide inputs to TestSuite, but that should be done anyway. `random_element` is also useful to have, and can be used to implement `some_elements` and `_an_element_`. Ideally, every object should run its TestSuite at least once in the doctests.

> I think it's best to work with this as some enormous PR rather than lots of small ones

I think that makes sense. It will probably be faster than separate smaller PRs, but it will still take a while to review a PR of this size.

> the time I have to work on this is fleeting

Just to clarify, do you mean you will soon have no more time to work on this, or that you only have small amounts of time here and there to work on this, but with no upcoming endpoint where you can't work on it anymore?

My next 3 weeks are quite busy, until December 15. Would you prefer I do many small passes over different parts of your code looking for different things each time over the next few weeks as I am able, or would you prefer a large review of everything at once in about 3-4 weeks?

2025-11-24 15:05 UTC, GiacomoPope commented
Sorry for the delay in response. I have small amounts of time semi-infrequently rather than lost of free time, which almost never happens now. I am grateful for any work you do on the review here though and will try and help however I can to get this reviewed efficiently

2025-11-24 18:10 UTC, vincentmacri commented
Okay. I do really want this to get into Sage (I think I have my own implementation of balanced divisor arithmetic for spit hyperelliptic curves lying around somewhere, but it's somewhat hacky and not remotely in a state to be made into a PR). I'll take a deep dive into your code in about 3 weeks when I'll have more time. If you could get this to a state where all relevant CI tests passing in the meantime, that would be a big help.

So I know which sources to look at when reviewing, does your balanced divisors implementation align closer to the description in the GHM paper or the description in Galbraith's book? Or a bit of both? I find the notation in Galbraith's book to be a bit cleaner, but it also has some non-obvious typos (which I know you know: when I sent some corrections to Galbraith a while back he forwarded me an email you sent him with some other corrections).

2025-11-24 19:01 UTC, fchapoton commented
I allowed myself a little fix about the linter warnings (partial fix only)

2025-11-25 12:10 UTC, GiacomoPope commented
> I allowed myself a little fix about the linter warnings (partial fix only)

Thanks so much @fchapoton, I'll attempt to fix the rest, now we have `uv` this is much easier for me to do (shows how long ive been ignoring sage that im only trying uv now...)

> So I know which sources to look at when reviewing, does your balanced divisors implementation align closer to the description in the GHM paper or the description in Galbraith's book? Or a bit of both?

So a bit of both, probably for the same reasons as you. I like Galbraith's book, but the typos meant i needed the paper to fix a few pieces so in the end there's an amalgamation of both resources.

(Aside) did you find a correction to the proof with the typo? I meant to, but never got around to it.

2025-11-25 13:35 UTC, GiacomoPope commented
It looks like the documentation build is broken in other PR, so maybe this is unrelated to this branch?

2025-11-25 17:51 UTC, vincentmacri commented
> (Aside) did you find a correction to the proof with the typo? I meant to, but never got around to it.

It's been a while since I looked at it, I can't recall.

2025-11-25 17:51 UTC, vincentmacri commented
> It looks like the documentation build is broken in other PR, so maybe this is unrelated to this branch?

Yeah, doc build is indeed broken on CI right now.

2025-12-10 19:13 UTC, vincentmacri commented
@GiacomoPope Can you merge the latest develop? That should trigger a new CI run and the docbuild is working now. Also resolve the merge conflicts.

I have some long flights with long layovers next week, so I'll try to look at this then.

2025-12-12 15:39 UTC, GiacomoPope commented
I have done the boring job of adding copyright (I hope I was accurate, some of the files we've changed are as old as sage itself...)

I also resolved conflicts and merged. I will keep an eye on the CI and keep it up to date for your flight

2025-12-14 19:28 UTC, vincentmacri requested changes
A quick first look, I only got a chance to look at some of the files so this is by no means exhaustive feedback. But there is some general formatting/style/best practices feedback that you can apply throughout. I have some more general questions that I'll post in a separate comment.

With other things I had going on mostly out of the way now (i.e. most of my PhD coursework) this PR is now near the top of my priority list, so other than the upcoming holidays and my conference travel this week I hope to be able to respond fairly quickly now.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +
```suggestion
Adapted from ``sage/schemes/hyperelliptic_curves/constructor.py``
```

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +r"""
Maybe just name this file ``constructor.py`` for consistency with the existing elliptic and hyperelliptic packages?

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +#                     2006 David Kohel <kohel@maths.usyd.edu>
```suggestion
#       Copyright (C) 2006 David Kohel <kohel@maths.usyd.edu>
#                     2019 Anna Somoza <anna.somoza.henares@gmail.com>
#                     2025 Sabrina Kunzweiler
#                     2025 Gareth Ma
#                     2025 Giacomo Pope

```

This should be sorted from oldest to newest. For the sake of consistency, I think it's better to have one person per line. I think it is encouraged but not required to list the email addresses of the authors as well.

This applies to all the copyright headers.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +"""
Move this into the main docstring for the module so it shows up in the documentation.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +    f, h=0, check_squarefree=True, distinguished_point=None
```suggestion
    f, h=0, check_squarefree: bool = True, distinguished_point=None
```

While we don't require type annotations, they are encouraged. Especially when you're dealing with basic types where it's easy to figure out what the correct annotation is.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/meson.build
> +extension_data_cpp = {}
I don't think this should be here if you aren't using C++ in any Cython files.

Did you create this file manually? We have a script `tools/update-meson.py` that creates the `meson.build` files (mostly) automatically. Unless you're doing something exotic that script should "Just Work".

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/jacobian_generic.py
> +    def __iter__(self):
The benefit of `__iter__` is that you don't need to construct the entire list before you can start doing computations with elements. The way you've implemented this of yielding from an already-constructed list means we don't get that benefit. Ideally this should be implemented the other way around, where `__iter__` is a something like:

```python
def __iter__(self) -> Iterator:
    for foo in bar:
        yield baz(foo)
```

and then `list` is just `return list(iter(self))`.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +    def __genus(f, h):
```suggestion
    def genus(f, h) -> Integer:
```

The reason we use (single) underscores is to hide a function/method from the public API. Helper functions that are internal to another function aren't in the public API anyway, so we don't prefix their names with underscores.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        sage: HK.points_at_infinity()
What's going on with these test failures?

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        return (dh_2 - 1) // 2
```suggestion
        # Some classes still have issues with degrees returning `int`
        # rather than Sage Integer types
        df = f.degree()
        dh_2 = 2 * h.degree()
        if dh_2 < df:
            return Integer((df - 1) // 2)
        return Integer((dh_2 - 1) // 2)
```

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        return (dh_2 - 1) // 2
This version only does one `int` to `Integer` conversion instead of two.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/constructor.py
> +    def __check_no_affine_singularities(f, h):
```suggestion
    def check_no_affine_singularities(f, h) -> bool:
```

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        """
```suggestion
        r"""
```

It technically doesn't matter here since these functions don't show up in the docs, but using `r"""` instead of `"""` reduces the amount of escape sequences needed for some LaTeX expressions, and so we prefer it.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        return G
```suggestion
        if h.is_zero():
            return Y**2 - F
        H = sum(h[i] * X**i * Z ** (d - i) for i in range(d + 1))
        return Y**2 + H * Y - F
```

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/constructor.py
> +        # Some classes still have issues with degrees returning `int`
If you know which classes these are, you can fix them in this PR. If not, it's fine.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +):
```suggestion
from sage.schemes.hyperelliptic_curves_smooth_model import (
    invariants,
)
from sage.schemes.hyperelliptic_curves_smooth_model.hyperelliptic_finite_field import (
    HyperellipticCurveSmoothModel_finite_field,
)
from sage.schemes.hyperelliptic_curves_smooth_model.hyperelliptic_padic_field import (
    HyperellipticCurveSmoothModel_padic_field,
)
from sage.schemes.hyperelliptic_curves_smooth_model.hyperelliptic_rational_field import (
    HyperellipticCurveSmoothModel_rational_field,
)

from .hyperelliptic_generic import HyperellipticCurveSmoothModel_generic

"""
TODO List

### Invariants

There seems to be massive redundancy in having these methods and the ones imported into
invariants. I think we should fix this by putting the methods themseleves into this class.
"""


class HyperellipticCurveSmoothModel_g2(HyperellipticCurveSmoothModel_generic):
```

You should be able to simplify the other imports similarly.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        d = max(Integer(h.degree()), (Integer(f.degree()) + 1) // 2)
```suggestion
        d = Integer(max(h.degree(), (f.degree() + 1) // 2))
```

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +        return (dh_2 - 1) // 2
I feel like I should know this, but my flight was at an awful hour and I don't sleep well on planes so my brain is not running at 100%. Can you remind me where this formula comes from? What's it called? (And maybe add an inline comment with the name of the formula so people reading the code in the future can look it up.) Same comment applies for a lot of the formulas you're using here, an inline comment saying something like `# Bob's formula` or `# Sally's theorem` would help a lot with readability.

2025-12-14 19:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_constructor.py
> +    if not isinstance(F, Polynomial):
Can we not annotate the input parameters with `Polynomial` as well? That doesn't mean you can remove this check, since type annotations are not checked at runtime, but it does let our CI catch any violations within library code, and it also makes things a bit more clear to users reading the documentation.

2025-12-14 19:40 UTC, vincentmacri commented
General questions:

1. There are quite a few places in the code with a "TODO" comment suggesting potential refactoring. Was your intention for these comments to indicate places for future work after this PR is merged, or were you looking for feedback on addressing these points now?
2. There are a lot of classes and files here! I'm most familiar with the finite field case so I'll focus on reviewing that first. Can you describe the overall purpose of each class/file and how it fits together? Just for the base classes and the finite field classes is fine, I assume the non-finite fields are essentially the same in terms of design and just implementation differs (do highlight any important differences though). Some specific questions:
  a. Can you give some example code for actually performing balanced divisor Jacobian arithmetic on a split hyperelliptic curve? I'm sure you have one somewhere, but there is a lot of code and it will help me review it if I know the entry-points/workflow into the more substantial parts of the code. In terms of line count, there is a lot of boilerplate code here, which is fine, but it makes it difficult to tell what needs my attention.
4. So this is a by the book implementation of balanced divisors as described by GHM? There are improvements this method (there is a [NUCOMP variant of balanced divisors](https://link.springer.com/chapter/10.1007/978-3-030-60026-6_23) due to one of my supervisor's former students). I don't expect you to implement the improved version in this PR (in fact, please don't, there is plenty to review here already), but is the code designed in a way that it wouldn't be overly difficult to change the algorithm used to perform reduction?

I am somewhat (quite) sleep deprived as I write this due to the travel, please let me know if you want me to clarify anything as I'm sure this could have been worded better! And thank you again for your work to get this into Sage!

2025-12-16 16:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/hyperelliptic_g2.py
> +        )
It's better to have all imports at the top of the file at the module level unless they are expensive or cause circular import issues.

2025-12-16 16:56 UTC, GiacomoPope commented
I'm now "on holiday" and so in front of my laptop less than usual. I'll try and address things ASAP -- I don't know if @grhkm21 or @sabrinakunzweiler have any time before Christmas

2025-12-16 16:58 UTC, vincentmacri commented
> The idea is that `hyperelliptic_curves_sm` will be available with the old model for some time, until someone decides we should depreciate the old model in favour of this new implementation.

Other than possibly breaking old code, are there any disadvantages to deprecating the old model in favour of this implementation? Would it be possible to change the old functions to wrappers around the smooth model? (I am not asking that this be done in this PR, I just want to know what you think the plan should be for the future.)

2025-12-16 17:04 UTC, vincentmacri commented
> I'm now "on holiday" and so in front of my laptop less than usual. I'll try and address things ASAP -- I don't know if @grhkm21 or @sabrinakunzweiler have any time before Christmas

No worries! I am a few days away from being on holiday myself! We're doing 10.8 release candidates now, so it's not like this would make the next stable release anyway.

2025-12-16 17:27 UTC, GiacomoPope commented
> Other than possibly breaking old code, are there any disadvantages to deprecating the old model in favour of this implementation? 

I don't think so. Ultimately this should do everything the old code did, but also perform correct arithmetic for the cases the old code silently failed on. 

The issue with backwards compatibility is that this new model will produce different results for even models so we can't do a drop in replacement for old code. 

I think the way forward is to depreciate the old code and have this in the background, then when we can, we replace this impl under HyperellipticCurve and rename the old one to HyperellipticCurveOld or whatever and then remove it entirely

2025-12-17 14:54 UTC, user202729 commented
Side note on this

> This PR looks WAY bigger than it is, as it duplicates ALL code from `hyperelliptic_curves` and then has modifications to allow this to work in the new curve model. I believe the best thing to do in the long run is to depreciate the old hyperelliptic curve impl and have this replace it, but this will take years(?) so I think we'll just have to have both side by side for a while.

it isn't entirely clear whether this would introduce additional maintenance burden downstream compared to make a flag like `bint smooth=False`, but then someone (you) already do the copy paste and I imagine it would be a huge amount of work to change it.

2025-12-17 16:01 UTC, GiacomoPope commented
The two models just aren't compatible, I guess we could allow HyperellipticCurve to create either the current version or the smooth version as a constructor with a bool and then switch the default then remove the old one eventually?

Honestly I don't know how to kill the old code. I kinda thing just deleting the old code now is also fine... this code should be a strict improvement in the broken arithmetic and then identical for everything else

2025-12-17 17:22 UTC, yyyyx4 commented
The current (soon: old) implementation is already not maintained very actively. So I think it's fine to:
- Make the new one the default immediately, with a warning that says "if you want the old behaviour, add `impl="old"` to your constructor, but note that this is (1) buggy in the even-degree case, (2) unmaintained, and (3) will be removed in a future release". The warning could be silenced by explicitly passing `impl="new"` to the constructor.
- Remove the old implementation in $$t_1\geq1$$ years and add a deprecation warning to the `impl="new"` flag that says "this flag is not needed any longer and will be removed in a future release".
- Remove the `impl="new"` flag entirely in $$t_2\geq t_1+1$$ years.

(Assumption: The two implementations actually behave identically for the odd model, as in, all of the original tests still pass.)

The justification for making the new one the default immediately is that code which relies on the old behaviour is probably already broken. So, in a sense, this is a stopgap for an existing correctness issue.

2025-12-17 23:06 UTC, vincentmacri commented
> The justification for making the new one the default immediately is that code which relies on the old behaviour is probably already broken. So, in a sense, this is a stopgap for an existing correctness issue.

I am fine with "breaking" code that is already broken. We have deprecation policies to give users a warning if changes to Sage are going to break their working code. If the new version has the same API/names (i.e. users using the current stuff won't need to change their code to use the new stuf) then I don't think we need to keep the old code around.

Is the behaviour identical for the odd degree model?

2025-12-18 08:14 UTC, GiacomoPope commented
It should be totally the same mathematically but now the whole thing is built on top of the new weighted projected code then I think some parents will be different and the curve equation will have slightly different properties. 

I think maths wise; it should be identical but sage wise there are differences at the object levels

2025-12-18 11:18 UTC, sabrinakunzweiler commented
> It should be totally the same mathematically but now the whole thing is built on top of the new weighted projected code then I think some parents will be different and the curve equation will have slightly different properties.
> 
> I think maths wise; it should be identical but sage wise there are differences at the object levels

In particular, when explicitly working with projective coordinates of points on a hyperelliptic curve, the weighted projective space makes a difference. And I would assume that this breaks code for different applications. 
An example is Coleman integration, where one works with local coordinate functions. We adapted the sage functions in `hyperelliptic_padic_field` to the new setting. But I guess there are also private packages that rely on the old one.

2025-12-18 19:49 UTC, vincentmacri commented
> It should be totally the same mathematically but now the whole thing is built on top of the new weighted projected code then I think some parents will be different and the curve equation will have slightly different properties.
> 
> I think maths wise; it should be identical but sage wise there are differences at the object levels

So am I understanding correctly that other than unwillingness/inability to update old code, there is no reason not to use the smooth model? Then in terms of deprecation/transition I suggest the following:

1. Deprecate but do not yet remote the old non-smooth model. Emit a [deprecation warning](https://doc.sagemath.org/html/en/reference/misc/sage/misc/superseded.html#sage.misc.superseded.deprecation) directing users to the new smooth model.
2. When creating an even degree hyperelliptic curve under the old model, additionally emit a [stopgap warning](https://doc.sagemath.org/html/en/reference/misc/sage/misc/stopgap.html), again directing users to the smooth model.
3. If we intend to eventually only have the smooth model, then these objects should be created by calling the function `HyperellipticCurve`, but that currently constructs curves under the old model. I thought about using a `smooth_model` parameter switch in this function, but I see no way to cleanly do that without having to go through two deprecation periods (as the `smooth_model` switch should be deprecated after removing the non-smooth model).
4. Add a `HyperellipticCurveSmooth` function that acts as the public function to use the new smooth model. This function should be marked as [experimental](https://doc.sagemath.org/html/en/reference/misc/sage/misc/superseded.html#sage.misc.superseded.experimental). Explain that the smooth model is new and is planned to be renamed to `HyperellipticCurve` after the non-smooth model is deprecated.
5. Per our deprecation policy, a year after this PR is merged we can remove the old non-smooth model. We can then change the `HyperellipticCurve` function to construct curves with the new smooth model, and delete the experimental `HyperellipticCurveSmooth` function.

This plan is slightly annoying, but it is the simplest way to handle the transition I can think of without violating our deprecation policy. I do think it is perhaps a good idea that the new code be marked as experimental for a bit given the sheer amount of new code here in such an important mathematical object.

2026-01-08 16:20 UTC, GiacomoPope commented
I added the decorator `@sage.misc.superseded.experimental(issue_number=39161)` to the new function `HyperellipticCurveSmoothModel`.

I added the following snippet to the constructor for `HyperellipticCurve`

```py
    # Handle warnings for the depreciation of the current code in favour of the new
    # HyperellipticCurveSmoothModel which uses weighted projective space and allows
    # for correct arithmetic for Jacobian(H) when the degree of the curve is even.
    if f.degree() % 1:
        sage.misc.superseded.depreciation(
            39161,
            "this function will be replaced by the currently experimental constructor HyperellipticCurveSmoothModel.",
        )
    else:
        sage.misc.stopgap.set_state(True)
        sage.misc.stopgap(
            "Some results are incorrect for even degree models, use HyperellipticCurveSmoothModel until this constructor is replaced.",
            39161,
        )
        sage.misc.stopgap.set_state(False)
```

2026-01-14 15:29 UTC, fchapoton commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        superseded.depreciation(
```suggestion
        superseded.deprecation(
```

2026-01-14 15:30 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        superseded.depreciation(
I make this typo so often...

2026-01-15 21:26 UTC, vincentmacri commented
> This plan is slightly annoying, but it is the simplest way to handle the transition I can think of without violating our deprecation policy.

I know it was my idea, but I really don't like this idea. I've asked on [sage-devel](https://groups.google.com/g/sage-devel/c/Y7R2aX6qUR0) about it, maybe since this is replacing broken code violating the deprecation policy would be okay.

2026-01-15 21:40 UTC, vincentmacri reviewed
Try to fix the test failures.

The fact that a lot of this was copied from `hyperelliptic_curves` to `hyperelliptic_curves_smooth_model` makes it hard to see what was changed. Is there a commit in the history where you copied `hyperelliptic_curves` to `hyperelliptic_curves_smooth_model` but didn't make any changes yet, so I can diff between those commits when looking at this? If not, would you mind creating such a commit (either do some rebase magic, or delete all files in `hyperelliptic_curves_smooth_model`, copy all files in `hyperelliptic_curves` to `hyperelliptic_curves_smooth_model`, commit, then undo it and commit again).

2026-01-15 21:40 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/constructor.py
> +Constructor for hyperelliptic curves using the smooth model
The first line of the docstring gets rendered as the page title, so it shouldn't be part of a sentence. https://doc-pr-39161--sagemath.netlify.app/html/en/reference/arithmetic_curves/sage/schemes/hyperelliptic_curves_smooth_model/constructor

2026-01-15 21:40 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/constructor.py
> +        sage: H = HyperellipticCurveSmoothModel(x^8+1, x^4+1); H
```suggestion
        sage: H = HyperellipticCurveSmoothModel(x^8+1, x^4+1); H
        FutureWarning: This class/method/function is marked as experimental ...
```

Should address the doctest failure. You might need this in a few other files as well (in the first doctest that calls this code in each file).

2026-01-15 21:40 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves_smooth_model/constructor.py
> +        sage: HK.points_at_infinity()
Seems to be some kind of issue with types. Rather than use `is_one()` or `is_zero()`, why not use `== 1` and `== 0`?

2026-01-16 16:48 UTC, GiacomoPope commented
No idea why there are suddenly so many failing doc tests... I'll try and find time next week to fix them. It all seems to be part of the weighted projective space? maybe some changes have happened on main which affect how the old code was being called.

@grhkm21 maybe you'll see fixes faster than me, depending on how busy you are

2026-01-16 22:04 UTC, vincentmacri commented
Tagging a few people who do stuff with curve arithmetic and/or are listed as authors of some of the hyperelliptic code and I was able to figure out their GitHub usernames. @nbruin @JohnCremona @roed314 @kedlaya @robertwb 

Do any of you have thoughts on if or to what extent deprecation policies would apply here if we were to replace the old hyperelliptic curve implementation with this smooth model implementation? Are there any objections to replacing it without a deprecation period? If you think we need a deprecation period, any suggestions on how to do that smoothly?

2026-01-19 19:16 UTC, vincentmacri commented
A lot of the doctest failures are just because the experimental warning needs to be accounted for in the expected output of the doctests.

@GiacomoPope Would you be okay with just replacing the existing hyperelliptic curve code in this PR? Should make the diffs a lot cleaner and easier to review if they are changing files rather than adding new ones. If someone objects then we can rename it to hyperelliptic smooth after I'm otherwise done reviewing.

And maybe leave out the experimental warning for now as well so you don't have to update a bunch of doctests while we do the code review. If we do a one-shot replace of the hyperelliptic code I don't think we even need the experimental warning at all to be honest.

Sorry for going back and forth on the renaming/deprecation stuff, we should probably update our policies to have better ways to deal with these kinds of situations in the future.

2026-01-19 19:27 UTC, GiacomoPope commented
Yea I can do that. Today I was trying to build sage using conda and nothing worked so tomorrow I'll try again. I posted about this in Zulip too. 

I also tried sage -b but that didn't work so maybe I'll just go back to using configure and make. The new system is so confusing for me haha

I'll try and make a new PR in place for hyperelliptic and see how that goes :)

2026-01-19 19:39 UTC, JohnCremona commented
I have no objections to replacing the old code with the new, though I don't think I have ever used the old code.

2026-01-19 20:09 UTC, vincentmacri commented
> Yea I can do that. Today I was trying to build sage using conda and nothing worked so tomorrow I'll try again. I posted about this in Zulip too.
> 
> I also tried sage -b but that didn't work so maybe I'll just go back to using configure and make. The new system is so confusing for me haha

There have been some recent (and I think good) changes to building Sage. Were you referencing the latest build instructions for building with conda? https://doc-develop--sagemath.netlify.app/html/en/installation/source

This *should* work (might need to be from a fresh clone):

```python
mamba env create --file environment-3.12-linux.yml --name sage-dev
mamba activate sage-dev
pip install --no-build-isolation --editable .
./sage
```

You can replace `mamba` with `conda` if you have `conda` installed but not `mamba` (I've actually only tested this myself with `conda` as that's what's available in Fedora). Building the docs locally is still a bit finicky, but the docs should build fine on the CI.

2026-01-19 20:12 UTC, vincentmacri commented
Nevermind, I see on Zulip that you're on a Mac. I have no experience building Sage on a Mac.

2026-01-19 20:43 UTC, GiacomoPope commented
I have this annoying error which makes it look like sage just isn't being installed at all but what I might try tomorrow is totally cleaning out the sage repo in case I have old temp files causing an issue. 

```
Jack: sage % mamba env create --file environment-3.13-macos-x86_64.yml --name sage-dev
...

Transaction finished


To activate this environment, use:

    mamba activate sage-dev

Or to execute a single command in this environment, use:

    mamba run -n sage-dev mycommand
```

```
Jack: sage % mamba activate sage-dev
(sage-dev) Jack: sage % pip install --no-build-isolation --editable .
Obtaining file:///Users/Jack/sage/sage
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied:

...

Building wheels for collected packages: sagemath
  Building editable for sagemath (pyproject.toml) ... done
  Created wheel for sagemath: filename=sagemath-10.9b3-cp313-cp313-macosx_26_0_x86_64.whl size=16564 sha256=106ae66d9a08eff72ec70cf9f126874a447e67c55ed426f8fbc20d58de75a4d2
  Stored in directory: /private/var/folders/_z/44xmm4f54y7_x27lg605vrn40000gn/T/pip-ephem-wheel-cache-i3w0qr0k/wheels/0c/e4/31/1e4c9da737c15e95f4df6def84decdec16ec5fbed7a3772ac6
Successfully built sagemath
Installing collected packages: sagemath
  Attempting uninstall: sagemath
    Found existing installation: sagemath 10.9b3
    Uninstalling sagemath-10.9b3:
      Successfully uninstalled sagemath-10.9b3
Successfully installed sagemath-10.9b3
```

```
(sage-dev) Jack: sage % ./sage
Traceback (most recent call last):
  File "/Users/Jack/sage/sage/src/bin/sage-ipython", line 9, in <module>
    from sage.misc.banner import banner
  File "/Users/Jack/sage/sage/src/sage/misc/banner.py", line 15, in <module>
    from sage.env import SAGE_BANNER, SAGE_VERSION
  File "/Users/Jack/sage/sage/src/sage/env.py", line 29, in <module>
    import sage.config
ModuleNotFoundError: No module named 'sage.config'
```

```
(sage-dev) Jack: sage % mamba run -n sage-dev ./sage
Traceback (most recent call last):
  File "/Users/Jack/sage/sage/src/bin/sage-ipython", line 9, in <module>
    from sage.misc.banner import banner
  File "/Users/Jack/sage/sage/src/sage/misc/banner.py", line 15, in <module>
    from sage.env import SAGE_BANNER, SAGE_VERSION
  File "/Users/Jack/sage/sage/src/sage/env.py", line 29, in <module>
    import sage.config
ModuleNotFoundError: No module named 'sage.config'
```

2026-01-20 14:12 UTC, GiacomoPope commented
OK so I have sage working locally again and I think the local tests should pass on the CI. If the CI is happy I will refactor everything again to replace the HyperellipticCurve class.

2026-01-20 16:52 UTC, GiacomoPope commented
OK so this CI passes, and I've done the refactor to include everything over the top of the new code but now things are pretty broken for things using monsky_washnitzer... I'll push something now but it's broken and I need help / more time to figure out what's happened here.

2026-01-20 16:55 UTC, GiacomoPope commented
@grhkm21 @sabrinakunzweiler if you have time, i think you are both better than me at the maths for the failures from the padic side.

There's also a new weirdness with the parent of the Jacobian:

```
**********************************************************************
File "src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py", line 85, in sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassField.parent
Failed example:
    D.parent()
Expected:
    Set of rational points of Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 - 1
Got:
    Abelian group of points on Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 - 1
**********************************************************************
File "src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py", line 108, in sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassField.scheme
Failed example:
    J = H.jacobian()(F); J                                                # needs sage.rings.number_field
Expected:
    Set of rational points of Jacobian of Hyperelliptic Curve
     over Number Field in a with defining polynomial x^2 - 2
     defined by y^2 = x^5 + x
Got:
    Abelian group of points on Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 + x
**********************************************************************
File "src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py", line 132, in sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassField.str
Failed example:
    D = J(P,Q); D # indirect doctest
Expected:
    (x^2, y + x + 1)
Got:
    (x^2, -x - 1 : 0)
**********************************************************************
```

For some reason the parent has change from the set of points to the Abelian group? I don't know why but I'll try and trace it. I also need to check if there's been changes in hyperellipic_curves since i made this fork so long ago as my copy paste might have removed old features. I will check the diffs for this.

2026-01-20 18:01 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
> -#  Copyright (C) 2006 David Kohel <kohel@maths.usyd.edu>
I assume this was accidental, but do not remove people from the authors or copyright.

2026-01-20 18:02 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
> -#  Copyright (C) 2006 David Kohel <kohel@maths.usyd.edu>
Thank you for spotting this. I actually need to check carefully across all files as some were written as "new" files in the old directory and copy pasting could have caused issues. I will check everything carefully tomorrow.

2026-01-20 18:04 UTC, GiacomoPope commented
I'm puzzled by the errors which are now present in the jacobian_morphism -- it makes little sense to me that this is broken. 

The padic stuff I'm less surprised about but fixing it might require some work

2026-01-20 21:20 UTC, vincentmacri requested changes
First review pass of `src/sage/schemes/hyperelliptic_curves/constructor.py` (and a couple comments on other files).

Looks good, mostly just code style nitpicks and documentation suggestions.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/elliptic_curves/hom.py
> +        import sage.schemes.elliptic_curves.weierstrass_morphism as wm
Why did you move this here? Imports should normally be at the top of the file unless there is a good reason to do otherwise. We do have https://doc.sagemath.org/html/en/reference/misc/sage/misc/lazy_import.html if this was just a circular import issue.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +- We currently cannot support the construction of curves over rings
```suggestion
- We do not yet support the construction of hyperelliptic curves over rings
```
Clearer wording

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/all.py
> -from sage.schemes.hyperelliptic_curves.kummer_surface import KummerSurface
You took out quite a few imports here. How come?

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    def __check_no_affine_singularities(f, h):
If this is a local method there is no need for an underscored name.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +- We currently cannot support the construction of curves over rings
Actually, I don't understand this. In the other files you say we support construction of hyperelliptic curves over a general ring. Did you forget to remove this TODO at some point?

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/weighted_projective/weighted_projective_point.py
> +            [R(u * t**w) for u, w in zip(self._coords, self.codomain().weights())]
```suggestion
            R(u * t**w) for u, w in zip(self._coords, self.codomain().weights())
```
I think the list construction is unnecessary.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/projective/projective_homset.py
> +# TODO: Should this inherit from the weighted projective class?
You mean with all weights equal to 1? I can't think of any reason this wouldn't work. Can you?

I am not asking you to make this change though (we can leave it to future work).

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
```suggestion
```
I don't think this blank line is needed, ignore this comment if it's just the GitHub diff interface confusing me.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> -lazy_import('sage.libs.pari', 'pari')
Why get rid of the lazy imports? These are supposed to help with Sage startup time and circular dependencies.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> -#  Copyright (C) 2010 Alyson Deines <aly.deines@gmail.com>, Marina Gresham
Several authors accidentally removed from copyright header.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> -- Jean-Pierre Flori, Jan Tuitman (2013)
Several authors accidentally removed here

2026-01-20 21:20 UTC, vincentmacri commented on src/doc/en/reference/references/index.rst
> +             Algorithmic Number Theory: 8th International Symposium, ANTS-VIII Banff, Canada, May 17-22, 2008 Proceedings 8.
Add Galbraith's public key crypto book if you referenced that. It's a good source to link to for your implementation.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        """
Note to myself in case I forget later: this is Exercise 10.1.1 in Galbraith's book.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        # Some classes still have issues with degrees returning `int`
Which classes? You're welcome to fix it in this PR if you know where it is. If it's too hard to trace, no big deal.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        d = Integer(max(h.degree(), (f.degree() + 1) // 2))
Clever avoidance of calling ceil! :+1:

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +        the hyperelliptic curve.
Note for self: this is Galbraith Definition 10.1.10

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    # Check the polynomials are of the right type
```suggestion
    # Check the polynomials are of the right type
    # D is the discriminant; use this for the type check
    # rather than f and h, one of which might be constant.
```

I was very confused about what F was until I saw the deleted comment explaining it above.

Let's call it `D` instead to not confuse it with the `F` in the helper function above.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
>      F = h**2 + 4 * f
```suggestion
    D = h**2 + 4 * f
```

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    base_ring = F.base_ring()
```suggestion
    polynomial_ring = D.parent()
    base_ring = D.base_ring()
```

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    genus = genus(f, h)
This reassigns the name that used to point to the helper function to the value of the genus. Not wrong, but a bit tricky to read. Can we use different names for the genus function and the genus variable?

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    genus = genus(f, h)
This reassigns the name that used to point to the helper function to the value of the genus. Not wrong, but a bit tricky to read. Can we use different names for the genus function and the genus variable?

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    if genus == 0:
```suggestion
    if genus <= 0:
```

I think something else will give an error for cases where the genus equation gives something less than 0, but just to be safe.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    def __defining_polynomial(f, h):
```suggestion
    def homogenize_defining_polynomial(f, h):
```
To make the function name more distinct from the variable name.

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +       the input defines a hyperelliptic curve
Document the `distinguished_point` parameter

2026-01-20 21:20 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +    The constructor accepts a distinguished point as an argument::
Include a sentence or two about what the distinguished point can be used for.

2026-01-20 21:28 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> -def _parse_multivariate_defining_equation(g):
It seems this was used somewhere by elliptic curves.

Also, it would be a nice bonus if this function could be used to construct a hyperelliptic curve from a multivariate polynomial.

2026-01-20 21:29 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> -def _parse_multivariate_defining_equation(g):
Thanks for spotting this -- seems like there's a good chunk more work to do to totally align the new code with what existed before.

2026-01-20 21:31 UTC, GiacomoPope commented
I'll try and first address all your comments and then I need to try and uncover the weirdness with the Jacobian morphism doctest fails. I think I might have to build the older commit an compare line by line to see where the parent objects start diverging and why

2026-01-20 23:55 UTC, vincentmacri requested changes
First pass of hyperelliptic_generic.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> -lazy_import("sage.functions.all", "log")
Keep the `lazy_import` unless there is a reason to change it.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> -    TESTS::
Can we keep these tests?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> -EXAMPLES::
Keep the examples

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        assert self._d == self._genus + 1
```suggestion
        self._d = max(h.degree(), (f.degree() + 1) // 2)
        if self._d != self._genus + 1:
            raise ValueError('genus does not match expected value')
```
If you want this to throw an error, be explicit rather than use `assert`.

If this constructor is not user-facing and the input should have been validated before, then leave it as an assert.

Remove the TODO either way unless there is remaining work here.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        A = WeightedProjectiveSpace([1, self._genus + 1, 1], self._base_ring)
```suggestion
        A = WeightedProjectiveSpace((1, self._genus + 1, 1), self._base_ring)
```
It's a micro-optimization, but constructing a tuple is faster than constructing a list and it's no more verbose either so might as well use a tuple.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def weights(self) -> list[int]:
```suggestion
    def weights(self) -> tuple[Integer]:
```
Sage functions that return an integer should return a Sage `Integer`, not a Python `int`. Main exception is implementations of Python dunder methods like `__hash__` and `__len__`.

Also, return types should normally be a tuple, not a list.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `[1, g + 1, 1]`, where `g` is the genus of the curve.
```suggestion
        `(1, g + 1, 1)`, where `g` is the genus of the curve.
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        return [1, self._genus + 1, 1]
```suggestion
        return (ZZ.one(), self._genus + 1, ZZ.one())
```

Adding an `int` to an `Integer` gives an `Integer`, so as long as `self._genus` is a Sage `Integer` (if not, fix that) then we don't need a manual conversion for the middle value.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
>  from sage.rings.real_mpfr import RR
```suggestion
from sage.rings.real_mpfr import RR
from sage.rings.integer import Integer
from sage.rings.integer_ring import ZZ
```
If `Integer` is only used in type annotations and not at runtime, then it should be in an `if TYPE_CHECKING` block (`ruff` will correctly complain otherwise).

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def _repr_(self):
```suggestion
    def _repr_(self) -> str:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        # printing polynomial rings to change output.
We should keep those, and you should add a `names` parameter to the hyperelliptic curve constructor to support this. This would be a real breaking change otherwise. It's also a nice feature to have.

This should not be based on string replacement because you could have generators in the base ring that are called `x` or `y`. Here's an example where a user would want to be able to name their generators., and where trying to do a hacky string replacement would fail.

```python
R.<x, y> = GF(101)[]
S.<X> = R[]
H = HyperellipticCurve(X^3 * y + x)
print(H)  # Hyperelliptic Curve over Multivariate Polynomial Ring in x, y over Finite Field of size 101 defined by y^2 = y*x^3 + x
```

whereas before a user could do:

```python
H = HyperellipticCurve(X^3 * y + x, names=('u', 'v'))
print(H)  # Hyperelliptic Curve over Multivariate Polynomial Ring in x, y over Finite Field of size 101 defined by v^2 = y*u^3 + x
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def genus(self):
```suggestion
    def genus(self) -> Integer:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `<https://www.math.u-bordeaux.fr/~qliu/Notes/disc.pdf>`_ for the
Any references should be added to the bibliography file and linked that way.

Also, a citation to a journal article would be preferable. Or a journal article and some other more accessible sources like the one you linked.

Even better is if you can track down the paper that originally defined the notion, which I think I did: https://www.ams.org/journals/tran/1994-342-02/S0002-9947-1994-1195511-X/

Some slightly different definitions/notation in this paper, but I think it's equivalent to what you have.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +
I assume the next example is demonstrating some theorem? Can you add a sentence explaining what the example is doing?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +            sage: for p in prime_range(3, 300):
```suggestion
            sage: for p in prime_range(3, 50):
```

300 is overkill, keep in mind every test you add is run multiple times on every commit on every PR. Testing Sage takes enough time already.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        the curve is inert or split we expect zero or two roots.
```suggestion
        When the curve is ramified, we expect one root. When
        the curve is split we expect two roots. When the curve
        is inert we expect zero roots. 
```
Clearer wording

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        self._alphas = (x**2 + x * h[d] - f[2 * d]).roots(multiplicities=False)
Is there a reason you use `self._alphas` to cache some code paths instead of the `@cached_method` decorator to cache all code paths?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def roots_at_infinity(self):
```suggestion
    def roots_at_infinity(self) -> list:
```
I'd prefer if this returns a tuple but you're calling `.roots` which returns a list for some reason. If you want, change this function to always return a tuple.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_split(self):
```suggestion
    def is_split(self) -> bool:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_ramified(self):
```suggestion
    def is_ramified(self) -> bool:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_singular(self, *args, **kwargs):
```suggestion
    def is_singular(self) -> Literal[False]:
```

And add `from typing import Literal` at the beginning of the file.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_smooth(self):
```suggestion
    def is_smooth(self) -> Literal[True]:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +
```suggestion
```

These methods aren't hacky, they're to ensure all curves share a common interface and basic functionality. If you look in the implementation of elliptic curves you'll see a genus method that's hardcoded to return 1.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def points_at_infinity(self):
```suggestion
    def points_at_infinity(self) -> tuple:
```

Bonus points if you know what the type is, then make this `tuple[Foo]`.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        Return ``True`` if the curve is ramified, i.e. there is one rational
```suggestion
        Return ``True`` if the curve is ramified, i.e. there is exactly one rational
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_inert(self):
```suggestion
    def is_inert(self) -> bool:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        Return `G^\\pm(x)` for curves in the split degree model.
```suggestion
        Return `G^{\pm(x)}` for curves in the split degree model.
```
https://doc-pr-39161--sagemath.netlify.app/html/en/reference/arithmetic_curves/sage/schemes/hyperelliptic_curves/hyperelliptic_generic#sage.schemes.hyperelliptic_curves.hyperelliptic_generic.HyperellipticCurve_generic.infinite_polynomials

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        TODO: the name of this function could be better?
`split_G_plus_minus` maybe? Does this function need to be public anyway? Can't it be private? Then it doesn't appear in the docs and so the name doesn't really matter.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        if not len(alphas) == 2:
```suggestion
        if not self.is_split():
```
Readability

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def hyperelliptic_polynomials(self):
```suggestion
    def hyperelliptic_polynomials(self) -> tuple:
```
Is it `tuple[Polynomial]`?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
>      def is_x_coord(self, x):
```suggestion
    def is_x_coord(self, x) -> bool:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def is_weierstrass_point(self, P):
```suggestion
    def is_weierstrass_point(self, P) -> bool:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        TODO: It would be better to define this function for points directly.
I agree. It's also okay to leave this and then just have a function on points that calls this one.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +                points = self.points_at_infinity()
```suggestion
                # If Z = 0 then P is a point at infinity,
                # so we cannot be in the inert case and
                # must be in the split case here.
                points = self.points_at_infinity()
```
Got tripped up for a second until I realized what was happening.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +            # For the the split and ramified case, a point at infinity is chosen,
Isn't there a correspondence between if you use $\infty^+$ or $\infty^-$ and whether you use $G^+$ or $G^-$ for Jacobian arithmetic? How do make sure you make a consistent choice?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        raise ValueError("distinguished point not found")
```suggestion
        raise ValueError("curve has no points")
```

Isn't the only way you can reach this is if your curve is pointless?

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        of the form `(u, v : n)`, where
```suggestion
        of the form `(u, v, n)`, where
```
I don't think the GHM paper or Galbraith's book use a colon here.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        - `(u,v)` is the Mumford representative of a divisor `P_1 + ... + P_r`,
```suggestion
        - `(u, v)` is the Mumford representative of a divisor `P_1 + ... + P_r`,
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `n` is omitted in the description.
I'm not a fan of this. I think $n$ should always be included for consistency. Maybe unless it's constant $0$ or $g$.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        infinity) and the genus is odd::
Maybe demonstrate in this example how one can change the ring to an extension field where the curve is not inert? I think that's how the inert case is handled in practice for computations.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def rational_points(self, **kwds):
```suggestion
    def rational_points(self, **kwds) -> list:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        - ``prec`` --  desired precision of the local coordinates
```suggestion
        - ``prec`` -- desired precision of the local coordinates
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        For a non-Weierstrass point ``P = (a,b)`` on the hyperelliptic
```suggestion
        For a non-Weierstrass point ``P = (a, b)`` on the hyperelliptic
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
>          AUTHOR:
```suggestion
        AUTHORS:
```

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        for _ in range((RR(log(prec, 2))).ceil()):
```suggestion
        for _ in range(prec.bit_length()):
```
A simpler expression. Off by one from what you had before for powers of two if that matters.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        for _ in range(int(log(prec, 2))):
Again, consider `prec.bit_length()`

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        for _ in range((RR(log(prec + 2) / log(2))).ceil()):
Simplify this, you definitely don't need two logs. You can probably use `.bit_length`.

2026-01-20 23:55 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        for _ in range((RR(log(prec + 2) / log(2))).ceil()):
`bit_length`

2026-01-20 23:58 UTC, vincentmacri commented
> I'll try and first address all your comments and then I need to try and uncover the weirdness with the Jacobian morphism doctest fails. I think I might have to build the older commit an compare line by line to see where the parent objects start diverging and why

I've left a lot of comments, so please take your time. Click the re-request review button once you're ready for me to continue looking at this. I've only looked closely at two files so far. It is a lot of code, but I should be able to slowly work through it now.

2026-01-21 10:04 UTC, GiacomoPope commented
So I know why there;s an issue with `jacobian_morphism` the old code used `HyperellipticCurve` instead of `HyperellipticCurveSmoothModel` for some doc tests, which is why things suddenly change!

2026-01-21 17:27 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +- We currently cannot support the construction of curves over rings
The weighted projective space does not handle rings i believe, so if we say a ring should work somewhere, we're wrong now?

2026-01-21 17:49 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        self._alphas = (x**2 + x * h[d] - f[2 * d]).roots(multiplicities=False)
no, this could be changed i think

2026-01-21 17:52 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `n` is omitted in the description.
Hmm ok, i will rework this then.

2026-01-21 17:56 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `n` is omitted in the description.
That said, if it can be calculated from $\deg(u)$ and $g$ then you don't necessarily need to store and compute it as you perform Jacobian arithmetic, you can just have have a method that computes it that is used by the `_repr_` and `_latex_` methods.

2026-01-21 18:11 UTC, GiacomoPope commented
I made an attempt to tackle some low hanging fruit but will try and get through everything asap. 

Thanks so much for the detailed review

2026-01-23 11:44 UTC, GiacomoPope commented
Discussing some things with @sabrinakunzweiler I have uncovered a bigger issue.

We have for elliptic curves in projective space the following definition:

```
class EllipticCurve_padic_field(EllipticCurve_field, HyperellipticCurve_padic_field):
```

But for elliptic curves the space is simply projective space, where as for hyperelliptic curves with weighted projective space (1 : g + 1 : 1) we have a different projective space so the new Hyperelliptic curve code is breaking the old elliptic curve functions.

2026-01-23 11:54 UTC, GiacomoPope commented
I think the only thing we can do if we want to merge this PR is to take the old code for the elliptic curve case and implement coleman integration on the padic elliptic curve and remove this class dependency -- but that's another big change for how the old elliptic cuvres over padic fields used to behave (although we can try and capture as much of the old functionality as reasonably possible)

2026-01-23 15:09 UTC, GiacomoPope commented
So my proposal for this fix is to take the padic inheritance and remove it by bulking out the ell_padic file.

A draft of this work is here: https://github.com/sagemath/sage/pull/41496

If we think this is a reasonable fix, then I believe the next step is to go through this code carefully and optimise it for the case of g=1 and then once this is merged we can merge it into this branch and we should fix many of the currently broken doctests.

2026-02-26 09:29 UTC, GiacomoPope commented
Now https://github.com/sagemath/sage/pull/41496 has been merged, i can get back to trying to clean this PR up whilst (hopefully) having all doctests pass

2026-02-26 10:54 UTC, GiacomoPope commented
So I just added the old printing ring back to the code which allows input of a custom name.

There's two dockets failures we need to sort.


**The old Kummer Surface code is projective**

This might be something @sabrinakunzweiler can fix quickly as she knows a lot more than me about Kummer Surfaces. I don't know exactly what we expect her

```
File "src/sage/schemes/hyperelliptic_curves/kummer_surface.py", line 38, in sage.schemes.hyperelliptic_curves.kummer_surface.KummerSurface.__init__
Failed example:
    K = KummerSurface(J); K
Exception raised:
    Traceback (most recent call last):
      File "/Users/Jack/sage/sage/src/sage/doctest/forker.py", line 734, in _run
        self.compile_and_execute(example, compiler, test.globs)
        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/Jack/sage/sage/src/sage/doctest/forker.py", line 1158, in compile_and_execute
        exec(compiled, globs)
        ~~~~^^^^^^^^^^^^^^^^^
      File "<doctest sage.schemes.hyperelliptic_curves.kummer_surface.KummerSurface.__init__[4]>", line 1, in <module>
        K = KummerSurface(J); K
      File "/Users/Jack/sage/sage/src/sage/schemes/hyperelliptic_curves/kummer_surface.py", line 96, in __init__
        phi = Hom(C, self)([X.parent().zero(), Z**2, X*Z, a0*X**2], Schemes())
              ~~~^^^^^^^^^
      File "/Users/Jack/sage/sage/src/sage/categories/homset.py", line 426, in Hom
        H = Hom(X, Y, category, check=False)
      File "/Users/Jack/sage/sage/src/sage/categories/homset.py", line 453, in Hom
        H = X._Hom_(Y, category)
      File "/Users/Jack/sage/sage/src/sage/schemes/generic/scheme.py", line 608, in _Hom_
        return SchemeHomset(self, Y, category=category, check=check)
      File "sage/structure/factory.pyx", line 372, in sage.structure.factory.UniqueFactory.__call__
      File "sage/structure/factory.pyx", line 415, in sage.structure.factory.UniqueFactory.get_object
      File "/Users/Jack/sage/sage/src/sage/schemes/generic/homset.py", line 194, in create_object
        return X._homset(X, Y, category=category, base=base_ring, **extra_args)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/Jack/sage/sage/src/sage/schemes/generic/algebraic_scheme.py", line 501, in _homset
        return self.__A._homset(*args, **kwds)
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
      File "/Users/Jack/sage/sage/src/sage/schemes/weighted_projective/weighted_projective_space.py", line 288, in _homset
        raise NotImplementedError(
            "_homset not implemented for weighted projective space"
        )
    NotImplementedError: _homset not implemented for weighted projective space
```


**The Jacobian Morphism is behaving differently than it used to**

I'm not sure why this is breaking or what's happened. I can try and get to the bottom of this.

```
src/bin/sage -t --warn-long 5.0 --random-seed=74150366579632126613940701202113523275 src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
    [352 tests, 10.69s wall]
src/bin/sage -t --warn-long 5.0 --random-seed=74150366579632126613940701202113523275 src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
**********************************************************************
File "src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py", line 85, in sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassField.parent
Failed example:
    D.parent()
Expected:
    Set of rational points of Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 - 1
Got:
    Abelian group of points on Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 - 1
**********************************************************************
File "src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py", line 108, in sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassField.scheme
Failed example:
    J = H.jacobian()(F); J                                                # needs sage.rings.number_field
Expected:
    Set of rational points of Jacobian of Hyperelliptic Curve
     over Number Field in a with defining polynomial x^2 - 2
     defined by y^2 = x^5 + x
Got:
    Abelian group of points on Jacobian of Hyperelliptic Curve over Rational Field defined by y^2 = x^5 + x
```

2026-02-26 11:12 UTC, sabrinakunzweiler commented
> **The old Kummer Surface code is projective**
> 
> This might be something @sabrinakunzweiler can fix quickly as she knows a lot more than me about Kummer Surfaces. I don't know exactly what we expect her

Yes, I can take care of this. At some point I started implementing this on the branch `kummer`, where I wanted to include a more general model and arithmetic. This was unfortunately never finished, but I can copy the parts that are needed to replace the old code .

2026-02-27 17:17 UTC, GiacomoPope commented
Sabrina has managed tp seriously improve the Kummer file and now all doctests pass so I believe we're good for review.

2026-02-27 22:09 UTC, vincentmacri commented
Some of the CI failures look relevant. Also, I won't have time to look at this much until the week of March 16.

2026-03-02 09:21 UTC, GiacomoPope commented
Yes, you're right. It looks like the projective curve used to have `riemann_surface()` which the weighted projective curve does not have. What really happens is the given curve computes the affine space and then computes the riemann surface from this.

The fix I think it creating an `affine_patch()` for the weighted projective space

2026-03-02 15:18 UTC, GiacomoPope commented
OK, some hot-fixes to some final failures, this is now looking OK

2026-03-03 01:36 UTC, vincentmacri commented
> OK, some hot-fixes to some final failures, this is now looking OK

CI failures are about not adding the new files to meson. The update-meson script in `tools/` can automate this process.

2026-03-10 22:35 UTC, vincentmacri requested changes
Looks good so far, most requested changes are just small formatting things that you can accept in the GitHub UI. I haven't taken a detailed look at the correctness of the Jacobian arithmetic implementation yet.

You should try to add a doctest that uses `TestSuite.run` on all objects you've added, especially for groups or other objects where Sage can check that the axioms hold for some random elements.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/curves/projective_curve.py
> -        A hyperelliptic curve::
Why was this example removed?

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/curves/weighted_projective_curve.py
> +            Implement this directly for weighted projectivce space, this code currently
```suggestion
            Implement this directly for weighted projective space, this code currently
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/curves/weighted_projective_curve.py
> +            Implement this directly for weighted projectivce space, this code currently
```suggestion
            Implement this directly for weighted projective space, this code currently
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/elliptic_curves/constructor.py
> +    The input `g` should have the form `g(x, y) = y^2 + h(x) y - f(x)`,
Why is this function that helps construct hyperelliptic curves in a file for elliptic curves?

Even if you take the perspective that elliptic curves are just a case of hyperelliptic curves (a perspective that I subscribe to), then I think this belongs in the hypererelliptic code.

If this is actually just meant for elliptic curves, then please update the docstring accordingly. (And maybe the code as well, if it can be simplified.)

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/constructor.py
> +in weighted projective space `\mathbb{P}(1 : g + 1 : 1)`.
```suggestion
Constructor for hyperelliptic curves using the smooth model

Uses weighted projective space `\mathbb{P}(1 : g + 1 : 1)`.
```
Formatting fix. The first line of the module docstring is the title of the document, so it shouldn't be part of a full sentence that continues on the next line. https://doc-pr-39161--sagemath.netlify.app/html/en/reference/arithmetic_curves/sage/schemes/hyperelliptic_curves/constructor

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +        return list(self.rational_points_iterator())
I generally would prefer we only provide an iterator and do not provide a list version, given the colossal number of points that a curve might have. Is there a reason (for example, backwards compatibility) you have both `rational_points_iterator` and `rational_points`? If there isn't a reason to have both, I would have only `rational_points` and I would make it an iterator. Users can simply call `list` on the result if they need to.

If this is for backwards compatibility or because we rely on the list of rational points being cached for performance (which we ideally shouldn't, but that can be left for follow-up work if we do) then this is fine.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +    def count_points_matrix_traces(self, n=1, M=None, N=None):
Tagging @edgarcosta who knows a lot about this hyperelliptic point counting stuff.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
The diffs are a bit confusing, but is this a new method or different algorithm than we had before? If so, it would be good to say in the documentation what algorithm is used and link to the references. If this is just refactoring and you aren't sure what algorithm is being used, I'm not going to ask you to track it down (but if you happen to know it would be nice to include).

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +            sage: K = GF(next_prime(1<<10))
```suggestion
            sage: K = GF(next_prime(1^10))
```
I do not expect the typical reader of Sage documentation to be familiar with bit shifting. (Perfectly fine for you to use this in library code, just try to avoid being overly clever in the `EXAMPLES` in docstrings).

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +    def zeta_function(self):
Reminder for myself: test the performance impact of the change to the zeta function computation.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +        # the best possible -- David Harvey
@edgarcosta Do you happen to know if a better bound has been worked out?

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +        F = f ** ((p - 1) / 2)
```suggestion
        F = f ** ((p - 1) >> 1)  # f ** ((p - 1) / 2)
```

Minor optimization.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/weighted_projective/weighted_projective_point.py
> +                if w == 1 and not c == 0:
```suggestion
                if w.is_one() and not c.is_zero():
```
The previous code should be faster (avoids coercion overhead)

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +    def __init__(self, defining_polynomial, f, h, genus, names=['x', 'y']):
```suggestion
    def __init__(self, defining_polynomial, f, h, genus: Integer, names=['x', 'y']):
```
The way you've written this code, the `genus` should be an `Integer` and not an `int`. That is fine because this constructor is not user-facing. The type annotation will let the type checker make sure that library code is calling it with `Integer`.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        defined by `y^2 + h*y = f`.
```suggestion
        Return the parent ring of the defining polynomials `f, h`, of this hyperelliptic curve.
```
Clarity

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        if hasattr(self, "_split_G_plus_minus"):
`@cached_method` should be easier than manual caching, no? (Same comment applies in a few other places.)

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +                # must be in the split case here.
```suggestion
```
Repeated comment

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        )
```suggestion
        if self.base_ring().characteristic() == 0:
            raise ValueError("in characteristic 0, a distinguished_point needs to be specified with `set_distinguished_point`")
```

`assert` statements are for ensuring the correctness of library code, not for checking that user input is valid.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `n` is omitted in the description.
I still think that for consistency we should always include `n` in the output.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
> +    def __init__(self, projective_model, f, h, genus, names=['x', 'y']):
```suggestion
    def __init__(self, projective_model, f, h, genus: Integer, names=['x', 'y']) -> None:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +    def __init__(self, projective_model, f, h, genus, names=["x", "y"]):
```suggestion
    def __init__(self, projective_model, f, h, genus: Integer, names=["x", "y"]) -> None:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
>      def is_in_weierstrass_disc(self, P):
```suggestion
    def is_in_weierstrass_disc(self, P) -> bool:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
>      def is_same_disc(self, P, Q):
```suggestion
    def is_same_disc(self, P, Q) -> bool:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py
> +r"""
Other than the minor style comments, this file looks good but I'm not too familiar with the p-adic case. @edgarcosta does this all look good to you?

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_rational_field.py
> +    def __init__(self, projective_model, f, h, genus, names=['x', 'y']):
```suggestion
    def __init__(self, projective_model, f, h, genus: Integer, names=['x', 'y']) -> None:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_g2_homset_ramified.py
> +    in genus two for hyperlliptic curves with an ramified model
```suggestion
    in genus two for hyperlliptic curves with a ramified model
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_g2_homset_split.py
> +    in genus two for hyperlliptic curves with an split model
```suggestion
    in genus two for hyperlliptic curves with a split model
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
>      def dimension(self):
```suggestion
    def dimension(self) -> Integer:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
>          return Integer(self.curve().genus())
```suggestion
        return self.curve().genus()
```
This should already be an `Integer`, is it not?

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
> +            yield point
```suggestion
        yield from self.point_homset().points()
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_generic.py
> +    def order(self):
```suggestion
    def order(self) -> Integer:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_generic.py
> +    def cardinality(self, extension_degree=1):
```suggestion
    def cardinality(self, extension_degree=1) -> Integer:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_generic.py
> +            assert not (g % 2)
Is it possible for this to happen? If it can happen, this should be a `ValueError` and not an `assert`.

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_split.py
> +        https://www.math.auckland.ac.nz/~sgal018/Dave-Mireles-Full.pdf
References should be links to the references file: https://doc.sagemath.org/html/en/developer/coding_basics.html#sage-s-master-bibliography-file

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
> +        """
```suggestion
            sage: TestSuite(J).run()
        """
```
Checks the group axioms holds on whatever is returned by `J.some_elements()`. (Make sure `J.some_elements()` is implemented if it isn't.)

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
> +    def __hash__(self):
```suggestion
    def __hash__(self) -> int:
```

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/kummer_surface.py
>  Kummer surfaces over a general ring
I don't know much about this stuff, but as far as I can tell the only changes here are formatting? Is there anything non-trivial?

2026-03-10 22:35 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
> -    @cached_method
What was wrong with `@cached_method`?

2026-03-11 08:57 UTC, GiacomoPope commented on src/sage/schemes/curves/projective_curve.py
> -        A hyperelliptic curve::
I moved it to the weighted projective curve as this is what is the top level calling function

2026-03-11 09:00 UTC, GiacomoPope commented on src/sage/schemes/elliptic_curves/constructor.py
> +    The input `g` should have the form `g(x, y) = y^2 + h(x) y - f(x)`,
So i don't know the full history of this function but i can try and summarize what i understand.

The documented way to construct a hyperelliptic curve is from `f` and optionally `h`, but at some point someone allowed `HyperellipticCurve(f)` to accept `f` to be a multivariate polynomial describing the curve equation and then this function would parse this to get `f` and `h`. I thought this was really janky, and because it is undocumented i just left it.

For the elliptic curve case, this function still remains as a hacky method of creating a hyperelliptic curve from an elliptic curve for some of the padic methods. I will make a PR moving this file to somewhere where this is more obvious and you can comment on whether you prefer it.

2026-03-11 09:03 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
I think this is all just refactoring we didnt add anything special i believe

2026-03-11 09:04 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_finite_field.py
> +            sage: K = GF(next_prime(1<<10))
this needs to be 2^10, not 1^10 but i will fix it

2026-03-11 09:05 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        if hasattr(self, "_split_G_plus_minus"):
yes probably, i need to do this refactor...

2026-03-11 09:08 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_generic.py
> +            assert not (g % 2)
i dont think it can happen and the assert would mean something had gone seriously wrong

2026-03-11 09:22 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
> -    @cached_method
honestly im not sure why there was this change

2026-03-11 10:04 UTC, GiacomoPope commented
There's an issue with the test suite...

```py
sage: x = polygen(GF(5))
sage: H = HyperellipticCurve(x^5 + 3 * x + 1)
sage: J = H.jacobian(); J
Jacobian of Hyperelliptic Curve over Finite Field of size 5 defined by y^2 = x^5 + 3*x + 1
sage: J.parent()
<class 'sage.schemes.hyperelliptic_curves.jacobian_g2_generic.HyperellipticJacobian_g2_generic_with_category'>
sage: zero = J.zero()
sage: zero
(1, 0)
sage: zero.parent()
Abelian group of points over Finite Field of size 5 on Jacobian of Hyperelliptic Curve over Finite Field of size 5 defined by y^2 = x^5 + 3*x + 1
sage: J
Jacobian of Hyperelliptic Curve over Finite Field of size 5 defined by y^2 = x^5 + 3*x + 1
```

Which is the cause of this error:

```
      File "/Users/Jack/sage/sage/src/sage/categories/additive_magmas.py", line 684, in _test_zero
        tester.assertTrue(self.is_parent_of(zero))
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/Caskroom/miniforge/base/envs/sage-dev/lib/python3.13/unittest/case.py", line 744, in assertTrue
        raise self.failureException(msg)
    AssertionError: False is not true
```

Then there's two other errors which i understand less

```
      Failure in _test_pickling:
      Traceback (most recent call last):
        File "/Users/Jack/sage/sage/src/sage/misc/sage_unittest.py", line 296, in run
          test_method(tester=tester)
          ~~~~~~~~~~~^^^^^^^^^^^^^^^
        File "sage/structure/sage_object.pyx", line 679, in sage.structure.sage_object.SageObject._test_pickling
        File "/usr/local/Caskroom/miniforge/base/envs/sage-dev/lib/python3.13/unittest/case.py", line 907, in assertEqual
          assertion_func(first, second, msg=msg)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Caskroom/miniforge/base/envs/sage-dev/lib/python3.13/unittest/case.py", line 900, in _baseAssertEqual
          raise self.failureException(msg)
      AssertionError: (1, 0) != (1, 0)
```

This one looks like an issue with the types of `1` and `0`? Picking seems to be doing something weird.

This last one makes no sense to me:

```
      Failure in _test_category:
      Traceback (most recent call last):
        File "/Users/Jack/sage/sage/src/sage/misc/sage_unittest.py", line 296, in run
          test_method(tester=tester)
          ~~~~~~~~~~~^^^^^^^^^^^^^^^
        File "sage/structure/element.pyx", line 718, in sage.structure.element.Element._test_category
        File "/usr/local/Caskroom/miniforge/base/envs/sage-dev/lib/python3.13/unittest/case.py", line 744, in assertTrue
          raise self.failureException(msg)
      AssertionError: False is not true
```

2026-03-11 10:09 UTC, GiacomoPope commented
just a further comment: the same test suite would fail for main

```py
sage: x = polygen(GF(5))
sage: H = HyperellipticCurve(x^5 + 3 * x + 1)
sage: J = H.jacobian(); J
Jacobian of Hyperelliptic Curve over Finite Field of size 5 defined by y^2 = x^5 + 3*x + 1
sage: z = J.zero()
sage: z.parent()
Set of rational points of Jacobian of Hyperelliptic Curve over Finite Field of size 5 defined by y^2 = x^5 + 3*x + 1
```

2026-03-11 16:08 UTC, vincentmacri commented on src/sage/schemes/elliptic_curves/constructor.py
> +    The input `g` should have the form `g(x, y) = y^2 + h(x) y - f(x)`,
> I will make a PR moving this file to somewhere where this is more obvious and you can comment on whether you prefer it.

You can if you want, but I'm happy to leave it for this PR and you can make the other PR after this is merged.

2026-03-11 16:09 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
> -    @cached_method
Generally, I would prefer `@cached_method`, but this is a minor issue so I won't ask you to change it.

2026-03-11 16:36 UTC, GiacomoPope commented
I'm tempted to remove these tests for now and fix the unit tests in a new PR

2026-03-11 16:45 UTC, vincentmacri commented
> I'm tempted to remove these tests for now and fix the unit tests in a new PR

Can you leave them in for now? I will hopefully have time to finish my review next week, and I can look into the `TestSuite` failures as part of that. If we can't figure it out and everything else is fine, then you can remove the `TestSuite` run and leave fixing it for a follow-up.

2026-03-12 12:03 UTC, GiacomoPope commented
```py
sage: R.<x> = GF(13)[]
sage: H = HyperellipticCurve(x^5 + 2*x + 1)
sage: J = H.jacobian()
sage: JFp = J(GF(13))
sage: 
sage: z = JFp.zero()
sage: z.is_zero()
True
sage: z == 0
True
sage: z != 0
False
sage: zz = loads(dumps(z))
sage: 
sage: zz.is_zero()
True
sage: zz == 0
True
sage: zz != 0
False
sage: z == zz
False
sage: tuple(z) == tuple(zz)
True
```

So there's a bug with picking on this branch, but not on main

```py
sage: z = JFp.zero()
sage: zz = loads(dumps(z))
sage: z == zz
True
sage: type(z)
```

2026-03-12 12:42 UTC, GiacomoPope commented
```py
sage: D = J.random_element()
sage: DD = loads(dumps(D))
sage: 
sage: D == DD
False
sage: tuple(D) == tuple(DD)
True
sage: D.parent() == DD.parent()
True
sage: D.parent() == loads(dumps(DD.parent()))
True
sage: D.domain() == loads(dumps(DD.domain()))
True
sage: D.codomain() == loads(dumps(DD.codomain()))
True
sage: tuple(D)  == loads(dumps(tuple(DD)))
True
sage: D.category() is DD.category()
True
sage: D.scheme() == loads(dumps(DD.scheme()))
True
```

I can't find what's different!!!

EDIT:

```py
sage: D.parent() == DD.parent()
True
sage: D.parent() is DD.parent()
False
```

This is the issue... I will try and find a minimal fix

2026-03-12 15:07 UTC, GiacomoPope commented
OK this took WAY too long but I have something working with the exception of the `_test_elements` unit test, this fails as there's an issue with the category of the parent of the elements of the homset but this fails for both this branch and main.

2026-03-12 15:09 UTC, GiacomoPope commented
This branch:

```py
sage: R.<x> = GF(7)[]
....: H = HyperellipticCurve(3*x^6 + 2*x^2 + 1)
....: J = Jacobian(H)
....: JK = J(GF(7))
....: e = JK.an_element()
....: isinstance(e, JK.category().element_class)
False
sage: type(e)
<class 'sage.schemes.hyperelliptic_curves.jacobian_morphism.MumfordDivisorClassFieldInert'>
sage: JK.category().element_class
<class 'sage.categories.homsets.HomsetsOf.element_class'>
```

Main:

```py
sage: R.<x> = GF(7)[]
....: H = HyperellipticCurve(3*x^6 + 2*x^2 + 1)
....: J = Jacobian(H)
....: JK = J(GF(7))
....: e = JK.an_element()
....: isinstance(e, JK.category().element_class)
False
sage: type(e)
<class 'sage.schemes.hyperelliptic_curves.jacobian_morphism.JacobianMorphism_divisor_class_field'>
sage: JK.category().element_class
<class 'sage.categories.homsets.HomsetsOf.element_class'>
```

2026-03-12 23:08 UTC, grhkm21 commented
I committed a few small changes. They address the following bugs:
```python
#!/usr/bin/env sage
"""
Test script to demonstrate fixes for PR #39161

Issues fixed:
1. Pickle/unpickle equality (loads(dumps(P)) == P should be True)
2. J.is_parent_of(J.zero()) should return True
3. lift_u(0) should not raise NameError on split model
"""

def test_pickle_ramified():
    """Test pickle/unpickle on ramified model"""
    x = polygen(GF(5))
    H = HyperellipticCurve(x^5 + 3*x + 1)
    J = H.jacobian()
    P = J.random_element()
    result = loads(dumps(P)) == P
    print(f"[{'PASS' if result else 'FAIL'}] Pickle ramified: loads(dumps(P)) == P -> {result}")
    return result

def test_pickle_split():
    """Test pickle/unpickle on split model"""
    x = polygen(GF(5))
    H = HyperellipticCurve(x^6 + x + 1)
    J = H.jacobian()
    P = J.random_element()
    result = loads(dumps(P)) == P
    print(f"[{'PASS' if result else 'FAIL'}] Pickle split: loads(dumps(P)) == P -> {result}")
    return result

def test_pickle_inert():
    """Test pickle/unpickle on inert model"""
    x = polygen(GF(5))
    H = HyperellipticCurve(2*x^6 + 1)
    J = H.jacobian()
    P = J.random_element()
    result = loads(dumps(P)) == P
    print(f"[{'PASS' if result else 'FAIL'}] Pickle inert: loads(dumps(P)) == P -> {result}")
    return result

def test_is_parent_of():
    """Test J.is_parent_of(J.zero())"""
    x = polygen(GF(19))
    H = HyperellipticCurve(x^5 + x, x^2 + 1)
    J = H.jacobian()
    result = J.is_parent_of(J.zero())
    print(f"[{'PASS' if result else 'FAIL'}] is_parent_of: J.is_parent_of(J.zero()) -> {result}")
    return result

def test_lift_u_zero():
    """Test lift_u(0) on split model - should not raise NameError"""
    x = polygen(GF(7))
    H = HyperellipticCurve(x^6 + x + 1)
    J = H.jacobian()
    try:
        result = J.lift_u(0)
        print(f"[PASS] lift_u(0): returned {result}")
        return True
    except NameError as e:
        print(f"[FAIL] lift_u(0): NameError - {e}")
        return False
    except Exception as e:
        print(f"[FAIL] lift_u(0): {type(e).__name__} - {e}")
        return False

def run_all_tests():
    """Run all tests and return overall result"""
    print("=" * 60)
    print("Testing hyperelliptic Jacobian fixes")
    print("=" * 60)

    results = []
    results.append(test_pickle_ramified())
    results.append(test_pickle_split())
    results.append(test_pickle_inert())
    results.append(test_is_parent_of())
    results.append(test_lift_u_zero())

    print("=" * 60)
    passed = sum(results)
    total = len(results)
    print(f"Results: {passed}/{total} tests passed")
    print("=" * 60)

    return all(results)

success = run_all_tests()
import sys
sys.exit(0 if success else 1)
```
This gave 0/5 tests passed before the commit, and 5/5 now

2026-03-17 21:41 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_inert.py
> +            sage: TestSuite(JK).run(skip='_test_elements')
This shouldn't be getting skipped. I will investigate.

2026-03-17 22:36 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_inert.py
> +            sage: TestSuite(JK).run(skip='_test_elements')
I think this is an issue with incorrect use of the category framework, I'm going to try to find a fix.

2026-03-17 22:37 UTC, GiacomoPope commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_inert.py
> +            sage: TestSuite(JK).run(skip='_test_elements')
It seemed to be a pretty deep issue with categories and homsets --  i tried, but i couldn't fix it

2026-03-17 22:37 UTC, grhkm21 commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_inert.py
> +            sage: TestSuite(JK).run(skip='_test_elements')
IIRC it's because SchemeMorphism are weird and don't behave well with the category framework, e.g. parent of J.zero() is the homset not J itself. This behaviour exists for other scheme-related things e.g. elliptic curves as well, I don't think it should be fixed in this PR.

2026-03-17 22:40 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_homset_inert.py
> +            sage: TestSuite(JK).run(skip='_test_elements')
Fair enough. I found a few more minor issues with the category framework, since I was working locally while investigating this I'll open a PR against your branch.

2026-03-17 23:10 UTC, vincentmacri commented
I've opened https://github.com/GiacomoPope/sage/pull/2 with some minor fixes. Otherwise, code structure looks good. All that remains I think is for me to review the correctness of the balanced divisors implementation. Is that pretty much all in `jacobian_morphism`?

Also, don't forget to move the citation to the bibliography (I pointed this out above).

2026-03-17 23:47 UTC, vincentmacri requested changes
The diffs are too long to easily read in my browser. Is it alright if I submit the rest of my suggestions via a PR to your branch?

2026-03-17 23:47 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
> +            # too large?
It looks like you do this reduction in `_add_`, `_neg_` etc already? In that case you don't need to do it in `__init__`, but you should make sure that a user cannot construct an unreduced divisor (so reduce it before calling `__init__`. Or you can reduce it in `__init__` (in which case you can maybe some of the reduction in `_add_` etc is redundant and can be removed).

2026-03-17 23:47 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
> +        return self._parent
```suggestion
```
Isn't the implementation inherited from `element.pyx` sufficient?

2026-03-17 23:47 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/jacobian_morphism.py
> +    def is_zero(self):
Subclasses of element should not override `is_zero`, instead they should only override `__bool__`. Element implements `is_zero` as `return not self`.

2026-03-20 22:22 UTC, vincentmacri commented on src/sage/schemes/hyperelliptic_curves/hyperelliptic_generic.py
> +        `n` is omitted in the description.
Nevermind, I see now that this is dependent on the types. I think before I misunderstood it as whether `n` is included in the output depends on the value. This is fine then.

2026-03-23 20:16 UTC, vincentmacri commented
I've opened another PR with suggestions and a question, but otherwise I think this is almost ready to merge.

Just a few last things:

1. There are several `TODO` notes in the code. Did you want to discuss any of them now and address them in this PR, or do you want to leave that for future work?
2. There is a merge conflict that needs to be resolved.
3. After everything else is done, since you've basically refactored all the hyperelliptic code, would you mind running our stricter linting autofix settings on it to save us from future code cleanup? I can do another PR if you prefer, but then my name will be all over the git blame on stuff that is mostly your work. Just run these two commands:
  i. To run our stricter linting rules and autofix violations: `ruff check --preview --fix src/sage/schemes/hyperelliptic_curves`
  ii. To fix some rules that are probably going to be added to our stricter list of linting rules soon anyway: `ruff check --preview --fix --select RET src/sage/schemes/hyperelliptic_curves`

2026-03-23 21:57 UTC, GiacomoPope commented
0. I merged your PR
1. I think the TODO can be left for later
2. I have sorted this
3.a. I get failures, mainly from imports from `lazy_import`, however there are two failures which we could fix, one I did myself but the other is in a scary function and I don't know if something will break if I change it

```
PLW0642 Reassigned `self` variable in instance method
   --> src/sage/schemes/hyperelliptic_curves/hyperelliptic_padic_field.py:734:17
    |
732 |                 A = PolynomialRing(RationalField(), "x")
733 |                 f = A(self.hyperelliptic_polynomials()[0])
734 |                 self = HyperellipticCurve(f).change_ring(K)
    |                 ^^^^
735 |                 xP = P[0]
736 |                 xPv = xP.valuation()
    |
help: Consider using a different variable name
```
3.b `ruff check --preview --fix --select RET src/sage/schemes/hyperelliptic_curves` I fixed all errors from this.

2026-03-24 18:58 UTC, vincentmacri commented
Alright, as long as you fixed as much as you could that's fine. The linter is pretty reliable at not breaking things, but circular import issues are one thing it struggles with.

Positive review from me then! Thank you for all this work, and for bearing through this very long code review! I think this is the second-longest code review we've had on the Sage GitHub by number of comments!

I do have one last question, just so there is something written down for future reference:

For the inert case, what did you reference when writing the implementation? Most of the papers I've seen on the subject ignore the inert case.

2026-03-24 18:58 UTC, vincentmacri approved these changes

2026-03-24 19:42 UTC, GiacomoPope commented
I honestly can't remember where I learnt about the inert case. Is it not in the morales paper or Galbraith book? Maybe I figured it out with help from Magma and Sabrina?

2026-03-24 19:48 UTC, GiacomoPope commented
Thank you so much for taking on the gargantuan task of reviewing this PR. I know it was a huge amount of work but I hope in the long run it really helps with Sage

2026-03-24 22:52 UTC, vincentmacri commented
> I honestly can't remember where I learnt about the inert case. Is it not in the morales paper or Galbraith book? Maybe I figured it out with help from Magma and Sabrina?

Galbraith's book discusses it a bit but in much less detail than the other cases. Anyway, that's fine! Just wanted to make sure I wasn't missing some resource.

2026-04-08 22:47 UTC, merged

2026-04-09 09:21 UTC, yyyyx4 commented
Big thanks to all those who contributed to this monumental effort!

2026-04-09 09:22 UTC, GiacomoPope commented
Yeah, thanks everyone! Really happy about this PR and excited to build on it