Add keyword prec for exponential and logarithm of Drinfeld modules
sagemath/sage pull request #39214
Opened 2024-12-28 11:25 UTC by xcaruso

Currently, the methods `exponential` and `logarithm` for Drinfeld modules return a `LazyPowerSeriesRing` for which not all methods are available.
We add a keyword `prec`. When it is `Infinity` (which is the default), the behavior is unchanged. However, when we pass in a finite number, a classical power series (up to the given precision) is returned. 

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [x] I have created tests covering the changes.
- [x] I have updated the documentation and checked the documentation preview.

2024-12-28 14:17 UTC, mantepse commented
Off topic: Which methods are missing in `LazyPowerSeries`?

2024-12-28 14:54 UTC, xcaruso commented
e.g. `sqrt` (it is implemented only for series congruent to 1 modulo `x`), `nth_root`, `continued_fraction`...
Also printing more terms is a little bit tricky; we need to set the parameter `parent.options.display_length` (which moreover is global, we cannot easily change this for just one shot).

2024-12-28 17:06 UTC, mantepse commented
> e.g. `sqrt` (it is implemented only for series congruent to 1 modulo `x`), `nth_root`,

Oh, I missed the possibility of taking out `x^n`!

> `continued_fraction`...

I actually have code for that, but was too lazy to get it in.

> Also printing more terms is a little bit tricky; we need to set the parameter `parent.options.display_length` (which moreover is global, we cannot easily change this for just one shot).

I agree.  Maybe we can discuss this at sd128?

2025-01-02 13:25 UTC, mantepse commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        On the contrary, when ``prec`` is a finite number, all the
```suggestion
        If ``prec`` is a finite number, all the
```
(`on the contrary` would imply, to my non-native ear, that I assumed something which is not the case)

2025-01-02 13:25 UTC, mantepse commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +            return L([0] + [coeff_log(i) for i in range(1, prec)], prec=prec)
```suggestion
        L = PowerSeriesRing(self._base, name, default_prec=prec)
        return L([0] + [coeff_log(i) for i in range(1, prec)], prec=prec)
```
And also in `coeff_log`.

2025-01-02 13:25 UTC, mantepse commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +            return L([0] + [coeff_exp(i) for i in range(1,prec)], prec=prec)
```suggestion
        L = PowerSeriesRing(self._base, name, default_prec=prec)
        return L([0] + [coeff_exp(i) for i in range(1,prec)], prec=prec)
```
(and actually also in `coeff_exp`)

2025-01-03 08:49 UTC, xcaruso commented
> > Also printing more terms is a little bit tricky; we need to set the parameter `parent.options.display_length` (which moreover is global, we cannot easily change this for just one shot).
> 
> I agree. Maybe we can discuss this at sd128?

Sure!
I implemented a few years ago exact $p$-adics using relaxed artihemtics. The precision model there is able to handle both infinite and finite precision in the same parent. Maybe, it's also a good option to follow this.

2025-01-03 09:52 UTC, mantepse commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        required coefficients are computed at once::
```suggestion
        If ``prec`` is a finite number, all the
        required coefficients are computed at once::
```

2025-01-21 23:26 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        required coefficients are computed at once::
Not sure about that suggestion. Xavier's formulation allows the reader to recall that they are on the second option for the type of `prec`. I would suggest that Xavier leaves that unchanged.

2025-01-21 23:45 UTC, kryzar commented
Once again, it seems that the failed tests are independent to that PR:
- [First failed test](https://github.com/sagemath/sage/actions/runs/12595135062/job/35103822234?pr=39214#step:10:9822)
- [Second failed test, first failed subtest](https://github.com/sagemath/sage/actions/runs/12595135062/job/35103822234?pr=39214#step:9:8877)
- [Second test, second failed subtest](https://github.com/sagemath/sage/actions/runs/12595135066/job/35103826235?pr=39214#step:9:8864)
- [Third test, first failed subtest](https://github.com/sagemath/sage/actions/runs/12595135066/job/35103826054?pr=39214#step:9:8877)
- [Third failed test, second failed subtest](https://github.com/sagemath/sage/actions/runs/12595135066/job/35103826235?pr=39214#step:9:8864)

@xcaruso, could you merge from `develop` and push here? I have hope this will fix the issue. (I don't believe I have authorizations on your fork (which I am not asking for), as I tried to do that but failed.)

2025-01-21 23:50 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +    def exponential(self, prec=Infinity, name='z'):
Thanks to this line I learnt that there was a constant for $\infty$ in Sage! Thanks!

2025-01-22 00:06 UTC, kryzar requested changes
I did my review. I only request that you add the latest changes from develop. My comments in the review are only suggestions, and you can freely choose to accept them or not. I'll approve the review either way. The only thing truly missing are the valid automatic tests (which unfortunately do not seem to be your fault's...).

Thank you very much for this lovely and useful PR :blue_heart:

2025-01-22 00:06 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +          a lazy power series in returned
```suggestion
        - ``prec`` -- an integer or ``Infinity`` (default: ``Infinity``);
          the precision at which the series is returned; if ``Infinity``,
          a lazy power series in returned, else, a classical power series
          is returned.
```

2025-01-22 00:06 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        return L([0] + [coeff_exp(i) for i in range(1,prec)], prec=prec)
Maybe that's just me but I like to also add the `else` statement, for readability. Do what you want, tho.

Btw, I believe if you exclude $0$ from `[coeff_exp(i) for i in range(1,prec)]` maybe you should comment `coeff_exp` that the input should be $\geqslant 1$. Furthermore, maybe removing the cast `k = ZZ(k)` and replacing `range(1, prec)` by IntegerRange(1, prec)` would be cleaner.

2025-01-22 00:06 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> -
I think I would have kept (and updated) this block, but maybe that's just me.

2025-01-22 00:06 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +    def logarithm(self, prec=Infinity, name='z'):
Same remarks as for the exponential.

2025-02-11 21:05 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        required coefficients are computed at once::
I agree with Antoine: I prefer keeping `On the contrary`.

2025-02-11 21:06 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        return L([0] + [coeff_exp(i) for i in range(1,prec)], prec=prec)
Be careful that `coeff_exp` is also used when `prec` is `Infinity`.

2025-02-11 21:07 UTC, xcaruso commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> -
Well, it's already said a few lines ago. I find it redundant.

2025-02-11 21:16 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> +        return L([0] + [coeff_exp(i) for i in range(1,prec)], prec=prec)
Ok

2025-02-11 21:17 UTC, kryzar commented on src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
> -
Ok

2025-02-12 23:03 UTC, kryzar approved these changes
Once again, these failing doctests seem unrelated to our work. Therefore, I approve the PR.

Many thanks to Xavier.

2025-02-21 21:19 UTC, merged